### ISSUE TITLE
Is it normal that I still don't have my domain name?

### ISSUE THREAD

**Issue by el2zay** [is-a-dev/register#1000]
Hello,
I did a PR on July 24 and have not heard from you since July 26. The last email you sent me was "Merged #960 into main." A friend told me he got his domain name in one day.

Should I do a new PR or just wait?
![image](https://user-images.githubusercontent.com/79168733/127651201-b741fd7c-f969-4e9d-bb3b-2a7f415fd5dc.png)

**Comment by hackermondev** [comment]
Your domain works for me! https://el2zay.is-a.dev/ leads to your GitHub site. Clear your cache if you do not see this.

![image](https://user-images.githubusercontent.com/60828015/127655404-1f326cc0-2d71-4c6f-a5ba-77230d776c8e.png)

It shows a 404 page when I go to the site which I think it an issue on your side. You need to tell GitHub that the domain is linked to your site. Learn more [here](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site)

**Comment by el2zay** [comment]
Thank you for your quick response,
I tried to go to the settings of the github page to put the custom domain, once finished it puts me that the connection is not secure. 

Now I just tried again and it works strangely.

Sorry for the inconvenience
Have a good day.

Elie
![image](https://user-images.githubusercontent.com/79168733/127661399-ed099691-71e3-45e9-a3cd-32622ade2078.png)
