### ISSUE TITLE
Support: Privacy Error + 404

### ISSUE THREAD

**Issue by arib21** [is-a-dev/register#1003]
Domain: https://arib21.is-a.dev

I was getting a privacy error for the domain. But it now throws a "There isn't a GitHub Pages site here."

![](https://user-images.githubusercontent.com/69956399/127772469-5db08376-7155-42f3-862b-d219322dfea3.png)

But when I try to access it on my Windows10 Machine, it still shows "Privacy error"

![image](https://user-images.githubusercontent.com/69956399/127772620-b2118c00-7f7a-4cfd-a90d-21f014f4a179.png)

**Comment by TheBotlyNoob** [comment]
For both issues, you need to create a `CNAME` file with `arib21.is-a.dev` as the contents

**Comment by arib21** [comment]
How to do that?

**Comment by TheBotlyNoob** [comment]
you can access the website now
