### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by at669** [is-a-dev/register#10059]
Your domain name: amanda

Explain any issues you are facing

After #9776, I see on https://manage.is-a.dev/domains that my domain is listed and I've set a password in the Hosting Settings, but using that password, I can't access the Manage files online editor. I reliably get this:

> Unable to login to FTP server hosts.is-a.dev with username amanda.
> 
> Are you sure your username and password are correct? Please contact your ISP helpdesk or system administrator for help.

What am I missing?

Thanks!

**Comment by andrewstech** [comment]
Sorry for the delay, my GitHub notifications don't appear to be working. I will look into this issue for you.

**Comment by at669** [comment]
Hey, no worries! I actually just got a "Your hosting details" email about 15 minutes ago which gave me my login credentials. I'll close this ticket out for now, thanks!
