### ISSUE TITLE
Transfer domain name to new username

### ISSUE THREAD

**Issue by lackypal** [is-a-dev/register#10063]
I've changed my github username. That's why I want to change my is-a.dev subdomain. How can I do it? 
My current domain [l0ser.is-a.dev](https://l0ser.is-a.dev). I want to change it to [lacky.is-a.dev](https://lacky.is-a.dev)

**Comment by VaibhavSys** [comment]
Just submit a PR with the changes, make sure to do it from your old GitHub account, or current one if you updated username only.

**Comment by lackypal** [comment]
One more question: Can I update the website code also like a whole new design?

**Comment by VaibhavSys** [comment]
> One more question: Can I update the website code also like a whole new design?

Yes, you can

**Comment by LackyPal** [comment]
I'd a created a PR, and it's accepting. But the old domain is still active. Please remove it so that others can use it if they want
