### ISSUE TITLE
How do i set up the certificate to work with is-a.dev?

### ISSUE THREAD

**Issue by JoaquinDaBest** [is-a-dev/register#10061]
when I add a CNAME record from rice.is-a.dev TO keenwa.x10.mx the domain does not work.

it might be the certificate, how would I set it up?

P.S. for keenwa.x10.mx I am using x10 hosting

**Comment by YouFoundAlpha** [comment]
![image](https://github.com/is-a-dev/register/assets/86548581/761ec1fe-718f-4dba-b48c-bee83775e16e)
From what I can see the issue is not the SSL certificate from is-a.dev
Its the SSL certificate from x10 hosting that's causing the issue
@JoaquinDaBest

**Comment by YouFoundAlpha** [comment]
@WilliamDavidHarrison Do you know what's causing this issue?

**Comment by YouFoundAlpha** [comment]
I got this when I tried to visit rice.is-a.dev 
![image](https://github.com/is-a-dev/register/assets/86548581/68cd959a-016f-4747-ad9c-b1449a0cea96)

**Comment by YouFoundAlpha** [comment]
> keenwa.x10.mx

One solution you can do is to just make it a redirect record to redirect to keenwa.x10.mx
![image](https://github.com/is-a-dev/register/assets/86548581/60d39273-1d6d-47a1-b4ec-d9de429f840d)

**Comment by JoaquinDaBest** [comment]
I can configure the certificate if I want, I am just not aware of how I should do it

**Comment by VaibhavSys** [comment]
I am not sure about the process of setting up certificates in x10 hosting, but you can manually get a SSL certificate from Lets Encrypt or any other provider and use it on your server. You can also use [InfinityFree](https://www.infinityfree.com/) to get a SSL certificate, it allows you to get a certificate automatically from a number of providers including Lets Encrypt and Google however, its better to avoid that if possible.
