### ISSUE TITLE
Domain johna.is-a.dev deleted?

### ISSUE THREAD

**Issue by Johna-123** [is-a-dev/register#10111]
Domain name: https://johna.is-a.dev

My domain name seems to have gotten removed.
I opened a pull request a few days ago to re-register the domain: https://github.com/is-a-dev/register/pull/10023

**Comment by WilliamDavidHarrison** [comment]
It was removed in the domain cleanup (#9887) as it must not have been reachable at that time. Sorry for the inconvenience, I have merged your PR.
