### ISSUE TITLE
[Support] FTP Access, Domain Activation and Discord Linking issues

### ISSUE THREAD

**Issue by Riddim-GLiTCH** [is-a-dev/register#10244]
Your domain name: https://riddim-glitch.is-a.dev

Explain any issues you are facing

## FTP Access.
After some difficulty, I managed to gain FTP access to my domain's management panel. It would let me log on, but not upload files correctly. This has been resolved with minor troubleshooting. I am however facing the small issue of not being able to directly modify the files on the server. Instead, I have to keep a local copy of my site to edit, then copy the files to the FTP server to overwrite the modified files. This isn't very optimal in my experience. Is there anything I can do to resolve this?

## Domain Activation.
As mentioned above, I was able to upload my website data to the FTP server. Everything should work fine. However, upon visiting my domain, it tells me to return to the dashboard to activate my domain. I am unable to find anything on the dashboard that seems like it would let me do it.

## Discord Linking.
It is not very clear to me how Discord linking works. I was able to figure out what Contents the dashboard is asking for, and it lets me submit the data just fine. It tells me that my discord was successfully linked. However, Discord seems to not be able to verify the domain.

See the attached screenshots below, I have obscured the contents fields as I am not sure about the security implications of said information being public.
![image](https://github.com/is-a-dev/register/assets/87764384/8f159cd6-4be4-4204-a707-5afced9ff4ac)
![image](https://github.com/is-a-dev/register/assets/87764384/45db09f0-0a89-4928-a47e-bf794b5a77da)

**Comment by andrewstech** [comment]
> Your domain name: https://riddim-glitch.is-a.dev
> 
> Explain any issues you are facing
> 
> ## FTP Access.
> After some difficulty, I managed to gain FTP access to my domain's management panel. It would let me log on, but not upload files correctly. This has been resolved with minor troubleshooting. I am however facing the small issue of not being able to directly modify the files on the server. Instead, I have to keep a local copy of my site to edit, then copy the files to the FTP server to overwrite the modified files. This isn't very optimal in my experience. Is there anything I can do to resolve this?
> 
> ## Domain Activation.
> As mentioned above, I was able to upload my website data to the FTP server. Everything should work fine. However, upon visiting my domain, it tells me to return to the dashboard to activate my domain. I am unable to find anything on the dashboard that seems like it would let me do it.
> 
> ## Discord Linking.
> It is not very clear to me how Discord linking works. I was able to figure out what Contents the dashboard is asking for, and it lets me submit the data just fine. It tells me that my discord was successfully linked. However, Discord seems to not be able to verify the domain.
> 
> See the attached screenshots below, I have obscured the contents fields as I am not sure about the security implications of said information being public. ![image](https://private-user-images.githubusercontent.com/87764384/292174445-8f159cd6-4be4-4204-a707-5afced9ff4ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTU4MjEsIm5iZiI6MTcwMzE1NTUyMSwicGF0aCI6Ii84Nzc2NDM4NC8yOTIxNzQ0NDUtOGYxNTljZDYtNGJlNC00MjA0LWE3MDctNWFmY2VkOWZmNGFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDEwNDUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwZTc2Nzg0YjBmZWJjNGFhZTYwYmYzMzQwZGNjZTQ4ODJiNDI4ZjQ4ZGE1YTM4MzMyMzExNmE5OTY2MjQxOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6_msLylx9k9BppfFrTtMbAxUEyBWzpcIhuLjkcz3yGo) ![image](https://private-user-images.githubusercontent.com/87764384/292174590-45db09f0-0a89-4928-a47e-bf794b5a77da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNTU4MjEsIm5iZiI6MTcwMzE1NTUyMSwicGF0aCI6Ii84Nzc2NDM4NC8yOTIxNzQ1OTAtNDVkYjA5ZjAtMGE4OS00OTI4LWE0N2UtYmY3OTRiNWE3N2RhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDEwNDUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3NmNlM2FjMzdmNmU2NGE5MjY5NjU4ODM0ZDBlNzU1MTQ2YzcwNzRlMzZiZGVlM2M5MzczZWUyMmU3OWM2NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZueOV2illWmZ8P6zY_xMZzYDeOqGw0k8JBZ8vFHSolY)

Hello I have activated your site.  As for discord click verify using https. Ftp can be a pain in the ass. There is multiple FTP clients that you can use/install I use Winscp but there is plenty of others. I would not recommend using the windows file explorer as its FTP client is odd it requires copping everything.
