### ISSUE TITLE
Domain says "not activated"

### ISSUE THREAD

**Issue by realpeanut** [is-a-dev/register#10261]
### Expected outcome
After editing the "index.html" and uploading my css, nothing works.

### Observed outcome
When entering my domain into the web browser, it hit me with the message "Whoops, that site has not been activated visit manage.is-a.dev to activate it."

**Comment by WilliamDavidHarrison** [comment]
What is your domain name?

**Comment by andrewstech** [comment]
> peanut.is-a.dev

Activated
