### ISSUE TITLE
Unable to login to FTP via online or any other client

### ISSUE THREAD

**Issue by vikkubaligas** [is-a-dev/register#10285]
Your domain name:
https://vikkubaliga.is-a.dev/

My pull request got merged and I just got a mail regarding the next procedure. I got the mail on 21 Dec 2023, 08:09.

It says I need to click on edit and I will get FTP credentials and access to the online file manager [WIP]. But when I click on edit, I get only the username. Password is shown as "Set by User".

So, what is my password? I had registered using GitHub. But still I tried a few which I would regularly use. 
I also tried "Set by User" 🤣 

I am not able to login using the online editor and also many other FTP clients. I am not able to login.

**Comment by NotAJocke** [comment]
Same here

**Comment by SamarthGhante** [comment]
Yeah, Me also tried all the passwords but its not working

**Comment by vikkubaligas** [comment]
So I found out the solution. Give it some time, you'll get the email with the password. In my case, the mail with password was in the spam folder. That's why I found the mail a week later.
