### ISSUE TITLE
WIP Projects and Registering question 

### ISSUE THREAD

**Issue by Suspense4615** [is-a-dev/register#1029]
Hey there! I currently have two questions about this cool service. Firstly, I'm *thinking* of building a personal website to list project stuff, text documents, mockups.. etc but it is not done and I haven't started yet. Can I still register a isadev domain?

Secondly, I didn't really get how to choose the domain we want. Is it the PRed file's name or the CNAME? If that's the former, what should the CNAME be since it will be replaced with the isadev link? I assume I can use github's free domain thing based on the username

Thanks

**Comment by TheBotlyNoob** [comment]
For the first question: yes, you can still register an `is-a.dev` domain.

For the second question: if you create, lets say `mydomain.json` then that would be `mydomain.is-a.dev`, the `CNAME` should be `mydomain.is-a.dev`. And yes, you can use GitHub Pages.

**Comment by Suspense4615** [comment]
okay, thank you for the quick reply!

**Comment by TheBotlyNoob** [comment]
No problem!
