### ISSUE TITLE
[Bug] SSL_ERROR_UNRECOGNIZED_NAME_ALERT

### ISSUE THREAD

**Issue by Riddim-GLiTCH** [is-a-dev/register#10300]
I tried visiting my website (riddim-glitch.is-a.dev) a couple days ago. And encountered this screen. 
![image](https://github.com/is-a-dev/register/assets/87764384/b4c58b15-9580-43db-b062-ac94b8fc4bab)
I left it then, as I assumed it was an outage or other error of sorts that would soon be resolved. Now, about two days later, I am still seeing this screen upon visiting my site.
### Expected outcome
See this screenshot taken from the last github pages deployment of my website. This page is now deprecated and will soon be set to redirect to the is-a.dev page instead.
![image](https://github.com/is-a-dev/register/assets/87764384/63af4a12-4545-4f96-9033-686cb82cb5f1)

### Observed outcome
`SSL_ERROR_UNRECOGNIZED_NAME_ALERT`
I think there might be an issue with the SSL/TLS handshake, or the SSL Certificate is malformed.

I did the following on my end to troubleshoot the issue
I checked to make sure my browser and the installed certificates are up-to-date.
I observed the same behavior across different platforms, such as my phone, my tablet, and my PC at work.
I observed the same behavior across different web browsers. Tested with Mozilla Firefox and Brave Privacy Browser.
I am not running anti-malware services of any kind other than Windows Defender on Windows, and a strong common sense on Linux.

**Comment by Riddim-GLiTCH** [comment]
Two days after this post the issue persists. Bumping to avoid it from going stale.

**Comment by Riddim-GLiTCH** [comment]
Bump

**Comment by wdhdev** [comment]
This doesn't seem to be occurring anymore.
