### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by asma019** [is-a-dev/register#10314]
Your domain name: bd.is-a.dev

Explain any issues you are facing

I have hosted the website on your hosting. But SSL is issuing. I need Help sir.

Screenshot:
![Screenshot_161](https://github.com/is-a-dev/register/assets/102788416/e2bf41d6-8d13-45cf-8860-bb66c71ca4fe)

Thank you!

**Comment by andrewstech** [comment]
Your site is working for me. It's giving me a 404 as you appear to have deleted the index.html if you are still having SSL issues then clear your cache or use incognito browsing.

**Comment by asma019** [comment]
Yeah, it works now,
