### ISSUE TITLE
Domain Isn't Activated

### ISSUE THREAD

**Issue by dhiyazhar** [is-a-dev/register#10321]
### Expected outcome

After I had replaced the index.html with my own website's files, it should displayed my website. 

### Observed outcome

The site's still showing "Whoops, that site has not been activated visit manage.is-a.dev to activate it.". I had searched manage.is-a.dev thoroughly and can't find anything to activate it. My domain's name is dhiyazhar.is-a.dev

![Screenshot 2023-12-23 215141](https://github.com/is-a-dev/register/assets/63506653/c2032579-2e8d-4000-a807-b45b055ce997)

**Comment by WilliamDavidHarrison** [comment]
Your domain has been activated.
