### ISSUE TITLE
Github login requests excessive permissions

### ISSUE THREAD

**Issue by bast0006** [is-a-dev/register#10342]
### Expected outcome
I was attempting to log into the management site through github. Requesting my email address is fine.

### Observed outcome
It also requests read and _write_ access to _all my public repositories_. I'm not going to give a robot write access to my personal projects to log into a third-party site.

**Comment by WilliamDavidHarrison** [comment]
1. The website requires that permission to modify your fork of is-a-dev/register. We will never update any of your other repositories.
2. The source code for the website is public here: https://github.com/is-a-dev/register.is-a.dev

You can always choose to manually create the file and open a PR that way. The manage site is only to make registration easier and quicker, and you can always unauthorise the app after you're done.
