### ISSUE TITLE
Unable to set up github as hoster with domain .is-a.dev as mentioned in doc.

### ISSUE THREAD

**Issue by kamlendras** [is-a-dev/register#10369]
### Expected outcome
![Screenshot_20231225-081713](https://github.com/is-a-dev/register/assets/96082996/7e8a3854-37c8-4530-b66b-37f31a37580c)

### Observed outcome
![Screenshot_20231225-081251](https://github.com/is-a-dev/register/assets/96082996/88ae21f3-4dbd-4890-93ad-13bcc4f45f7e)

I did the same as manual mentioned but it didn't worked :(

**Comment by kamlendras** [comment]
Help indeed!

**Comment by VaibhavSys** [comment]
Your domain is using is-a-dev hosting records, not GitHub Pages.

**Comment by kamlendras** [comment]
> Your domain is using is-a-dev hosting records, not GitHub Pages.

So how to use github pages?
I did tried to use that domain in gh-pages domain section, but that just redirected to 404 page of is-a.dev

**Comment by wdhdev** [comment]
Please read the documentation, do not create issues for these simple issues. https://www.is-a.dev/docs
