### ISSUE TITLE
Please no kaizerzone.is-a.dev i want dujexsplays.is-a.dev

### ISSUE THREAD

**Issue by DujexsYT** [is-a-dev/register#10403]
## 🔍 ReviewMate Analysis
File: [domains/kaizerzone.json](https://github.com/is-a-dev/register/blob/1f08b2e37a6a72feb84d9845f7cede6abade7bc2/domains%2Fkaizerzone.json)
Content URL: http://dujexsyt.github.io

<details>
<summary><h3>📸 Screenshot</h3></summary>

![domains/kaizerzone.json](https://i.ibb.co/cDmh1ny/d84a02995334.png)
</details>

_Originally posted by @reviewmate[bot] in https://github.com/is-a-dev/register/issues/10402#issuecomment-1869184007_

**Comment by WilliamDavidHarrison** [comment]
You just need to rename your file and open another PR.
