### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by zenjahid** [is-a-dev/register#10405]
Your domain name: 
jahid.is-a.dev
zenjahid.is-a.dev

Explain any issues you are facing
I get a web page with this message instead "Whoops, that site has not been activated visit manage.is-a.dev to activate it."

Comment
After receiving the validation email, I logged in to manage.is-a.dev, used the FTP credentials to edit the "index.html" file but nothing seems to work.

**Comment by andrewstech** [comment]
Hello, I have manually activated both your domains
