### ISSUE TITLE
Hosting settings not working

### ISSUE THREAD

**Issue by netsterX** [is-a-dev/register#10400]
abdel.is-a.dev

my domain is on the is-a.dev hosting and when I try to go to the hosting settings to change the password I get redirected but I always get ERR_SSL_UNRECOGNIZED_NAME_ALERT
and when I change the url to http only I get 'go away' as a response from hosts.is-a.dev/api/panel?domain=abdel&jwt=ey....
Please help me !!!!

**Comment by andrewstech** [comment]
> abdel.is-a.dev
> 
> my domain is on the is-a.dev hosting and when I try to go to the hosting settings to change the password I get redirected but I always get ERR_SSL_UNRECOGNIZED_NAME_ALERT and when I change the url to http only I get 'go away' as a response from hosts.is-a.dev/api/panel?domain=abdel&jwt=ey.... Please help me !!!!

Sorry for the late response when it says go away is that on the page or in some console.

Your record included an IPV6 address of our old server and I'm wondering if someone else had taken it over. Not to worry it's been removed from your subdomain now.

**Comment by abdessattarElyagoubi** [comment]
thank you so much @andrewstech

**Comment by andrewstech** [comment]
> thank you so much @andrewstech 

Your welcome
