### ISSUE TITLE
Status returns 504. manage.is-a.dev has expired ssl certificate

### ISSUE THREAD

**Issue by Jirafey** [is-a-dev/register#10459]
https://manage.is-a.dev
https://status.is-a.dev

Expected outcome:
working status website and manage.is-a.dev

Outcome:
![image](https://github.com/is-a-dev/register/assets/97115044/7c3122d3-4878-4136-967e-0529c9e2229b)

**Comment by andrewstech** [comment]
Thanks for reporting this. Both sites are now back online.
