### ISSUE TITLE
DNS issues

### ISSUE THREAD

**Issue by ScytheMed1a** [is-a-dev/register#10544]
I'm trying to add dns records for playit.gg but I have no idea how.
If someone could answer that would be great.

![image_2023-12-30_123447787](https://github.com/is-a-dev/register/assets/51488969/c29cddaf-5b1d-4b7b-b475-c95be41db3e3)

**Comment by ScytheMed1a** [comment]
this is more like an support question

**Comment by andrewstech** [comment]
I'm sorry but we don't support NS records.
