### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by yanNotDev** [is-a-dev/register#1061]
Your domain name:
https://yan.is-a.dev/
Explain any issues you are facing
Redirects to https://www.is-a.dev/

**Comment by hackermondev** [comment]
Clear your cache, it works fine for me.
![image](https://user-images.githubusercontent.com/60828015/130441435-95e2425a-b73f-4368-a8e2-9e080df8b514.png)

**Comment by yanNotDev** [comment]
oh that worked, ty
