### ISSUE TITLE
My domain not works.

### ISSUE THREAD

**Issue by Hemal80** [is-a-dev/register#10621]
Your domain name:
bangladesh.is-a.dev
hemal.is-a.dev
hemalmondal.is-a.dev
jv.is-a.dev
sudo.is-a.dev
sudosu.is-a.dev
su.is-a.dev
supusr.is-a.dev

Explain any issues you are facing
Whoops, that site has not been activated visit manage.is-a.dev to activate it.
![chrome_vjZZ2aV0Wy](https://github.com/is-a-dev/register/assets/90780543/d6f43c7f-63c6-4e14-af47-b29257674620)
![chrome_yAJ6vlrkAG](https://github.com/is-a-dev/register/assets/90780543/72874810-9e51-4f41-89cf-f9e77c0e62aa)

**Comment by andrewstech** [comment]
I have just activated all your domains
