### ISSUE TITLE
Whoops, that site has not been activated visit manage.is-a.dev to activate it.

### ISSUE THREAD

**Issue by boomshakazulu** [is-a-dev/register#10628]
ftp upload completed

### Expected outcome
navigating to dallonlahoda.is-a.dev should bring up my site

### Observed outcome
navigating to dallonlahoda.is-a.dev brings up "Whoops, that site has not been activated visit manage.is-a.dev to activate it."

**Comment by andrewstech** [comment]
Your site has been activated
