### ISSUE TITLE
Website not showing up unexpectedly

### ISSUE THREAD

**Issue by chadcat7** [is-a-dev/register#10686]
### Expected outcome
The link https://nam.is-a.dev should work and show the website at chadcat7.github.io

### Observed outcome
It redirects to is-a.dev now. Even though there were no commits made earlier that could have caused this. This started happening randomly

**Comment by danknessdra** [comment]
This is also happening to me https://rmd.is-a.dev/

**Comment by wdhdev** [comment]
This issue is resolved.
