### ISSUE TITLE
Domain  error

### ISSUE THREAD

**Issue by jOaawd** [is-a-dev/register#10697]
when i try to vist my domain it says 
*

This site can’t be reachedThe webpage at https://fmode.is-a.dev/ might be temporarily down or it may have moved permanently to a new web address.
ERR_SSL_UNRECOGNIZED_NAME_ALERT

*

**Comment by jOaawd** [comment]
and now it says Whoops, that site has not been activated visit manage.is-a.dev to activate it.** i just uploaded ftp files to my site how do i activate it??//

**Comment by CuteDog5695** [comment]
![image](https://github.com/is-a-dev/register/assets/69630113/e6e4df5e-ac23-4bc7-93c5-22b9d634c339)
activated the subdomain for you, it should now show your website

**Comment by jOaawd** [comment]
Okay let me check! and thanks

**Comment by jOaawd** [comment]
> ![image](https://private-user-images.githubusercontent.com/69630113/294137724-e6e4df5e-ac23-4bc7-93c5-22b9d634c339.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzOTU5NTUsIm5iZiI6MTcwNDM5NTY1NSwicGF0aCI6Ii82OTYzMDExMy8yOTQxMzc3MjQtZTZlNGRmNWUtYWMyMy00YmM3LTkzYzUtMjJiOWQ2MzRjMzM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDE5MTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlMjVhZTMzOGJlY2NhNjE5N2VmYmI3ZTQ0MGE1NTQ4NzEwYjYwNTQ1ZTRlNTYzZjkzNjE2NDgxNGRmZjFmNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NGCpcn4tdpbFEUCDh3KgBiaLGVgqOwft8aOjKja5HH0) activated the subdomain for you, it should now show your website


I try to go to my subdomain but it says, *This site can’t be reachedThe webpage at https://fmode.is-a.dev/ might be temporarily down or it may have moved permanently to a new web address.
ERR_SSL_UNRECOGNIZED_NAME_ALERT*

**Comment by CuteDog5695** [comment]
try clearing your cache, might be that problem. btw the website shows this so you might want to double check your code
![image](https://github.com/is-a-dev/register/assets/69630113/9ec218cb-6822-40ba-8475-9d0099509b84)

**Comment by CuteDog5695** [comment]
ima assume issue is resolved so im closing it now. if you still have an issue make another one
