### ISSUE TITLE
Feedback/suggestion

### ISSUE THREAD

**Issue by IbrahimDevX** [is-a-dev/register#1069]
Make a @is-a.dev email. Not like MX records so like if u have Ibrahim.is-a.dev you could also get ibrahim@is-a.dev too.

Cheers

**Comment by phenax** [comment]
@IbrahimDevX, unfortunately, that is dangerous as it can allow people to impersonate being a representative of the is-a-dev team. We are working on adding MX records to the website and it will be available soon. Follow #844, for updates. Closing issue.
