### ISSUE TITLE
Registration Issue

### ISSUE THREAD

**Issue by TartejBrothers** [is-a-dev/register#10725]
### Expected outcome
I was registering for a new domain and it showed up this error. My current site is hosted on Firebase

### Observed outcome
![image](https://github.com/is-a-dev/register/assets/112921727/76646804-d19a-4e77-821f-c769453ae2ee)

**Comment by wdhdev** [comment]
Is this issue still occurring?

**Comment by andrewstech** [comment]
This message usually appears if the file already exists in your fork but not the main repo
