### ISSUE TITLE
URL Record isn't redirecting to my new site

### ISSUE THREAD

**Issue by vachanmn123** [is-a-dev/register#10813]
Hey! I raised a Pull Request that was merged recently, I put a URL record to my new website: #10642

I want https://vachanmn.is-a.dev/ to redirect to https://vachanmn.tech/

Please tell me where I may have messed up and how I can fix it. 

Thanks

**Comment by b1ek** [comment]
looks like ci/cd errored out or something since there are no A/AAAA recods for that domain

**Comment by vachanmn123** [comment]
There is an A record on that domain, is there a way to re-trigger the CI/CD so it can try again or something?

**Comment by b1ek** [comment]
> There is an A record on that domain

uhh, no. no, there isn't.

```bash
$ nslookup vachanmn.is-a.dev 
Server:		1.1.1.1
Address:	1.1.1.1#53

Non-authoritative answer:
*** Can't find vachanmn.is-a.dev: No answer
```

Also, [you kind of removed it yourself](https://github.com/is-a-dev/register/pull/10642/files). I suppose that this "URL" thing should automatically set the A/AAAA to the is-a.dev ip (which would make the redirect), but as you can see it didnt work

**Comment by vachanmn123** [comment]
The docs tell me to simply put in a URL Record that would point to my new domain... Is the fix going to be to add a A/AAAA record? If so, where should it point to?

**Comment by vachanmn123** [comment]
okay, so I did some digging around (pun unintended) and realised the CI pipeline is supposed to create a A record for my domain pointing to 68.65.123.44 (Like every other domain). 

Here is an example of a domain with a URL Record...

```
NAME         | TTL    | DATA        
-------------+--------+-------------
cli.is-a.dev | 1,200s | 68.65.123.44
```

I am guessing maybe manually triggering the CI pipeline so it creates the required record would be the fix?

**Comment by vachanmn123** [comment]
Bump! Anyone with a solution?

**Comment by vachanmn123** [comment]
The PR didn't seem to fix it, can someone please assist me?

**Comment by wdhdev** [comment]
I'm not gonna lie, I have no clue why this is happening.
@phenax Can you look into this? The records should be published.

**Comment by wdhdev** [comment]
@vachanmn123 Would you be willing to try deleting the domain and recreating it?

**Comment by vachanmn123** [comment]
Sure I can try that

**Comment by wdhdev** [comment]
@vachanmn123 Can you open a PR deleting your domain and I will merge it, then once I've merged it open a PR re-adding your domain and I'll merge that.

**Comment by vachanmn123** [comment]
I've made a PR deleting my domain

**Comment by wdhdev** [comment]
Merged, can you now recreate your file.

**Comment by vachanmn123** [comment]
I have made the new PR

**Comment by vachanmn123** [comment]
https://github.com/is-a-dev/register/actions/runs/7550686254/job/20556703575

Action run seems to have an error, 
Adding zone for pss-us-01.oxmc: (A 73.140.108.118:3001)...
0/1
[
  {
    "result": {
      "statusmsg": "Invalid DNS record: Supplied address for A record is invalid",
      "newserial": null,
      "status": 0
    }
  }
]
{
  added: 2,
  removed: 0
}

**Comment by DEV-DIBSTER** [comment]
Yeah that wasn't supposed to be merged... A record should have just been a straight IP.

**Comment by vachanmn123** [comment]
Any progress?

**Comment by wdhdev** [comment]
No

**Comment by vachanmn123** [comment]
Anything yet?

**Comment by CuteDog5695** [comment]
so nothing at the moment, but we are still looking into the issue

**Comment by YouFoundAlpha** [comment]
You could use https://redirect.pizza to redirect from the is-a.dev domain to your own domain

**Comment by vachanmn123** [comment]
I think I will do that.. Thanks @YouFoundAlpha

**Comment by YouFoundAlpha** [comment]
Could someone close this issue
It has been resolved
https://github.com/is-a-dev/register/pull/11493

**Comment by CuteDog5695** [comment]
issue resolved (as Alpha said) so ill close this now
