### ISSUE TITLE
One commit damaged all files

### ISSUE THREAD

**Issue by b1ek** [is-a-dev/register#10825]
Hey yall, I noticed that my domain: `blek.is-a.dev` (#5389) is a 301 redirect, so after a little research i found that [this commit](https://github.com/is-a-dev/register/commit/c06f9ce77c46bfad906805a9e38fa2e23f930143) deleted it.

It appears to belong to #10689, which has been merged a few days ago. It damaged some other files as well.

I tried to open a revert PR, but github wouldn't let me.

Its also funny how it comes up as a blank commit in the PR viewer but is actually quite dangerous.

**Comment by wdhdev** [comment]
@b1ek That merge commit would not have been why your domain was removed. It was most likely removed as a part of the domain cleanup where our script must've detected your domain name as unreachable so it was removed.

**Comment by b1ek** [comment]
> @b1ek That merge commit would not have been why your domain was removed. It was most likely removed as a part of the domain cleanup where our script must've detected your domain name as unreachable so it was removed.

yeah, i found it: #9882
