### ISSUE TITLE
Issue with Subdomain Redirection (lakhindar.is-a.dev)

### ISSUE THREAD

**Issue by LakhindarPal** [is-a-dev/register#10840]
### Expected outcome
I expect my subdomain `lakhindar.is-a.dev` to correctly point to my designated content or website.

### Observed outcome
Recently, when accessing `lakhindar.is-a.dev`, it redirects to the `is-a.dev` site instead of displaying my content. This issue started occurring recently, and I haven't made any changes on my end.

I've attached a screenshot of the observed outcome
![Screenshot_2024-01-07-17-21-32-29_4641ebc0df1485bf6b47ebd018b5ee76](https://github.com/is-a-dev/register/assets/72681474/3fdc43e9-7de6-4824-aabb-b0d3253cc03c)

**Comment by CuteDog5695** [comment]
![image](https://github.com/is-a-dev/register/assets/69630113/8e12a809-1686-4c08-a7ee-cc7ffc2fc41b)
sorry for late reply but maintenance is over and your website is back, so ill close this issue now
