### ISSUE TITLE
Subdomain Redirection Issue

### ISSUE THREAD

**Issue by SealedSaucer** [is-a-dev/register#10841]
### Expected outcome

My subdomain `phantom.is-a.dev` should redirect to the website given in the repo.

### Observed outcome

The subdomain redirects to `www.is-a.dev` instead of the designated website in the repo.

![image](https://github.com/is-a-dev/register/assets/71928730/6c600c8d-cef5-4e3f-8c50-427c7219750f)
![image](https://github.com/is-a-dev/register/assets/71928730/b18a272f-ac5a-4942-9438-701746d7ce11)

I haven't made any changes in my code or records.

Link to my subdomain file in this repo: https://github.com/is-a-dev/register/blob/main/domains/phantom.json

Thanks.

**Comment by CuteDog5695** [comment]
is-a.dev is in maintenance atm because of dns issues

**Comment by CuteDog5695** [comment]
![image](https://github.com/is-a-dev/register/assets/69630113/7dfd7457-900a-4f6d-acf8-4807b13e8d6d)
site is up so issue resolved, closing this issue now
