### ISSUE TITLE
Issue with subdomain (redirecting to is-a.dev) (domain: akshtt.is-a.dev)

### ISSUE THREAD

**Issue by LegendOP1041** [is-a-dev/register#10852]
Your domain name: akshtt.is-a.dev

Explain any issues you are facing

Under maintenance
is-a.dev website is under maintenance. This doesn't include all the user created subdomains which should function normally.
If you're getting this page on your sub-domain, please create an issue on https://github.com/is-a-dev/register or send an email to phenax5@gmail.com

**Comment by CuteDog5695** [comment]
website is back up so ill close this issue (sorry for late reply btw)
