### ISSUE TITLE
Support - I need help with the dns records.

### ISSUE THREAD

**Issue by TheProgrammingUniversity** [is-a-dev/register#10985]
![image](https://github.com/is-a-dev/register/assets/155764097/acb8e846-901b-440f-8398-260b38f67843)

I have no idea how to fix this and I don't know how to add dns and a records.

**Comment by CuteDog5695** [comment]
you have is-a.dev hosting, so you cant link your github page with your is-a.dev domain unless you change domains.
https://ss.cutedog5695.is-a.dev/raw/i/04KAcYSX.png

**Comment by G2C-DC** [comment]
Is it possible to change it but keep the same domain(tyler.is-a.dev)?

**Comment by CuteDog5695** [comment]
of course, you just change the records in the file then make a PR (if you dont know how to do it look here https://www.is-a.dev/docs/github_pages/)

**Comment by G2C-DC** [comment]
Thanks!

**Comment by G2C-DC** [comment]
I still don't understand this...
Can you possibly do it?

**Comment by G2C-DC** [comment]
Also, is it possible to move a domain from my account to another account?

**Comment by VaibhavSys** [comment]
> I still don't understand this... Can you possibly do it?

What do you not understand?

> is it possible to move a domain from my account to another account?
Yes, change the `username` field in the JSON file to the account username you want to transfer to. This must be done from the current username in it.

**Comment by G2C-DC** [comment]
> > I still don't understand this... Can you possibly do it?
> 
> What do you not understand?
> 
> > is it possible to move a domain from my account to another account?
> > Yes, change the `username` field in the JSON file to the account username you want to transfer to. This must be done from the current username in it.

It does not allow me to add files to domains file

**Comment by TheProgrammingUniversity** [comment]
Nevermind, I got it.
