### ISSUE TITLE
Error while uploading zip file in ftp editor.

### ISSUE THREAD

**Issue by LakhindarPal** [is-a-dev/register#11028]
Your domain name: lakhindar.is-a.dev

**Explain any issues you are facing**
I'm facing error while uploading zip file in ftp editor. I was trying to upload a zip file, and it said `Archive LakhindarPal.zip was not processed because its filename extension was not recognized. Only zip, tar, tgz and gz archives are supported at the moment.`

![Screenshot_2024-01-12-10-28-49-76_4641ebc0df1485bf6b47ebd018b5ee76](https://github.com/is-a-dev/register/assets/72681474/616b18b6-f16e-4272-b00e-d6f9adfc258f)

**Comment by andrewstech** [comment]
Unfortunately this is a bug with net2FTP which is a third party site that acts as an FTP client. I would try using a different FTP client.

**Comment by LakhindarPal** [comment]
Facing the same issue with tar, tgz extension also
