### ISSUE TITLE
Support for Certificate already exists for nithin.is-a.dev and is usable.

### ISSUE THREAD

**Issue by nithinlycanz** [is-a-dev/register#11030]
Your domain name: nithin.is-a.dev

Explain any issues you are facing
IT shows Certificate already exists for nithin.is-a.dev and is usable.

**Comment by VaibhavSys** [comment]
Your site seems to be working, what is the issue?
> IT shows Certificate already exists for nithin.is-a.dev and is usable.

Can you define "it"?

**Comment by nithinlycanz** [comment]
It is not showing my website even if I login to ftp SSL certificate is not getting access

**Comment by wdhdev** [comment]
Your domain seems to be resolvable, closing this issue.
