### ISSUE TITLE
EMAIL FEEDBACK.

### ISSUE THREAD

**Issue by andrewstech** [is-a-dev/register#11057]
Place your feedback here.

**Comment by KennySB-dev** [comment]
User Interface and Design: pretty sleek, and easy to use/user-friendly.
in my opinion the only thing i would change would be the font used when reading the email message, as its grayed out on gray background.

Performance and Reliability: Pretty good speed regarding when the emails arrive after they are sent (when i tested it, once gmail said sent it loaded in the is-a.dev mailbox after 3-5 seconds, but obv it will vary with internet speeds, and i dont have the best   internet) all the buttons/features included work, and do their job.

Features and Functionality: I dont think that is-a.dev needs more features, it already has very easy methods to create a sub domain, and has docs, which i know some free subdomains that dont have any of those.

Security and Privacy: I dont see any privacy issues in is-a.dev, especially sinse a maintener confirmed that you guys have an anti ddos program (i forgot what its called) with the mail domains.

overall rating: 10/10 :D very nice helpers/contributers... etc
