### ISSUE TITLE
Restore deleted domains

### ISSUE THREAD

**Issue by LakhindarPal** [is-a-dev/register#11113]
Your domain name: lakhindar.is-a.dev

I observed that my file, along with files from other users, has been deleted without notice. I kindly request a thorough investigation into this matter and appropriate measures to address the issue promptly.

**Comment by CuteDog5695** [comment]
is-a.dev hosting got shutdown, thats why it got deleted

**Comment by wdhdev** [comment]
After conducting a thorough investigation, I have concluded that the PR was made by a 22 year old guy named Andrew who lives in the UK.

**Comment by CuteDog5695** [comment]
btw heres the PR where your PR got deleted https://github.com/is-a-dev/register/pull/11098

**Comment by LakhindarPal** [comment]
I checked dashboard, it's showing I don't have any domain. When I tried to create a new domain using the same old subdomain (lakhindar), it's showing unavailable

**Comment by wdhdev** [comment]
You will need to delete your fork first.
