### ISSUE TITLE
DNS check unsuccessful

### ISSUE THREAD

**Issue by LakhindarPal** [is-a-dev/register#11152]
**Your domain name:** lakhindar.is-a.dev

**Explain any issues you are facing**

Facing this problem while adding custom domain at github-pages.
`
lakhindar.is-a.dev is improperly configured
Your site's DNS settings are using a custom subdomain, lakhindar.is-a.dev, that is set up as an A record. We recommend you change this to a CNAME record pointing to lakhindarpal.github.io. For more information, see documentation (InvalidARecordError).
`

**Comment by LakhindarPal** [comment]
I'd created the pull request using `CNAME` record. See #11119

**Comment by YouFoundAlpha** [comment]
@LakhindarPal You can try changing your CNAME record to point to github's A records like this:
```
    "A": [
      "185.199.108.153",
      "185.199.109.153",
      "185.199.110.153",
      "185.199.111.153"
    ]
    ```

**Comment by wdhdev** [comment]
The site is resolvable, closing this issue.
