### ISSUE TITLE
DNS Records Not Updated

### ISSUE THREAD

**Issue by itsmenewbie03** [is-a-dev/register#11174]
Your domain name: `itsmenewbie03.is-a.dev`

My domain was created yesterday through #11143.
However until today the domain still points to `68.65.123.44`
![image](https://github.com/is-a-dev/register/assets/89230263/38e36730-01a4-49ee-a10f-460b8325fa67)
And not on my server's ip `46.250.251.63`.

**Comment by wdhdev** [comment]
@phenax Records aren't being deployed again.
