### ISSUE TITLE
Support DNS Check Fail

### ISSUE THREAD

**Issue by tootypatrooty6** [is-a-dev/register#11214]
Your domain name: blockbreaker.is-a.dev

Explain any issues you are facing:
I keep getting a failed dns error whenever I try connecting my domain to pages. Here is my error:
blockbreaker.is-a.dev is improperly configured
Your site's DNS settings are using a custom subdomain, blockbreaker.is-a.dev, that is set up as an A record. We recommend you change this to a CNAME record pointing to theblockbreaker.github.io. For more information, see (documentation link)

please help!!!!

**Comment by wdhdev** [comment]
1. Your subdomain's DNS has probably not updated yet.
2. I've noticed that your domain is pointing to another person's GitHub.io subdomain (theblockbreaker.github.io), is this correct?

**Comment by tootypatrooty6** [comment]
Do I create a web server here? 
<img width="562" alt="image" src="https://github.com/is-a-dev/register/assets/113472285/072ebe3b-4670-4584-94c9-f205b6c382b3">

**Comment by wdhdev** [comment]
is-a.dev Hosting was shut down, that shouldn't be an option on the site.
