### ISSUE TITLE
Still doesn't work

### ISSUE THREAD

**Issue by meesam4687** [is-a-dev/register#11241]
### It redirects to is-a.dev homepage 
I have waited for 24 hours and it still redirects.

**Comment by YouFoundAlpha** [comment]
@meesam4687 Try clearing your browser cache and try again

**Comment by meesam4687** [comment]
> @meesam4687 Try clearing your browser cache and try again
Nope still doesn't

**Comment by YouFoundAlpha** [comment]
Have you tried changing the record from CNAME to A records?
like this:
```
    "A": [
      "185.199.108.153",
      "185.199.109.153",
      "185.199.110.153",
      "185.199.111.153"
    ]

**Comment by meesam4687** [comment]
It started working on its own.
Thanks for trying to help.

**Comment by YouFoundAlpha** [comment]
> It started working on its own. Thanks for trying to help.

👍🏻
