### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by heyjumanji** [is-a-dev/register#11296]
### Website down
The website and the domain are down non of the website are loading?

**Comment by wdhdev** [comment]
I don't seem to be able to replicate this issue, what is your subdomain?

**Comment by heyjumanji** [comment]
> I don't seem to be able to replicate this issue, what is your subdomain?

jumanji.is-a.dev & heyjumanji.is-a.dev

**Comment by wdhdev** [comment]
@heyjumanji is-a.dev Hosting was shutdown, therefore your domains were removed.
