### ISSUE TITLE
????!!!!

### ISSUE THREAD

**Issue by spacewd69** [is-a-dev/register#11303]
### Your subdomain
spacewd.is-a.dev
### The issue
Getting an error when I registered with CNAME
![Screenshot_20240120_004744_Chrome](https://github.com/is-a-dev/register/assets/121475790/11e85ab6-b7dd-481b-be1c-80cfe5c1be36)

**Comment by wdhdev** [comment]
Your DNS seems to not have been deployed yet. This is a known issue.

**Comment by spacewd69** [comment]
Oh, I configured spacewd69.is-a.dev wrong so I made this one

**Comment by wdhdev** [comment]
Enable enforce HTTPS, that should fix any issues.

**Comment by spacewd69** [comment]
I'll try but it said unavailable in the screenshot I provided

**Comment by spacewd69** [comment]
Last comment of this issue
Ladies and gentlemen, it works.
