### ISSUE TITLE
Subdomain gone

### ISSUE THREAD

**Issue by tharth0ur** [is-a-dev/register#11332]
### now it's gone, when i type "athir.is-a.dev" it redirects me to "www.is-a.dev" with a message (below) and i can't register it again, **can you help ?**

Redirecting you to [www.is-a.dev](https://www.is-a.dev/)...

If you were expecting your website to show up here, it may take some time for your changes to reflect.

**Comment by wdhdev** [comment]
Your domain was removed because it used is-a.dev hosting, which was shutdown.

**Comment by tharth0ur** [comment]
> Your domain was removed because it used is-a.dev hosting, which was shutdown.
> 
> If you would like your files, you can join our Discord server and ping me there: https://discord.gg/PZCGHz4RhQ

Well i don't need the hosting or the files but i still want the subdomain back, is that possible?

**Comment by CuteDog5695** [comment]
you can get the domain back by re-registering the domain

**Comment by tharth0ur** [comment]
> you can get the domain back by re-registering the domain

i've been trying but I can't, can anyone remove it so i can re-register?

![Screenshot_20240121_145138.jpg](https://github.com/is-a-dev/register/assets/45873643/fd809f7e-6718-42b2-9a6b-72f1beb546d4)

**Comment by wdhdev** [comment]
Delete your fork and try again.
