### ISSUE TITLE
Support - Delete prakarsh.is-a.dev and replace by infinotiver.is-a.dev

### ISSUE THREAD

**Issue by prakarsh17** [is-a-dev/register#11369]
### Your subdomain
prakarsh.is-a.dev (working)
registered for infinotiver.is-a.dev
### The issue
I am young and I tend to make mistakes...
I had forked this repo very early and edited to add prakarsh.is-a.dev domain but I didnt require it so I didnt opened a pull requests now 2 years after or so I used web dashboard to register infinotiver.is-a.dev (but I dont think that registered correctly because of the already forked repo)..

I would be very grateful if you guys delete prakarsh.is-a.dev and register infinotiver.is-a.dev correctly
Regards

**Comment by wdhdev** [comment]
You can delete your fork, then re-fork the repository deleting your old domain and adding your new one.
