### ISSUE TITLE
Change a txt record...

### ISSUE THREAD

**Issue by giocoliere** [is-a-dev/register#11375]
### Your question
Hi, I'm the register of gioco.is-a.dev connected to giocoliere.github.io ...i'm making the request, due to an error, to change the following txt record
from:     _github-pages-challenge-giocoliere.gioco.is-a.dev                                6da8f68c4f74f990d4d75ad48bdd93
into:      _github-pages-challenge-giocoliere.gioco.is-a.dev                                606e07dc7ac1839e0ba38403e1a710

so i can verify the domain on my github profile and put it into my page, cuz now if i go to gioco.is-a.dev it says this:
![Screenshot 2024-01-22 185957](https://github.com/is-a-dev/register/assets/95962492/8f322419-7476-4241-af94-6b50e6682be9)

**Comment by wdhdev** [comment]
https://docs.is-a.dev
