### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by giocoliere** [is-a-dev/register#11409]
### Your subdomain
giocoliere.is-a.dev and gioco.is-a.dev
### The issue
Hi, i was asking for help: i registered both subdomains in the website of manage.is-a.dev, and both got accepted and now can't be registered...but when i check on the domain list i see only gioco.is-a.dev
![Screenshot 2024-01-23 223345](https://github.com/is-a-dev/register/assets/95962492/af6d3de9-8132-4102-a4ae-8b7d26c70408)

**Comment by giocoliere** [comment]
![Screenshot 2024-01-23 223452](https://github.com/is-a-dev/register/assets/95962492/54c0e570-c0cd-4cd3-9790-cadf4e0709f4)

**Comment by wdhdev** [comment]
It doesn't seem to exist: https://github.com/is-a-dev/register/tree/main/domains/giocoliere.json

Was your domain using is-a.dev Hosting?

**Comment by giocoliere** [comment]
Ye I think so

**Comment by CuteDog5695** [comment]
then it got removed since is-a.dev hosting shutdown, you'd need to re-register the domain if you want that domain

**Comment by giocoliere** [comment]
on the website is inpossible...i tried

**Comment by wdhdev** [comment]
Do you still want your hosting files? If so, please join our Discord server in the README.

**Comment by giocoliere** [comment]
Done
