### ISSUE TITLE
Unused/Broken Domains

### ISSUE THREAD

**Issue by TheBotlyNoob** [is-a-dev/register#1150]
This is just to notify everyone who has a broken/unused domain.
If you need help fixing your domain, comment on this issue, or create a new issue.
If you have just parked a domain for later use, we ask that you give it away to someone else who might put it to better use.

> If you are having issues with Vercel or Netlify, try [Railway](https://railway.app?referralCode=jj)

<details>
<summary><b>Users who have broken domain(s)</b></summary>
<p>

@Drago-Dev24 - drago.is-a.dev
@cmulay - cmulay.is-a.dev
@ashiishme - ashish.is-a.dev
@abhishek-sankar - abhishek.is-a.dev
@TheBotlyNoob - cloudy.is-a.dev
@hackermondev - botspointer.is-a.dev
@dariatrainor - daria.is-a.dev
@deadshotofficial - deadshot.is-a.dev
@gvagenas - devrealm.is-a.dev
@Athira-L-I - athira-li.is-a.dev
@AtulPatil-me - atul.is-a.dev
@Avnoor-Gamerz - avnoor-gamerz.is-a.dev
@B45i - b45i.is-a.dev
@awanshrestha - awan.is-a.dev
@AozoraDev - aozora.is-a.dev
@echo2477 - echo2477.is-a.dev
@dotiful - art.is-a.dev
@Danix421 - danix.is-a.dev
@eldinesh - dinesh.is-a.dev
@designbyadrian - designer.is-a.dev
@hackermondev - developerjosh.is-a.dev
@AugustinJose1221 - augustin.is-a.dev
@wafflecoffee - emma.is-a.dev
@vitordino - dino.is-a.dev
@ericp3reira - ericp3reira.is-a.dev
@thispsj - f2cqjkp4gwog.is-a.dev
@asadkhan777 - asad-khan.is-a.dev
@dbarnes18 - dillonb07.is-a.dev
@alexkjoseph - alexjoseph.is-a.dev
@BhadraJayakumarSandhya - bhadra.is-a.dev
@ezedinff - ezedinff.is-a.dev
@Erisa - erisa.is-a.dev
@Farzanfa - farzan.is-a.dev
@TheBotlyNoob - fonts.is-a.dev
@7xh - flexico.is-a.dev
@forsas - forsas.is-a.dev
@fsanchir - fsanchir.is-a.dev
@FatGrizzly - fatgrizzly.is-a.dev
@iamganeshsekhar - ganesh.is-a.dev
@tewarig - gaurav.is-a.dev
@GiladE - gilad.is-a.dev
@gkhabas76 - govinda.is-a.dev
@Nystrex - hadi.is-a.dev
@super-jedi - harikrishnanps.is-a.dev
@Harikrishnan6336 - harikrishnan.is-a.dev
@harshpat - harsh-patel.is-a.dev
@haseena-hassan - haseena.is-a.dev
@hikaruisasleep - hikaru.is-a.dev
@hishamalip - hisham.is-a.dev
@huajianmao - hjmao.is-a.dev
@iamsdas - iamsdas.is-a.dev
@undefined - iop3.is-a.dev
@Hidden-black - hiddenblack.is-a.dev
@ging-dev - gingdev.is-a.dev
@Hugovidafe - hugovidafe.is-a.dev
@DevJustForever - justforever.is-a.dev
@kartiktalwar2003 - kartik.is-a.dev
@Kaweees - kaweees.is-a.dev
@whynaidu - ivedant.is-a.dev
@ivolimasilva - ivolimasilva.is-a.dev
@jeevan900929 - jeevan.is-a.dev
@thedemonium - demonium.is-a.dev
@aryavinodan - arya.is-a.dev
@Johannestegner - jite.is-a.dev
@aanthr0 - aanthr0.is-a.dev
@govind-shenoy - govind.is-a.dev
@TheBotlyNoob - ish.is-a.dev
@jacob13400 - jacob.is-a.dev
@dipan29 - dipan.is-a.dev
@heyimnitho - kaguwo.is-a.dev
@KevinBrogan - kevin.is-a.dev
@kiranhart - kiran.is-a.dev
@miltzi - josh.is-a.dev
@lacti - lacti.is-a.dev
@hackermondev - lazyllama.is-a.dev
@lijujayakumar - liju.is-a.dev
@JavaScriptpy - kyle.is-a.dev
@Killua7362 - killua.is-a.dev
@laxminagln - laxminag.is-a.dev
@Whtery1087 - meloun7.is-a.dev
@double-square - levprograming.is-a.dev
@LukeIsHereToDevelop - luke.is-a.dev
@liquiddevelopmentnet - lxquid.is-a.dev
@hackermondev - lord-xenon.is-a.dev
@mbrav - mb.is-a.dev
@LellisV2 - lellis.is-a.dev
@joeleeofficial - login-brawley.is-a.dev
@Eyobyb - medhanite.is-a.dev
@michaelmano - michael.is-a.dev
@mioscape - mioscape.is-a.dev
@mklabs - mk.is-a.dev
@MohanedAshraf - moha.is-a.dev
@mikeattara - mpy.is-a.dev
@madhank93 - madhan.is-a.dev
@mamunhpath - mamun.is-a.dev
@saifulppro - lazycoder.is-a.dev
@patriciafelixx - patriciafelix.is-a.dev
@MysteriousK69 - mysteriousk.is-a.dev
@LejhandGamingYT - lejhand.is-a.dev
@melwyn95 - melwyn.is-a.dev
@Koolwiza - koolwiza.is-a.dev
@m42e - m42e.is-a.dev
@MaximKing1 - maximking.is-a.dev
@Radiergummi - moritz.is-a.dev
@codethoma - mrthundergod.is-a.dev
@MarkusJx - markus.is-a.dev
@opensourze - opensourze.is-a.dev
@Pajsen9263 - pajsen.is-a.dev
@paranoiasystem - paranoiasystem.is-a.dev
@nimish-gupta - nimish.is-a.dev
@neslinesli93 - neslinesli93.is-a.dev
@notefct - notefct.is-a.dev
@vnom1 - ntg.is-a.dev
@undefined - picklerick.is-a.dev
@OraSora - notsora.is-a.dev
@Nirlep5252 - nirlep.is-a.dev
@owainjones74 - owain.is-a.dev
@nishch - nishant.is-a.dev
@marcchew - marcchew.is-a.dev
@OceanTechnic - ocean.is-a.dev
@philphirn - psj.is-a.dev
@markdimi - markos.is-a.dev
@TheBotlyNoob - r4yish.is-a.dev
@hogakesan - r2d2.is-a.dev
@Rapixar - rapixar.is-a.dev
@rahuldahal - rahul.is-a.dev
@perisrai - peris.is-a.dev
@prajaymas - prabhakaranjm.is-a.dev
@nandkk05 - nand.is-a.dev
@hackermondev - nathan.is-a.dev
@hackermondev - pyro.is-a.dev
@PraveenPal4232 - praveen.is-a.dev
@reuben-x - reuben.is-a.dev
@rogerpanza - roger.is-a.dev
@psharma04 - psharma.is-a.dev
@sparkstark03 - rusiru.is-a.dev
@treboryx - robert.is-a.dev
@saeef - saeef.is-a.dev
@rohithp7777 - rohith.is-a.dev
@Raksixoffical - raksix.is-a.dev
@Diordnas - sandro.is-a.dev
@u0f - retr0.is-a.dev
@Rayvid - rayvid.is-a.dev
@martinthampi - saviomartin.is-a.dev
@reed-jones - reed.is-a.dev
@X3NOSIZ - pratyay.is-a.dev
@ScarVite - scarvite.is-a.dev
@saviomartin - savio.is-a.dev
@shajanjp - shajanjp.is-a.dev
@Vandesm14 - shane.is-a.dev
@SharifClick - sharifclick.is-a.dev
@sifulbd - siful.is-a.dev
@GameGodS3 - sudev.is-a.dev
@string-null - string-null.is-a.dev
@insuusvenerati - stiforr.is-a.dev
@ShambhaviCodes - shambhavi.is-a.dev
@sshyran - shyran.is-a.dev
@SkyLeite - sky.is-a.dev
@SlavicMan - slavicman.is-a.dev
@TheBotlyNoob - solareclipse995.is-a.dev
@smartfrigde - smartfridge.is-a.dev
@StalkerMeyr - space.is-a.dev
@syofyanzuhad - syofyanzuhad.is-a.dev
@snaildos - snaildos.is-a.dev
@tonetheman - tonycolston.is-a.dev
@tsull360 - tsull360.is-a.dev
@Btwonu - val.is-a.dev
@Tomaas0 - tomas.is-a.dev
@Slddev - sappy.is-a.dev
@StevenRonnyFrohlich - steven.is-a.dev
@SuperHarmony910 - superharmony910.is-a.dev
@swanny246 - swanny.is-a.dev
@misticorion - sumedhaa.is-a.dev
@duaboola - shibiliya.is-a.dev
@vikyaiyer - vikyaiyer.is-a.dev
@the-garlic-os - the-garlic-os.is-a.dev
@TheBotlyNoob - windows.is-a.dev
@tmccarthyj - tyler.is-a.dev
@TibebeJS - tibebe.is-a.dev
@undefined - thequackyduck.is-a.dev
@Xander1233 - xndr.is-a.dev
@joeleeofficial - ws.is-a.dev
@LellisV2 - web.is-a.dev
@tolisdev - tolis.is-a.dev
@tovade - tovade.is-a.dev
@joeleeofficial - wscr.is-a.dev
@undefined - yujia.is-a.dev
@xorob0 - tim.is-a.dev
@SwapnilChand - swapnil.is-a.dev
@ameliakiara - tokisaki.is-a.dev
@umahmood21 - usman.is-a.dev
@yummyweb - yum.is-a.dev
@yCyanxW - ycyanx.is-a.dev
@yourfriendoss - yourfriend.is-a.dev
@A-Tokyo - tokyo.is-a.dev
@undefined - z4ff.is-a.dev
@mzrtamp - zhycorp.is-a.dev
@TheBotlyNoob - ziari.is-a.dev
@zplusfour - zplusfour.is-a.dev
@auguwu - august.is-a.dev
@PlatinBae - bae.is-a.dev
@Fauzannnnh - fauzannnnh.is-a.dev
@JackOPXL - jack.is-a.dev
@bashoudev - bashou.is-a.dev
@thesct22 - thesct22.is-a.dev
@mattcasey - matt.is-a.dev
@DevJustForever - motion42.is-a.dev
@markrity - mark.is-a.dev
@KodingDev - koding.is-a.dev
@SamL2020 - saml2020.is-a.dev
@ririxidev - ririxi.is-a.dev
@SealedSaucer - phantom.is-a.dev
@tanishq-soni - tanishq.is-a.dev
@tjrgg - tjrgg.is-a.dev
@tjrgg - tjr.is-a.dev
@Nami2012 - vaskian.is-a.dev
@oofquest - oofy.is-a.dev
@hackermondev - ionetty.is-a.dev
@lsantana486 - lsantana.is-a.dev
@clynt707 - psyro.is-a.dev
@Waxaranai - wisnu.is-a.dev

</p>
</details>

**Comment by AozoraDev** [comment]
I've been having trouble with hosting lately. The hosting service I'm using (foxxy.id) has shut down so I have to find a better hosting. That's very time consuming.

**Comment by thetayloredman** [comment]
mine go yeet

**Comment by TheBotlyNoob** [comment]
> I've been having trouble with hosting lately. The hosting service I'm using (foxxy.id) has shut down so I have to find a better hosting. That's very time consuming.

try [railway](https://railway.app)

**Comment by AozoraDev** [comment]
> > I've been having trouble with hosting lately. The hosting service I'm using (foxxy.id) has shut down so I have to find a better hosting. That's very time consuming.
> 
> try [railway](https://railway.app)

Interesting. They had free plan too.
Hmm... I'll try it later. Thanks!

**Comment by TheBotlyNoob** [comment]
no problem!

**Comment by agam778** [comment]
Yup, I have a broken domain
I have a domain agam778.is-a.dev
Its PR is also merged

But I can't use it tho
I tried netlify and vercel but both gave the same problem 
![130551087-6d3ad273-83ba-45d7-b106-60a6d93a2c2b.png](https://user-images.githubusercontent.com/68941022/133465524-4d7e7eba-d721-44d9-bcda-86239f8c6dc0.png)
![130551045-0fb4de29-f9eb-4e4f-94c4-2b58645dd0ba.png](https://user-images.githubusercontent.com/68941022/133465537-03072832-ceec-458e-acc0-c96feebd0839.png)

**Comment by TheBotlyNoob** [comment]
Yeah, Vercel and Netlify will not work, sorry!

**Comment by TheBotlyNoob** [comment]
like I said before, try [railway](https://railway.app)

**Comment by agam778** [comment]
> like I said before, try [railway](https://railway.app)

K I'll try 🙂
Do I have to create a new PR too? 😅

**Comment by TheBotlyNoob** [comment]
yes, unfortunately

**Comment by agam778** [comment]
K then, no worries 👍

**Comment by agam778** [comment]
> K then, no worries 👍
> Can I have a sample of a .json file using railway?

@TheBotlyNoob

**Comment by TheBotlyNoob** [comment]
look at https://github.com/is-a-dev/register/blob/main/domains/jj.json (my domain)

**Comment by agam778** [comment]
> get the `CNAME` from following https://docs.railway.app/deploy/exposing-your-app
> 
> then [follow the docs](https://github.com/is-a-dev/register/blob/main/docs/domains-json.md) to create a domain

Ah I see, thanks a lot

**Comment by aanthr0** [comment]
Honestly, you can delete mine for the time being. If I decide to use it
again, I'll make a new PR.

Cheers.

**Comment by cmulay** [comment]
Hey! 
I had a broken domain too, I'll try railway and send a new PR.
Thanks !!

**Comment by anoopmsivadas** [comment]
Hey, I will also try railway and create a new PR. Thanks :) 👍🏽

**Comment by agam778** [comment]
Thanks a lot @TheBotlyNoob my website is now up and running without any issues!

**Comment by TheBotlyNoob** [comment]
> Thanks a lot @TheBotlyNoob my website is now up and running without any issues!

no problem!

**Comment by thispsj** [comment]
@TheBotlyNoob I can't keep my site live 24×7 (because I'm testing it on Google Cloud and it incurs extra/useless billing on my account if I'll keep it live all the time.) That's the basic reason that I chose a domain with a random name. So that others don't have any problems.

**Comment by TheBotlyNoob** [comment]
@thispsj why do you need Google Cloud? If you could switch to [railway](https://railway.app/?referralCode=rK--pl) they have a genrerous free plan.

**Comment by thispsj** [comment]
@TheBotlyNoob I can't. I know there are many free services like Deta,Railway,Heroku etc but none of them match my requirements. I do use Railway for some other projects that match my requirements.

**Comment by agam778** [comment]
> @TheBotlyNoob I can't. I know there are many free services like Deta,Railway,Heroku etc but none of them match my requirements. I do use Railway for some other projects that match my requirements.

What's your site used for?

**Comment by thispsj** [comment]
> > @TheBotlyNoob I can't. I know there are many free services like Deta,Railway,Heroku etc but none of them match my requirements. I do use Railway for some other projects that match my requirements.
> 
> What's your site used for?

@agam778 I can't disclose that completely but it uses websockets and RPCs .

**Comment by agam778** [comment]
> > > @TheBotlyNoob I can't. I know there are many free services like Deta,Railway,Heroku etc but none of them match my requirements. I do use Railway for some other projects that match my requirements.
> > 
> > What's your site used for?
> 
> @agam778 I can't disclose that completely but it uses websockets and RPCs . (And those free things provide only http(s) routing )

Oh, kk then

**Comment by agam778** [comment]
Ok so .is-a.dev domains also work with cloudflare pages

**Comment by thatcatdrout** [comment]
[does layar0 work?](https://www.layer0.co/)

**Comment by agam778** [comment]
There's a problem with the root domain (https://is-a.dev), it says cannot continue due to "Potential Security Issue"
![image](https://user-images.githubusercontent.com/68941022/147629486-4f1abbd2-9732-4529-8e8a-2b40af73e3a5.png)

So I checked the SSL of website - https://www.ssllabs.com/ssltest/analyze.html?d=is-a.dev
and it shows SSL expired 
![image](https://user-images.githubusercontent.com/68941022/147629530-aebc1faa-821c-4881-b043-6926512ca73d.png)

When will this be fixed?

**Comment by jackmawer** [comment]
is there any precedent for claiming broken domains? jack.is-a.dev is still broken since this issue was created and it would be awesome to claim it.

**Comment by phenax** [comment]
@jackmawer. Unfortunately, we cannot allow anyone else to claim it without the consent of the original author. You could try opening a [new discussion here](https://github.com/is-a-dev/register/discussions/new) and tagging the user from the [jack.json file](https://github.com/is-a-dev/register/blob/main/domains/jack.json).

**Comment by WilliamDavidHarrison** [comment]
Your on that list @TheBotlyNoob loo

**Comment by TheBotlyNoob** [comment]
:flushed:

**Comment by Abdulazizkhan-K-N-B** [comment]
aknb.json file merged but i can't use aknb.is-a.dev domain.

**Comment by WilliamDavidHarrison** [comment]
I'm going to make a mega PR later today deleting most of the completely broken domains.

**Comment by jobcmax** [comment]
[https://yujia.is-a.dev/](https://yujia.is-a.dev/) is not dead :)

**Comment by WilliamDavidHarrison** [comment]
@Danix421 what is your domain?

**Comment by WilliamDavidHarrison** [comment]
> @WilliamDavidHarrison `danix.is-a.dev`

I have removed your domain.

**Comment by ericp3reira** [comment]
Hi everyone!

Could you please release my domain as well (`ericp3reira.is-a.dev`)? And sorry for taking so long in answering this issue.

Cheers!

**Comment by mtgsquad** [comment]
@ericp3reira Hello! Please send us another confirmation response, so that I have full authority to remove your subdomain.

**Comment by ericp3reira** [comment]
Hey @mtgsquad! Thanks for the quick reply.

I got some time in my pc and remove it myself. Is that ok?

**Comment by WilliamDavidHarrison** [comment]
> Hey @mtgsquad! Thanks for the quick reply.
> 
> I got some time in my pc and remove it myself. Is that ok?

All good, I have merged your PR.

**Comment by piotr25691** [comment]
> I'm going to make a mega PR later today deleting most of the completely broken domains.

just 14 domains, all starting with the letter A? ain't there more domains to verify they are valid?

**Comment by WilliamDavidHarrison** [comment]
> > I'm going to make a mega PR later today deleting most of the completely broken domains.
> 
> just 14 domains, all starting with the letter A? ain't there more domains to verify they are valid?

I only did a couple

**Comment by WilliamDavidHarrison** [comment]
I'm going to do more soon lol

**Comment by Mathu-lmn** [comment]
Hey, my domain request got merged a few days ago but I get NET::ERR_CERT_COMMON_NAME_INVALID error.
My initial website : https://mathu-lmn.github.io/ works just fine so I don't understand
(https://github.com/is-a-dev/register/blob/main/domains/mathu-lmn.json)

**Comment by WilliamDavidHarrison** [comment]
@Mathu-lmn You need to link your GitHub Pages website to your is-a.dev domain.

Also, next time, can you please open a separate issue.

**Comment by eldinesh** [comment]
> This is just to notify everyone who has a broken/unused domain. If you need help fixing your domain, comment on this issue, or create a new issue. If you have just parked a domain for later use, we ask that you give it away to someone else who might put it to better use.
> 
> > If you are having issues with Vercel or Netlify, try [Railway](https://railway.app?referralCode=jj)
> 
> Users who have broken domain(s)

I've been using it since day 1. And it's working not broken. I'm using it on gitHub pages. Please check again.

**Comment by lfom** [comment]
Hello! I've seem some comments in issues/PRs saying that (static?) sites hosted on Netlify actually work with is-a.dev. Some special configuration is needed or it should work just fine? Thanks

**Comment by WilliamDavidHarrison** [comment]
It won't work as the SSL certificates will not issue with the is-a.dev domain.

**Comment by lavafroth** [comment]
Hey! My subdomain lavafroth.is-a.dev looks broken.

**Comment by wdhdev** [comment]
@lavafroth This is due to a CI issue not publishing records.

I'm going to close this issue as it is not relevant anymore.

**Comment by lavafroth** [comment]
@wdhdev, is there something I have to do about this CI issue?

**Comment by wdhdev** [comment]
@lavafroth You just have to wait for @phenax to fix it.

**Comment by lavafroth** [comment]
@wdhdev @phenax Thank you so much for the fix! 😄
