### ISSUE TITLE
Make a function to check if CNAME or A records are pointing at vercel or netlify

### ISSUE THREAD

**Issue by YouFoundAlpha** [is-a-dev/register#11673]
### What do you want added?
Make a function in the validation script to check if the CNAME or A record is pointing at vercel or netlify to make it an automation instead of doing it manually

**Comment by YouFoundAlpha** [comment]
I asked ChatGPT (as I'm not familliar with the Ramda library) to write a function for the https://github.com/is-a-dev/register/blob/d5faa0a8200dc754ffe4a67fb393c174a4bde18f/utils/validations.js 
to check if the domain is pointing at vercel or netlify and it came out with this (I don't know if this is going to work and I have not tested it yet)
```
const isDeployedOnHostingService = (domain) => {
  const hostingServices = ['vercel.app', 'netlify.app'];
  return hostingServices.some(service => domain.includes(service));
};

// Example usage:
const domain1 = 'example.vercel.app';
const domain2 = 'mywebsite.netlify.app';

console.log(isDeployedOnHostingService(domain1));  // true
console.log(isDeployedOnHostingService(domain2));  // true

**Comment by wdhdev** [comment]
We probably won't do this as we may support them at some point in the future.

**Comment by YouFoundAlpha** [comment]
> y won't do this as we may sup

ok
