### ISSUE TITLE
My subdomain not redirecting to my website with URL record

### ISSUE THREAD

**Issue by YouFoundAlpha** [is-a-dev/register#11670]
### Your subdomain
yfa.is-a.dev
### The issue
It says that it can't reach the page

**Comment by YouFoundAlpha** [comment]
This is my PR with the changes https://github.com/is-a-dev/register/pull/11636

**Comment by YouFoundAlpha** [comment]
and when I did nslookup it was empty
no records at all
I have cleared my cache and everything

**Comment by VaibhavSys** [comment]
URL records are currently having issues

**Comment by YouFoundAlpha** [comment]
> URL records are currently having issues

Ok

**Comment by YouFoundAlpha** [comment]
> URL records are currently having issues

Is URL records still broken?

**Comment by CuteDog5695** [comment]
> > URL records are currently having issues
> 
> Is URL records still broken?

no, seems that its back to normal. recent domains which use URL record (including mines) are working

**Comment by YouFoundAlpha** [comment]
> > > URL records are currently having issues
> > 
> > 
> > Is URL records still broken?
> 
> no, seems that its back to normal. recent domains which use URL record (including mines) are working

Thanks
