### ISSUE TITLE
Why does my website redirect to the original url?

### ISSUE THREAD

**Issue by catfoolyou** [is-a-dev/register#11680]
I've seen people use the .is-a.dev domain for their website, but mine just redirects to the original url when I go to it. Is it supposed to be this way?

**Comment by wdhdev** [comment]
What is your domain?

**Comment by catfoolyou** [comment]
The original is vast-puce-hippo-shoe.cyclic.app which is a web service hosted on cyclic

**Comment by VaibhavSys** [comment]
> The original is vast-puce-hippo-shoe.cyclic.app which is a web service hosted on cyclic

We meant your is-a-dev domain, but I just looked through it and its `catfoolyou.is-a.dev`, and it seems to redirect perfectly for me. Try clearing your cache or checking your DNS.
