### ISSUE TITLE
Domain is not listed in the is-a.dev dashboard but shows up as already taken in registration

### ISSUE THREAD

**Issue by byKeksYT** [is-a-dev/register#11771]
On 21st of December of 2023, my domain `verstandlxs.is-a.dev` got accepted. 
#10226 
When I log into the dashboard now, I do not see any domains. Additionally, when I try to register the domain `verstandlxs.is-a.dev` now, it shows up as already taken.
Have I done something wrong at the time of the registration in December or is this the case because I did not use the domain for more than one month?

**Comment by Stef-00012** [comment]
delete the domain from your fork and try again
