### ISSUE TITLE
Is it possible to use DKIM and DMARC?

### ISSUE THREAD

**Issue by RehanPlayz** [is-a-dev/register#1178]
Is it possible to use DKIM and DMARC with an is-a.dev (sub)domain?

**Comment by phenax** [comment]
We have been planning adding DKIM and DMARC at the root level. Unfortunately, it is a bit complicated in terms of security for a sub-domain service which is why it is on hold for a bit. Will update any progress on the pull request.

**Comment by RehanPlayz** [comment]
> We have been planning adding DKIM and DMARC at the root level. Unfortunately, it is a bit complicated in terms of security for a sub-domain service which is why it is on hold for a bit. Will update any progress on the pull request.

Oh ok
