### ISSUE TITLE
My url got deleted i cant register it again?

### ISSUE THREAD

**Issue by Caiden-P** [is-a-dev/register#11822]
everything all my domains(lodestone, caiden, caiden.xyz) were removed it says i have 0 lodestone is still available but my main caiden and caiden.xyz arent?

**Comment by Caiden-P** [comment]
i tried syncing my fork it made everything show as available and i was able to restore one of them (cumcord) its now in a pr but the rest it says they are available i go to set it up it says whoops error there is already a pull request for that

**Comment by Caiden-P** [comment]
and there is no PR for them? do i just delete my fork entirely and start over? i dont wanna do anything permanent

**Comment by Caiden-P** [comment]
![image](https://github.com/is-a-dev/register/assets/119334408/14c3dbd7-515a-4228-b402-46a60c518ab5)
 new error

**Comment by VaibhavSys** [comment]
Delete your fork

**Comment by Caiden-P** [comment]
i deleted it lmao, yeah no still the same:
![image](https://github.com/is-a-dev/register/assets/119334408/d2f58ebb-71f4-4d7e-b656-92bdfb675575)
whooooops

**Comment by Caiden-P** [comment]
its forking again and then its literally adding the domain to my forked version with all the data and never makes a pr?

**Comment by Caiden-P** [comment]
![image](https://github.com/is-a-dev/register/assets/119334408/c515636f-1bd9-4e44-9012-2d2c1991bca0)
![image](https://github.com/is-a-dev/register/assets/119334408/2d08706c-4635-4604-8528-61cdd1603a45)

mine has it i delete it i try to register lodestone suddently its there with the records i gave but a pr never went

**Comment by vuthanhtrung2010** [comment]
U have an opened pr, u should manually create a lot of files and create a pr, it will includes all your changes.
