### ISSUE TITLE
My domains were deleted

### ISSUE THREAD

**Issue by Caiden-P** [is-a-dev/register#11858]
bro this is bullshit all my domainds got deleted and the one i was able to make a pr for gets denided bec its nsfw? even tho it was allowed before then all 4 domains got deleted this is actually so stupid

**Comment by CuteDog5695** [comment]
not the only reason you didnt get your domains, they also didnt have the right records. btw only cumcord was the nsfw one

**Comment by CuteDog5695** [comment]
and to answer your question on why it got deleted, it most probably got caught in the cleanups, so theres your answer

**Comment by vuthanhtrung2010** [comment]
> bro this is bullshit all my domainds got deleted and the one i was able to make a pr for gets denided bec its nsfw? even tho it was allowed before then all 4 domains got deleted this is actually so stupid

You can check domains was deleted with reasons here: https://github.com/is-a-dev/register/pull/11598
Use ctrl + F to find.

**Comment by Caiden-P** [comment]
guess what non of my domains are on there:
cumcord
caiden
caiden.xyz
lodestone 
none of them are there

**Comment by Caiden-P** [comment]
> not the only reason you didnt get your domains, they also didnt have the right records. btw only cumcord was the nsfw one

it didnt even make prs for the rest all of them said whoops a pr already exists for this domain

**Comment by Caiden-P** [comment]
the only mention of removed domain is cumcord
https://github.com/is-a-dev/register/pull/9887
bec it was unresolved the rest do not have any explanation to them they literally vanished
they all have the accepted original pr and nothing else they just suddenly disappeared

**Comment by Caiden-P** [comment]
and when i got the whoops another pr exists no pr existed but someone the domain got added to my fork and nothing else

**Comment by VaibhavSys** [comment]
@Caiden-P
> caiden
> caiden.xyz
> lodestone
> cumcord

They were removed in the [hosting shutdown](https://github.com/is-a-dev/register/commit/a46548b6602a13661a6e9fdf89ced3d6b8c3aa79) and `cumcord` was removed in the [cleanup](https://github.com/is-a-dev/register/commit/a6b29d13f562db9597aff318d5c44aa98cc74000).

You can recreate your domains, if you are having issues with the manage site, try deleting your fork and try again.

**Comment by vuthanhtrung2010** [comment]
> > not the only reason you didnt get your domains, they also didnt have the right records. btw only cumcord was the nsfw one
> 
> it didnt even make prs for the rest all of them said whoops a pr already exists for this domain

U cannot open multiple prs in a row
