### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by ServerDeveloper9447** [is-a-dev/register#1209]
Your domain name: duck.is-a.dev

Explain any issues you are facing
My domain was working till 3 hours before from the time this issue is submitted. But now after 3 hours, it just doesn't work. When I go to duck.is-a.dev it just redirects to .is-a.dev (hompage). I checked and saw that the json file is there with everything fine but... it just doesn't work. Should I resubmit the json file?

**Comment by phenax** [comment]
It seems to be working fine on our end. Usually this problem occurs when the old DNS record is cached in your browser. Try clearing your browser cache or using a different browser to confirm and resolve this issue.

**Comment by ServerDeveloper9447** [comment]
I came to know that if I prefix 'https://' then it opens my site but if I just open duck.is-a.dev it just redirects. Why? Anyone can open the site without the https prefixed and if they do they will be redirected to the hompage. Please fix this if its a bug

**Comment by phenax** [comment]
Again, I think it is more than likely that it is related to browser cacheing. Please try using incognito browser. Yours is a CNAME DNS record, which doesn't care about http or https. It only resolves the DNS query.

**Comment by TheBotlyNoob** [comment]
The domain works. Like @phenax said its probably your browser caching the DNS info.

![image](https://user-images.githubusercontent.com/72417807/134924934-4b3b72bb-bf9b-4f97-91e3-6af8a5875be5.png)
