### ISSUE TITLE
Domain not added even though PR was merged.

### ISSUE THREAD

**Issue by FC5570** [is-a-dev/register#1210]
Hello. My pull request for `fc5570.is-a.dev` was [merged](https://github.com/is-a-dev/register/pull/1203) a day ago, but the JSON file is not visible in the domains directory. Do I have to make a PR again to get my domain added, or has it been already added?

**Comment by phenax** [comment]
Not sure what happened there. I think it might have something to do with the force push by push bot. You'll have to create another pull request.

Also, unfortunately, we currently do not support vercel (#489)

**Comment by FC5570** [comment]
Sadge. Thanks.
