### ISSUE TITLE
Report abuse

### ISSUE THREAD

**Issue by YUUTO-cool** [is-a-dev/register#1214]
Domain you want to report: 
https://phantom.is-a.dev

### Reason
Explain why you think this domain is being abused

**Comment by phenax** [comment]
Could you explain why you think this domain is being abused?

**Comment by TheBotlyNoob** [comment]
this is not an `is-a.dev` domain, so even it is being abused, we cannot do much.

**Comment by phenax** [comment]
phantom.is-a.dev reditects to phantomcodes.ga

**Comment by TheBotlyNoob** [comment]
oh, okay

**Comment by leecheeyong** [comment]
yeah, you guys can take down the domain that redirects to that domain if its being abused
