### ISSUE TITLE
Support: Can't manage domain.

### ISSUE THREAD

**Issue by MayankServers** [is-a-dev/register#12185]
### Your subdomain
lightarea.is-a.dev
### The issue
I have recently get the subdomain lightarea.is-a.dev but I can't manage it when I log into the dashboard it says that there is no domain LightArea.is-a.dev registered with my account please solve this issue!

**Comment by MayankServers** [comment]
You can also see the pull request being merged [https://github.com/is-a-dev/register/pull/10659](url)

**Comment by MayankServers** [comment]
@wdhdev @andrewstech

**Comment by CuteDog5695** [comment]
I see you used is-a.dev hosting. Recently is-a.dev hosting shutdown resulting in your domain getting deleted. You can get back the domain by re-registering, but you would need to find another hosting (Like Github Pages or Cloudflare Pages, just to name a few)
