### ISSUE TITLE
My domain site is not there. 

### ISSUE THREAD

**Issue by sequel-tj** [is-a-dev/register#12258]
subdomain: tanmayjaiswal.is-a.dev
Issue: The site was active few months back but today, when I visited it was not there. What's the issue? 

![image](https://github.com/is-a-dev/register/assets/74481733/77ea71d7-4bc6-4123-b1bb-ef1ffe5fa5cd)

**Comment by 21Z** [comment]
Recently is-a.dev [hosting shutdown](https://github.com/is-a-dev/register/commit/a46548b6602a13661a6e9fdf89ced3d6b8c3aa79), You can get back the domain by re-registering, but you would need to use another hosting (Like Github Pages or Cloudflare Pages)

**Comment by Stef-00012** [comment]
the previous comment explained why your website was removed, is-a.dev hostimg was shutdown around 1 month ago

if you want i can give a zip file containing all the files you had on is-a.dev hosting

**Comment by Stef-00012** [comment]
> Yes, please provide the zip file. Thanks

here it is
[tanmayjaiswal.zip](https://github.com/is-a-dev/register/files/14363526/tanmayjaiswal.zip)
