### ISSUE TITLE
Verify domain ownership via DNS record

### ISSUE THREAD

**Issue by hugovidafe** [is-a-dev/register#1228]
At this time, TXT records are available, but if I want to verify my subdomain on Google Search console what I need to do?

I don't want to use HTML tag because I need to associate with Google Analytics.

**Comment by Hugovidafe** [comment]
Hello?

**Comment by pythonmcpi** [comment]
Google Search console allows you to upload a html file to your website to verify.

**Comment by Hugovidafe** [comment]
Yeah, I know but I need to check the subdomain with a DNS record...

**Comment by Hugovidafe** [comment]
Oh, a dot: .

**Comment by MaskDuck** [comment]
I saw the message at the Discord server and I will copy it.

![image](https://user-images.githubusercontent.com/70831061/155922696-bf1ff27b-0e97-4dab-b5e5-2a25f9d1a747.png)

(from @ phenax)

**Comment by MouseMoosz** [comment]
bump

**Comment by MouseMoosz** [comment]
bump

**Comment by omxpro** [comment]
Any updates?

**Comment by TerraPlayz** [comment]
Welcome to 2023. This issue is still open

**Comment by WilliamDavidHarrison** [comment]
I don't think this will be added as this can cause issues with other services.
