### ISSUE TITLE
Adding a redirect to personally owned domain

### ISSUE THREAD

**Issue by Blakeinstein** [is-a-dev/register#1231]
Your domain name: `blaine.is-a.dev`

First of all huge thanks for this service!
I was able to get a face on the web before I could afford a domain, all thanks to you guys.

Now that I have a decent domain, although not the best, is the reason why I would like to redirect 
`blaine.is-a.dev` -> `blaine.vip`

Currently I have it the other way around. I looked at https://github.com/is-a-dev/register/blob/main/docs/hosted-at/others.md and realized that all I would need is to change the cname target. But I am unsure, if the url will be added to the SSL certificate generated by Github Pages.
It will contain `blaine.vip` but not the is a dev domain. I speculate that it will just work, redirect the cert requests to blaine.vip as well. But I would like to confirm with you guys first.

**Comment by pythonmcpi** [comment]
You can use a URL record to redirect users from blaine.is-a.dev to blaine.vip. You shouldn't mirror content on two different hostnames, because that affects search engines.

**Comment by KK-Designs** [comment]
Hello @Blakeinstein, you need to use `URL` instead of `CNAME` for your domain. For example, your `blaine.json` would look a little something like this:

```json
{
  "description": "The face of Blaine, on the web",
  "repo": "https://github.com/Blakeinstein/Blakeinstein.github.io",
  "owner": {
    "username": "Blakeinstein",
    "email": "rishi1998@gmail.com"
  },
  "record": {
    "URL": "https://blaine.vip"
  }
}
```

Also, make sure to use `Force HTTPS` in the GitHub page settings.

**Comment by anselal** [comment]
If i want to redirect to my own domain, I mist use URL right? Do I also need to define a repo?

**Comment by phenax** [comment]
@anselal, yes. Use a URL record ([docs](https://github.com/is-a-dev/register/blob/main/docs/domains-json.md#record-required)). And you don't need a repo. The `repo` field in the json file is optional. Closing this issue as it has been answered already.
