### ISSUE TITLE
Removal

### ISSUE THREAD

**Issue by Yunexiz** [is-a-dev/register#12398]
### Your subdomain
Any domain with the email literallynoname13@gmail.com (This email is inactive)
### The issue
I got a new email and now i would like all the domains connected with my previous email removed.

**Comment by Yunexiz** [comment]
> You can find all the domains linked with that email here: https://api.is-a.dev/lookup/user?email=literallynoname13@gmail.com

What should I do? Edit it to a new email and send a PR?

**Comment by Omxpro** [comment]
> > You can find all the domains linked with that email here: https://api.is-a.dev/lookup/user?email=literallynoname13@gmail.com
> 
> What should I do? Edit it to a new email and send a PR?

yes
