### ISSUE TITLE
Not able to change the records of the existing subdomain

### ISSUE THREAD

**Issue by rohansharma-developer** [is-a-dev/register#12510]
My website https://rohansharma.is-a.dev routes to https://rohansharma.me, which I don’t own now. I need help to publish my web site through GitHub pages to the subdomain. If that’s possible able to be done on my existing domain, Please help with the issue….

**Comment by Omxpro** [comment]
> My website https://rohansharma.is-a.dev routes to https://rohansharma.me, which I don’t own now. I need help to publish my web site through GitHub pages to the subdomain. If that’s possible able to be done on my existing domain, Please help with the issue….

read https://is-a/dev/docs and open a pr

**Comment by rohansharma-developer** [comment]
Thanks for the help...
