### ISSUE TITLE
Recieved a mail of unverified domain

### ISSUE THREAD

**Issue by ashishagarwal2023** [is-a-dev/register#12528]
![image](https://github.com/is-a-dev/register/assets/83082760/bec17a70-0a84-4c4d-866c-0409efc96db4)
The website is still working at ashishagarwal.is-a.dev thought.
![image](https://github.com/is-a-dev/register/assets/83082760/a24c8a99-2f74-49c1-8fa3-35cc7a5d6a31)

**Comment by Omxpro** [comment]
> ![image](https://private-user-images.githubusercontent.com/83082760/309530904-bec17a70-0a84-4c4d-866c-0409efc96db4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MDU0NzYsIm5iZiI6MTcwOTUwNTE3NiwicGF0aCI6Ii84MzA4Mjc2MC8zMDk1MzA5MDQtYmVjMTdhNzAtMGE4NC00YzRkLTg2NmMtMDQwOWVmYzk2ZGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDIyMzI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0OWFjZTkyOTFmNmY4MTc0N2E1YzMwMzg3OTczY2NjOTQwYmNhNTE2OTYwMjk3NDY2YWU5Y2JlMGQwY2U0MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yZjJV67aYxjgCqDbYoQw8nc-DLTUuyuL11IxZ0yJs4U) The website is still working at ashishagarwal.is-a.dev thought. ![image](https://private-user-images.githubusercontent.com/83082760/309530926-a24c8a99-2f74-49c1-8fa3-35cc7a5d6a31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MDU0NzYsIm5iZiI6MTcwOTUwNTE3NiwicGF0aCI6Ii84MzA4Mjc2MC8zMDk1MzA5MjYtYTI0YzhhOTktMmY3NC00OWMxLThmYTMtMzVjYzdhNWQ2YTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDIyMzI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MTJmZmIwYTVhNTJlYWMwOWRkZGE5N2ZjNDEzZDI1NGEwMTVlNDA4ZGEwMjU5M2Q2MTRiZDQ4ZDY3ZjA1NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NxD2_Gxa3pM4_4Ab_fqCot9sZ199jCQFx7OH28vl1Io)

re configure your domain. open a PR for it

**Comment by ashishagarwal2023** [comment]
Anyone

**Comment by YouFoundAlpha** [comment]
> Anyone

Have you created a PR with the github-pages-challenge?

**Comment by ashishagarwal2023** [comment]
Alright

**Comment by ashishagarwal2023** [comment]
https://github.com/is-a-dev/register/pull/12579

**Comment by YouFoundAlpha** [comment]
> #12579
now you'll just have to wait for a maintainer to merge it

**Comment by ashishagarwal2023** [comment]
Thanks it worked
