### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by skgupta507** [is-a-dev/register#12529]
### Your subdomain
sunil.is-a.dev
### The issue
hello team
i need to change the url the subdomain points to can anyone help me with this. I would to point to (https://sk-portfolio-five.vercel.app/) this site as it is my portfoilio website.

**Comment by Omxpro** [comment]
> ### Your subdomain
> sunil.is-a.dev
> 
> ### The issue
> hello team i need to change the url the subdomain points to can anyone help me with this. I would to point to (https://sk-portfolio-five.vercel.app/) this site as it is my portfoilio website.

you can only redirect to vercel. for anything else we do not support vercel

**Comment by skgupta507** [comment]
> > ### Your subdomain
> > sunil.is-a.dev
> > ### The issue
> > hello team i need to change the url the subdomain points to can anyone help me with this. I would to point to (https://sk-portfolio-five.vercel.app/) this site as it is my portfoilio website.
> 
> you can only redirect to vercel. for anything else we do not support vercel

the previous pointing link also belongs to vercel so i just  needed to point it to the new link

**Comment by 21Z** [comment]
The previous link also redirects to vercel, if you want to change the link, open a PR.
