### ISSUE TITLE
Raw API: All API jobs have failed

### ISSUE THREAD

**Issue by dushmanta05** [is-a-dev/register#12580]
I'm getting these errors in the mail. I don't know what's happening. Can anyone explain or help me with this? 

![Screenshot](https://github.com/is-a-dev/register/assets/73304098/179e189b-7870-4164-9d53-29db4b465f9c)

**Comment by VaibhavSys** [comment]
Disable GH Actions on your fork.

**Comment by dushmanta05** [comment]
Thank you for your response @VaibhavSys 👍
