### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by boolean44-repos** [is-a-dev/register#12676]
### Your subdomain
mail.boolean44.is-a.dev
### The issue
i cant get emails

**Comment by DEV-DIBSTER** [comment]
You need to check if all the email records are added. Notably I noticed no TXT records. These are records that you should add on your own.

**Comment by boolean44-repos** [comment]
it never asked for txt

**Comment by boolean44-repos** [comment]
made a new pr

**Comment by boolean44-repos** [comment]
idk why it failed the checks
