### ISSUE TITLE
Report abuse

### ISSUE THREAD

**Issue by darakonas20** [is-a-dev/register#12778]
### Domain
https://phantom.is-a.dev/support
### Reason

advertising a program agents dc tos
### Proof

![image](https://github.com/is-a-dev/register/assets/157143461/3c0961eb-f9fc-4711-ac99-de6530ca6dd3)
![image](https://github.com/is-a-dev/register/assets/157143461/90497eef-a71b-438b-a6b7-1da252083666)

**Comment by VaibhavSys** [comment]
The domain has been removed. Thank you for the report!
