### ISSUE TITLE
Subdomain redirecting to the main domain instead of my website

### ISSUE THREAD

**Issue by SealedSaucer** [is-a-dev/register#12783]
### Instead of redirecting to the website I mentioned in the config file, it's redirecting me to [is-a.dev](https://is-a.dev).

![image](https://github.com/is-a-dev/register/assets/71928730/180252cf-c167-440d-b890-04fb040f3e49)

I didn't change anything on my website code nor my DNS Records.

Thanks.

**Comment by VaibhavSys** [comment]
The content which you were hosting on your domain is not allowed and your domain has been removed.
https://github.com/is-a-dev/register/pull/12780

**Comment by SealedSaucer** [comment]
What exactly is not allowed?

**Comment by SealedSaucer** [comment]
I read the [Code of Conduct](https://github.com/is-a-dev/register/blob/main/CODE_OF_CONDUCT.md) and I don't think I have broken any of the rules in it.

![image](https://github.com/is-a-dev/register/assets/71928730/cf3c5dfe-12ea-41bf-b262-cab1467d121d)

- **Use common sense** - It's not that complicated. Just be nice to people.
> I am, most of the time
- **Don't abuse the service** - This service is intended for developers to get a cleaner URL for their personal websites.
> I am using the domain for my personal website
- **No wrongful use** - Do not use this service as a way, to promote hacking, scams, fraud, and other illegal activites.
> I am not promoting hacking, scams, fraud, or any other illegal activities.

I am assuming you are thinking the products on the website are illegal, which is not the case. I am developer trying to make money by selling products on Sellix. I am not directly hosting anything on the subdomain provided by is-a.dev. All of the links take you to a third-party website hosted by Sellix.

None of the products I sell involves any kind of hacking or fraud. I am not scamming anyone as you can see from the [feedback](https://phantom.mysellix.io/feedback). The latest one star rating is from the same guy who reported my domain. They are trying to take down my socials for not being able to scam me (please read the pastebin text). None of the products are illegal. I have clearly written in my [ToS](https://phantom.mysellix.io/terms) that my store is not affiliated with Discord.

I would very much appreciate if you can do something in this case. I have been using phantom.is-a.dev as my website link everywhere on the internet and it would be very sad to lose it. If you are still adamant about your decision even after reading this issue, I am down to remove the links from the website.

Thanks.

**Comment by wdhdev** [comment]
Just because you say you are not affiliated with Discord, does NOT mean you can ignore their ToS. You are selling programs and possibly stolen Discord accounts from what I can see. This breaks Discord's ToS. Same with Telegram, you are selling Telegram accounts along with spam Telegram bots which also breaks their ToS.

You will not be allowed to use is-a.dev again.

**Comment by SealedSaucer** [comment]
Those are generated accounts... Not stolen... And as I said before, I didn't knew breaking a company's ToS is against the Code of Conduct.
