### ISSUE TITLE
Why it was closed?

### ISSUE THREAD

**Issue by adyoblu** [is-a-dev/register#12888]
### Your question
i have registered a subdomain for me some time ago and was approved but i recently went back to check it and was no longer valid.

[Pull request](https://github.com/is-a-dev/register/pull/8781)

**Comment by CuteDog5695** [comment]
> ### Your question
> i have registered a subdomain for me some time ago and was approved but i recently went back to check it and was no longer valid.
> 
> [Pull request](https://github.com/is-a-dev/register/pull/8781)

domain used is-a.dev hosting, it shutdown recently. if you want to host your website but have your is-a.dev domain you can use github pages or cloudflare pages.
oh btw if you want your website file let me know
