### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by d1snin** [is-a-dev/register#1295]
Your domain name: d1snin.is-a.dev, d1s.uno.

How can i fix this?
![image](https://user-images.githubusercontent.com/68169685/137978957-257b5e40-078a-4385-a1b0-1bf28b5f9e6b.png)

I use cloudflare pages for my website.
Here is my DNS records:
![image](https://user-images.githubusercontent.com/68169685/137979210-317a1bcf-76bd-43ec-be24-0aac3800b093.png)
My PR: https://github.com/is-a-dev/register/pull/1275

**Comment by pythonmcpi** [comment]
Your error looks like a server misconfiguration, which doesn't seem to be a problem with is-a.dev.

If you're trying to redirect d1sin.is-a.dev to 35188086.website-8ek.pages.dev, you should use a URL record. If you want to serve a different set of pages for d1sin.is-a.dev, you'll need to configure whatever hosting service you use to serve the second set of pages, as well as a ssl certificate for the is-a.dev domain.

**Comment by phenax** [comment]
Yes. It seems like the ssl certificate for your website doesn't include your .is-a.dev subdomain. [Maybe this could help](https://developers.cloudflare.com/ssl/edge-certificates/custom-certificates). Closing this issue.
