### ISSUE TITLE
GitHub pages use case Feedback/suggestion

### ISSUE THREAD

**Issue by yorodm** [is-a-dev/register#13]
I think it will be useful to expand the examples with an use case that shows how to use the service to migrate a blog from GitHub pages.

**Comment by phenax** [comment]
I have already mentioned the github pages instructions in [the api docs][./API.md] under the "How to register" section.

But I agree, it can be a bit clearer. I am currently working on a way to automate letting people know the next steps after registering a domain which I think will help with this.

**Comment by phenax** [comment]
Closing this issue as a new "For github pages users" section has been added to the api docs. Thank you for the suggestion :)
