### ISSUE TITLE
Add multiple types of records to domain.

### ISSUE THREAD

**Issue by ScytheMediaTheDev** [is-a-dev/register#13027]
### Your question
How would I add multiple records bc I am a bit low on knowledge with domains and hosting? I want to keep my existing record but what would I do to add them for different types?
Would it go like this? I would like to have more info just in case

"record": {
		"MX": ["mx1.improvmx.com"]
                "TXT": ["example"]
	} 
}

**Comment by wdhdev** [comment]
Yep, that's how you add multiple records. Keep in mind, you cannot have other records with CNAME records.

**Comment by ScytheMediaTheDev** [comment]
Thanks!
