### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by prasadsawant7** [is-a-dev/register#13033]
### The issue
I went to this site: https://manage.is-a.dev/domains and logged in with my github account but my domain name is not visible there, also when I tried to recreate the domain the same website shown me that domain name is not available. When I entered the domain in browser after some timeout it redirected me to the main website of .is-a-dev.

**Comment by Stef-00012** [comment]
Your domain used is-a.dev hosting which got shutdown

**Comment by prasadsawant7** [comment]
How can I retrieve it?

**Comment by DEV-DIBSTER** [comment]
@prasadsawant7 We have backups of your hosting files. Please provide the domain that you want the file backups for.

**Comment by CuteDog5695** [comment]
do you still want your files back?

**Comment by prasadsawant7** [comment]
Yes I want my files back

**Comment by CuteDog5695** [comment]
Then can you tell us the domain you had before it got removed? (Just to make sure we have the right file)
