### ISSUE TITLE
My domain disappeared !?

### ISSUE THREAD

**Issue by NamesMT** [is-a-dev/register#13187]
### Your subdomain
namesmt.is-a.dev

### Expected outcome
Should exists, maybe 404 or blank

### Observed outcome
Is default un-registered subdomain page: redirecting to is-a.dev

### Context
About half a year ago I opened a PR: #9374 to register `namesmt.is-a.dev`
Now I logged back into `manage.is-a.dev` to check, my subdomain is gone, not under my account.
I couldn't re-register it either, seems like the API saw that my repo exists and doesn't allow re-creating it.
![image](https://github.com/is-a-dev/register/assets/23612546/ded2f5a8-39ab-4e42-a3bf-693e782442c8)

**Comment by 21Z** [comment]
Your domain used is-a.dev hosting, which was [shutdown](https://github.com/is-a-dev/register/commit/a46548b6602a13661a6e9fdf89ced3d6b8c3aa79) sometime ago..
You can still re-register it but you have to use a different hosting service like Github or Cloudflare Pages.
Delete the fork on your account and you should be able to re-register it.

**Comment by NamesMT** [comment]
Ahhhh okay, ty!
