### ISSUE TITLE
How to set up TXT record validation for non-Github pages

### ISSUE THREAD

**Issue by hxhieu** [is-a-dev/register#13270]
Hi,

I am still discovering how could I do this TXT record validation, so far the custom domain been merged here [https://github.com/is-a-dev/register/pull/13200](https://github.com/is-a-dev/register/pull/13200)
However, the next step instruction email mentioned about custom domain on Github pages but unfortunately my site is not hosted on Github pages but Azure instead.
How could I add the TXT record required by Azure to our `is-a.dev` sub domain?

Thanks.

**Comment by VaibhavSys** [comment]
Hello,

I believe that you are talking about the TXT verification with CNAME as mentioned in [Azure Container Apps documentation](https://learn.microsoft.com/en-us/azure/container-apps/custom-domains-certificates#add-a-custom-domain-and-certificate). You can add the TXT records as you normally would, you can read our [documentation](https://is-a.dev/docs) for reference.

**Comment by hxhieu** [comment]
Thanks and PR created [https://github.com/is-a-dev/register/pull/13315](https://github.com/is-a-dev/register/pull/13315)
