### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by Riihime** [is-a-dev/register#13350]
### Your subdomain
`riihime.is-a.dev`

### The issue
Hello, I would like to be helped with the following issue: I chose the record type as "A" and needed to change it to "CNAME" later on to verify on GitHub. However, I could not find a way to do that so I deleted the repository. The domain, however, still exists without a repository on my account. How do I fix this? If there is no way to fix it on my side, I'd love my domain to be deleted. Thank you and have a nice day!

**Comment by VSeryi** [comment]
You don't see it on the [management website](https://manage.is-a.dev/domains)?

If not, you can always use the [manual method](https://github.com/is-a-dev/register?tab=readme-ov-file#manual-registration).

When you do the fork you will see that in the domain folder is your [subdomain ](https://github.com/is-a-dev/register/blob/main/domains/riihime.json) (it is not saved in your repo, but in the is-a-dev) and you can modify it to your liking and do the pull request again.

**Comment by Riihime** [comment]
I still can see it on the management website.
I just fork the .is-a.dev repository again and edit [my domain.](https://github.com/is-a-dev/register/blob/main/domains/riihime.json). I want to ask if this repository does the same as the deleted one and if I edit the file, changing A to CNAME and the address, will it be changed? Thanks.

**Comment by VSeryi** [comment]
Let's see, the repository you deleted is a "temporary" copy that you make in your user to be able to modify the files in this repo and then "ask" (the pull request) to make those same changes in this repo.

Now you have to do the same process:

1. You do the fork
2. You make the changes you want (in your case change the A to CNAME) in your fork
3. Make the Pull Request.

And when it merge into this repository, the changes will be applied.

**Comment by Riihime** [comment]
Thank you so much!
