### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by Myrdincx** [is-a-dev/register#13399]
### Your subdomain
myrdin.is-a.dev 
### The issue
I have created a pull request with the [_discord.myrdin.is-a.dev](https://github.com/is-a-dev/register/pull/13329) file which seems to have been merged to the main branch.
However, when trying to actually verify my domain on Discord, I get the following error: `Unable to validate domain`.
How would I be able to fix this issue?
Thanks in advance :)

**Comment by wdhdev** [comment]
It seems your JSON file name includes `.is-a.dev` which is incorrect, I have fixed this in #13402
