### ISSUE TITLE
Refer to another completed question.

### ISSUE THREAD

**Issue by ScytheMediaTheDev** [is-a-dev/register#13437]
Hey there, I was looking back at another question I asked about adding multiple records to one domain (https://github.com/is-a-dev/register/issues/13027). I saw that wdhdev said you can have multiple but not CNAME records with TXT or others. Why is that? Like I said this is a "reopening" of my last question.

**Comment by wdhdev** [comment]
It is simply a DNS restriction https://en.wikipedia.org/wiki/CNAME_record#Restrictions

**Comment by ScytheMediaTheDev** [comment]
Ok, Thanks!
