### ISSUE TITLE
As the documentation states, enforce HTTPS.

### ISSUE THREAD

**Issue by xKotelek** [is-a-dev/register#13443]
As the documentation states, enforce HTTPS.

_Originally posted by @VaibhavSys in https://github.com/is-a-dev/register/issues/12101#issuecomment-1969064430_

I can't enforce HTTPS as shown in my screenshot![image](https://github.com/is-a-dev/register/assets/98203141/c79d1d96-8a94-413d-bd77-3731ffe231d4)

**Comment by VaibhavSys** [comment]
Your domain has the wrong records setup. If you want to use GitHub Pages, you need to point your domain to the GH Pages servers, but you currently have a CNAME pointing to kotelek.dev in your [domain](https://github.com/is-a-dev/register/blob/main/domains/kotelek.json).

**Comment by xKotelek** [comment]
> Your domain has the wrong records setup. If you want to use GitHub Pages, you need to point your domain to the GH Pages servers, but you currently have a CNAME pointing to kotelek.dev in your [domain](https://github.com/is-a-dev/register/blob/main/domains/kotelek.json).

so how to without github pages redirect to https://kotelek.dev with my CNAME? if i can't do that i'll set cname to xkotelek.github.io and redirect from there

**Comment by VaibhavSys** [comment]
> > Your domain has the wrong records setup. If you want to use GitHub Pages, you need to point your domain to the GH Pages servers, but you currently have a CNAME pointing to kotelek.dev in your [domain](https://github.com/is-a-dev/register/blob/main/domains/kotelek.json).
> 
> so how to without github pages redirect to https://kotelek.dev with my CNAME? if i can't do that i'll set cname to xkotelek.github.io and redirect from there

I didn't understand what you mean, can you please explain it more clearly?

**Comment by xKotelek** [comment]
> > > Your domain has the wrong records setup. If you want to use GitHub Pages, you need to point your domain to the GH Pages servers, but you currently have a CNAME pointing to kotelek.dev in your [domain](https://github.com/is-a-dev/register/blob/main/domains/kotelek.json).
> 
> > 
> 
> > so how to without github pages redirect to https://kotelek.dev with my CNAME? if i can't do that i'll set cname to xkotelek.github.io and redirect from there
> 
> 
> 
> I didn't understand what you mean, can you please explain it more clearly?

I want to set up an github page for my domain so i set CNAME to kotelek.is-a.dev and i just redirect user to my website on my gh page?

**Comment by 21Z** [comment]
> so how to without github pages redirect to https://kotelek.dev with my CNAME? if i can't do that i'll set cname to xkotelek.github.io and redirect from there

If you want to **redirect** users to https://kotelek.dev, you can use a URL record with value `https://kotelek.dev`
