### ISSUE TITLE
issue setting up my domain

### ISSUE THREAD

**Issue by N-Nilashan** [is-a-dev/register#13520]
### Your question
![Screenshot 2024-04-21 141419](https://github.com/is-a-dev/register/assets/153603329/40301d51-a148-44fe-b415-df209f5f4580)

**Comment by alfonsop123** [comment]
Then set the game to that

**Comment by N-Nilashan** [comment]
> Then set the game to that

What do you mean?

**Comment by alfonsop123** [comment]
:/

**Comment by N-Nilashan** [comment]
![image](https://github.com/is-a-dev/register/assets/153603329/f95195be-bcb8-4792-be6b-9683fb711f9a)

its been two days since I updated my domain

**Comment by alfonsop123** [comment]
But it has not said invalid so far it seems to be good?

**Comment by N-Nilashan** [comment]
http://n-nilashan.is-a.dev/

check this link, its redirecting the site to is-a.dev site
but the dns check is still in progress

**Comment by alfonsop123** [comment]
do you know what it saids btw
Redirecting you to [www.is-a.dev](https://www.is-a.dev/)...

If you were expecting your website to show up here, it may take some time for your changes to reflect.
