### ISSUE TITLE
claiming a is-a.dev domain

### ISSUE THREAD

**Issue by nieekha** [is-a-dev/register#13617]

**Comment by wdhdev** [comment]
@nieekha Please provide your error or what's happening.

**Comment by triach-rold** [comment]
I'm pretty sure you can't claim the website yet because the [PR submitted](https://github.com/is-a-dev/register/pull/13616) is not yet approved and merged by the maintainers of the project.

**Comment by CuteDog5695** [comment]
> ### niteshpanthi.is-a.dev
> ### i am unable to claim the is-a.dev domain could somenoe assist me please

As what triach-rold said, your PR wasn't merged so you didn't have the domain, but 30 min ago I did merge it so now you have the domain. Closing issue now as resolved, if you have any other problems make another issue.
