### ISSUE TITLE
Firebase Setup

### ISSUE THREAD

**Issue by imagineeeinc** [is-a-dev/register#1362]
Your domain name: imagineee.web.app

Explain any issues you are facing
Hi, I have a firebase domain, but i am not sure of how to set it up to work with is-a.dev domain, as I can't change any domains in firebase without verifying ownership, I can't change ssl certificate.

Or maybe it'll just work like that, I really don't know.

Thanks for any help in advance.

**Comment by pythonmcpi** [comment]
You can use a TXT record to verify that you have control over your .is-a.dev domain.

**Comment by imagineeeinc** [comment]
how does that work, I've never worked with domains before
