### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by lean-cc** [is-a-dev/register#13673]
### Your subdomain
kars.is-a.dev

### The issue
When opening the url in any browser i get the following error:

![Screenshot from 2024-04-28 13-18-17](https://github.com/is-a-dev/register/assets/114680621/f50c163b-552b-4772-b70a-1741ba60e0ae)

**Comment by triach-rold** [comment]
<img width="588" alt="Screenshot 2024-04-29 at 1 07 49 AM" src="https://github.com/is-a-dev/register/assets/156170660/341f1ebb-b9c1-49e5-8654-1824bb3e6155">

Error can be replicated on safari too.

**Comment by triach-rold** [comment]
Maybe (tinfoil hat) it's an SSL fail of some kind ?

**Comment by DEV-DIBSTER** [comment]
Noticing your CNAME is pointed towards Cloudflare. Double check if any Cloudflare settings as they have plenty of security options, might be interfering with other domains coming into your pages site. Other than that, I'm not sure.
