### ISSUE TITLE
DNS Issues

### ISSUE THREAD

**Issue by ScytheMediaTheDev** [is-a-dev/register#13687]
### What is actually shows me:
![Screenshot 2024-04-29 8 18 31 AM](https://github.com/is-a-dev/register/assets/159197373/eafc006e-e5fb-42fa-85e4-229eb53cd8ed)

How do I fix?

**Comment by 21Z** [comment]
Your domain has MX records set to mx1.improvmx.com, You need to set CNAME record as your github repo to use the domain for your github site.

**Comment by CuteDog5695** [comment]
> Your domain has MX records set to mx1.improvmx.com, You need to set CNAME record as your github repo to use the domain for your github site.

or you could use A records for github pages (185.199.108.153, 185.199.109.153, 185.199.110.153, 185.199.111.153)

**Comment by ScytheMediaTheDev** [comment]
Hey @21Z and @CuteDog5695 would it be possible to keep the current MX and add CNAME? I have no idea about domain limits.

**Comment by CuteDog5695** [comment]
you cant use CNAME with any other record

**Comment by ScytheMediaTheDev** [comment]
what about A records @CuteDog5695 ?

**Comment by CuteDog5695** [comment]
> what about A records @CuteDog5695 ?

with A records you can use them with any record (except for URL and CNAME because URL is for redirecting while CNAME is like an alias or smth)

**Comment by ScytheMediaTheDev** [comment]
dang 
well I have all DNS set up so if you want to check out my website @CuteDog5695 here it is: https://scythemedia.is-a.dev/
