### ISSUE TITLE
Feedback/suggestion: Find an alternate way to store the domains/*.json files for security of email and discord ids and other info

### ISSUE THREAD

**Issue by hirenchauhan2** [is-a-dev/register#13721]
### What do you want added?
Secure way to store the domain related info in DB or in private storage instead of making it public in GitHub.

I came to this repo by some filtering on GH for trending repos for JS language. Upon going through some JSON files in `domains/` folder I saw a lot of personal data like emails, discord user id or some other id, social handles, etc. These details can be used for social engineering, marketing and whatnot. 🤷‍♂️ 

The amount of personal info (email, socials, discord Ids, etc.) can be used for any kind of use(good and bad - which is more likely in most cases) without any trace or audit of access since its public in GitHub.

If you don't think this is serious issue, then please close it! 😃 

Thank you.

**Comment by wdhdev** [comment]
It would be too much effort to move to a different system and we would also have to get Phenax to approve it as none of us have access to API keys and the required tools.
