### ISSUE TITLE
Your connection is not private

### ISSUE THREAD

**Issue by ScytheMediaTheDev** [is-a-dev/register#13762]
### What actually happened 
![image](https://github.com/is-a-dev/register/assets/159197373/17ee231c-5fd2-4b7d-9b46-d504679a2f48)

**Comment by CuteDog5695** [comment]
![image](https://github.com/is-a-dev/register/assets/69630113/497e0a7b-e002-481d-811f-25e206e99155)
did you enable this on your github page?

**Comment by ScytheMediaTheDev** [comment]
@CuteDog5695 
![image](https://github.com/is-a-dev/register/assets/159197373/ec79fc6f-ec98-4b70-9664-65b1969bed45)

**Comment by ScytheMediaTheDev** [comment]
Unavailable for your site because a certificate has not yet been issued for your domain

**Comment by ScytheMediaTheDev** [comment]
Nevermind as the "Enforce HTTPS" let me press the checkmark and it says it has a certificate. Thanks! The site is launched at ScytheMedia.is-a.dev
