### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by Nooby69** [is-a-dev/register#13800]
## Your Subdomain:

huz.is-a.dev 

## The Issue:

The issue I am facing is that my subdomain hasn't linked yet, maybe because of the TXT of the replit.com
My TXT: replit-verify=5b77bf69-39e2-433c-add4-e59c20476eab

![image](https://github.com/is-a-dev/register/assets/92811228/e1c35861-119b-448c-ac11-c9b0959eba48)

**Comment by CuteDog5695** [comment]
> ## Your Subdomain:
> huz.is-a.dev
> 
> ## The Issue:
> The issue I am facing is that my subdomain hasn't linked yet, maybe because of the TXT of the replit.com My TXT: replit-verify=5b77bf69-39e2-433c-add4-e59c20476eab
> 
> ![image](https://private-user-images.githubusercontent.com/92811228/327779916-e1c35861-119b-448c-ac11-c9b0959eba48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MjIxMzksIm5iZiI6MTcxNDgyMTgzOSwicGF0aCI6Ii85MjgxMTIyOC8zMjc3Nzk5MTYtZTFjMzU4NjEtMTE5Yi00NDhjLWFjMTEtYzliMDk1OWViYTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDExMjM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNmI1MmYwNWZjZmMwOTRlYjMzNmU0OWI2NDBiYWEyY2RiOTA4MTk1MTM3MGFmNDI2ZWRhYTQ4MGE1NGM3ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vvNnFV2KbKQHjF3sg-oWl-2opDb9Ez8vXfdMbdOYg_U)

is-a.dev doesnt use cloudflare, its most probably because the DNS hasn't propagated yet, wait 48 hrs like replit told you and if it still doesn't work let us know

**Comment by Nooby69** [comment]
> > ## Your Subdomain:
> > huz.is-a.dev
> > ## The Issue:
> > The issue I am facing is that my subdomain hasn't linked yet, maybe because of the TXT of the replit.com My TXT: replit-verify=5b77bf69-39e2-433c-add4-e59c20476eab
> > ![image](https://private-user-images.githubusercontent.com/92811228/327779916-e1c35861-119b-448c-ac11-c9b0959eba48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MjIxMzksIm5iZiI6MTcxNDgyMTgzOSwicGF0aCI6Ii85MjgxMTIyOC8zMjc3Nzk5MTYtZTFjMzU4NjEtMTE5Yi00NDhjLWFjMTEtYzliMDk1OWViYTQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA0VDExMjM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNmI1MmYwNWZjZmMwOTRlYjMzNmU0OWI2NDBiYWEyY2RiOTA4MTk1MTM3MGFmNDI2ZWRhYTQ4MGE1NGM3ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vvNnFV2KbKQHjF3sg-oWl-2opDb9Ez8vXfdMbdOYg_U)
> 
> is-a.dev doesnt use cloudflare, its most probably because the DNS hasn't propagated yet, wait 48 hrs like replit told you and if it still doesn't work let us know

This issue is still persisting; it hasn't been resolved despite giving it ample time.
![image](https://github.com/is-a-dev/register/assets/92811228/edd41a44-459a-4401-b409-b162c2224ea6)
![image](https://github.com/is-a-dev/register/assets/92811228/dc7606cf-a0cf-4484-a0ac-fc704f09f6f4)

**Comment by CuteDog5695** [comment]
weird....
is 5b77bf69-39e2-433c-add4-e59c20476eab.id.repl.co the record replit wants you to put in the domain or is it another thing? (reason why im asking is because the record I mentioned is in the domain)

**Comment by Nooby69** [comment]
> weird.... is 5b77bf69-39e2-433c-add4-e59c20476eab.id.repl.co the record replit wants you to put in the domain or is it another thing? (reason why im asking is because the record I mentioned is in the domain)

Yuh the record replit wants me to put in the domain is cname which you mentioned already, but it didn't connected yet, hence I thought that you maybe need to add the TXT record also.

**Comment by wdhdev** [comment]
We don’t support Replit’s TXT verification record yet so unfortunately you will most likely have to use another provider.
