### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by Praizee** [is-a-dev/register#13823]
### Your subdomain

https://stephen-adeniji.is-a.dev/

### The issue

How do I get past this please?

![image](https://github.com/is-a-dev/register/assets/89282358/3fe65a16-5558-4e34-8d48-26877407b8d6)

The 'is-a.dev' domain keeps redirecting to vercel

**Comment by CuteDog5695** [comment]
you chose URL record, which ofc just redirects so you cant connect the domain. If you wanted to connect the domain then Vercel and Netlify arent an option since it doesnt work atm, so as an afternative you could try Cloudflare Pages

**Comment by Praizee** [comment]
Oh okay
Thanks
