### ISSUE TITLE
https://manage.is-a.dev/ is redirecting to https://github.com/is-a-dev/register

### ISSUE THREAD

**Issue by jasmeetsinghbhatia** [is-a-dev/register#13860]
### Your subdomain
https://jasmeetsingh.is-a.dev/

### Expected outcome
This used to take to the manage dashboard where I had setup the analytics for my domain. 
### Observed outcome
visting https://manage.is-a.dev/ is now redirecting to https://github.com/is-a-dev/register and I am not able to view the analytics of my subdomain.

**Comment by LoganPaxton** [comment]
I believe they moved it to Discord?

> Join our [Discord server](https://discord.gg/is-a-dev-830872854677422150), head to the commands channel and run /register. The bot will ask you a few questions then will generate your PR and domain automatically. The bot also allows for domain deletion and editing.

**Comment by CuteDog5695** [comment]
> ### Your subdomain
> https://jasmeetsingh.is-a.dev/
> 
> ### Expected outcome
> This used to take to the manage dashboard where I had setup the analytics for my domain.
> 
> ### Observed outcome
> visting https://manage.is-a.dev/ is now redirecting to https://github.com/is-a-dev/register and I am not able to view the analytics of my subdomain.

we shutdown manage website due to many invalid PR's

**Comment by wdhdev** [comment]
If you are wanting more information on the manage site shutdown, please join our Discord server.
