### ISSUE TITLE
What bug did you encounter?

### ISSUE THREAD

**Issue by CycloneAddons** [is-a-dev/register#13894]
### Your subdomain 
cycloneaddons.is-a.dev

### Expected outcome 
my portfolio https://GitHub.com/CycloneAddons/cycloneaddons.github.io

### Observed outcome 
redirecting to is-a.dev

**Comment by CycloneAddons** [comment]
![Screenshot_2024-05-09-08-32-19-658_com android chrome](https://github.com/is-a-dev/register/assets/90061864/e60780b6-b2b9-4046-8480-c2e79f0560a0)

**Comment by tylercalumacker** [comment]
It looks fine to me. Also, if this is for your portfolio then I would recommend a page for your projects and add a bit more information about yourself. Companies want that.

**Comment by CuteDog5695** [comment]
> ![Screenshot_2024-05-09-08-32-19-658_com android chrome](https://private-user-images.githubusercontent.com/90061864/329112828-e60780b6-b2b9-4046-8480-c2e79f0560a0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNTMwNDIsIm5iZiI6MTcxNTI1Mjc0MiwicGF0aCI6Ii85MDA2MTg2NC8zMjkxMTI4MjgtZTYwNzgwYjYtYjJiOS00MDQ2LTg0ODAtYzJlNzlmMDU2MGEwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDExMDU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzYWZlMTk1NzA3OTBjNGVkMDhlZGMwMjhjYzIwMWQxYTk3MWViOTUzZjdiYjYzMWM4NjQxMzcyYTU0NWRkYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eG_S_-eHphyYq-cnWGa6mULIfO9ev-PQiswGWvlvDeU)

could be cache problem, try clearing cache

**Comment by wdhdev** [comment]
The website works for me, this is a cache issue, try clearing your cache. You can find a guide on this on Google.
