### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by ScytheMediaTheDev** [is-a-dev/register#13919]

**Comment by CuteDog5695** [comment]
> ### What happened to the manage dashboard for is-a.dev? I was using it for editing and registering subdomains. Why cant we register through there now?

is-a.dev manage dashboard shutdown, for more information join the discord server

**Comment by ScytheMediaTheDev** [comment]
ok thanks. btw you should add a widget on is-a.dev with widgetbot.io to show the DC server. Just a suggestion @CuteDog5695
