### ISSUE TITLE
How long does it take for a CNAME to change to a desired CNAME.

### ISSUE THREAD

**Issue by dzired** [is-a-dev/register#1396]
I was just wondering how long it took for a cname to change. I asked for a change and it was accepted, but it still has not changed yet. Just wondering for an estimate.
![2D5CE4C9-1823-4711-AA01-F8B44E310FC5](https://user-images.githubusercontent.com/70129751/142792940-2239de51-841d-4f7a-a7e5-30d6f0403d94.jpg)

**Comment by AcaiBerii** [comment]
for me it took like 72 hrs lol

**Comment by hackermondev** [comment]
Is it still not connected?

**Comment by dzired** [comment]
![image](https://user-images.githubusercontent.com/70129751/143794441-33046fa4-52c1-488c-8f91-26e58bce0961.png)

**Comment by dzired** [comment]
When I try it on github, it still doesn't work for the ____.github.io cname

**Comment by dzired** [comment]
bump, ill try it later to double check it but I dont think its changed yet

**Comment by dzired** [comment]
still hasnt changed

**Comment by dzired** [comment]
![897361533770809414](https://user-images.githubusercontent.com/70129751/145664700-85f3948c-65df-4598-96dc-a92b3c205a55.gif)
