### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by RadioactivePotato** [is-a-dev/register#14035]
### Your subdomain
krunch.is-a.dev
### The issue
The subdomain redirects to is-a.dev (only on `krunch.is-a.dev`, `krunch.is-a.dev/whatever` works)

Also, for some reason, the DNS check is endless
![image](https://github.com/is-a-dev/register/assets/75719839/540e2368-8598-4ad8-a241-835a2529e234)

***
https://github.com/is-a-dev/register/blob/835c61336c953d36e315d6c53565c33fa648d1d8/domains/krunch.json#L7

The repo for my site is https://github.com/radioactivepotato/radioactivepotato.github.io

**Comment by CuteDog5695** [comment]
> The subdomain redirects to is-a.dev
Try clearing your cache in your browser

**Comment by RadioactivePotato** [comment]
It doesn't redirect to is-a.dev anymore, but the page is blank, the tab title works, but the content of the page doesn't, inspecting using the dev console shows that the code works properly, but it doesn't display the contents for some reason

**Comment by 21Z** [comment]
This is an issue with your code, does it work for you without the is-a.dev domain?

**Comment by RadioactivePotato** [comment]
It probably is
