### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by spacewd69** [is-a-dev/register#14170]
### Your subdomain
spacewd.is-a.dev
### The issue
Can you please delete the subdomain above? I no longer use it and i have deleted the website that used it.

**Comment by 21Z** [comment]
Fork this repository,
then on your fork, delete your domain file (`spacewd.json`) from the domains folder and open a PR

**Comment by spacewd69** [comment]
I would but i cant

**Comment by 21Z** [comment]
> I would but i cant

Wdym you can't, why not?

**Comment by spacewd69** [comment]
Githib limits it down to 1,000 files and my file (spacewd.json) is one of the files beyond the 1,000 file limit

**Comment by spacewd69** [comment]
Nvm i found an easier way to delete it (Go to file.)

**Comment by 21Z** [comment]
You could have just searched it in the folder btw

**Comment by spacewd69** [comment]
I didnt know that also i am now trying to delete it as it is now an
indonesian scam site
