### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by thatcatdrout** [is-a-dev/register#1443]
Your domain name: thatcatdrout.netlify.app

Explain any issues you are facing

So i have a site on netlify and i wanna add "is-a.dev" to the site but netlify does not work (as you said on annother issue) but Railway does not work! (Im using gatsby for my site) please help

**Comment by MaskDuck** [comment]
You should read [this](https://github.com/is-a-dev/register/blob/dd982847bee81832c19ea31a32d5e966c8d00802/docs/README.md). It say that you should not use Netlify, instead use other service!

**Comment by thatcatdrout** [comment]
forget it i ported my app over to Stormkit and i think it will work
