### ISSUE TITLE
Font issue with `logo.svg`

### ISSUE THREAD

**Issue by wdhdev** [is-a-dev/register#14487]
The image https://github.com/is-a-dev/register/blob/main/media/logo.svg does not match the other logos' font.

![](https://github.com/is-a-dev/register/raw/main/media/logo.svg)

**Comment by phenax** [comment]
Aah. Seems like I exported this one incorrectly.

**Comment by wdhdev** [comment]
I'm surprised no one noticed it for 4 years 🤣
