### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by Char0nDev** [is-a-dev/register#14623]
**charon.is-a.dev**

 charon.is-a.dev is improperly configured
Domain does not resolve to the GitHub Pages server. For more information, see [documentation](https://docs.github.com/articles/setting-up-a-custom-domain-with-github-pages/) (NotServedByPagesError).

**Comment by Char0nDev** [comment]
@wdhdev

**Comment by CuteDog5695** [comment]
Your CNAME is pointed to a different CNAME thats not by github. You'd need to change your CNAME record to char0ndev.github.io

**Comment by Char0nDev** [comment]
but how ?

**Comment by CuteDog5695** [comment]
Edit your json file from your fork, after you make the changes you need to make a PR.
