### ISSUE TITLE
Subdomain returns DNS_PROBE_FINISHED_NXDOMAIN

### ISSUE THREAD

**Issue by tobezdev** [is-a-dev/register#14767]
### Your subdomain
`tobez.is-a.dev`

### The issue
Welp, you just can't connect to it. Seems odd, as I can use other sites like https://www.is-a.dev/, but who knows?
I've attempted connecting on multiple devices, networks and without VPN, to no avail :(

Not too sure what the error `DNS_PROBE_FINISHED_NXDOMAIN` means, but open to trying different solitions :)

![Error Screenshot](https://github.com/is-a-dev/register/assets/83095177/2f090e7a-110c-4250-8f3e-a023d6710cd8)

TIA

**Comment by VaibhavSys** [comment]
That is strange, as your domain contains a URL record. You can try using [Redirect Pizza](https://redirect.pizza) in the mean time

**Comment by CuteDog5695** [comment]
URL records have been unstable for a while now, I think this is like the 2nd or third time this has happened. I'd recommend you go to https://redirect.pizza/ (Like what the maintainer above said) since its way more reliable and stable currently.
