### ISSUE TITLE
My PR has been open for over 2 months now

### ISSUE THREAD

**Issue by KK-Designs** [is-a-dev/register#1482]
I had accidentally created an incorrect `CNAME` and created a new pull request as the docs said to. All validation checks were passed but no one came to approve and merge my pull request.

> Pull request #1417 

User             |  Pull request
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/71038229/146442731-1f68658d-7f13-424d-bbef-ffedb518a2cc.png)  |  ![image](https://user-images.githubusercontent.com/71038229/146443785-2b420040-2e5f-44d5-a369-188e8a7bf08c.png)

**Comment by MaskDuck** [comment]
yeah metoo

**Comment by KK-Designs** [comment]
If the developer abounded or delayed wait times, he could have told us.

**Comment by KK-Designs** [comment]
@is-a-dev I'm here almost 3 times every week you can just put me in charge of approving and rejecting PR's.

**Comment by hexed** [comment]
@Codeize @hackermondev @mtgsquad @TheBotlyNoob

**Comment by YummyOreo** [comment]
i think this is dead, the last commit was 20 days ago

**Comment by KK-Designs** [comment]
Or maybe he had better things to do. Still, even if he did abandon the project he could have at least told us.

**Comment by YummyOreo** [comment]
yeah

**Comment by phenax** [comment]
https://github.com/is-a-dev/register/discussions/1529

**Comment by KK-Designs** [comment]
Ok, thank you. I understand that.
