### ISSUE TITLE
Whats your question

### ISSUE THREAD

**Issue by vrbz** [is-a-dev/register#14833]
i was wondering if it would be possible to delete my subdomain (vrbz.is-a.dev) or at least transfer it over to my discord account instead?

**Comment by RohanDaCoder** [comment]
You could fork the repo, delete your domain file, commit it, then open a pull request

Only if you own the domain...

**Comment by CuteDog5695** [comment]
> i was wondering if it would be possible to delete my subdomain (vrbz.is-a.dev) or at least transfer it over to my discord account instead?

That subdomain doesn't exist though, did you delete it already?

**Comment by vrbz** [comment]
> That subdomain doesn't exist though, did you delete it already?

The subdomain doesn't no, but i tried to make it in discord, the subdomain is available, however i can't create it because the file already exists

**Comment by Priyanshul130** [comment]
my file exist in the domain folder but i am not able to access it in the web

**Comment by CuteDog5695** [comment]
> my file exist in the domain folder but i am not able to access it in the web

Make a issue yourself, or make a help thread on discord.

**Comment by Priyanshul130** [comment]
ohkkkkkk but now everything is resolved 🫠
