### ISSUE TITLE
Whats your question

### ISSUE THREAD

**Issue by Insencel** [is-a-dev/register#14876]
### Your question
When creating a pull reqeust I am confused about two "requirements" that are stated in the template:

"You have completed your website.": For me the answer is no. I wish to use this as a testing-sub domain and for setting up Typo3. I am starting to work on my website, but according to the setup guide i need to bind a subdomain so my linux server knows which requests to accept for my Typo3 instance. So no I don't have completed my website, is this a problem for setting up a subdomain with A record?

"The website is reachable.": Again, probably not yet. I am trying to set it up. Is that a problem?

**Comment by wdhdev** [comment]
That's no problem, just create your PR anyway and I'll let our maintainers know to approve it :)
