### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by Insencel** [is-a-dev/register#14875]
### Your subdomain
insencel.is-a.dev (don't think it exists yet?)

### The issue
I've tried to create a push request for it on this repository a few days ago and am unsure if it went through or if it was rejected because I didn't create an issue before making the pull request (documentation says to open an issue before any changes in the repository and i missed that before). 
I'm unsure if I now should try to make another pull request (if the first one even went through) or if i should continue to wait.

**Comment by wdhdev** [comment]
> documentation says to open an issue before any changes in the repository and i missed that before

The docs do not say that if I remember correctly.
Also you have not even opened a PR: https://github.com/is-a-dev/register/pulls?q=sort%3Aupdated-desc+is%3Apr+author%3AInsencel
