### ISSUE TITLE
Support with DNS RECORD

### ISSUE THREAD

**Issue by xKotelek** [is-a-dev/register#14910]
### Your subdomain
kotelek.is-a.dev
### The issue
I use "URL" type of record pointing to https://kotelek.dev but:
1. GitHub still doesn't want me to enable Enforce HTTPS
![image](https://github.com/user-attachments/assets/9df94cae-5127-4d3f-aa2d-cb5373d7f72b)
2. I get "This website uses unsupported protocol" error
![image](https://github.com/user-attachments/assets/9f0c6095-15fa-4476-a8f2-dcbb6e6a93ed)

**Comment by wdhdev** [comment]
You need to configure a CNAME record, not a URL record in that case. Change your record to a CNAME record with the content `your-github-username.github.io`
