### ISSUE TITLE
[Feedback/suggestion] add `_` to `extraSupportedNames`

### ISSUE THREAD

**Issue by MCPE-PC** [is-a-dev/register#14952]
### What do you want added?

The test does not allow `_` in the domain name by default and requires 2 or more characters.

I wanted to use [ForwardDomain.net](https://forwarddomain.net/) in #14913 and its domain name for the `TXT` record is `_.(DN)`.

[https://github.com/is-a-dev/register/blob/37c2cb9e83e366f5f9ddeb9c005436c331cbe4a7/utils/validations.js#L39-L47](https://github.com/is-a-dev/register/blob/37c2cb9e83e366f5f9ddeb9c005436c331cbe4a7/utils/validations.js#L39-L47)

Seeing here, I suggest adding the exact `_` to the allowlist.

**Comment by d3vadam** [comment]
Why do you wanna forward a is-a.dev domain? It's meant to be used to showcase your work and/or a portfolio.

**Comment by MCPE-PC** [comment]
@d3vadam I first considered making a separate showcase website but I decided to forward it to my primary personal website.
The site is under redevelopment as of now.

**Comment by wdhdev** [comment]
I would recommend just using https://redirect.pizza or our built in URL records.
