### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by anoopmsivadas** [is-a-dev/register#150]
Your domain name: anoop.is-a.dev

Explain any issues you are facing
I was trying to use it with gitlab page. But in order to verify the domain's ownership have to update the ```TXT``` field in the DNS record.

**Comment by phenax** [comment]
Currenty, we are facing some issues with publishing the recently merged domains. Will let you know as soon as the issue has been resolved.

**Comment by anoopmsivadas** [comment]
OK Cool!

**Comment by phenax** [comment]
Your subdomain `anoop.is-a.dev`, should be accessable now. Make sure you select `Enforce https` in your github pages settings for https. Closing this issue now.
