### ISSUE TITLE
3 days have passed and my domain doesn't link to my page

### ISSUE THREAD

**Issue by FormunaGit** [is-a-dev/register#15071]
### Your subdomain
formuna.is-a.dev
### The issue
When accessing [formuna.is-a.dev](https://formuna.is-a.dev/), it doesn't send me to my website (formunagit.github.io). Instead, it gives me this message:
```
Redirecting you to [www.is-a.dev](https://www.is-a.dev/)...

If you were expecting your website to show up here, it may take some time for your changes to reflect.
```
I've been given this message several times.
This is a screenshot from the `Pages` settings in my website repo:
![image](https://github.com/user-attachments/assets/282cb214-109c-4d1d-a501-a8d47cc5d0a3)

**Comment by CuteDog5695** [comment]
Works for me, clear your browser cache

**Comment by FormunaGit** [comment]
Oh... I'm sorry for making an issue :(
