### ISSUE TITLE
1 letter subdomains

### ISSUE THREAD

**Issue by wdhdev** [is-a-dev/register#15083]
Can we add support for 1 letter subdomains? Is there a reason they aren't supported?

I would like to setup a subdomain called `m.is-a.dev` for maintainer email addresses as `maintainers.is-a.dev` is too long.

**Comment by EducatedSuddenBucket** [comment]
yes i want that

**Comment by EducatedSuddenBucket** [comment]
to use i.esb.is-a.dev isntead of img.esb.is-a.dev

**Comment by wdhdev** [comment]
If I can get @phenax's approval on this, I should be able to just update the CI myself as I don't think it would be too difficult.

**Comment by phenax** [comment]
@wdhdev Sounds good!

On a sidenote, if we alias maintainers to `m`, someone with `h` for example can pretend to be the official "help". Not a problem with 1 letter subdomains in particular, just something to be aware of.

**Comment by wdhdev** [comment]
I'm sure our maintainers will be able to detect any potential abuse quite quickly. Now that gave me an idea, is it worth creating a page on the docs or something with all the official domain names run by the staff?
