### ISSUE TITLE
site not reachable

### ISSUE THREAD

**Issue by kunsh13** [is-a-dev/register#15200]
> I'm about to merge this; your site will be available at https://kunsh13.isa.dev/iptv.

The site can't be reached
@orxngc

_Originally posted by @kunsh13 in https://github.com/is-a-dev/register/issues/15146#issuecomment-2255436447_

**Comment by wdhdev** [comment]
He made a typo there by accident. It should be https://kunsh13.is-a.dev/iptv. Please note you need to setup GitHub Pages with your custom domain properly for it to work.

**Comment by kunsh13** [comment]
> He made a typo there by accident. It should be https://kunsh13.is-a.dev/iptv. Please note you need to setup GitHub Pages with your custom domain properly for it to work.

Ok thank you
