### ISSUE TITLE
Users with multiple 1 letter subdomains

### ISSUE THREAD

**Issue by wdhdev** [is-a-dev/register#15201]
We have decided to limit the amount of 1 letter **root** subdomains (not nested subdomains like `a.william.is-a.dev`) to 1 per user on a first come, first served basis. This is due to the fact we do not want a monopoly of one user owning many of them.

The users listed below will have to decide on which one letter subdomain they would like to keep, and the rest will become available.

@PogMaster9001 - `0.is-a.dev`, `1.is-a.dev`, `a.is-a.dev`, `b.is-a.dev`, ~~`p.is-a.dev`~~ - you must choose one to keep, the others will be removed
~~@Yunexiz - `d.is-a.dev`, `k.is-a.dev`, `y.is-a.dev` - you must choose one to keep, the others will be removed~~

Please note the domains listed here **are** up for grabs by the rest of the public if they want them until you make your decision. So the one you want to keep may be gone if another user wants it before you reply here.

**Comment by Yunexiz** [comment]
Just delete k.json and d.json

**Comment by Yunexiz** [comment]
I've set up everything on my side so it should seamlessly dissappear

**Comment by PogMaster9001** [comment]
Ill keep 0.is-a.dev
