### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by kunsh13** [is-a-dev/register#15219]
Hey what do I do about this?
```See the image```

![Screenshot_20240729_201434_Chrome](https://github.com/user-attachments/assets/bc4e1407-1699-4d0f-9470-7f32e191d055)

**Comment by EducatedSuddenBucket** [comment]
Bro read the docs https://docs.is-a.dev/

**Comment by kunsh13** [comment]
> Bro read the docs https://docs.is-a.dev/

Aah this means I have to open another pull request Gosh
