### ISSUE TITLE
question

### ISSUE THREAD

**Issue by kunsh13** [is-a-dev/register#15223]
### My question
Q1. How can I use the domain in multiple repositorys(i have added the domain in my github account's settings)?

Q2. How can I use the domain to receive and view emails on it?

**Comment by kunsh13** [comment]
> Q1: I don't understand what you are saying, elaborate Q2: improvmx, search it up

Elaboration for Q1:

For example 
kunsh13.is-a.dev/repo1 ,  kunsh13.is-a.dev/repo2 
And so on

**Comment by kunsh13** [comment]
Also I wanted to know that whether java script is enabled, as when I open my site it is blank and just shows css buttons

**Comment by orxngc** [comment]
Q1: For kunsh13.is-a.dev, use a CNAME record of kunsh13.github.io. Then you will be able to do kunsh13.is-a.dev/repo1 and kunsh13.is-a.dev/repo2.
Javascript has nothing to do with the domain. If it isn't working, it means you broke your own code, 'tis nothing to do with us.

**Comment by kunsh13** [comment]
will this do it?

![image](https://github.com/user-attachments/assets/048d1b23-fd47-4d7a-90d1-9f645afdce7e)

**Comment by EducatedSuddenBucket** [comment]
use a records for github pages (find it yourself) if you want to use mail with the same subdomain , and you can send mail using improvmx

**Comment by kunsh13** [comment]
> will this do it?
> 
> ![image](https://private-user-images.githubusercontent.com/52669820/353407172-048d1b23-fd47-4d7a-90d1-9f645afdce7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNDEyNTYsIm5iZiI6MTcyMjM0MDk1NiwicGF0aCI6Ii81MjY2OTgyMC8zNTM0MDcxNzItMDQ4ZDFiMjMtZmQ0Ny00ZDdhLTkwZDEtOWY2NDVhZmRjZTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDEyMDIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMWNjNGY4ZjE3YWRiNmYyYmJkMjlkZTNjYWUwMDExODE0ZTUzZTQ2ZmU4OWZjY2QxNDQ4NzBjNzA2ZWRjMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jBLRKZ_jZi_V59Zx35fpW5DzXoIMdewFEeQGJ-3RxFU)

??

**Comment by kunsh13** [comment]
hey, on the usual GitHub domain, my website worked fine but when I added ```kunsh13.is-a.dev``` I get the following errors in the browser console


![image](https://github.com/user-attachments/assets/b1e75a54-9e4f-4151-a0e0-46b1b8249969)

**Comment by dhruvakalur** [comment]
> > Q1: I don't understand what you are saying, elaborate Q2: improvmx, search it up
> 
> Elaboration for Q1:
> 
> For example kunsh13.is-a.dev/repo1 , kunsh13.is-a.dev/repo2 And so on
> 
> And for Q2: I don't want to just forward emails I receive (as you suggested) on the is-a.dev Domain I want to send and receive both directly from is-a.dev domain

someone tell how Q2 can be done

**Comment by kunsh13** [comment]
> For kunsh13.is-a.dev, use a CNAME record of kunsh13.github.io. Then you will be able to do kunsh13.is-a.dev/repo1 and kunsh13.is-a.dev/repo2. Javascript has nothing to do with the domain. If it isn't working, it means you broke your own code, 'tis nothing to do with us.

@orxngc I am already using a CNAME record of kunsh13.github.io however it is not working
I'm talking abt <name>.is-a.dev/<repo-name>

**Comment by orxngc** [comment]
@kunsh13 That is very odd. Are you sure the repository is named correctly? Is the repository public?

**Comment by kunsh13** [comment]
> @kunsh13 That is very odd. Are you sure the repository is named correctly? Is the repository public?

The repo is indeed named correctly and is public

**Comment by kunsh13** [comment]
> > @kunsh13 That is very odd. Are you sure the repository is named correctly? Is the repository public?
> 
> The repo is indeed named correctly and is public

Hello,
reply pls

**Comment by 21Z** [comment]
@kunsh13 Make a repository with the name `kunsh13.github.io`, this is known as your user site
now assign the custom domain to this repo (in the repo's settings)
now when you visit kunsh13.is-a.dev/repo1 or kunsh13.is-a.dev/repo2 it should work as you expected

**Comment by SkyExploreWasTaken** [comment]
@kunsh13 for email you can use the service [SimpleLogin](https://SimpleLogin.io) because it's really easy to send emails with that.

**Comment by kunsh13** [comment]
> @kunsh13 Make a repository with the name `kunsh13.github.io`, this is known as your user site now assign the custom domain (kunsh13.is-a.dev) to this repo (in this repo's settings) now when you visit kunsh13.is-a.dev/repo1 or kunsh13.is-a.dev/repo2 it should work as you expected

I have tried it but it is still not working (by assigning the domain to the repo ```github.com/kunsh13/kunsh13``` in the settings)

**Comment by 21Z** [comment]
> I have tried it but it is still not working (by assigning the domain to the repo `github.com/kunsh13/kunsh13` in the settings)


`github.com/kunsh13/kunsh13.github.io` not `github.com/kunsh13/kunsh13`
