### ISSUE TITLE
Receiving the error message «net::ERR_CERT_COMMON_NAME_INVALID» while trying to access my page.

### ISSUE THREAD

**Issue by KittyNeverDies** [is-a-dev/register#15327]
### Your subdomain
https://kittyneverdies.is-a.dev/

### The issue
I'm trying to use the is-a-dev domain for my website, which is hosted on GitHub Pages. The website is supposed to display the content of this page: https://kittyneverdies.github.io/.

However, when I try to open the website, I receive an error in my browser: "net::ERR_CERT_COMMON_NAME_INVALID". All the browsers I've tried to use display a warning: "Your connection is not private. Attackers might be trying to steal your information from kittyneverdies.is-a.dev".

I can open other subdomains on the is-a.dev subdomain, such as "www" or "dog". I'm not sure why this issue is happening and if it's caused by me.

Thank you for any help or support you can provide.

**Comment by CuteDog5695** [comment]
You need SSL. Go to the Pages section on your sites repo and click on "Enable HTTPS"
