### ISSUE TITLE
Website SSL issues

### ISSUE THREAD

**Issue by Ewan-Dev** [is-a-dev/register#15341]
### Your subdomain
ewan.is-a.dev
### The issue
My website is not live yet; after checking the latest commit on my JSON file, it has the details of another user. But my JSON file has the **correct** information **in the domains folder**. May I have assistance?

**Comment by CuteDog5695** [comment]
Seems that you haven't gotten a SSL for your domain currently. Since you are using Github Pages go to your repo's settings and go to the Pages section, and then there you can click on "Enable HTTPS". After you have done that you can clear your browser cache and it should work.

**Comment by Ewan-Dev** [comment]
Hi, thanks for your reply. I think this already seems to be the case (attached). Do you propose any other reason why?
![Uploading Screenshot 2024-08-04 at 15.02.33.png…]()

**Comment by Ewan-Dev** [comment]
> Seems that you haven't gotten a SSL for your domain currently. Since you are using Github Pages go to your repo's settings and go to the Pages section, and then there you can click on "Enable HTTPS". After you have done that you can clear your browser cache and it should work.

Hi. Thanks for your time. I figured I had to add the domain (name.is-a.dev) in settings > pages > custom domain.
