### ISSUE TITLE
SSL Certificate's Expired

### ISSUE THREAD

**Issue by alexpcooper** [is-a-dev/register#1535]
### Expected outcome
https://is-a.dev/ will load

### Observed outcome
*.is-a.dev Certificate ha Expired: Saturday, 25 December 2021 at 06:49:47 Greenwich Mean Time

**Comment by StringentDev** [comment]
Encountered this too. They will need to recreate the LetsEncrypt certificate... I use OpenSSL for mine and it works (weirdly)

**Comment by phenax** [comment]
This was on hold due to the issue described in #1529. This has been fixed today.
