### ISSUE TITLE
Can I use "sub-domains" on my domain name?

### ISSUE THREAD

**Issue by FormunaGit** [is-a-dev/register#15360]
Can I use, for example, `api.formuna.is-a.dev` and link it to a different server(/port)?
I really would like to use my domain as an e-mail (ImprovMX?) and to have self-hosted instances usable on it.

**Comment by wdhdev** [comment]
Yes, you can.

**Comment by FormunaGit** [comment]
How would I do this? Is there any special thing I have to do or do I just type `api.formuna.is-a.dev` as the custom url for a github page?

**Comment by wdhdev** [comment]
Yes, just do that.
