### ISSUE TITLE
Support : Changing the domain

### ISSUE THREAD

**Issue by nightcoder26** [is-a-dev/register#15380]
### My subdomain
[nightcoder26.is-a.dev](https://nighcoder26.is-a.dev/)

### The issue
Is there way to change the domain name without requesting for a new one.

I used my GitHub username instead of the desired domain name. Could you please assist me with updating the domain name to bhavitha.is-a.dev ?

Thank you for your understanding and help!

**Comment by CuteDog5695** [comment]
You can just rename the json file in your fork.

**Comment by nightcoder26** [comment]
Thank you
