### ISSUE TITLE
I recently got a domain arafat.is-a.dev but when I try to add it to my github pages site, its showing its alread taken. Please help me.

### ISSUE THREAD

**Issue by yasar-arafath** [is-a-dev/register#15439]
I recently got a domain arafat.is-a.dev but when I try to add it to my github pages site, its showing its alread taken. Please help me.

i am getting like this: The custom domain `arafat.is-a.dev` is already taken. If you are the owner of this domain, check out https://docs.github.com/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages for information about how to verify and release this domain.

_Originally posted by @yasar-arafath in https://github.com/is-a-dev/register/issues/15426#issuecomment-2275793323_

**Comment by oliik2013** [comment]
do you registered this domain and the pull got accepted?

**Comment by wdhdev** [comment]
Simply verify your domain to your account using this link: https://docs.github.com/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages

Then, it will be locked to your GitHub account.
