### ISSUE TITLE
[Support]

### ISSUE THREAD

**Issue by MRJ-Badshah** [is-a-dev/register#1546]
Your domain name:
mrj.is-a.dev
Explain any issues you are facing:
I created mrj.json 3 day ago till not activated why??????

**Comment by MaskDuck** [comment]
#1529

**Comment by phenax** [comment]
We are currently trying to catch up with the backlog and will get to your pr soon

**Comment by MRJ-Badshah** [comment]
Thanks for reply 😃

**Comment by aduckuwu** [comment]
LOL, I waited for 2 months, what are you expecting :)

**Comment by MRJ-Badshah** [comment]
Ok
