### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by r-b-l-x** [is-a-dev/register#15614]
### Your subdomain
https://rblx.is-a.dev/

### The issue
Sorry to bother you. The https://rblx.is-a.dev/ subdomain was activated a few days ago, but it never worked. I have tried with 5 different browsers on 3 different networks, but with none of them I can view the website. In all cases I get errors about the impossibility to create a secure connection (for example in Firefox: "This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox may only connect to it securely. As a result, it is not possible to add an exception for this certificate.") or messages like "SSL: no alternative certificate subject name matches target host name 'rblx.is-a.dev'.". I changed the site (on https://r-b-l-x.github.io/ ) by putting a very simple test page (in order to be sure that there are no problems related to my specific website). The site is on github and also by checking the rblx.json file uses the same structure as others files with related site on github. Thank you

**Comment by r-b-l-x** [comment]
The json file was added 3 days ago, if I simply have to wait longer (maybe this time 24 hours are not enough), I will wait and sorry for the message

**Comment by omsenjalia** [comment]
> ### Your subdomain
> https://rblx.is-a.dev/
> 
> ### The issue
> Sorry to bother you. The https://rblx.is-a.dev/ subdomain was activated a few days ago, but it never worked. I have tried with 5 different browsers on 3 different networks, but with none of them I can view the website. In all cases I get errors about the impossibility to create a secure connection (for example in Firefox: "This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox may only connect to it securely. As a result, it is not possible to add an exception for this certificate.") or messages like "SSL: no alternative certificate subject name matches target host name 'rblx.is-a.dev'.". I changed the site (on https://r-b-l-x.github.io/ ) by putting a very simple test page (in order to be sure that there are no problems related to my specific website). The site is on github and also by checking the rblx.json file uses the same structure as others files with related site on github. Thank you

Did you click "Enforce HTTPS" when you added this domain to your GitHub repo?

**Comment by Yunexiz** [comment]
> ### Your subdomain
> https://rblx.is-a.dev/
> 
> ### The issue
> Sorry to bother you. The https://rblx.is-a.dev/ subdomain was activated a few days ago, but it never worked. I have tried with 5 different browsers on 3 different networks, but with none of them I can view the website. In all cases I get errors about the impossibility to create a secure connection (for example in Firefox: "This site uses HTTP Strict Transport Security (HSTS) to specify that Firefox may only connect to it securely. As a result, it is not possible to add an exception for this certificate.") or messages like "SSL: no alternative certificate subject name matches target host name 'rblx.is-a.dev'.". I changed the site (on https://r-b-l-x.github.io/ ) by putting a very simple test page (in order to be sure that there are no problems related to my specific website). The site is on github and also by checking the rblx.json file uses the same structure as others files with related site on github. Thank you

My antivirus is blocking it as "Invalid certificate name" - SSL error.

**Comment by r-b-l-x** [comment]
> Did you click "Enforce HTTPS" when you added this domain to your GitHub repo?

Thank you. Now everything works
I explain what happened in case it could be useful for someone else.
I inserted "rblx.is-a.dev" in Githug > Page > Custom domain and this operation disabled (subsequently to the DNS check) the "enforce HTTPS" (checked in gray and not possible to disable/enable). I have now put "https://rblx.is-a.dev" and "enforce HTTPS" switched itself on by default.
Thank you again!
