### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by UrgingOfc** [is-a-dev/register#15625]
### Your subdomain
https://urging.is-a.dev
### The issue
When I try to access my website I get an error concerning SSL (ERR_SSL_UNRECOGNIZED_NAME_ALERT). I'm using one of my DanBot Hosting server for this domain

**Comment by EducatedSuddenBucket** [comment]
hey
make sure you proxied your domain using dbh!server proxy cmd , if you didnt pls do , if it still doesnt work, make usre your server is online

**Comment by UrgingOfc** [comment]
> hey make sure you proxied your domain using dbh!server proxy cmd , if you didnt pls do , if it still doesnt work, make usre your server is online

I already did that. I had my website up until last month when I started getting messages saying it was down. My server is UP, but I can't access it using the domain

**Comment by EducatedSuddenBucket** [comment]
Hmm, are you donator?, I see you are using donator proxy ip, also can you try reproxying using dbh!server proxy ,if that doesn't work , delete the domain's json,unproxy it, create the domain json again

**Comment by UrgingOfc** [comment]
> Hmm, are you donator?, I see you are using donator proxy ip, also can you try reproxying using dbh!server proxy ,if that doesn't work , delete the domain's json,unproxy it, create the domain json again

Done that and worked. My server was still proxied with the old proxy system of DBH. Thanks!
