### ISSUE TITLE
Github saying the domain is already taken although it is not

### ISSUE THREAD

**Issue by Bikoil** [is-a-dev/register#15653]
### Your subdomain
biko.is-a.dev
### Expected outcome
-  Expected github to accept the custom domain
### Observed outcome
- The following error:
![20240819_22h36m49s_grim](https://github.com/user-attachments/assets/8521ca0e-601d-48e1-ae75-f2b506a054ea)

# More context
So, originally after registering for a is-a.dev subdomain, said domain did work just fine without any issues, [Here is the pull request of registration](https://github.com/is-a-dev/register/pull/14940) But then after a bit, I decided to change the custom domain of my [repository](https://github.com/Bikoil/bikoil.github.io) to something else, after a bit, I wanted to change it back to is-a.dev subdomain, upon attempting, the shared image above is the given error, I have absolutely no clue how to fix it, and no one else has taken the subdomain either.
Help would be extremely appreciated :pray:

**Comment by CuteDog5695** [comment]
Like the error says, try to verify your domain via TXT. You can follow along here https://www.is-a.dev/docs/github-pages-verification/

**Comment by Bikoil** [comment]
> Like the error says, try to verify your domain via TXT. You can follow along here [is-a.dev/docs/github-pages-verification](https://www.is-a.dev/docs/github-pages-verification/)

Sorry for not replying for a long time, but I'll open a pull request to my `biko.json` file to edit the record, thanks
