### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by abdessattar23** [is-a-dev/register#15671]
### The issue
Hello Team, Thanks for this fancy work. I had this domain abdessattar.is-a.dev and it was associated with my github account and after pushing a repository that has a malware the account has been suspended and I lost the portfolio repository as well as the control of domain name. Now I made a new account and I need like to transfer the domain to my new github account and when I modify the domain name json file I  get a message the email needs to be first approved by the old account which is already gone, how am I gonna recover it please ( I still have the associated email address if you wish to verify my identity!!

Thanks in advance for you help as I know you will

**Comment by wdhdev** [comment]
Please send an email to william@williamharrison.dev from the email address on file to confirm ownership and then you can open a PR updating your contact details. Also, please provide some details about your suspension, e.g. the email from GitHub.

**Comment by abdessattar23** [comment]
Ok staff I sent the email and opened a PR thanks a lot for your support appreciate it @wdhdev
