### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by GrapeAppleFruit** [is-a-dev/register#1580]
Your domain name:
https://grapeapplefruit.is-a.dev

Explain any issues you are facing:
Keeps redirecting to https://www.is-a.dev and saying to create an issue.

**Comment by phenax** [comment]
Please link your pull request here

**Comment by GrapeAppleFruit** [comment]
How do I do that

**Comment by phenax** [comment]
Have you created a pull request registering your subdomain?

**Comment by GrapeAppleFruit** [comment]
No

**Comment by phenax** [comment]
@GrapeAppleFruit, please read the readme for the project as well as the documentation for help with registering your subdomain
