### ISSUE TITLE
Issue with Cloudflare and Fruitionsite

### ISSUE THREAD

**Issue by aduckuwu** [is-a-dev/register#1590]
![image](https://user-images.githubusercontent.com/70831061/150459028-4d23b978-6282-4004-9bd8-d259842d8145.png)
This is the error I had. I've configured with my domain name, and use Cloudflare and Fruition so I can serve my site. Unfortunately, it throws this error in the is-a.dev domain (https://maskduck.is-a.dev), but not in the main domain name (https://maskduck.ninja).

**My domain name**
https://maskduck.is-a.dev

**Comment by MaskDuck** [comment]
Basically I do use a cloudflare worker to handle my site.

**Comment by phenax** [comment]
I think cloudflare isn't configured properly to allow CNAME records. You'll have to run through the docs. Can't help you more unfortunately since I haven't personally used cloudflare.
