### ISSUE TITLE
Support for Domain verification Github Pages

### ISSUE THREAD

**Issue by Techpro709** [is-a-dev/register#1615]
Your domain name: https://prozt.is-a.dev/

Explain any issues you are facing

I tried connecting my domain to my GitHub pages like I have done before but it said it is owned by someone else.

Github gave me steps to verify it is my domain.

What do I do next?

1. Create a TXT record in your DNS configuration for the following hostname: _github-pages-challenge-Techpro709.prozt.is-a.dev
2. Use this code for the value of the TXT record: *********************************** ( I don't know if this is some sort of secret key
3. Wait until your DNS configuration changes. This could take up to 24 hours to propagate.

**Comment by Techpro709** [comment]
Please help?

**Comment by phenax** [comment]
The CNAME seems to be linking correctly to `techpro709.github.io` so it seems like a different account has added this subdomain to their account. Could you share a screenshot of this issue?

Currently, we do not allow `.` in subdomains so registering a TXT record with that name will not be possible for verification. I could add support for it if I can make time in the next couple of weeks.

**Comment by Techpro709** [comment]
Thanks for the message @phenax, I think I solved the problem though.

I found out another one of my repos had the name first so it didn't like that.

I removed it and fortunately it looks like it is working.
