### ISSUE TITLE
Website not registering at the momment

### ISSUE THREAD

**Issue by cupglassDEV** [is-a-dev/register#16289]
Mentions https://discord.com/channels/830872854677422150/1288342248198770778/1288343988977406033 on the is-a.dev community server

**Comment by cupglassDEV** [comment]
Any updates? Untill now it still dosent work

**Comment by cupglassDEV** [comment]
Closing in favor of https://github.com/is-a-dev/register/pull/16293 and other PR that I will watch

I will close this issue as solved, if the issue hasn't been occurring again

**Comment by cupglassDEV** [comment]
Looks like it still occuring, im trying to reopen the issue again

**Comment by cupglassDEV** [comment]
Someone already opened this with enough info, i will close this

**Comment by CuteDog5695** [comment]
> Someone already opened this with enough info, i will close this

opened it for you

**Comment by cupglassDEV** [comment]
> > Someone already opened this with enough info, i will close this
> 
> opened it for you

No, i mean just merge the issue with the other guy @winbo-yml-exe

**Comment by CuteDog5695** [comment]
Ah, not really possible xD

**Comment by cupglassDEV** [comment]
> Ah, not really possible xD

hehehe

**Comment by cupglassDEV** [comment]
Js wanted to organize, so i do that

even tho, technically its not possible
