### ISSUE TITLE
how use please

### ISSUE THREAD

**Issue by SkidaDev** [is-a-dev/register#16284]

**Comment by JustDeveloper1** [comment]
read this https://github.com/is-a-dev/register?tab=readme-ov-file#manual-registration

**Comment by CuteDog5695** [comment]
> ### i am very need in the is the domain but i am NOT ABLE to get it!!!!!! please i am not old enough. Too buy that so please help get that stuff for me. Thank you alot!
> 

Are you under 13?

**Comment by winbo-yml-exe** [comment]
Read the goddamn README on the repo.

**Comment by cupglassDEV** [comment]
> ### i am very need in the is the domain but i am NOT ABLE to get it!!!!!! please i am not old enough. Too buy that so please help get that stuff for me. Thank you alot!
@SkidaDev 
where is your etiquette for saying this? 
(r u under 13? bcs github TOS dosent allows that https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#3-account-requirements on point 4)

btw like other said, READ THE GODDAMN README. Its literally on the FRONT of the repo

**Comment by wdhdev** [comment]
People cannot read.
