### ISSUE TITLE
Cloudflare Email Routing

### ISSUE THREAD

**Issue by Grafaffel** [is-a-dev/register#16294]
### Cloudflare Email Routing

I'd like to know if it's possible to use Cloudflare Email Routing with an <kbd>.is-a.dev</kbd> subdomain. 
I'm opening this issue because I want to confirm whether I can do this by changing the
<kbd>NS</kbd> records on my subdomain.

Thanks in advance

**Comment by cupglassDEV** [comment]
Back then they support those things on is-a.dev, including MX and NS
But now it was deprecated, idk if they have any newer solution to this

**Comment by CuteDog5695** [comment]
> ### Cloudflare Email Routing
> 
> I'd like to know if it's possible to use Cloudflare Email Routing with an .is-a.dev subdomain. I'm opening this issue because I want to confirm whether I can do this by changing the NS records on my subdomain.
> 
> Thanks in advance

I think for Email Routing you need to use Cloudflare DNS, which we don't support since we don't have `NS` Records.

**Comment by Grafaffel** [comment]
> I think for Email Routing you need to use Cloudflare DNS, which we don't support since we don't have `NS` Records.

ok, but are there any plans on allowing <kbd>NS</kbd> Records? I've seen this relatively new PR https://github.com/is-a-dev/register/pull/16287

**Comment by wdhdev** [comment]
If NS records are implemented, it'll be likely restricted to maintainers due to the potential abuse risk. Also, for email forwarding you can use https://improvmx.com instead of Cloudflare.
