### ISSUE TITLE
Subdomain(s) not working for unknown reason

### ISSUE THREAD

**Issue by winbo-yml-exe** [is-a-dev/register#16295]
### Your subdomain
https://sparkos.is-a.dev

### Expected outcome
show contents of https://sparkos-win.github.io

### Observed outcome
redirects to is-a.dev. i did clear my browser cache. digging the subdomain shows this:

sparkos.is-a.dev.    100    IN    A    68.65.123.44

it somehow has an A record which i did **NOT** make. going to that ip just shows a 403 forbidden error. [this is my json file if you need it](https://github.com/is-a-dev/register/blob/main/domains/sparkos.json)

**Comment by cupglassDEV** [comment]
Hey, its an ongoing issue in is-a.dev. You can go to my own issue https://discord.com/channels/830872854677422150/1288342248198770778/1288343988977406033 because i have this exact strange problem with my domain too

**Comment by cupglassDEV** [comment]
Hey, its an ongoing issue in is-a.dev. You can go to my own issue https://discord.com/channels/830872854677422150/1288342248198770778/1288343988977406033 because i have this exact strange problem with my domain too

(its a is-a.dev community server btw, just to refers to my help thread)

**Comment by cupglassDEV** [comment]
Btw this is related to #16293, but unfortunately this issue dosent get any solution (it keeps failing to is-a.dev like you said)

![Screenshot_20240925-215405.jpg](https://github.com/user-attachments/assets/431df94f-55db-4ca9-9ff5-38b612c6fc6d)

![Screenshot_20240925-215418.jpg](https://github.com/user-attachments/assets/4bf9a573-1dfb-49e4-b7b2-1d1854b8e85b)

**Comment by CuteDog5695** [comment]
@winbo-yml-exe We are aware of the issue, we tried removing 0.is-a.dev but still didn't work so we have to find another solution. My theory could be that we reached the limit for cPanel.

**Comment by cupglassDEV** [comment]
(Related to the maintainer itself, https://community.cloudflare.com/t/moving-subdomain-service-to-cloudflare-dns/716357)
> ###### (reference #13995)
> # Alternatives
> ## [Cloudflare](https://www.cloudflare.com/application-services/products/dns/)
> * **Pros**
>   
>   * Free, up until certain limits
>   * Cloudflare proxy option
>   * Caching via Cloudflare's global CDN (when proxy is enabled)
>   * Faster DNS deployment
>   * Built-in DDoS protection for subdomains (when proxy is enabled)
>   * NS record support for subdomains
>   * Free email forwarding (can setup [support@is-a.dev](mailto:support@is-a.dev), [security@is-a.dev](mailto:security@is-a.dev), etc)
>   * Cloudflare Zero Trust
>     
>     * Tunnels
> * **Cons**
>   
>   * Record limit, although can be increased by contacting support I believe
>   * Not great support

@CuteDog5695 Does the Cloudflare team accepts our OSS form? If they do, its gonna be no hassle relating to these issues that we've had

**Comment by CuteDog5695** [comment]
@wdhdev made the OSS form for Cloudflare, now we are waiting for a response.

**Comment by cupglassDEV** [comment]
> @wdhdev made the OSS form for Cloudflare, now we are waiting for a response.

@CuteDog5695 Ok 👍

**Comment by cupglassDEV** [comment]
@winbo-yml-exe We already tried to do these
1. Remove 0.is-a.dev, but it dosent work too
2. Re adding domains like in my PR https://github.com/is-a-dev/register/pull/16301, but it still fails

Maybe the possible solution is the cpanel limit, its gonna be a long hour for this

**Comment by cupglassDEV** [comment]
Maybe you can read this if you want to know
https://github.com/is-a-dev/register/issues/14153

**Comment by CuteDog5695** [comment]
I don't think its record limit now. In #9707 phenax (the owner of the domain) said that cPanel doesn't have a limit, while namecheap does. Maybe cPanel is broken in some way then?

**Comment by wdhdev** [comment]
I believe CPanel might have a subdomain limit or technical limitation of around 5,000 subdomains.

@phenax Would I be able to gain access to CPanel to take a look?

**Comment by cupglassDEV** [comment]
> I don't think its record limit now. In #9707 phenax (the owner of the domain) said that cPanel doesn't have a limit, while namecheap does. Maybe cPanel is broken in some way then?

hmm so whats the problem for now??

**Comment by CuteDog5695** [comment]
We use cPanel for the DNS part, though I think thats still namecheap but different.

**Comment by user0-07161** [comment]
I once digged something (i forgot what tho) and got some responses from namecheap

**Comment by phenax** [comment]
> I believe CPanel might have a subdomain limit or technical limitation of around 5,000 subdomains.
No. Cpanel edits the zone file directly and it doesn't have any limits.

The problem here is similar to [what happened here](https://github.com/is-a-dev/register/issues/9707). Sometimes one of the records get written incorrectly to the zone file and it stops reading reading changes made after. My guess is its either a record that starts with _ or some txt value that didn't get escaped correctly in the zone file. I've spoken to support and they're dealing with it. Unfortunately since we don't control the instance, we have to wait for daddy namecheap to edit it for us.

![part-2024_09_26_21_42_48](https://github.com/user-attachments/assets/f29bd357-af05-4297-9e4c-f80855636cb7)

**Comment by DEV-DIBSTER** [comment]
> > I believe CPanel might have a subdomain limit or technical limitation of around 5,000 subdomains.
> 
> No. Cpanel edits the zone file directly and it doesn't have any limits.
> 
> The problem here is similar to [what happened here](https://github.com/is-a-dev/register/issues/9707). Sometimes one of the records get written incorrectly to the zone file and it stops reading reading changes made after. My guess is its either a record that starts with _ or some txt value that didn't get escaped correctly in the zone file. I've spoken to support and they're dealing with it. Unfortunately since we don't control the instance, we have to wait for daddy namecheap to edit it for us.
> 
> ![part-2024_09_26_21_42_48](https://private-user-images.githubusercontent.com/11407672/371230152-f29bd357-af05-4297-9e4c-f80855636cb7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNjc3NTIsIm5iZiI6MTcyNzM2NzQ1MiwicGF0aCI6Ii8xMTQwNzY3Mi8zNzEyMzAxNTItZjI5YmQzNTctYWYwNS00Mjk3LTllNGMtZjgwODU1NjM2Y2I3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDE2MTczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlZDZhNzRhNDY5YjllNWM0MDY3YjVmODA0NWVjNThiNzZiNjNkNzk5NjI3NDY2NTNiNmY5ODVhNGIxZmJkM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WyuznlgKPBXsHNnAHsPmJNLOnvAy_jovukqYW4FZSgk)

Do you think one of the domains slipped past the validation checks and caused this?

**Comment by phenax** [comment]
> Do you think one of the domains slipped past the validation checks and caused this?

Don't think so. I think it's more of a problem with the way the zone file is edited. Sometimes some record gets appended to the file but it has some thing that gives bind a hard time so it fails.

Update: They think it's `_github-pages-challenge-clay990.suraj` causing the issue. Odd.
![part-2024_09_26_21_53_04](https://github.com/user-attachments/assets/7b5de525-79cb-44da-8f32-114cecb2d6de)

**Comment by winbo-yml-exe** [comment]
> > Do you think one of the domains slipped past the validation checks and caused this?
> 
> Don't think so. I think it's more of a problem with the way the zone file is edited. Sometimes some record gets appended to the file but it has some characters that gives bind's parser a hard time so it fails.
> 
> Update: They think it's `_github-pages-challenge-clay990.suraj` causing the issue. Odd. ![part-2024_09_26_21_53_04](https://private-user-images.githubusercontent.com/11407672/371233736-7b5de525-79cb-44da-8f32-114cecb2d6de.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNjg2MjcsIm5iZiI6MTcyNzM2ODMyNywicGF0aCI6Ii8xMTQwNzY3Mi8zNzEyMzM3MzYtN2I1ZGU1MjUtNzljYi00NGRhLThmMzItMTE0Y2VjYjJkNmRlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDE2MzIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MDEzMjJhZDBmZTdlZDk2Mjc3YTNhN2QyMzk1YzUxOGVlNjk0YzRjNTc2YjQ1NGUxOTY3NTdmZGU4MTMwYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8RZJYA4J6oG5repJtTzr-qaceVjXIgN95COs0Ug9GLY)

Try removing that file I guess.

**Comment by 21Z** [comment]
"similiar subdomains like _github-pages-challenge-clay990.suraj", they didnt say the issue was with only that domain, and removing those type of files means you wont be able to verify your domain on github, which could create issues such as others claiming/using a domain that is not theirs.

**Comment by phenax** [comment]
> "similiar subdomains like _github-pages-challenge-clay990.suraj", they didnt say the issue was with only that domain, and removing those type of files means you wont be able to verify your domain on github, which could create issues such as others claiming/using a domain that is not theirs.

Yeah. Removing them is out of the question. I don't think that's the issue tho. If 1 record starting with _ doesn't cause a problem which we have been using for a while, I don't see how having many of them would. This looks more like an awkward TXT to me. Still with support on that.

**Comment by CuteDog5695** [comment]
> > Do you think one of the domains slipped past the validation checks and caused this?
> 
> Don't think so. I think it's more of a problem with the way the zone file is edited. Sometimes some record gets appended to the file but it has some characters that gives bind's parser a hard time so it fails.
> 
> Update: They think it's `_github-pages-challenge-clay990.suraj` causing the issue. Odd.

This could be the reason why 
![image](https://github.com/user-attachments/assets/2ca28fac-e529-4431-8e81-7263b39ec8af)

**Comment by phenax** [comment]
Welp. I removed some invalid records and it seems to have fixed things. It could either be the MX record starting with `_` (cant find anything about this being problematic) or it is `vulpine` which has an invalid `"MX": ["mx1.improvmx.com, mx2.improvmx.com"],` entry.

I'll open a PR with the changes and tag the owners.

**Comment by CuteDog5695** [comment]
Oh i just made a PR, you can close it if you want to

**Comment by phenax** [comment]
@CuteDog5695 you can fix the vulpine record as well in you PR and tag both the owners.

**Comment by CuteDog5695** [comment]
A maintainer just merged the PR, though that PR was only for the github txt one (which needed to be removed anyways). I'll update the vulpine record then

**Comment by winbo-yml-exe** [comment]
> Welp. I removed some invalid records and it seems to have fixed things. It could either be the MX record starting with `_` (cant find anything about this being problematic) or it is `vulpine` which has an invalid `"MX": ["mx1.improvmx.com, mx2.improvmx.com"],` entry.
> 
> I'll open a PR with the changes and tag the owners.

This seemed to fix 2 of my domains, https://discord.winbo.is-a.dev and https://sparkos.is-a.dev

**Comment by winbo-yml-exe** [comment]
https://sparkos.is-a.dev doesn't work tho (yet)

**Comment by CuteDog5695** [comment]
@phenax Made a PR for `vulpine.json` now, the entire time MX records had both MX records in one string. I do not even know how that slid through

**Comment by winbo-yml-exe** [comment]
And https://sparkos.is-a.dev works now, just have to add a CNAME to the GitHub repo. Will be closing the issue, thanks for helping.

![{87B4A051-2B7F-4BD7-B1DC-193785B8ADDB}](https://github.com/user-attachments/assets/12cadc76-1ef2-4d2d-8829-40caf6b28953)

**Comment by CuteDog5695** [comment]
At least phenax could help us honestly. That I'm glad about
