### ISSUE TITLE
Link Expired 

### ISSUE THREAD

**Issue by yuwindev** [is-a-dev/register#16310]
Discord server invite link has expired, please update new link

**Comment by EducatedSuddenBucket** [comment]
@yuwindev this should work https://discord.gg/PhwY364w

**Comment by CuteDog5695** [comment]
Oh I just noticed this issue. I think it got invalidated since we changed the vanity link, since we have level 3 boost now. I'll try to update it later.

**Comment by CuteDog5695** [comment]
Updated link to https://discord.gg/is-a-dev now

**Comment by killuazoldyckreal** [comment]
it's still expired

> Updated link to https://discord.gg/is-a-dev now

**Comment by CuteDog5695** [comment]
its back to https://discord.gg/is-a-dev-830872854677422150 now
