### ISSUE TITLE
Domain still not linked

### ISSUE THREAD

**Issue by itzPrabhat** [is-a-dev/register#1633]
My domain is still not linked. It been a month but still it redirects me to https://www.is-a.dev 
My website: https://pbdev.ml and the is-a.dev domain: https://www.prabhat.is-a.dev

**Comment by phenax** [comment]
There is no `prabhat.json` file in the domains directory. If you haven't created a pull request yet, please read the README of this project and the documentation for help with registering a subdomain. Closing this pr.
