### ISSUE TITLE
Report abuse

### ISSUE THREAD

**Issue by itsarazesh** [is-a-dev/register#1641]
Domain you want to report: aungs.is-a.dev

### Reason
Explain why you think this domain is being abused

Hello, I would like to inform you that domain “aungs.is-a.dev” has redirect me to other website that contains fake scam Nitro. It’s tell me to put my password and when I clicked on it, my Discord account can’t be logged in. After that, my Discord account is spreading “aungs.is-a.dev” domain everywhere. But now the owner of the site has changed it, so it won’t be fair to me and others who got scammed by that link. I would like you to take down that sub-domain right now.

**Comment by phenax** [comment]
@itsarazesh, I'm unable to verify this claim since both the old repl and the new one point seem to have been changed. Please provide some additional proof (screenshots will do) so that we can proceed with this.

**Comment by itsarazesh** [comment]
Here’s the picture I screenshots yesterday before he changed the CNAME
![Uploading A060E80F-F04D-48E2-A61B-1609CBCC67A2.jpeg…]()

**Comment by phenax** [comment]
@itsarazesh, I cant see the screenshot there. Github may have glitched out. Could your try again?

**Comment by itsarazesh** [comment]
Or here’s the link if the image doesn’t load properly 
![](https://cdn.discordapp.com/attachments/852891796572209216/936916845007622175/IMG_6955.png)

**Comment by phenax** [comment]
Also, try sending an email to `contact@repl.it` as well. The 2 repl links that were used can be seen here -> https://github.com/is-a-dev/register/pull/1639/files.

**Comment by itsarazesh** [comment]
I will try contact them, but the link will be remove or not? Because I have seen many people repost and spam it.

**Comment by phenax** [comment]
The subdomain will be taken down in some time. At the moment there is no rush since it no longer is hosting the harmful content. Please share a screenshot of the spam link in discord if possible so that the claim is harder to dispute.

**Comment by AungS8430** [comment]
hi, I'm here and my website doesn't looks like that

**Comment by AungS8430** [comment]
https://aungkung-site.idkreplit.repl.co/

**Comment by AungS8430** [comment]
this is my website

**Comment by itsarazesh** [comment]
It was appear like that yesterday, before you changed your CNAME. Now, it’s normal website but people who clicked the link yesterday couldn’t log in into there Discord account as well as I.

**Comment by AungS8430** [comment]
looks like my replit account got hacked, https://replit.com/@idkreplit/aungkung-site you can take a look at my code which I get the CNAME

**Comment by AungS8430** [comment]
It's just the normal website

**Comment by AungS8430** [comment]
![image](https://user-images.githubusercontent.com/97497608/151656440-b1c65712-858e-44df-aec8-56534f4a9c1f.png)
This is if you enter the website using CNAME

**Comment by AungS8430** [comment]
nothing was wrong

**Comment by itsarazesh** [comment]
@AungS8430 - I said yesterday not today. I know that your website is normal website right now today. But as I said that it was happen yesterday. I could aware of you taking my Discord account for spreading the malicious link around. But I could not guarantee that your website yesterday was you or not.

**Comment by AungS8430** [comment]
hmm, I never do something like that, yesterday, I tried enter my website but I can't cuz of it said: "Run Repl, to see output", so I change the CNAME

**Comment by phenax** [comment]
@AungS8430, unfortunately, hacked or not, we will have to suspend the domain if it is being used for malicious purposes.

**Comment by AungS8430** [comment]
okay

**Comment by AungS8430** [comment]
I'll try moving out of replit for more reliable
