### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by ghost** [is-a-dev/register#1643]
Your domain name: dinothedev

Explain any issues you are facing

SSL_ERROR_INTERNAL_ERROR_ALERT error

![image](https://user-images.githubusercontent.com/77805841/151719067-a380afef-4a91-495e-8532-50d47cb7b119.png)

**Comment by phenax** [comment]
SSL for CNAME records is issued by the hosting so there is nothing we can do from our end.
`http://dinothedev.is-a.dev` works but your repl isn't running. Try to see if replit is configured correctly and also run the repl.

**Comment by phenax** [comment]
Closing this issue as the user seems to have been deleted
