### ISSUE TITLE
Feedback/suggestion: Underscores and/or better TXT records.

### ISSUE THREAD

**Issue by saxophone-guy** [is-a-dev/register#16469]
### What do you want added?
I feel that adding a way to set up TXT records to specific names is a needed feature, because for setting up an IPFS-based website through gateways without CNAME records on the apex domain is unnecessarily difficult, requiring the use of a proxy setup.

Perhaps such a way can be applied:
```json
"records": {
	"TXT": {
		"@": "Something here",
		"_dnslink": "dnslink=/ipfs/..."
	}
}
```

**Comment by saxophone-guy** [comment]
PS: Creating subdomains doesn't work as underscores aren't allowed (alphanumerical, remember?)

**Comment by wdhdev** [comment]
As @VaibhavSys said, specific domains with underscores in them are allowed. (e.g. `_discord`, `_gitlab-pages-verification-code`, `_acme-challenge`, etc.)
You can see the list here: https://github.com/is-a-dev/register/blob/main/utils/validations.js#L55-L65
