### ISSUE TITLE
Privacy Error with Replit

### ISSUE THREAD

**Issue by justamirror** [is-a-dev/register#1663]
### Expected outcome
I expected my website to appear normally, with no error.

### Observed outcome
I got a chrome privacy error when I visited it. Screenshot if needed:
![image](https://user-images.githubusercontent.com/66569648/152617029-5b9289c7-f89b-4a5f-b61e-b18ea957b0e8.png)

**Comment by justamirror** [comment]
Link to the subdomain replit gives me is fine: https://justa6.repl.co/

**Comment by phenax** [comment]
It seems to be working fine. Please clear your browser cache and try again. Closing this issue.
