### ISSUE TITLE
CNAME Cross-User Banned

### ISSUE THREAD

**Issue by ponfertato** [is-a-dev/register#16634]
### Is there anything that can be done about this other than changing the entry?

My main domain is registered on cloudflare and because of this there is a problem with access to the is-a.dev domain

**Comment by CuteDog5695** [comment]
As far as I see, your CNAME record (potatoenergy.ru) is using Cloudflare proxy IP's. Maybe because of that its having a problem?
Also what hosting are you using with it by any chance?

**Comment by ponfertato** [comment]
> Also what hosting are you using with it by any chance?

I use my own server with traefik as a load balancer

> Maybe because of that its having a problem?

As far as I understand, Cloudflyer prohibits the use of CNAME records for different clients if the main domains do not belong to it
That's why I wanted to clarify this question, maybe someone else has a similar situation...

**Comment by wdhdev** [comment]
> As far as I understand, Cloudflyer prohibits the use of CNAME records for different clients if the main domains do not belong to it

Yup, this is a configuration issue on your end, not us. You can technically use Cloudflare for SaaS however I would just recommend disabling CF proxy on your domain to fix it.
