### ISSUE TITLE
Use Dynamic DNS with this service

### ISSUE THREAD

**Issue by 3nf94Cmnds** [is-a-dev/register#16662]
How would I use Dynamic DNS with this service? My provider doesn't allow us to have a static **public** IP, so is, and how is, this possible? I would use Dynu, but if I have to change then tell me. Thanks in advance!
_Our provider forces us to use a dynamic IP, but this project only supports static IPs._

**Comment by wdhdev** [comment]
What records would you require for this to work?

**Comment by wdhdev** [comment]
#16663
