### ISSUE TITLE
Support Unban

### ISSUE THREAD

**Issue by notugotskilz** [is-a-dev/register#16804]
### Your subdomain
dont have one yet
### The issue
Why did I get banned from your discord server?

**Comment by wdhdev** [comment]
What is your username and Discord ID?

**Comment by notugotskilz** [comment]
> What is your username and Discord ID?

bla3de and 1114211215049240646

**Comment by wdhdev** [comment]
You got banned for violating Discord's terms of service regarding selling accounts and stuff I believe.

**Comment by notugotskilz** [comment]
> You got banned for violating Discord's terms of service regarding selling accounts and stuff I believe.

Is it possible for me to get unbanned?

**Comment by notugotskilz** [comment]
> You got banned for violating Discord's terms of service regarding selling accounts and stuff I believe.

It was a accident

**Comment by wdhdev** [comment]
It is not an accident.
