### ISSUE TITLE
``codedsprit.is-a.dev`` not working, but either redirecting to main domain itself!

### ISSUE THREAD

**Issue by codedsprit** [is-a-dev/register#16825]
Hii,

I have made a pr, and its now merged but the domain is not working codedsprit.is-a.dev either is redirecting to ``is-a.dev`` domain itself, I have looked through this [Issue](https://github.com/is-a-dev/register/issues/16295) but can't find any help.. 

Now what should I do to live the domain https://codedsprit.is-a.dev .

**Comment by wdhdev** [comment]
Doesn't exist https://github.com/is-a-dev/register/tree/main/domains/codedsprit.json

**Comment by wdhdev** [comment]
You registered sprit.is-a.dev, not codedsprit.is-a.dev.

**Comment by codedsprit** [comment]
Yess, but 
sprit.is-a.dev neither working..
![Screenshot_2024_1026_092730](https://github.com/user-attachments/assets/fdf8660a-c41b-401e-b749-49e40014d477)

Or am I misunderstood.

**Comment by wdhdev** [comment]
Make sure your provider has generated an SSL for it.
