### ISSUE TITLE
For how much time will is-a.dev be here?

### ISSUE THREAD

**Issue by NiceSapien** [is-a-dev/register#1687]
Can I use my is-a.dev domain everywhere instead of my hosting provider provided domain? For how much time will is-a.dev be here? Any guesses or something...

**Comment by NiceSapien** [comment]
In simple words, does that mean is-a.dev will be here for 10 years?

**Comment by phenax** [comment]
Yes. It will be here for the next 10 years. But also, more than that.

**Comment by NiceSapien** [comment]
That's great! Thank you very much.
