### ISSUE TITLE
DNS of Subdomains Down?

### ISSUE THREAD

**Issue by WebCoder49** [is-a-dev/register#16877]
### Your subdomain
N/A (I don't own any)

### Expected outcome
To be able to access subdomains of is-a.dev, for example my friend's page <https://llama.is-a.dev>, or any other such as <https://iamai.is-a.dev> or <https://free.is-a.dev>.

### Observed outcome
I can find no DNS records for any of the subdomains of is-a.dev, only for the root domain is-a.dev (and www.is-a.dev), meaning any of the personal websites hosted on is-a.dev cannot be accessed and give "Hmm. We’re having trouble finding that site. We can’t connect to the server at llama.is-a.dev." errors on Firefox (Wayland on Arch Linux in the UK).

**Comment by CuteDog5695** [comment]
We are in a downtime again, since we are moving to a different Cloudflare account. Check back on your domain in 24 hours.
