### ISSUE TITLE
.is-a.dev subdomains not working

### ISSUE THREAD

**Issue by orca-pet3910** [is-a-dev/register#16887]
### Your subdomain
orcapet.is-a.dev
### Expected outcome
my website
### Observed outcome
curl: HTTP 512, msedge: redirect to the main .is-a.dev website

**Comment by JustDeveloper1** [comment]
`.is-a.dev` is down.

**Comment by JustDeveloper1** [comment]
message from is-a.dev discord server > #service-news
> `@everyone` Effectively immediately, there will be some downtime (hopefully less than 24 hours), which is due to us moving the is-a.dev domain to a different Cloudflare account.
> 
> Thanks for your cooperation.

**Comment by orca-pet3910** [comment]
alright thank you
