### ISSUE TITLE
My domain is now redirecting to default home page of .is-a.dev

### ISSUE THREAD

**Issue by NatBLida68** [is-a-dev/register#16884]
### 
ashwa.is-a.dev  and https://natblida68.github.io  is now redirecting to .is-a.dev homepage instead of my portfolio web page.
is there anything that I need to change ?  
https://github.com/NatBLida68/NatBLida68.github.io

**Comment by PolishBoiYT** [comment]
It's down.
Just wait.

**Comment by CuteDog5695** [comment]
Can you please just read this for me? Its clearly stated here but I guess you just went straight to complaning about it.
![image](https://github.com/user-attachments/assets/e7a145e0-7474-4d81-af66-73f42a72fdfd)

**Comment by NatBLida68** [comment]
I didn't noticed , yeah you are right I checked my domain it redirected me so  I added a support request. You don't have to be rude about it. 
Maybe if it was in the home page of the site I would have noticed I'm not that kind of guy who reads readme everytime I checks a repo besides I thought it was something related to my change , I updated my code last day

**Comment by CuteDog5695** [comment]
> I didn't noticed , yeah you are right I checked my domain it redirected me so I added a support request. You don't have to be rude about it. Maybe if it was in the home page of the site I would have noticed I'm not that kind of guy who reads readme everytime I checks a repo besides I thought it was something related to my change , I updated my code last day

Its mostly because we announced it both in the Discord server and the Github README, sorry if I was rude, just a bit annoyed by these questions.
