### ISSUE TITLE
Support [Randomly my domain got removed or what ?]

### ISSUE THREAD

**Issue by heyjumanji** [is-a-dev/register#16892]
### Your subdomain
jumanji.is-a.dev
### The issue
Im using it for mx mail service but recently it says my domain is not registered even the domain is registered by isadrv team and says dns record could not found even it was working fine for like 6 months and even my domain dont open my site instead it redirect to the isadev site why? What's going on?

**Comment by cupglassDEV** [comment]
Hey, you didnt not read the readme

There was a downtime yesterday because of cloudflare account was switched to another (from the admins)

It will propagate later, but not so fast as what you think

**Comment by cupglassDEV** [comment]
@heyjumanji
