### ISSUE TITLE
My question

### ISSUE THREAD

**Issue by abiapp789** [is-a-dev/register#17093]
### My question

Did Not Connect: Potential Security Issue

Firefox detected a potential security threat and did not continue to abiapp789.is-a.dev because this website requires a secure connection.

What can you do about it?

abiapp789.is-a.dev has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.

The issue is most likely with the website, and there is nothing you can do to resolve it. You can notify the website’s administrator about the problem.

How to fix

**Comment by CuteDog5695** [comment]
Basically you need a SSL certificate for your domain since `.dev` is a top level tld.

**Comment by cupglassDEV** [comment]
> Basically you need a SSL certificate for your domain since `.dev` is a top level tld.

Or @CuteDog5695 said. Its basically depends on your website config

**Comment by qxb3** [comment]
I'm also encountering this issue on [#17111](https://github.com/is-a-dev/register/pull/17111). https://qxb3.is-a.dev/

Im using netlify

**Comment by cupglassDEV** [comment]
But i can open your website??
![image](https://github.com/user-attachments/assets/49175d99-4b74-4b4a-b45b-ec5b05a8890d)

**Comment by qxb3** [comment]
Yeah, seems like all i had to do is wait for a little bit more.
