### ISSUE TITLE
Prettier workflow

### ISSUE THREAD

**Issue by wdhdev** [is-a-dev/register#17103]
### What do you want added?
I want to implement a GitHub workflow that runs everytime a commit is pushed to the main branch, which runs Prettier:

```
prettier ./domains -w --tab-width 2 --print-width 120
```

**Comment by jadifydotco** [comment]
Just use the api: https://prettier.io/docs/en/api.html 

I know very much help

**Comment by cupglassDEV** [comment]
@jadifydotco 
> Just use the api: https://prettier.io/docs/en/api.html
> 
> I know very much help
You can't just do that, make a pr to help him also

He KNOWS that the docs exist

**Comment by cupglassDEV** [comment]
I already made the PR for this, see #17105
