### ISSUE TITLE
Discord invite link is invialid

### ISSUE THREAD

**Issue by Sxinar** [is-a-dev/register#17122]
Selam discord davet linkinizin süresi dolmuş.

**Comment by CuteDog5695** [comment]
Don't know Turkish, but judging by the title, our discord invite isn't invalid. Though Turkey is banned in Discord so maybe thats the problem.

**Comment by Sxinar** [comment]
> Türkçe bilmiyorum ama başlığa bakılırsa discord davetimiz geçersiz değil. Discord Türkiye'de yasaklı olduğu için sorun bu olabilir.

Hmmm but discord not use invite link.
I have A screenshot i want to New invite link please (İ know little turkish sorry)

**Comment by DEV-DIBSTER** [comment]
It's definitely the Turkey ban, any invites will not work considering the domains they use.

**Comment by Sxinar** [comment]
Teşekkür ederim.
