### ISSUE TITLE
Your connection is not private

### ISSUE THREAD

**Issue by rahulps1000** [is-a-dev/register#17144]
### Your subdomain
https://rahulps.is-a.dev/

i have deployed the website on netlify.

### Expected outcome
the site should be visible
https://myfolio-rahulps.netlify.app/

### Observed outcome
Your connection is not private
Attackers might be trying to steal your information from rahulps.is-a.dev (for example, passwords, messages, or credit cards). [Learn more about this warning](chrome-error://chromewebdata/#)
net::ERR_CERT_COMMON_NAME_INVALID

Please help me on this.

**Comment by cupglassDEV** [comment]
its not a bug, it should be on the question, because THIS is on the netlify side

**Comment by cupglassDEV** [comment]
@rahulps1000 https://answers.netlify.com/t/net-err-cert-common-name-invalid/8009/2 you need to click the "Renew Cerificate" on the netlify app

**Comment by rahulps1000** [comment]
@cupglassDEV there is no option to renew certificate in netlify

![image](https://github.com/user-attachments/assets/f87e18e7-ed6a-4a2b-8d72-010508ab4598)

**Comment by EducatedSuddenBucket** [comment]
@rahulps1000 the problem was that lets encrypt was issuing SSL certificate and you seem to have just did register the subdomain. Now it seems that Lets encrypt has issued you a SSL certificate and your site https://rahulps.is-a.dev/ works , so I guess you can close this issue

**Comment by rahulps1000** [comment]
Thankyou for your quick response
