### ISSUE TITLE
Quesion

### ISSUE THREAD

**Issue by SarnaxLii** [is-a-dev/register#1715]
If I want to remove the domain from the website What must I do Or just delete the Fork from your Git.

**Comment by phenax** [comment]
The way you created the domain is the same way you remove it. Create a pr with your file deleted.

**Comment by SarnaxLii** [comment]
I've put the xanax.json file in it, hope you approve it ASAP.

**Comment by SarnaxLii** [comment]
I've pulled, hope you get it together quickly.

**Comment by phenax** [comment]
@SarnaxLii, I still don't see a pull request from you. If you're having trouble creating a pr, [you can follow this guide from github](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by Ovutuleu92** [comment]
SarnaxLii subhuman scammer dog
