### ISSUE TITLE
Your connection is not private! ~ Support

### ISSUE THREAD

**Issue by justadmir** [is-a-dev/register#17184]
### Your subdomain
admir.is-a.dev
### The issue
It says  
![image](https://github.com/user-attachments/assets/f17026c6-ec16-4c03-a949-bd950e38f30e)

**Comment by xandaaah** [comment]
Did you forget to add admir.is-a.dev to the custom domain in Github? It should be in the repo settings. If you can't find it, just create a file called `CNAME` containing `admir.is-a.dev`.

**Comment by justadmir** [comment]
I already had that done i removed the costum domain rn and added again and its still the same.
