### ISSUE TITLE
Report abuse

### ISSUE THREAD

**Issue by Sec-Ops-team** [is-a-dev/register#17267]
### Reason
The website does not belong to Coda, and the site used Codashop brand & logo on its website

### Proof
The page infringed Codashop logo presented on their website and is used to lure users to buy diamonds on the website

**Comment by Sec-Ops-team** [comment]
Noted with thanks.

**Comment by vintheweirdass** [comment]
@Sec-Ops-team I got a info
![image](https://github.com/user-attachments/assets/2ff2f007-9ad8-4bee-b719-e1fd82d0b70c)
You can contact them under [abuse@dnspod.com](mailto:abuse@dnspod.com)

**Comment by Sec-Ops-team** [comment]
Thank you
