### ISSUE TITLE
I am still not able to open my domain

### ISSUE THREAD

**Issue by skarwuuu** [is-a-dev/register#17269]
### The domain skarwuuu.is-a.dev still shows up as not verified

![Screenshot 2024-11-20 174800](https://github.com/user-attachments/assets/72d17d98-f52d-450c-aec6-90f38d67e91d)

**Comment by vintheweirdass** [comment]
u are in the wrong steps

https://github.com/is-a-dev/register/blob/aa8198c2f747b82c0e0bcde3b02aa46e1da18e5e/domains/_vercel.skarwuuu.json#L8

do not delete the `vc-domain-verify=`. Just keep them
