### ISSUE TITLE
Change github to vercel but my githubpages problem

### ISSUE THREAD

**Issue by dimasandriano** [is-a-dev/register#17444]
Last week I moved hosting from GitHub to Vercel. everything runs normally. but my github page at https://dimasandriano.github.io always redirects to https://dimasandriano.is-a.dev, even though I have removed the custom domain in the repository

**Comment by sanoojes** [comment]
![image](https://github.com/user-attachments/assets/11c27935-98d6-422d-8672-9a07fcdd1612)

Did you remove the custom domain from GitHub Pages? I don't think it's gone yet.

**Comment by CuteDog5695** [comment]
The github website doesn't redirect to the is-a.dev domain for me, try clearing your browser cache.

**Comment by dimasandriano** [comment]
> The github website doesn't redirect to the is-a.dev domain for me, try clearing your browser cache.

Thank u sir 😁
