### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SarnaxLii** [is-a-dev/register#1750]
I can't add CloundFlare to protect my site. Because this is not a normal Domain, what should I do?

![image](https://user-images.githubusercontent.com/94861415/155765199-d4d582b2-23a0-48b3-9a97-a7093a44f298.png)

**Comment by phenax** [comment]
They're asking for a domain and you've given them a url. `sarnax.is-a.dev` is the domain.

**Comment by phenax** [comment]
That is pretty weird. I think you're configuring the wrong thing here. I haven't used cloudflare yet so can't be certain. Have you tried following [this guide](https://support.thinkific.com/hc/en-us/articles/360030360254-How-to-Set-up-Your-Custom-Domain-in-CloudFlare)?

**Comment by SarnaxLii** [comment]
It doesn't work on CLoudflare. // Thank

**Comment by MaskDuck** [comment]
hm, seems like is-a-dev is unfortunately work with cloudflare 😭

**Comment by anautonell** [comment]
Cloudflare only accepts domains and **NOT** subdomains, you need to contact the owner of is-a.dev to add his site to Cloudflare. You don't own the domain, you can't add CNAME records or change nameservers.

I hope this helps.

**Comment by anautonell** [comment]
^ Edit: You can't add any records yourself to verify you own the domain.

**Comment by FranklinOP-IND** [comment]
> It doesn't work on CLoudflare. // Thank

Scmaer Not Working More Then Scam

**Comment by Origintk** [comment]
Help guys [SarnaxLii](https://github.com/SarnaxLii) He is a scammer , he robbed me , I paid for a spoofer he deleted everything after receiving the money , waited 1 day and deleted me

**Comment by Santiagocostaa** [comment]
Help guys [SarnaxLii](https://github.com/SarnaxLii) He is a scammer , he robbed me , I paid for a spoofer he deleted everything after receiving the money , waited 1 day and deleted me

**Comment by SarnaxLii** [comment]
Show Proof Your account was created 6 hours ago, it's funny how you accuse me. Hopefully this idiot will be banned from github as soon as possible.

**Comment by anautonell** [comment]
@SarnaxLii Are you talking to me_

**Comment by SarnaxLii** [comment]
> @SarnaxLii Are you talking to me-

no bro
