### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by wilby-mj** [is-a-dev/register#1775]
Your domain name: ```wbalaile.is-a.dev```

Explain any issues you are facing:
- The domain looks to be working, however I don't know how to configure my server (cPanel) to work with the domain.
- When trying to access the site, an SSL error is thrown: ```Error code: SSL_ERROR_BAD_CERT_DOMAIN```. There are several domains listed in the error which I assume belong to my hosting provider.

**Comment by phenax** [comment]
`http://wbalaile.is-a.dev` works but `https://wbalaile.is-a.dev` gives you the ssl error. This is because, your ssl certificate doesn't include your subdomain. You can use [Let's encrypt](https://letsencrypt.org/) to get an ssl certificate for `wbalaile.is-a.dev`

**Comment by wilby-mj** [comment]
I've had a look at the Let's Encrypt website and the options they give went a bit over my head;
- I am not comfortable with using Shell at the moment and worry I may crash the server if I try to install Certbot (or the alternatives).
- My hosting provider's back-end (CPanel) does not provide a Let's Encrypt module/plugin/add on/app
- The manual method would just have me pulling out hair 🙇🏾‍♂️

I have created a CSR using the available SSL/TLS module and sent a request to the hosting provider to create a certificate for the domain. 

Do you have any other recommendations on how I can speed up the process ? ty.

**Comment by wilby-mj** [comment]
#1877

Changed CNAME to Railway.app provided one. However on the Railway app the repo cannot be deployed. Please help.

**Comment by wilby-mj** [comment]
No documentation on how to use Railway, decided to switch to Github pages and it works.
Each repo can have it's own page, just turn it on from the settings. Add the ```is-a.dev``` domain to the custom domain section then check the Force HTTPS box.
