### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by AbubakarKang** [is-a-dev/register#1807]
Your domain name: https://abubakar.is-a.dev/

Explain any issues you are facing
![download](https://user-images.githubusercontent.com/90056797/156930784-7b8b0826-cda1-4250-a0a1-b103488650c8.jpg)

The connection is said to not be private. How do I fix this?

**Comment by MaskDuck** [comment]
have you check the enforce https yet

**Comment by AbubakarKang** [comment]
What do you mean?

**Comment by phenax** [comment]
@AbubakarKang, please read the docs for information on how to configure your github pages repo for use with a custom domain -> https://github.com/is-a-dev/register/blob/main/docs/hosted-at/github-pages.md

**Comment by AbubakarKang** [comment]
Thank you, it should work now!
