### ISSUE TITLE
Report abuse

### ISSUE THREAD

**Issue by itsunderscores** [is-a-dev/register#1811]
Domain you want to report: [is-a.dev](https://sarnax.is-a.dev/#Skills) https://sarnax.is-a.dev/

### Reason
Explain why you think this domain is being abused:
This is a known scammer that has not only scammed me out of $130, but countless others. I was planning to purchase part of a code from a "project he created", but seems like it was never his and he didn't have the rest of it so he removed me and deleted all of our chat history. Luckily I was taking screenshots before he removed it all.

None the less, the website will be used to keep scamming multiple people out of their money.

**Comment by hackermondev** [comment]
Can you provide proof of him scamming you? (Screenshots of your conversations, etc)

**Comment by itsunderscores** [comment]
https://i.imgur.com/cr7TF4I.png (Payment sent)
https://i.imgur.com/KsXNA6H.png (Discord ID)
https://i.imgur.com/pjWXKwh.png (Blocking and clearing DMs)

**Comment by MaskDuck** [comment]
for some reason i cant acces it =(
Discord ID is 582142955742298132 I suppose, since they have talked in the is-a-dev Discord server before.

**Comment by hackermondev** [comment]
@itsunderscores What did you buy?

**Comment by hackermondev** [comment]
I see its game cheats but for what game? (just wondering lol)

**Comment by itsunderscores** [comment]
Valorant source code, it was for https://github.com/SarnaxLii/Valorant-Hack

**Comment by MaskDuck** [comment]
they dont even know how to use git properly lmao

**Comment by MaskDuck** [comment]
also would you mind to join our discord server so we can talk about this further

**Comment by MaskDuck** [comment]
this should reflect soon

**Comment by MaskDuck** [comment]
@SarnaxLii your domain have been removed due to cheats distribution.

**Comment by Santiagocostaa** [comment]
Help guys [SarnaxLii](https://github.com/SarnaxLii) He is a scammer , he robbed me , I paid for a spoofer he deleted everything after receiving the money , waited 1 day and deleted me

**Comment by MaskDuck** [comment]
@Santiagocostaa we can't do anything since we are not the law, we are only the subdomain provider =( sorry. we had taken down his subdomain used for providing cheats.

**Comment by SarnaxLii** [comment]
@Santiagocostaa Show me proof when I cheated on you idiot. Your account was created a day or two ago, that's funny.

**Comment by SarnaxLii** [comment]
I don't understand why you need to create a new account. I came to answer my own post. Isn't that a little funny? Fighting, I'm rooting for you, idiot.

**Comment by MaskDuck** [comment]
gonna lock as it is too heated

we had done our best to resolve this issue, we had taken down their domain.

unfortunately we are not law enforcement so we cant do anything more. sorry you'all.
