### ISSUE TITLE
Feedback/suggestion

### ISSUE THREAD

**Issue by nischay876** [is-a-dev/register#1812]
Add A wildcard certificate on all the subdomains because i see many old PR domains saying not secure connection because their certificate is expired

**Comment by phenax** [comment]
There is already a wildcard ssl certificate. That's what all URL redirections use. However, if someone is using a DNS record, it cannot be covered by that SSL certificate as that has to be issued by the hosting service. It is unfortunate but the best we can do is document and provide instructions for how to configure popular hosting services with a custom domain. We have a few services already documented but we could always use more. If you have the time, we'd really appretiate a pr for it!
