### ISSUE TITLE
Help me 

### ISSUE THREAD

**Issue by SarnaxLii** [is-a-dev/register#1816]
https://sarnax.is-a.dev/

My website is not working. but i can use your other I need help

**Comment by phenax** [comment]
https://github.com/is-a-dev/register/issues/1811

**Comment by SarnaxLii** [comment]
http://sarnax.com/ 😎

**Comment by MaskDuck** [comment]
not time to ads...

**Comment by MaskDuck** [comment]
it honestly isnt cool from the way you cheated us for the domain

**Comment by SarnaxLii** [comment]
Where did I scam? Fake evidence. Do you trust it?

**Comment by SarnaxLii** [comment]
Where do I sell cheats? You can verify that there is nothing linked to selling scams.

**Comment by SarnaxLii** [comment]
I think you haven't looked at my site very well. My website is a self-introduction of what I am doing. I am not advocating for you to use cheating.

**Comment by phenax** [comment]
@SarnaxLii, your website advertises selling cheats and the allegation is that you scammed a user under the preface of selling a cheat. So, we had to take action as we cannot allow any such events to be associated with our service.

**Comment by MaskDuck** [comment]
explain the index of this file?
https://github.com/SarnaxLii/sarnax-dev-page/blob/62de222f1e614a1897ccab66e707276e3aa45db5/index.html

**Comment by MaskDuck** [comment]
https://github.com/SarnaxLii/sarnax-dev-page/commit/ad2f2ffac0c02bc16e5f84c086b4b459b0ed6d8c
https://github.com/SarnaxLii/sarnax-dev-page/commit/2e7817292c331a2fa5f55e98495b1d69ca5989d3
https://github.com/SarnaxLii/sarnax-dev-page/commit/6355b351ba9f68360d14c4c9e9aa2415567fad0c
https://github.com/SarnaxLii/sarnax-dev-page/commit/48475195fd3fabeee4e41d81b6f09bbdd3ea4f7c
https://github.com/SarnaxLii/sarnax-dev-page/commit/1d70917377790b60d57d9132c1c7c7b0a07a0e23
https://github.com/SarnaxLii/sarnax-dev-page/commit/329e7e23f5d6e84eef51946232438fe45333a5a0
explain these commit?

**Comment by FranklinOP-IND** [comment]
> you (really low chance) may not scam but you DEFINATELY are using our services for selling game cheats on the website, which is against our rules

His Scamer His Multi People Scaming Don't Trust Him I Have Proof

**Comment by FranklinOP-IND** [comment]
> Where do I sell cheats? You can verify that there is nothing linked to selling cheating

Mother Fukcer Get Out Form HERE

**Comment by MaskDuck** [comment]
i believe they are scamming

**Comment by SarnaxLii** [comment]
It's funny how you accuse me although there is no evidence

**Comment by adversaru** [comment]
> > Where do I sell cheats? You can verify that there is nothing linked to selling cheating
> 
> Mother Fukcer Get Out Form HERE

Send here a proof of what you accuse him of.

**Comment by Santiagocostaa** [comment]
Help guys  [SarnaxLii](https://github.com/SarnaxLii) He is a scammer , he robbed me , I paid for a spoofer he deleted everything after receiving the money , waited 1 day and deleted me

**Comment by SarnaxLii** [comment]
@Santiagocostaa I want evidence of you accusing me. Your account has just been created. The funniest allegations

**Comment by Santiagocostaa** [comment]
I have a video or you give my money back or I will export you to everyone on the internet

**Comment by Santiagocostaa** [comment]
Unlike other people you must have stolen from, my father is a well-recognized lawyer and for him to ask for his data will be something easy in the justice of his country

**Comment by Santiagocostaa** [comment]
I hope you unblock me and we can resolve this without me having to take legal action

**Comment by itsunderscores** [comment]
I've already had my own thread regarding @[SarnaxLii](https://github.com/SarnaxLii) and him scamming. You're a low life bro. I also ran a background on your address history with the one you gave, it's all fraud related with Paxful.

**Comment by itsunderscores** [comment]
Also, nice botted stats.

**Comment by itsunderscores** [comment]
> I think you haven't looked at my site very well. My website is a self-introduction of what I am doing. I am not advocating for you to use cheating.

You link your Discord, and then have everyone that adds you join your Discord that strictly shows what you're selling. https://cdn.discordapp.com/attachments/954892493462306846/954894758696857600/unknown.png

**Comment by Santiagocostaa** [comment]
@SarnaxLii I'm going to file a lawsuit and ask for your assets to be frozen you shit thief

**Comment by Santiagocostaa** [comment]
@SarnaxLii I already asked binance, which we are filing a lawsuit against you

**Comment by adversaru** [comment]
> @SarnaxLii I already asked binance, which we are filing a lawsuit against you

I'd be glad to see a proof of what you're saying.

**Comment by Santiagocostaa** [comment]
@SarnaxLii  I sent the videos of our conversations which were learned by obs studio

**Comment by SarnaxLii** [comment]
> > @SarnaxLii I already asked binance, which we are filing a lawsuit against you
> 
> I'd be glad to see a proof of what you're saying.

It's been 5 days and I haven't been sued yet. I think threatening doesn't help :)

**Comment by SarnaxLii** [comment]
I'm waiting for someone to sue me on ridiculous charges. because I have never deceived anyone And it's funny how you use multiple accounts of your own to type cool conversations. In spite of the fact that you almost didn't know me well.

**Comment by SarnaxLii** [comment]
Hope I get a subpoena from Finland sent to my home. I'm not afraid to be found. because I didn't do anything wrong

**Comment by Ovutuleu92** [comment]
Sarnax you scam everyone lmao i cant believe i fell for your scam ahahahha.

You scammed me aswell for a cheat i asked you to make.
Then you scammed some other dudes aswell.
You scam EVERYONE beacuse you're a BROKE CUNT. You've got on life, money or bitches. You're a broke thailandeese dog.
Fucking go eat a bat bro for covid-22 or sum shit, stop scamming normal citizens.

**Comment by AdemTfm** [comment]
sarnaxlii is a scammer
