### ISSUE TITLE
Domain index isn't working but other pages are

### ISSUE THREAD

**Issue by ayvacs** [is-a-dev/register#1826]
The main page of my website (https://ave.is-a.dev) redirects you to www.is-a.dev, saying that the subdomain will take time to update. However, other pages of the subdomain (https://ave.is-a.dev/formatting, https://ave.is-a.dev/galaxy-hub) are working.
The site's source code is at https://github.com/ayvacs/ayvacs.github.io and its Pages config is below.
<img width="714" alt="image" src="https://user-images.githubusercontent.com/74518502/157579019-08c25ceb-b9b0-46f8-919b-fc641f428f8a.png">
Would anyone mind helping me out with this? It's been happening for 2 days.

**Comment by phenax** [comment]
Please clear your browser cache or try it with incognito/private mode in your browser
