### ISSUE TITLE
Domain Unlinked

### ISSUE THREAD

**Issue by leecheeyong** [is-a-dev/register#1867]
My friend's subdomain `garden.is-a.dev` was approved and linked to their project a few days ago and they encounter the same issue as #1345 after a few days. Please help to fix this, thanks.

**Comment by MaskDuck** [comment]
there is nothing wrong with their config file, ive informed this to maintainers, maybe wait for them ig

**Comment by phenax** [comment]
There was an inconsistent record entry which caused this issue. It has been fixed and your subdomain should be accessible now.

**Comment by leecheeyong** [comment]
alright, thanks
