### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by CoderPopCat** [is-a-dev/register#1904]
Your domain name: trying to get

Explain any issues you are facing:

I would like to have `zerotwo.is-a.dev` domain but there is already a zerotwo.json file with a domain config of someone but the github user does not exist and the repository for that has been removed from existence so if I could get that domain it would be nice

**Comment by MaskDuck** [comment]
no

**Comment by hackermondev** [comment]
The person had recently changed their username, so the record was no longer valid. We can contact them to see if they want to keep the domain or give it to you.

**Comment by MaskDuck** [comment]
@hackermondev i have asked the owner of the domain and they dont want to give
![image](https://user-images.githubusercontent.com/70831061/158955751-6adaacf9-6fd5-42e2-8b0f-98470821820a.png)

**Comment by MaskDuck** [comment]
@coderpopcat sorry, we cant give you the domain =(

**Comment by ConnorDoesDev** [comment]
im updating it

**Comment by MaskDuck** [comment]
ok

**Comment by CoderPopCat** [comment]
oh ok

> @CoderPopCat sorry, we cant give you the domain =(
