### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by MaskDuck** [is-a-dev/register#1912]
Your domain name: https://lytwest.is-a.dev
![image](https://user-images.githubusercontent.com/76743461/158960206-9f50adcd-d78c-4617-9347-a7465700d20e.png)
I am getting such an error, is there a solution? The certificate also says Github, but I get the error that the site link is not secure.
Edit: In my computer, it is fixed in the incognito tab, but it continues to give the same message to my other friends.

_Originally posted by @Lytwest in https://github.com/is-a-dev/register/pull/1907#issuecomment-1072117845_

**Comment by MaskDuck** [comment]
@Lytwest for documentation purpose we need to convert this to an issue.

the problem here is have you check the enforce https checkbox yet?

**Comment by Lytwest** [comment]
> @Lytwest for documentation purpose we need to convert this to an issue.
> 
> the problem here is have you check the enforce https checkbox yet?
I have no clue what's going on

**Comment by MaskDuck** [comment]
uh have you check the enforce https box yet

**Comment by MaskDuck** [comment]
![image](https://user-images.githubusercontent.com/70831061/158961032-1fac7942-93a8-4920-bb1e-35172b0e25d9.png)
@Lytwest

**Comment by MaskDuck** [comment]
you must check this checkbox for the domain to work

**Comment by Lytwest** [comment]
No, but it doesn't tick when I click it.

**Comment by MaskDuck** [comment]
wdym "able to mark"?

**Comment by Lytwest** [comment]
![image](https://user-images.githubusercontent.com/76743461/158961522-ba74067d-d32c-48f8-81e0-f3be7ce4b35c.png)
I just confirmed

**Comment by MaskDuck** [comment]
wait me a minute

**Comment by MaskDuck** [comment]
maybe wait since ssl takes sometimes to issue...

**Comment by MaskDuck** [comment]
can you access it yet

**Comment by Lytwest** [comment]
I think the problem is solved, I shared the link again and they said they were able to log in.

**Comment by MaskDuck** [comment]
ooo nice

**Comment by MaskDuck** [comment]
next time if you need help, feel free to create a new issue or join our [discord server](https://discord.gg/7UbzmX2fq2)!
