### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by CoderPopCat** [is-a-dev/register#1926]
After my pull request with my domain info was merged, I am still not able to see any page on `zero.is-a.dev`, not even a 404 page. I have configured everything on GitHub pages.

**Comment by MaskDuck** [comment]
can i see your gh pages config

**Comment by CoderPopCat** [comment]
![image](https://user-images.githubusercontent.com/79563127/159119035-a37180cd-f0ea-45fa-8592-b90d1823c32e.png)

**Comment by MaskDuck** [comment]
i can see something on zero.is-a.dev .

**Comment by MaskDuck** [comment]
![image](https://user-images.githubusercontent.com/70831061/159119205-e93d5e88-8967-4c5a-ad36-ac0b23d3966d.png)
everything i can see in zero.is-a.dev.

**Comment by CoderPopCat** [comment]
hm ok I will

**Comment by CoderPopCat** [comment]
works thank you
