### ISSUE TITLE
[SUGGESTION] Remove "other services" section

### ISSUE THREAD

**Issue by fxrysh** [is-a-dev/register#1954]
I think the maintainer(s) should remove the "other services" section. This is because `thedev.id` seems unmaintained while `js.org` is only for JS specific project. Maybe we should only keep `runs-on.tech`.

**Comment by fxrysh** [comment]
[`thedev.id`](https://github.com/fransallen/thedev.id) last commit was November 2021

**Comment by MaskDuck** [comment]
i see.

**Comment by fxrysh** [comment]
PR #1955
