### ISSUE TITLE
Report abuse

### ISSUE THREAD

**Issue by Pompakow123** [is-a-dev/register#2003]
Domain you want to report: 

https://daniel.is-a.dev/

### Reason
Explain why the  think this domain is being abused

So the owner of this domain is ddosing other sites here are screenshots: 
![image](https://user-images.githubusercontent.com/48710042/160403321-15f408b0-e8fa-49a7-9d50-3d0aea6192c5.png)
![image](https://user-images.githubusercontent.com/48710042/160403355-31ba5dfe-abc8-4feb-b766-dfc7c0cff9a7.png)
![image](https://user-images.githubusercontent.com/48710042/160403409-9b9a0631-83d4-4301-b637-ceb5d4150645.png)

edit 1: rephrased by @MaskDuck to remove too agressive words.

**Comment by MaskDuck** [comment]
*oh no they are a maintainer and someone i really trust*

**Comment by Magniquick** [comment]
> Domain you want to report:
> 
> [daniel.is-a.dev](https://daniel.is-a.dev/)
> 
> ### Reason
> Explain why the think this domain is being abused
> 
> So the owner of this domain is ddosing other sites here are screenshots: ![image](https://user-images.githubusercontent.com/48710042/160403321-15f408b0-e8fa-49a7-9d50-3d0aea6192c5.png) ![image](https://user-images.githubusercontent.com/48710042/160403355-31ba5dfe-abc8-4feb-b766-dfc7c0cff9a7.png) ![image](https://user-images.githubusercontent.com/48710042/160403409-9b9a0631-83d4-4301-b637-ceb5d4150645.png)
> 
> edit 1: rephrased by @MaskDuck to remove too agressive words.

tbh, he didn't use thesite for ddos
but yeah, I agree

**Comment by Magniquick** [comment]
> _oh no they are a maintainer and someone i really trust, i cant believe they have done that. they are pretty nice with me through._

tbh imo, felt real strong script kidde vibes when he said he "joined" anonymous

**Comment by whinee** [comment]
> cloudflare bypass
www, funny shit

**Comment by hackermondev** [comment]
Half of everything you said is a lie but I would also like to share this screenshot of you hitting MY site. 
![image](https://user-images.githubusercontent.com/60828015/160416488-0cf1fc77-8093-4fec-ac3c-8602f959482d.png)

**Comment by hackermondev** [comment]
You're the real script kiddie with your "stresser" discord server where you're ddosing people. https://discord.gg/ewjvCdBc

**Comment by Magniquick** [comment]
I take back everything I said
[daniel.is-a.dev](https://daniel.is-a.dev/) should ***NOT*** be taken down
as - 
1) the website didn't do the attack 
2) https://atom-api.xyz/ , the website of @Pompakow123 IS ***ILLEGALALLY SELLING DOS / DDOS ATTACKS VIA AN API***
3) @Pompakow123 ***DDOS*** @hackermondev website
proofs -
https://imgur.com/a/9ZvBNWn
https://discord.com/invite/mvjUC93GzJ

**Comment by MaskDuck** [comment]
agreed

screenshots can easily being faken

ill create some fake message screenshot rn

**Comment by Magniquick** [comment]
> agreed
> 
> screenshots can easily being faken
> 
> ill create some fake message screenshot rn

screenshots are real

**Comment by MaskDuck** [comment]
![image](https://user-images.githubusercontent.com/70831061/160418561-99b59995-fb36-4fb4-b4b9-52c8b0179dc2.png)

**Comment by Pompakow123** [comment]
BRUH HE FUCKING DELETED MESSAGES XD 

https://discord.gg/mvjUC93GzJ

![image](https://user-images.githubusercontent.com/48710042/160418428-67ab19bf-21ab-4146-84ef-0bc0f8080f69.png)

**Comment by Pompakow123** [comment]
His site still should be removed <3

**Comment by Pompakow123** [comment]
![image](https://user-images.githubusercontent.com/48710042/160418742-c5c4a5ef-b8a0-4bd6-a166-c17d2d10f7df.png)
and he is stupid asf: i bypassed your cf

**Comment by Pompakow123** [comment]
> > His site still should be removed <3
> 
> why ?

Why ? because he sen't  ddos attack and you saw a fucking messages

**Comment by Magniquick** [comment]
> > > His site still should be removed <3
> > 
> > 
> > why ?
> 
> Why ? because he sen't ddos attack and you saw a fucking messages

that has nothing to do with the website - his website is not in this
plus *your site sells dos attacks*

**Comment by Pompakow123** [comment]
BUT ITS HIS FUCKING SITE

**Comment by whinee** [comment]
I am really confused as to what really happened. In any case, I'm glad that the allegations against @hackermondev has been cleared.

> I suggest banning @Pompakow123 from this repository
Cannot agree more

**Comment by Magniquick** [comment]
> I take back everything I said [daniel.is-a.dev](https://daniel.is-a.dev/) should _**NOT**_ be taken down as -
> 
> 1. the website didn't do the attack
> 2. [atom-api.xyz](https://atom-api.xyz/) , the website of @Pompakow123 IS _**ILLEGALALLY SELLING DOS / DDOS ATTACKS VIA AN API !**_
> 3. @Pompakow123 _**DDOS**_ @hackermondev website
>    proofs -
>    [imgur.com/a/9ZvBNWn](https://imgur.com/a/9ZvBNWn)
>    [discord.com/invite/mvjUC93GzJ](https://discord.com/invite/mvjUC93GzJ)
>    @MaskDuck @whinee I suggest banning @Pompakow123 from this repository
>    I have sent abuse reports to OVH and Cloudfare (@Pompakow123 webste uses OVH for hosting and Cloudfare for DoS defence)

@whinee

**Comment by MaskDuck** [comment]
phenax is the only person who can block.

**Comment by MaskDuck** [comment]
even if they actually did attack your **illegal** website, that has nothing to do with his website. he didn't use his website for that. upon that, this report is not valid. id gonna close this.
