### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by MazenGohar** [is-a-dev/register#2005]
Your domain name:
mazengohar.is-a.dev
Explain any issues you are facing
My hosting provider says that it successfully connected the domain but it still takes me to is-a.dev.

**Comment by phenax** [comment]
You'll need to clear your browser cache if it is redirecting you to www.is-a.dev. It seems to be working from our end but it is a 404 page with "Not found" text so you may need to double check your hosting configuration.

**Comment by MazenGohar** [comment]
Woah! Thanks!
Clearing my browser cache worked!
