### ISSUE TITLE
Adding isadev to bearblog

### ISSUE THREAD

**Issue by asheeeshh** [is-a-dev/register#2032]
I'm not really sure about how to add isadev subdomain to my bearblog site, some help would be really appreciated, so far I've got this from the bearblog docs: https://github.com/HermanMartinus/bearblog/wiki/Custom-domains

**Comment by MaskDuck** [comment]
afaik there is no way sorry =(, but @is-a-dev/maintainers do you have any idea?

**Comment by asheeeshh** [comment]
> afaik there is no way sorry =(, but @is-a-dev/maintainers do you have any idea?

ah that's sad, thanks for replying though.

**Comment by MaskDuck** [comment]
is it fine to close this?
