### ISSUE TITLE
How do I link the domain?

### ISSUE THREAD

**Issue by MrPotato30** [is-a-dev/register#2063]
Hey, I just got the domain but when I tried to link it shows this
![image](https://user-images.githubusercontent.com/85820415/162217562-24098b41-23d1-4f4c-bbac-d1c5f2903b07.png)
What do I do now?

I can't check this box
![image](https://user-images.githubusercontent.com/85820415/162219968-1b9b7edb-d431-409e-8879-075b0123687a.png)

**Comment by MaskDuck** [comment]
you registered an url redirect.

**Comment by MaskDuck** [comment]
in your pr (#2059) you used a url record, which is a redirect

**Comment by MrPotato30** [comment]
oh no, should i edit the pr?

**Comment by MaskDuck** [comment]
please make a new pr.

**Comment by MrPotato30** [comment]
![image](https://user-images.githubusercontent.com/85820415/162246742-3de0ab17-3cad-476f-bff8-8dacadd2a8c7.png)
can you delete the previous file please?

**Comment by MrPotato30** [comment]
![image](https://user-images.githubusercontent.com/85820415/162249319-9b198847-0531-4628-91a4-8d7fbb95e4e2.png)
i thought the file got deleted but its still here
![image](https://user-images.githubusercontent.com/85820415/162249543-b50200e9-e252-4e4a-a60e-6be4e3661cf2.png)
