### ISSUE TITLE
page 404

### ISSUE THREAD

**Issue by MrPotato30** [is-a-dev/register#2073]
I linked the domain to the github pages and Ive waited 2 hours and it still returns 404. it keeps adding `/portfolio` at the end of the URL
try it: [spud.is-a.dev](https://spud.is-a.dev/)
![image](https://user-images.githubusercontent.com/85820415/162373347-b01b0ee7-33ad-4981-85ab-cc95562687fe.png)

**Comment by SX-9** [comment]
Its working now

**Comment by phenax** [comment]
Closing this issue since it seems to have been resolved. Please clear your browser cache if you're still facing problems.

**Comment by MrPotato30** [comment]
> Its working now

For me it's not. i tried it on google chrome and it works... but it doesn't work on brave?

**Comment by phenax** [comment]
If it works on any browser then this issue has nothing to do with the is-a-dev service.

PS - tried it on brave. It works. Please clear your browser and network cache.
