### ISSUE TITLE
InvalidDNSError

### ISSUE THREAD

**Issue by SX-9** [is-a-dev/register#2076]
Hi, so I just registered the subdomain `chat-with.sx9.is-a.dev` but when I linked it with github pages it shows this error, how do I fix it?

![SmartSelect_20220408-184840_Chrome](https://user-images.githubusercontent.com/90962949/162429913-f7cb4d3b-d508-4efc-9a19-af0839a38438.jpg)

**Comment by SX-9** [comment]
Ok nvm i fixed it

**Comment by phenax** [comment]
Try clearing the input, saving and then adding it back again after a reload. This github setting is known to behave weirdly from time to time

**Comment by SX-9** [comment]
Ok thx
