### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by rabbishuki** [is-a-dev/register#218]
Your domain name: rabbi-shuki.is-a.dev

I followed the instructions, and this is the result I get: 
![image](https://user-images.githubusercontent.com/24904197/95732516-85379f80-0c89-11eb-9877-8b0551ca5fba.png)

**Comment by phenax** [comment]
You need to check the `Enforce https` checkbox in your github page repo's settings. Reopen this issue if that doesn't fix this.
