### ISSUE TITLE
forks

### ISSUE THREAD

**Issue by boolean44-repos** [is-a-dev/register#2180]
people keep their forks and no others can fork

**Comment by MaskDuck** [comment]
?

**Comment by boolean44-repos** [comment]
nvm im dumb

**Comment by boolean44-repos** [comment]
can i switch to hanami.run ?

**Comment by MaskDuck** [comment]
feel free

**Comment by boolean44-repos** [comment]
final question

could my email be "name@boolean44.is-a.dev" instead of "name@mail.boolean44.is-a.dev"?

**Comment by MaskDuck** [comment]
if you remove the cname :)

**Comment by boolean44-repos** [comment]
there any downsides to removing the cname?

**Comment by MaskDuck** [comment]
yes, the website wont be unusable

**Comment by boolean44-repos** [comment]
will work or wont?

**Comment by Craftzman7** [comment]
wont work
