### ISSUE TITLE
Change domain

### ISSUE THREAD

**Issue by TigerbyteDev** [is-a-dev/register#2188]
Your domain name: tigerbyte.is-a.dev

I've tried to change my file, so it redirects to https://home.tigerbyte.dev because I bought that domain today. But GitHub seems to stop showing files after S. Could you change it manually, please? :/

**Comment by MaskDuck** [comment]
no sorry, we arent allowed to directly commit into the repo, all commits must be created through a pr.

**Comment by TigerbyteDev** [comment]
ok :/

**Comment by DanielRamp** [comment]
Did I understand correctly, you can't navigate to the file? If yes:

You can navigate with the `Go to File` button and then type e.g. `tiger`.
Or use [this direct link](https://github.com/is-a-dev/register/blob/main/domains/tigerbyte.json).

**Comment by MaskDuck** [comment]
![image](https://user-images.githubusercontent.com/70831061/164952222-03a8bf6f-2f15-4315-8c00-7e0af1891dbf.png)
for anyone are wondering, i cant commit directly to the `main` branch, which branch that you need to commit into that branch for record to exist.

i can open a pr through, but it need codeowners approval and i can't approve my own pr.

**Comment by TigerbyteDev** [comment]
Thank you :3 I didn't knew that button existed
