### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by Jakethebest1238** [is-a-dev/register#2189]
Your domain name:
jakehe.is-a.dev

Explain any issues you are facing
Verifying custom domain for Github Pages.

1. Create a TXT record in your DNS configuration for the following hostname: _github-pages-challenge-Jakethebest1238.jakehe.is-a.dev
2. Use this code for the value of the TXT record: f7b80c5bc45ec5****************
3. Wait until your DNS configuration changes. This could take up to 24 hours to propagate.

Is it possible to Verify the Custom Domain on Github Pages? If so, what are the next steps?

**Comment by hackermondev** [comment]
It is not possible to verify the custom domain since we do not allow TXT records for security reasons.

**Comment by Jakethebest1238** [comment]
That's fine, thank you for the fast reply.
