### ISSUE TITLE
how do i use improvmx with my subdomain?

### ISSUE THREAD

**Issue by WilliamDavidHarrison** [is-a-dev/register#2230]
I have put the records in the subdomain but on improvmx it wont verify

**Comment by MaskDuck** [comment]
define "it wont verify"?

**Comment by WilliamDavidHarrison** [comment]
> define "it wont verify"?

It says the dns records don't exist when in the subdomain file they do

**Comment by WilliamDavidHarrison** [comment]
> > define "it wont verify"?
> 
> It says the dns records don't exist when in the subdomain file they do

This is for william.is-a.dev
