### ISSUE TITLE
Support heroku

### ISSUE THREAD

**Issue by boolean44-repos** [is-a-dev/register#2271]
Your domain name: https://boolean44.is-a.dev/

Explain any issues you are facing how do i allow my domain to be used via heroku

**Comment by mtgsquad** [comment]
![image](https://user-images.githubusercontent.com/75879007/166609626-fa391860-e7c9-4594-b35e-99f075ab06ce.png)
As shown in the image above, heroku supports domain config using CNAME. and second, this is support for is-a.dev, if you are having issues with is-a.dev itself, like domain isn't working or keeps redirecting to main site. This is not heroku support.
