### ISSUE TITLE
How to add subdomain to subdomain for is-a.dev. Like blog.my-domain.is-a.dev in same json file.

### ISSUE THREAD

**Issue by avasthi-git** [is-a-dev/register#2275]
And how to add different CNAME record for the same.
Considering that CNAME for my-domain.is-a.dev and blog.my-domain.is-a.dev are different.
I hope you got my concern please help.

**Comment by mtgsquad** [comment]
There aren't actually made with the same file, you can simply make a new file called `blog.my-domain.json`, with the desired records just like your actual subdomain. The sub-subdomain will follow the same file format as your subdomain, just with different records.
