### ISSUE TITLE
Add requirement: reasonable content

### ISSUE THREAD

**Issue by MaskDuck** [is-a-dev/register#2376]
theres a lot of users (at least considerable amount of users) that has the page saying "test", "foobar" etc.

there should be a requirements of completed website to grant users subdomain. if not, it would be something called "domain keeping", where you just claim the domain and don't let others use it.

**Comment by MaskDuck** [comment]
this thread will be used to discuss which should qualify for "reasonable content".

**Comment by phenax** [comment]
I agree. But I think it will be pretty difficult to define what this line should be since, pulling up a template to park a sub-domain will not be that difficult. So, at the end it's still up to your judgment to figure out what counts as reasonable. Also, since we've allowed nested sub-domains, the use-cases for these have broadened as well.

The ones that are to be rejected for sure are the single html pages with some temporary text. For the others, I think for the first few non-trivial offenses, we can speak with other maintainers and see if we all agree on whether something should be approved or not. That way, the whole team can develop a consistent judgement for what is to be considered "reasonable".

**Comment by TheBotlyNoob** [comment]
I think that's a good idea

**Comment by WilliamDavidHarrison** [comment]
if someone is obviously just claiming a bunch of subdomains for example: abc, a, b, c then dont merge the prs?

**Comment by Magniquick** [comment]
some ideas -
-  site code must be foss 

- should not contain non-dev related stuff
- should not be "lorem ipsum" / placeholders

**Comment by MaskDuck** [comment]
i dont really agree with the 1st and 2nd one

**Comment by LogSkele** [comment]
yeah, people should be allowed to put non-dev related things

**Comment by mtgsquad** [comment]
What do you mean by "foss"? @Magniquick

**Comment by MaskDuck** [comment]
> What do you mean by "foss"? @ Magniquick

@mtgsquad open sourced

**Comment by Mosaab-Emam** [comment]
I disagree, lets say I am in the process of building my personal website, I would put some placeholder content as a 'placeholder' and update it with my actual code later.
Also, domain keeping is inherently present in whenever domain registering is present, people pay to buy domains they don't immediately use all the time, and the goal clearly is to prevent other people from using it. Honestly I don't know if this should be considered a problem at all.

**Comment by WilliamDavidHarrison** [comment]
This is different, since there are a finite amount of subdomains available, with most people using their name or online name, someone just hogging the domain with nothing/a placeholder on their website is annoying especially if that’s the subdomain they want.

**Comment by Mosaab-Emam** [comment]
I am not saying that it isn't annoying, but I find domains that I want unavailable all the time, and unused!.
Maybe I just learned to accept that.
Of course a reasonable middle ground is always welcome.

**Comment by phenax** [comment]
In addition to it not being fair, we also have to deal with cases of abuse or contents of the page violating our guidelines. A person can of course change the content later on but this still acts as an initial deterrent knowing that the content is moderated to some extent. is-a.dev is responsible for operating this service and by proxy, what people use it for.

In general, I personally find the practise of hogging on something even if you don't need it, very wrong but yet, extremely normalized. Let's avoid bringing that here.

**Comment by mtgsquad** [comment]
So, at the moment, we've got hogging to be stopped, and what else? @phenax should we be looking at the content of the site or not?

**Comment by SX-9** [comment]
yes ig i have no idea wth is this

**Comment by phenax** [comment]
> should we be looking at the content of the site or not?

We're already supposed to do that as mentioned in the [maintainer docs](https://github.com/is-a-dev/maintainer-docs/blob/main/pr-review.md#contents-of-the-website)? The only difference now would be a new criteria for rejection will be added where any empty, non-existent or unstyled "Hello world"-like text content will not be allowed for 1st level sub-domains. Registering multiple sub-domains is fine as long as they all contain valid content.

@is-a-dev/maintainers Let me know if you guys disagree. Otherwise we can update the documentation and close this issue.

**Comment by riso38** [comment]
Hello, dm seve.services on instagram for really good grabber. trust me.

**Comment by andrewstech** [comment]
> > should we be looking at the content of the site or not?
> 
> We're already supposed to do that as mentioned in the [maintainer docs](https://github.com/is-a-dev/maintainer-docs/blob/main/pr-review.md#contents-of-the-website)? The only difference now would be a new criteria for rejection will be added where any empty, non-existent or unstyled "Hello world"-like text content will not be allowed for 1st level sub-domains. Registering multiple sub-domains is fine as long as they all contain valid content.
> 
> @is-a-dev/maintainers Let me know if you guys disagree. Otherwise we can update the documentation and close this issue.

We could make a terms and conditions of the service and use a CLA as requirement for PRs to be merged

**Comment by andrewstech** [comment]
https://github.com/contributor-assistant/github-action

**Comment by WilliamDavidHarrison** [comment]
> https://github.com/contributor-assistant/github-action

I can help add the action.

**Comment by Bad-Boy-Codes** [comment]
> theres a lot of users (at least considerable amount of users) that has the page saying "test", "foobar" etc.
> 
> there should be a requirements of completed website to grant users subdomain. if not, it would be something called "domain keeping", where you just claim the domain and don't let others use it.

yes!!!
many people have reserved domains for no reason, plus some people try to fool others by selling them this domain,


I suggest there should a limit to how many domains can a person own by default, if they want more then contact the support in discord (that way atleast the discord chat won't be dead 💀)

**Comment by WilliamDavidHarrison** [comment]
I'll close this issue as the requirement is in place.
