### ISSUE TITLE
Add is-a.dev to the Public Suffix List

### ISSUE THREAD

**Issue by aeternesatiatus** [is-a-dev/register#2534]
Describe change I suggest you add is-a.dev to the Public Suffix List, in the likes of other similar free subdomain services like eu.org and js.org.

Additional context This would help against supercookies and other issues (i.e. per-domain rate limits)

**Comment by fu-sen** [comment]
I have reported this issue in the past.
https://github.com/is-a-dev/register/issues/793
The is-a.dev administrator was acting but not authorized.
https://github.com/publicsuffix/list/pull/1327

It is currently recommended to apply for Let’s Encrypt to resolve this issue.
Now that this is possible, the Public Suffix List will not register for Let’s Encrypt.

[HelioHost](https://www.heliohost.org/) recently encountered this issue. Root Admin here solved the problem with a Let's Encrypt application.
https://www.helionet.org/index/topic/52997-lets-encrypt-rate-limit/
https://www.helionet.org/index/topic/53298-great-ssl-news/
is-a.dev should be able to do the same.

**Comment by phenax** [comment]
For rate limiting issues, at the moment we plan to resolve them on a case by case basis as we have already done for Let's Encrypt by having our rate limit extended. As the comment above mentioned, we attempted to add it to the public suffix list but we were rejected. We might make another attempt in the future to get this on there. Keeping this issue open for now.

**Comment by MaskDuck** [comment]
well firefox highlight fucks up if we dont add

**Comment by riso38** [comment]
Hello, dm seve.services on instagram for really good grabber. trust me.

**Comment by WilliamDavidHarrison** [comment]
@phenax Maybe they won't allow is-a.dev as we don't support NS records? So, it would purely be for the Let's Encrypt rate limits.

**Comment by TerraPlayz** [comment]
Any update? Did you try to reapply?

**Comment by BBaoVanC** [comment]
> I have reported this issue in the past. #793 The is-a.dev administrator was acting but not authorized. [publicsuffix/list#1327](https://github.com/publicsuffix/list/pull/1327)
> 
> It is currently recommended to apply for Let’s Encrypt to resolve this issue. Now that this is possible, the Public Suffix List will not register for Let’s Encrypt.
> 
> [HelioHost](https://www.heliohost.org/) recently encountered this issue. Root Admin here solved the problem with a Let's Encrypt application. https://www.helionet.org/index/topic/52997-lets-encrypt-rate-limit/ https://www.helionet.org/index/topic/53298-great-ssl-news/ is-a.dev should be able to do the same.

Pretty sure they literally just wanted @phenax to say another valid reason other than just let's encrypt. There's a lot of reasons to add is-a.dev to the PSL, namely that it's semantically correct, and as mentioned above to avoid supercookies or display highlighting properly in browser address bar.

**Comment by EnderPoint07** [comment]
update?

**Comment by WilliamDavidHarrison** [comment]
No, not yet.

**Comment by wdhdev** [comment]
@phenax Do you mind if I reapply for the PSL?

**Comment by wdhdev** [comment]
I have opened a new PR adding is-a.dev, with more information this time.
https://github.com/publicsuffix/list/pull/1949

cc @phenax

**Comment by CuteDog5695** [comment]
is-a.dev has now been added to PSL (Public Suffix List) now
