### ISSUE TITLE
Feedback/suggestion: Allow numerical domains

### ISSUE THREAD

**Issue by WilliamDavidHarrison** [is-a-dev/register#2608]
eg. 12345.is-a.dev or 1.example.is-a.dev

**Comment by MaskDuck** [comment]
didnt we already allowed it

**Comment by WilliamDavidHarrison** [comment]
> 

no, i tried to create a domain: 2.william.is-a.dev but the github check failed but when i changed it to william2.is-a.dev the checks passed #2606

**Comment by WilliamDavidHarrison** [comment]
ohhhh, im dumb
