### ISSUE TITLE
SSL error: ERR_CERT_COMMON_NAME_INVALID for redirection urls

### ISSUE THREAD

**Issue by johan12345** [is-a-dev/register#270]
Your domain name: https://johan.is-a.dev

Explain any issues you are facing:

My domain uses the URL redirection feature, but it doesn't work because the SSL certificate it uses is for the wrong domain (`*.web-hosting.com`).
I am just getting `NET::ERR_CERT_COMMON_NAME_INVALID` errors.

**Comment by phenax** [comment]
I'm having difficulties getting certificates through certbot because of rate limiting. Will keep this issue updated.

**Comment by phenax** [comment]
Added an ssl certificate for redirections.
@johan12345, let me know if it works on your end so I can close this issue.

**Comment by johan12345** [comment]
Yes, it works now, thank you!
