### ISSUE TITLE
Feedback/suggestion: Create a support email

### ISSUE THREAD

**Issue by WilliamDavidHarrison** [is-a-dev/register#2709]
You guys should create a support email like “support@is-a.dev” so people can contact by email for certain things.

**Comment by omxpro** [comment]
> You guys should create a support email like “[support@is-a.dev](mailto:support@is-a.dev)” so people can contact by email for certain things.

According to pr number #1123 phenax [said](https://github.com/is-a-dev/register/pull/1123#pullrequestreview-749198921)  that for security reasons/spam reasons they will do it for later

**Comment by omxpro** [comment]
Phenax [said](https://github.com/is-a-dev/register/pull/1123#pullrequestreview-749198921) 

> Let's keep this PR for later. Do not merge it. We don't want to increase the attack surface immedietely after releasing a new feature
