### ISSUE TITLE
How do I do the txt dns record

### ISSUE THREAD

**Issue by Nzii3** [is-a-dev/register#2731]
This is for an image hosting, how do I do the second part? And when I do the first part (CNAME) it doesn’t seem to work. Im using GitHub pages with the CNAME file: https://github.com/Nziie3/nziie3.github.io

**Comment by Nzii3** [comment]
![Uploading 64A77D2A-BC60-4360-8DF3-D020C5319E22.jpeg…]()

**Comment by Nzii3** [comment]
![4CEF20B2-1941-40B3-A941-C15CE7871432](https://user-images.githubusercontent.com/106406461/176815333-1ff85567-28cf-4f91-aede-8ac4f07f99fe.jpeg)

**Comment by WilliamDavidHarrison** [comment]
I don’t think you can add that service because it requires verification of the domain.

**Comment by waydealphax** [comment]
we require verification on subdomains that arent managed by us, additionally you can't use github pages to host images on tixte, you need to have a CNAME that points to dns.tixte.com and not your github pages site.

**Comment by Nzii3** [comment]
@waydealphax So I can’t do it?

**Comment by waydealphax** [comment]
as cole has said to you, no this owuldbt be possible because they likely wont allow records like `_tixte-challenge`
