### ISSUE TITLE
Anger.is-a.dev Visibility on mobile and desktop

### ISSUE THREAD

**Issue by AngerminecraftYT** [is-a-dev/register#2804]
### Expected outcome
That you can see the page when going to my website

### Observed outcome
it shows on desktop "If you were expecting your website to show up here, it may take some time for your changes to reflect."
and on mobile it works perfectly fine and the page if visible

**Comment by omxpro** [comment]
It may take some time for the domain to regulate everywhere. You can use /dig command in our discord server for it. And on a Desktop you can try clearing cache of your website. It may help on a desktop to load your website. Or you can try a new browser. Thanks for using is-a.dev

**Comment by AngerminecraftYT** [comment]
> It may take some time for the domain to regulate everywhere. You can use /dig command in our discord server for it. And on a Desktop you can try clearing cache of your website. It may help on a desktop to load your website. Or you can try a new browser. Thanks for using is-a.dev

Okay, i will try this, but so people know it may show up earlier on phone then desktop.

Closed.
