### ISSUE TITLE
my pull request was accepted but my website is not to be working

### ISSUE THREAD

**Issue by Darkcoder402** [is-a-dev/register#2854]
my pull request was accepted but my website is not to be working pls look into the matter han help me 
thankyou,
Ethan

**Comment by bimal-inc** [comment]
Mine has the similar issue , it redirects me to the www.is-a.dev page.
Here is my Subdomain  `bimal.is-a.dev` .

**Comment by mtgsquad** [comment]
Please do not mention other maintainers as you can clearly see that I have responded, and learn to wait.

and second, clear your cache. The DNS records are correct, your host hasn't provided an SSL for it.

For further support, please create a thread in #help in our discord: https://discord.gg/TCqm9Cxt6m

**Comment by andrewstech** [comment]
> Mine has the similar issue , it redirects me to the [www.is-a.dev](http://www.is-a.dev) page. Here is my Subdomain `bimal.is-a.dev` . @andrewstech @MaskDuck

![Screenshot_2022-07-22-13-50-28-419_com android chrome](https://user-images.githubusercontent.com/45342431/180442779-d9f20741-ac89-4e43-b890-3769564163d7.jpg)
Working for me

**Comment by MouseMoosz** [comment]
Working for me too.
Clear your cache as suggested by mtgsquad

**Comment by omxpro** [comment]
Any updates on this?

**Comment by phenax** [comment]
Closing this as the website is working fine. If you're still facing issues, please clear your browser cache.

**Comment by bimal-inc** [comment]
thank you soory i wasn't on github for a little while. yeah it is working fine for me 
this was the working solution.
thank you devs.

> Please do not mention other maintainers as you can clearly see that I have responded, and learn to wait.
> 
> and second, clear your cache. The DNS records are correct, your host hasn't provided an SSL for it.
> 
> For further support, please create a thread in #help in our discord: https://discord.gg/TCqm9Cxt6m
