### ISSUE TITLE
using is-a.dev as a redirection service

### ISSUE THREAD

**Issue by monitrr** [is-a-dev/register#2867]
I had given a client my website (moni.is-a.dev), but now i want to use nextjs, which doesnt support is-a.dev to my knowledge, so could i use this domain as a redirection service?

**Comment by omxpro** [comment]
> I had given a client my website (moni.is-a.dev), but now i want to use nextjs, which doesnt support is-a.dev to my knowledge, so could i use this domain as a redirection service?

I am pretty sure you can. Because some of our users are using is-a.dev to redirect to another domain. You can use a `URL` record for this.

**Comment by monitrr** [comment]
ah ok, i just wanted to make sure i wouldnt get any abuse strikes or anything, tysm!

**Comment by mtgsquad** [comment]
@omxpro Invalid.
@monitrr You can use Next,js with is-a.dev, we just don't support netlify and vercel. For hosting you could use cloudflare pages, or railway.

**Comment by monitrr** [comment]
ah okay

**Comment by monitrr** [comment]
tysm!
