### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by ba-e** [is-a-dev/register#290]
![Screenshot_20201016-210801515.jpg](https://user-images.githubusercontent.com/50950966/96293609-b26eaf80-0ff3-11eb-8ca3-870228d94b37.jpg)

I can't access my redirection

**Comment by phenax** [comment]
I think the server is not configured correctly. It gives me an cloudfare error through http.

![part-2020_10_16_23_47_35](https://user-images.githubusercontent.com/11407672/96294488-13a17d80-100a-11eb-88e7-30a03b8c1a10.jpg)

And the cname seems to be proper too

```
$ dig bae.is-a.dev +noall +answer
bae.is-a.dev.           17745   IN      CNAME   bae.codes.
bae.codes.              45      IN      A       104.28.27.241
bae.codes.              45      IN      A       104.28.26.241
bae.codes.              45      IN      A       172.67.160.38
```

Can you give me some more information regarding your server?

**Comment by phenax** [comment]
Alternatively, you can just do a url redirection from `bae.is-a.dev` to `bae.codes`, which requires a lot less configuration. You can change your record type from CNAME to URL `https://bae.codes`.

**Comment by ba-e** [comment]
In my json file? 
I'm using github pages and cloudflare for page rules feature

**Comment by phenax** [comment]
Your cloudflare config. Have you added the rule for `bae.is-a.dev` there?

**Comment by ba-e** [comment]
No, how can I do it?

**Comment by phenax** [comment]
I haven't used cloudflare personally but I've found [this doc](https://support.cloudflare.com/hc/en-us/articles/217371987-Managing-Custom-Hostnames-SSL-for-SaaS-) that may help you out.

**Comment by ba-e** [comment]
Need enterprise customer account for that, can I just change my record like that
```json
"record": {
"URL": "https://bae.codes"
}
```

**Comment by phenax** [comment]
Sure. Create a new pr with the changes.
