### ISSUE TITLE
domain cname is not pointing to my website 

### ISSUE THREAD

**Issue by CYCNO** [is-a-dev/register#2908]
Domain you want to report: cycno.is-a.dev

### Reason
DNS of github is saying that domain is pointing to [YOUR USERNAME].github.io instead of cycno.github.io 
can you pls fix it

**Comment by mtgsquad** [comment]
This is not an abuse risk. (Issue assigned to @omxpro)

**Comment by omxpro** [comment]
> 



> Domain you want to report: cycno.is-a.dev
> 
> ### Reason
> DNS of github is saying that domain is pointing to [YOUR USERNAME].github.io instead of cycno.github.io can you pls fix it

Hello there. When applying for a domain you need to replace `[YOUR USERNAME]` with your actual GitHub username. Example: `omxpro.github.io`. also when entering the domain in your GitHub pages website you need to use `subdomain.is-a.dev` not `username.github.io` example when i host a web from ghub pages I use `om.is-a.dev` as a domain in my pages settings. Here is a few things you can do.

1. Provide some screenshots so we can understand more about the issue.
2. Has your pr been merged?

**Comment by CYCNO** [comment]
THIS IS WHAT IT SHOWING THE DNS PART IS NEVER COMPLETING 
![image](https://user-images.githubusercontent.com/90704569/180047299-bb43d3b3-9e9d-4c2e-8c14-fb020795882b.png)


AND AFTER GOING TO THE WEBSITE IT IS DIRECTING ME TO is-a.dev WEBSITE

**Comment by mtgsquad** [comment]
> THIS IS WHAT IT SHOWING THE DNS PART IS NEVER COMPLETING 
> ![image](https://user-images.githubusercontent.com/90704569/180047299-bb43d3b3-9e9d-4c2e-8c14-fb020795882b.png)
> 
> 
> AND AFTER GOING TO THE WEBSITE IT IS DIRECTING ME TO is-a.dev WEBSITE

Dude, you need to learn to chill, this is a free service and you are not entitled to it, you need to chill.

**Comment by mtgsquad** [comment]
And the DNS check is not our issue, it is an issue with GitHub, and second, clear your cache, the DNS may be propagated by know

**Comment by omxpro** [comment]
Fun fact: it works for me

![Screenshot_20220721-055336_Brave](https://user-images.githubusercontent.com/69719569/180104327-38421119-8d68-44e9-b344-8035418beb9d.png)

**Comment by WilliamDavidHarrison** [comment]
> Fun fact: it works for me
> 
> ![Screenshot_20220721-055336_Brave](https://user-images.githubusercontent.com/69719569/180104327-38421119-8d68-44e9-b344-8035418beb9d.png)

I thought Coming Soon pages weren't allowed

**Comment by omxpro** [comment]
> > Fun fact: it works for me
> > ![Screenshot_20220721-055336_Brave](https://user-images.githubusercontent.com/69719569/180104327-38421119-8d68-44e9-b344-8035418beb9d.png)
> 
> I thought Coming Soon pages weren't allowed

His pr was merged so idk if that's a rule anymore

**Comment by mtgsquad** [comment]
> > Fun fact: it works for me
> > 
> > ![Screenshot_20220721-055336_Brave](https://user-images.githubusercontent.com/69719569/180104327-38421119-8d68-44e9-b344-8035418beb9d.png)
> 
> I thought Coming Soon pages weren't allowed

Yeah, but if it's merged already there's no point.
