### ISSUE TITLE
Beta registration requires access to *private* repositories?

### ISSUE THREAD

**Issue by ofersadan85** [is-a-dev/register#2925]
This seems like a huge security risk on everyone who joins through the beta. Why is that needed?

**Comment by WilliamDavidHarrison** [comment]
@ofersadan85 I work on the beta project. Only the people that actually make the beta have access to the private repo.

**Comment by omxpro** [comment]
> This seems like a huge security risk on everyone who joins through the beta. Why is that needed?

Look i am not a GitHub expert so i don't know if what I am saying is right. But i don't think there is a permission that gives access to only public repo's. Correct me if i am wrong.

**Comment by omxpro** [comment]
And what William said is in fact true

**Comment by mtgsquad** [comment]
> > This seems like a huge security risk on everyone who joins through the beta. Why is that needed?
> 
> Look i am not a GitHub expert so i don't know if what I am saying is right. But i don't think there is a permission that gives access to only public repo's. Correct me if i am wrong.

You are correct. There is no specific scope for public repo

**Comment by MouseMoosz** [comment]
> > This seems like a huge security risk on everyone who joins through the beta. Why is that needed?
> 
> Look i am not a GitHub expert so i don't know if what I am saying is right. But i don't think there is a permission that gives access to only public repo's. Correct me if i am wrong.

GitHub has a scope [`public_repo`](https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps) which allows access to public repositories of a user, including read and write access.

**Comment by omxpro** [comment]
> > > This seems like a huge security risk on everyone who joins through the beta. Why is that needed?
> > 
> > 
> > Look i am not a GitHub expert so i don't know if what I am saying is right. But i don't think there is a permission that gives access to only public repo's. Correct me if i am wrong.
> 
> GitHub has a scope [`public_repo`](https://docs.github.com/en/developers/apps/building-oauth-apps/scopes-for-oauth-apps) which allows access to public repositories of a user, including read and write access.

That's in fact correct.

![Screenshot_20220721-164009_Brave](https://user-images.githubusercontent.com/69719569/180200130-4c41e2af-423e-4640-8b96-a6beb88e016c.png)

**Comment by ofersadan85** [comment]
I guess my question is why are repos needed at all? It would surely be enough to get just the login info (email and such) just like any other login through github allows. Write access to public repos is also a huge security risk.

> Only the people that actually make the beta have access to the private repo

With all due respect, I'm sure that the team is highly credible, but this is too much trust to put in strangers. Any strangers.

**Comment by WilliamDavidHarrison** [comment]
@ofersadan85 It is a team of 5, also I'm pretty sure only @mtgsquad and @andrewstech have access to the login details, also it's sign in with GitHub, so no passwords required.

**Comment by omxpro** [comment]
> I guess my question is why are repos needed at all? It would surely be enough to get just the login info (email and such) just like any other login through github allows. Write access to public repos is also a huge security risk.
> 
> > Only the people that actually make the beta have access to the private repo
> 
> With all due respect, I'm sure that the team is highly credible, but this is too much trust to put in strangers. Any strangers.

Repo's are needed to create a pr right? Or we can make a bot account like @andrewstech and make it open a pr for you.

**Comment by phenax** [comment]
> Beta registration requires access to *private* repositories?

@mtgsquad @andrewstech let's only use the public_repo scope as mentioned by @MouseMoosz 

> we can make a bot account

The reason we have it on github is we get an exact trail of who edited what. A github bot making the prs makes the blame logs worthless.

**Comment by andrewstech** [comment]
> > Beta registration requires access to _private_ repositories?
> 
> @mtgsquad @andrewstech let's only use the public_repo scope as mentioned by @MouseMoosz
> 
> > we can make a bot account
> 
> The reason we have it on github is we get an exact trail of who edited what. A github bot making the prs makes the blame logs worthless.

@ofersadan85 Thank you for bringing this to our attention. The changes have been made :)
![image](https://user-images.githubusercontent.com/45342431/180223023-b87369bb-c269-41cb-ab51-e415988b61f0.png)

**Comment by mtgsquad** [comment]
> I guess my question is why are repos needed at all? It would surely be enough to get just the login info (email and such) just like any other login through github allows. Write access to public repos is also a huge security risk.
> 
> > Only the people that actually make the beta have access to the private repo
> 
> With all due respect, I'm sure that the team is highly credible, but this is too much trust to put in strangers. Any strangers.

We cannot edit the register repo fork on your account without write access, and sadly we will not use any bot accounts as that will make operations and keeping track of domains considerably harder.

**Comment by ofersadan85** [comment]
Thank you all for the quick responses and fixes!
