### ISSUE TITLE
want to change the repository of domain

### ISSUE THREAD

**Issue by CYCNO** [is-a-dev/register#2941]
i wanna change the domain address and cname need help

**Comment by omxpro** [comment]
> i wanna change the domain address and cname need help

If you want to change it just edit your json file and edit the `"repo":` and `"CNAME"` feilds

**Comment by CYCNO** [comment]
but i did it with bot

**Comment by omxpro** [comment]
> but i did it with bot

What bot?

**Comment by andrewstech** [comment]
> > but i did it with bot
> 
> What bot?

BETA service

**Comment by MouseMoosz** [comment]
> but i did it with bot

Edit the `domains/subdomain.json` file and edit the values accordingly.
https://docs.is-a.dev

**Comment by omxpro** [comment]
Yep

**Comment by CYCNO** [comment]
> > but i did it with bot
> 
> Edit the `domains/subdomain.json` file and edit the values accordingly. https://docs.is-a.dev

i did it two times but and created pull request but you guys are not accepting that

**Comment by VaibhavDhiman0** [comment]
You closed the PRs yourself.

**Comment by CYCNO** [comment]
> You closed the PRs yourself.

i did it again can you now pls merge that

**Comment by CYCNO** [comment]
hi it's working on other devices but my pc didn,t showing that 

sorry for inconvenience,
and thanks for help,
CYCNO
