### ISSUE TITLE
Support: Github pages Enforce HTTPS disabled

### ISSUE THREAD

**Issue by taqnar** [is-a-dev/register#298]
Your domain name: https://muzammil.is-a.dev/

repo used for github pages
https://github.com/taqnar/taqnar.github.io

I had updated the CNAME to muzammil.is-a.dev in the repo settings of taqnar.github.io
I also checked before adding CNAME whether the site is running properly, at that time it ran smoothly and it also have https

But when I added CNAME 
It shows 3 steps to complete and stuck at the first one
Showing Certificate Request Error,
also the ENFORCE HTTPS is in disabled format
and mentioned to wait for 24 hours down there

Even after more than a day, it's not got progressed

When clicking on http://muzammil.is-a.dev/ it shows privacy error

Please Help to solve this issue

I am attaching the screenshot of the error
![Screenshot from 2020-10-17 23-04-17](https://user-images.githubusercontent.com/45489799/96349558-11a0f280-10ce-11eb-83f9-6d67127a6deb.png)

**Comment by phenax** [comment]
Try clearing the custom domain input and saving it. Then add the domain again and save it.

**Comment by taqnar** [comment]
@phenax I tried that way also but it doesn't work

**Comment by phenax** [comment]
Weird. Not sure whats happening here. Give it a day after changing it and check again.

**Comment by taqnar** [comment]
No Progress Still stuck at the first stage

**Comment by HeroGamers** [comment]
I am having this exact same issue on my subdomain, `marcus.is-a.dev`, no idea why this happens...
![image](https://user-images.githubusercontent.com/15278940/96410275-f4137c00-11e6-11eb-8e1b-61961d65fee0.png)

**Comment by phenax** [comment]
@HeroGamers @taqnar, [Create a ticket with the github support team](https://support.github.com/contact) with the screenshots. Seems like issueing certificate takes some time but you can speed it up if you create a ticket requesting it.

**Comment by phenax** [comment]
@taqnar, can you confirm for me if you filled the "Custom domain" input before the subdomain was published? I have a feeling this could be related to some kind of cache that delays this.

**Comment by HeroGamers** [comment]
@phenax just as I was filling out the ticket with the support ticket, I refreshed the page, and was that it had issued the certificate successfully!
Though, now it tells me this, after enforcing HTTPS:
![image](https://user-images.githubusercontent.com/15278940/96431450-ce48a000-1203-11eb-8239-d26f3ab9ad51.png)

**Comment by phenax** [comment]
@HeroGamers, I asked you to rename your repo to `herogamers.github.io`. Seems like you're configuring the wrong repo.

**Comment by HeroGamers** [comment]
@phenax I have another repo with that name - according to what I've found out on GitHub and other places, it should be possible to add a custom domain to GitHub Project pages as well. [This GitHub article](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site) doesn't use a GitHub user page for the custom domain, but a project page. It also says that, if using a repository that is not your github.io repository:
> The CNAME file should always point to <user>.github.io or <organization>.github.io, excluding the repository name.

Other places that talk about custom domains on GitHub **Project** pages are [this stackoverflow answer](https://stackoverflow.com/a/9123911), [this Medium blogpost](https://medium.com/@hossainkhan/using-custom-domain-for-github-pages-86b303d3918a) and [this other blogpost](https://zararah.net/blog/2015/12/27/redirecting-project-page-domain/).
The last two blogposts, seem to have the CNAME records to `[username].github.io.` (with a dot) and not `[username].github.io` though, which might be the change?
What do you think? I mean, it should be possible to use the Project page with the custom domain?

**Comment by HeroGamers** [comment]
It works now!

**Comment by phenax** [comment]
Using a project page works but as it wasn't working for you, I assumed it must be because of the repo. Glad to see everything worked out.

@taqnar let me know how it goes for you

**Comment by taqnar** [comment]
@phenax   I filled out the ticket and refreshed the page, got the certificate correctly
and now I am able to use on https successfully
Thank you for your service
:)
