### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by honeybadger4768** [is-a-dev/register#3070]
Your domain name: furkancetinkaya.is-a.dev

Hello, I using cloudflare pages for react app deploy but when I enter my domain I get ERR_SSL_VERSION_OR_CIPHER_MISMATCH error. Do I need to make a setting on Cloudflare pages?

**Comment by VaibhavSys** [comment]
Have you added it as a custom domain in cloudfare pages settings?
Please send a screenshot of the settings on that cloudfare pages site.

**Comment by honeybadger4768** [comment]
Oh, thank you. I don't know it. My domain is running now. Thank you
