### ISSUE TITLE
domain-name.is-a.dev redirected you too many times

### ISSUE THREAD

**Issue by gxlpes** [is-a-dev/register#3092]
Whenever I try to enter my domain, I keep getting this message from the browser. I already waited more than a day to let GitHub Pages settings setup all the DNS and HTTPS but I still don't see the website.

I used the beta website version to make my pull request.

My cookies were already cleared but still nothing loaded.

https://github.com/is-a-dev/register/pull/3058

```
This page isn’t working
gxlpes.is-a.dev redirected you too many times.
[Try clearing your cookies](https://support.google.com/chrome?p=rl_error&hl=en-US).
ERR_TOO_MANY_REDIRECTS
```

**Comment by VaibhavSys** [comment]
Use a CNAME record.
Learn more about setting up GitHub Pages with is-a-dev [here](https://is-a.dev/docs/github_pages/)

**Comment by VaibhavSys** [comment]
@gxlpes 
If the issue is resolved, please close this issue.

**Comment by gxlpes** [comment]
> @gxlpes If the issue is resolved, please close this issue.

I submitted a PR with my changes to see if the issue is resolved.
