### ISSUE TITLE
Whats your question

### ISSUE THREAD

**Issue by Nexzon** [is-a-dev/register#3102]
I wanted to know, how many .is-a.dev domains can i request. And can i rename my domains?

**Comment by VaibhavSys** [comment]
You can rename your domains.
There isn't a certain limit on the amount of subdomains you can request as long as they are being used for a purpose.

**Comment by Nexzon** [comment]
> You can rename your domains. There isn't a certain limit on the amount of subdomains you can request as long as they are being used for a purpose.

Alright, thanks bro. I rename in domain-name.json right?

**Comment by VaibhavSys** [comment]
> > You can rename your domains. There isn't a certain limit on the amount of subdomains you can request as long as they are being used for a purpose.
> 
> I rename in domain-name.json right?

Yes.

**Comment by Nexzon** [comment]
> > > You can rename your domains. There isn't a certain limit on the amount of subdomains you can request as long as they are being used for a purpose.
> > 
> > 
> > I rename in domain-name.json right?
> 
> Yes.

Alr, but its src we can't edit / change if i read correctly

**Comment by VaibhavSys** [comment]
> > > > You can rename your domains. There isn't a certain limit on the amount of subdomains you can request as long as they are being used for a purpose.
> > > 
> > > 
> > > I rename in domain-name.json right?
> > 
> > 
> > Yes.
> 
> Alr, but its src we can't edit / change if i read correctly

What do you mean?
You can edit the file inside `domains/domain.json`

**Comment by Nexzon** [comment]
> > > > > You can rename your domains. There isn't a certain limit on the amount of subdomains you can request as long as they are being used for a purpose.
> > > > 
> > > > 
> > > > I rename in domain-name.json right?
> > > 
> > > 
> > > Yes.
> > 
> > 
> > Alr, but its src we can't edit / change if i read correctly
> 
> What do you mean? You can edit the file inside `domains/domain.json`

Editing is source code, my website for example is X.is-a.dev.
If i made a typo i wanted to fix, would editing my X.github.io edit the thing? or just readd it in settigs tab

**Comment by VaibhavSys** [comment]
If you made a typo in `domain.is-a.dev`, you can submit a PR renaming `domains/domain.json` and then re-add it in GitHub pages settings tab or with whatever host you are using.
You would need to edit the CNAME record if you changed the username of the account the repository was on (Github Pages only).

**Comment by Nexzon** [comment]
> If you made a typo in `domain.is-a.dev`, you can submit a PR renaming `domains/domain.json` and then re-add it in GitHub pages settings tab or with whatever host you are using. You would need to edit the CNAME record if you changed the username of the account the repository was on (Github Pages only).

alr

**Comment by VaibhavSys** [comment]
> > If you made a typo in `domain.is-a.dev`, you can submit a PR renaming `domains/domain.json` and then re-add it in GitHub pages settings tab or with whatever host you are using. You would need to edit the CNAME record if you changed the username of the account the repository was on (Github Pages only).
> 
> alr

If you do not have any more queries then please consider closing this issue.
