### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by TheGeekDex** [is-a-dev/register#3116]
Your domain name: dex.is-a.dev

Explain any issues you are facing
Domain is not working

**Comment by VaibhavSys** [comment]
"Domain is not working" doesn't tell us much.

As it looks like, the host hasn't provided a SSL certificate for the subdomain, you will need to add this subdomain to the SSL certificate. Search up guides for that according to your host.

**Comment by mtgsquad** [comment]
@TheGeekDex

**Comment by TerraPlayz** [comment]
@TheGeekDex

**Comment by TheGeekDex** [comment]
I figured out how to create certificate but i need to provide A record for that, I created a pull request for that. Have a look.
