### ISSUE TITLE
Whenever you go to https://what.is-a.dev/ on mobile it redirects to to https://www.is-a.dev/ , but when you do it on desktop it works perfectly fine.

### ISSUE THREAD

**Issue by What-Question-Mark** [is-a-dev/register#3324]
### Expected outcome

It would stay at https://what.is-a.dev/

### Observed outcome

It redirects you to https://www.is-a.dev/

**Comment by phenax** [comment]
This is due to browser cache. Please clear browser data on mobile.

![part-2022_08_31_10_04_49](https://user-images.githubusercontent.com/11407672/187593550-ad4f50a4-66c6-43f4-8526-ef3f0c326365.jpg)
