### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by srhr17** [is-a-dev/register#335]
Your domain name: srhr17.is-a.dev (srhr17.github.io)

Explain any issues you are facing
![image](https://user-images.githubusercontent.com/46963593/96669343-a4fe5000-137a-11eb-91e5-52c3652e84b7.png)
 
I am getting error while adding the custom domain field

**Comment by phenax** [comment]
Your pr (#216) registered `srihari.is-a.dev` not `srhr17.is-a.dev`
