### ISSUE TITLE
GitHub now requires domain verfication to be used in GitHub Pages

### ISSUE THREAD

**Issue by VaibhavSys** [is-a-dev/register#3385]
GitHub is now requiring the domain to be verified using a TXT record to be used as a custom domain in GitHub Pages.
Documentation for this can be found [here](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages).

This doesn't seem to affect existing domains, this means that subdomains from is-a.dev cannot be used for GitHub Pages.

Refer: https://github.blog/changelog/2021-11-01-domain-verification-for-github-pages/

(added by @MaskDuck : if you need alternatives you can try [cloudflare pages](https://pages.cloudflare.com)\)

**Comment by VaibhavSys** [comment]
Related: #3386 #3384

**Comment by mtgsquad** [comment]
@VaibhavSys I am planning on writing an email to GitHub if there will be further ways for verification of domains

**Comment by phenax** [comment]
That is unfortunate. I think we can work around this by implementing a special record type for verification TXT. We'll also have to detect and convert github pages CNAME into A records for it to work.
Although this does create a problem with stale or even duplicate records since I don't think people will remove verification records after they've verified their subdomain. I think that's alright for now. If we run into issues, it'll be easy enough to spot and fix.

**Comment by mtgsquad** [comment]
> That is unfortunate. I think we can work around this by implementing a special record type for verification TXT. We'll also have to detect and convert github pages CNAME into A records for it to work.
> Although this does create a problem with stale or even duplicate records since I don't think anyone is going to remove verification records after they've verified their subdomain. I think that's alright for now. If we run into issues, it'll be easy enough to spot and fix.
> 
> @is-a-dev/maintainers, any other ideas for handling this?

Let's see if TXT is the only way to verify, if they do something like the Google search console does, where you can upload a file to your site, or you can add a meta tag to verify, if there are ways like that it may be possible to not use TXT. Also I believe that they want root verification? I'll check it out with my own domain (Molai.dev) and try to create a pages site that uses a subdomain on that.

**Comment by mtgsquad** [comment]
Alright, I see. They want a TXT record not on the subdomain itself but on `_github-pages-challenge-USERNAME.SUBDOMAIN.domain.tld`

**Comment by mtgsquad** [comment]
We could allow users to add _'s to their files, and this would allow them to create two files one for the subdomain itself with it's records, and one for this GitHub pages verification? We've already seen a few people do that.

**Comment by AlmostSuspense** [comment]
is there an estimate on approx when this issue can be resolved?

**Comment by KenWuqianghao** [comment]
facing the same issue right now

**Comment by mtgsquad** [comment]
> is there an estimate on approx when this issue can be resolved?

Probably by this Friday.

**Comment by mtgsquad** [comment]
Alright, after some further deliberations we've decided to delay this up to monday. Sorry for any inconvenience. For a temporary solution, consider moving to [Cloudflare Pages](https://pages.dev)

**Comment by ConorSheehan1** [comment]
> This doesn't seem to affect existing domains

Just BTW, I hit this issue after pushing a new commit to github pages. I'd already registered is-a.dev a few weeks ago and it was working, but getting an error about verification now.
