### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by Nzii3** [is-a-dev/register#3386]
Your domain name:
`nziie.is-a.dev`
Explain any issues you are facing
In my pull request, #3382 an automated system said my changes would show within 24 hours but the pull request wasn’t merged.

**Comment by andrewstech** [comment]
> Your domain name: `nziie.is-a.dev` Explain any issues you are facing In my pull request, #3382 an automated system said my changes would show within 24 hours but the pull request wasn’t merged.

Hi so  I'm sorry the bot sent the message. We are delaying all PR's that use GitHub pages as GitHub has implemented verification changes.

**Comment by Nzii3** [comment]
Dude, my website can't even be reached. How long are they being delayed?

**Comment by Nzii3** [comment]
And what are the verification changes?

**Comment by tachibana-shin** [comment]
> And what are the verification changes?

https://github.com/is-a-dev/register/issues/3384

**Comment by WilliamDavidHarrison** [comment]
Fixed: #3445

**Comment by Nzii3** [comment]
> Fixed: #3445

@WilliamDavidHarrison so what do I do to fix it?

**Comment by WilliamDavidHarrison** [comment]
> > Fixed: #3445
> 
> @WilliamDavidHarrison so what do I do to fix it?

Create a CNAME file with the content "nziie.is-a.dev"

**Comment by Nzii3** [comment]
Already done, but I think my PR needs to be merged: #3382

**Comment by WilliamDavidHarrison** [comment]
> Already done, but I think my PR needs to be merged: #3382

Yes it does.
