### ISSUE TITLE
Feedback/suggestion: Allow organisation verification

### ISSUE THREAD

**Issue by WilliamDavidHarrison** [is-a-dev/register#3452]
Allow GitHub organisations to verify their is-a.dev domain for GitHub Pages and maybe also allow organisations to verify the domain as well in the Verified and Approved Domains tab.

**Comment by phenax** [comment]
Is the process different for org and user? If so can you add links to docs related to it here?

**Comment by VaibhavSys** [comment]
> Is the process different for org and user? If so can you add links to docs related to it here?

Its almost the same.
[Docs](https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-organization-settings/verifying-or-approving-a-domain-for-your-organization)

**Comment by WilliamDavidHarrison** [comment]
> Is the process different for org and user? If so can you add links to docs related to it here?

To verify that you own a domain for organisations (this: [https://i.williamharrison.xyz/805a16e1](https://i.williamharrison.xyz/805a16e1)): _github-challenge-ORGNAME-org.subdomain.is-a.dev

For GitHub Pages it is the same for organisations and users,
