### ISSUE TITLE
What bug did you encounter?

### ISSUE THREAD

**Issue by leecheeyong** [is-a-dev/register#3511]
### Expected outcome
suppose to work as it should

### Observed outcome
got the 404 error, probably something went wrong with the DNS, anyways some of my subdomains like `garden.is-a.dev`, `short.is-a.dev`, `ink.is-a.dev` and many more, I think this wasn't just an issue of mine because I realized some other user's subdomain also didn't work

**Comment by tachibana-shin** [comment]
the same error I received notice that `is-a.dev` is being maintained

**Comment by phenax** [comment]
Yes. We had an issue with our zone. We are currently running a migration to fix all the affected sub-domains which can take up to an hour. I'll update add an update here when that is done.

**Comment by phenax** [comment]
Update: The migration has been completed and the sub-domains you've listed are working now on my end. Try clearing your browser cache if it doesn't work now.

**Comment by tachibana-shin** [comment]
working!

**Comment by leecheeyong** [comment]
thanks
