### ISSUE TITLE
NET::ERR_CERT_COMMON_NAME_INVALID with cname record

### ISSUE THREAD

**Issue by the-garlic-os** [is-a-dev/register#355]
My domain name is https://garlic-os.is-a.dev/ (JSON entry: [https://gith​ub.com/is-a-dev/register/blob/main/domains/garlic-os.json](https://github.com/is-a-dev/register/blob/main/domains/garlic-os.json))

I am using the [template for a GitHub Pages page](https://github.com/is-a-dev/register/blob/main/API.md#for-github-pages-users) and I get a NET::ERR_CERT_COMMON_NAME_INVALID error when I try to connect to my subdomain. I am using a cname record.

**Comment by phenax** [comment]
@the-garlic-os
You should read the [docs for github pages](https://github.com/is-a-dev/register/blob/main/API.md#for-github-pages-users). Seems like you haven't configured your repo correctly.

**Comment by the-garlic-os** [comment]
I don't know what you mean. It's the exact same as in the example, but with my information filled in.
![image](https://user-images.githubusercontent.com/14845347/97094102-4b668180-1617-11eb-8532-595bf8b76ef7.png)

**Comment by phenax** [comment]
Read the steps below the example

**Comment by the-garlic-os** [comment]
Woo hoo! A new error! We're getting somewhere. The GitHub Pages section of my site repo's settings says: "Your site's DNS settings are using a custom subdomain, the-garlic-os.is-a.dev, that's set up as an A record. We recommend you change this to a CNAME record pointing at [YOUR USERNAME].github.io."

GitHub apparently sees the-garlic-os.is-a.dev as an A record instead of a CNAME record. That's odd considering my JSON entry sets a CNAME record and not an A record.

**Comment by phenax** [comment]
The subdomain you registered is `garlic-os.is-a.dev`. It should start working when you remove the `the` from the gh pages custom domains settings

**Comment by phenax** [comment]
Your record has been published and is reflecting. Please check the `Ensure HTTPS` checkbox in your github repo settings. Closing this issue for now. You can re-open it if you are still facing issues.
