### ISSUE TITLE
All subdomains?

### ISSUE THREAD

**Issue by cfpwastaken** [is-a-dev/register#3695]
Can I register ALL subdomains for my domain?
Like a *.blah.json?

**Comment by WilliamDavidHarrison** [comment]
No, you can't unfortunately.

**Comment by cfpwastaken** [comment]
dang, will this ever be added in the future?

**Comment by phenax** [comment]
@cfpwastaken, we don't have plans for supporting that feature. Could you explain your use-case?

**Comment by cfpwastaken** [comment]
I change stuff around on my server very often, so having to wait for yet another subdomain to get approved is annoying. There are also some private services that would get a subdomain, which don't have to be listed here in this repository.

**Comment by WilliamDavidHarrison** [comment]
> I change stuff around on my server very often, so having to wait for yet another subdomain to get approved is annoying. There are also some private services that would get a subdomain, which don't have to be listed here in this repository.

For security, I believe there has to be a seperate file for each domain.

**Comment by phenax** [comment]
> For security, I believe there has to be a seperate file for each domain.

Yes. To be on the safer side in terms of contents being served though us, we have to review every new subdomain. Closing this issue since we don't plan on implementing this.
