### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by PokedArmory** [is-a-dev/register#3770]
# Your domain name:   poked.is-a.dev

### is.a.dev says the site is not secure, but my github site works just fine.

Is-a.dev:
<img src="https://user-images.githubusercontent.com/101025174/197442936-ceb15554-4733-4e6f-8bf4-e72afb0ac8a1.png" width=30% height=30%>

GitHub:
<img src="https://user-images.githubusercontent.com/101025174/197442868-a26b58d1-d7fe-432f-ad3c-b0e60e83366a.png" width=30% height=30%>

**Comment by WilliamDavidHarrison** [comment]
@PokedArmory Have you enabled `Enforce HTTPS` and added a file called `CNAME` to the repo?
