### ISSUE TITLE
Privacy Error

### ISSUE THREAD

**Issue by SageDotExe** [is-a-dev/register#3805]
How do i fix this? ![image](https://user-images.githubusercontent.com/88823085/198507568-07afcca3-688b-4f0d-a283-aeb8f90cc89f.png)

**Comment by VaibhavSys** [comment]
Configure HTTPS on your web hosting
Guides for some hostings can be found (here)[https://is-a.dev/docs].

**Comment by SageDotExe** [comment]
Thanks. it seems to be working now :)
