### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by akshayans** [is-a-dev/register#3819]
Your domain name:
https://akshayan.is-a.dev
Explain any issues you are facing

ERR_SSL_VERSION_OR_CIPHER_MISMATCH.
I get this error when going to my site.

**Comment by WilliamDavidHarrison** [comment]
Try clearing your cache and enabling `Enforce HTTPS`

**Comment by akshayans** [comment]
HTTPS in Cloudflare is already enabled. By the way, this is pointing to a subdomain on my main domain, not GitHub Pages or CloudFlare Pages.

**Comment by Bad-Boy-Codes** [comment]
update cloudfare version maybe, or maybe reset it once and try again

**Comment by akshayans** [comment]
I have closed this as I will move to GitHub Pages.
