### ISSUE TITLE
Why this is no longer count as a participation to Hacktoberfest ?

### ISSUE THREAD

**Issue by B45i** [is-a-dev/register#389]
Earlier commit to this repo was counting as a contribution to hacktoberfest, now its no longer showing as valid.
I think the tag was removed. What was the reason for that?.
I was counting on this as my last PR, now the fest is over and all 3 contributions went to waste. 

![image](https://user-images.githubusercontent.com/12771709/97805072-d7ad2000-1c79-11eb-82fa-668bcb160c07.png)

**Comment by phenax** [comment]
The hacktober tag was removed from the repo. I've added it back.

**Comment by B45i** [comment]
@phenax 
This still doesn't reflect in the hacktober fest page 

![image](https://user-images.githubusercontent.com/12771709/97950275-6033d980-1dbc-11eb-8542-9393e636af64.png)

**Comment by MarkusJx** [comment]
@B45i 
The tag was re-added on first of November, which is too late, for this to count - you're out of luck. This is obviously a fault of the Hacktoberfest Team for not clearly stating how this opt-in system really works. The only way you can know that the repos need to keep the tag through 15th of November for all PRs to count is by following the chat on Discord - what a shame.
