### ISSUE TITLE
Support for NS Records?

### ISSUE THREAD

**Issue by rubybb** [is-a-dev/register#394]
I'm curious if there is support for nameserver records.

**Comment by phenax** [comment]
There is no support for NS records since they are not supported in the underlying api this service uses.

**Comment by rubybb** [comment]
And is there a reason, we can't support them?

**Comment by phenax** [comment]
The underlying api that the service uses, doesn't support the NS record type. For most cases, an A record alternative is usually present which can be used here

**Comment by phenax** [comment]
Closing this issue for now as we can't add support for NS at the moment.
