### ISSUE TITLE
how to make sub subdomain

### ISSUE THREAD

**Issue by CYCNO** [is-a-dev/register#3972]
is there any way to make sub subdomain in is-a.dev
 like i have a sub domain name  so can i make `developer.example.is-a.dev` out of that sub domain 
like `example.is-a.dev`

**Comment by WilliamDavidHarrison** [comment]
> is there any way to make sub subdomain in is-a.dev like i have a sub domain name so can i make `developer.example.is-a.dev` out of that sub domain like `example.is-a.dev`

If you own the subdomain `example.is-a.dev` you can get `blog.example.is-a.dev`.

Just create a file called `blog.example.json` with the required records, etc and that will register `blog.example.is-a.dev`

**Comment by CYCNO** [comment]
@WilliamDavidHarrison Thanks
