### ISSUE TITLE
GitHub Pages InvalidARecordError

### ISSUE THREAD

**Issue by garlic-os** [is-a-dev/register#4000]
My domain name: https://garlic-os.is-a.dev/

I recently changed my username from `the-garlic-os` to `garlic-os` and updated my is-a.dev record accordingly (https://github.com/is-a-dev/register/pull/3953). After the pull request was accepted, I deleted the old subdomain in my github.io site's settings, then I went to register to the new one and got this error.
![image](https://user-images.githubusercontent.com/14845347/202866730-12975c48-edc5-4f84-9274-6df948b71a1c.png)

Did I do something wrong?

This is my record for reference:
```json
{
    "description": "garlicOS®'s is-a.dev domain",
    "repo": "https://github.com/garlic-os/garlic-os.github.io",
    "owner": {
        "username": "garlic-os",
        "email": "sisdfk@gmail.com"
    },
    "record": {
        "CNAME": "garlic-os.github.io"
    }
}
```

Thanks for your help.

**Comment by VaibhavSys** [comment]
#3953 is not merged yet. Helpers do not have write permissions to the repository, only maintainers can merge PRs.

**Comment by WilliamDavidHarrison** [comment]
What @VaibhavSys said, I may have approved the PR, it doesn't mean the PR has been merged.

**Comment by garlic-os** [comment]
OK, I see. My mistake. Thanks folks!
