### ISSUE TITLE
Creating a subdomain of .is-a.dev domain

### ISSUE THREAD

**Issue by Nzii3** [is-a-dev/register#4029]
How can I create a subdomain of my `is-a.dev` domain? I wanting to make `cdn.nziie.is-a.dev` domain.

**Comment by WilliamDavidHarrison** [comment]
@Nzii3 Just create a file called `cdn.nziie.json` and add the needed records, etc.

**Comment by SemantCodes** [comment]
> How can I create a subdomain of my `is-a.dev` domain? I wanting to make `cdn.nziie.is-a.dev` domain.

it already works

**Comment by Nzii3** [comment]
> @Nzii3 Just create a file called `cdn.nziie.json` and add the needed records, etc.

@WilliamDavidHarrison how would I format the file and what would be the records?

**Comment by Nzii3** [comment]
And do I add it to my repo or make a pr for this repo?

**Comment by WilliamDavidHarrison** [comment]
> > @Nzii3 Just create a file called `cdn.nziie.json` and add the needed records, etc.
> 
> @WilliamDavidHarrison how would I format the file and what would be the records?

How you normally do in your main file.

**Comment by VaibhavSys** [comment]
This may help: https://www.is-a.dev/docs/domain_structure/

**Comment by Nzii3** [comment]
@WilliamDavidHarrison Nvm, I submitted a PR and you’re the only one who reviewed it and it’s kind of far down in the PRs list so it will take a while for another review to actually “implement” it :/

**Comment by Nzii3** [comment]
#4049
