### ISSUE TITLE
Unsupported protocol? HUH?

### ISSUE THREAD

**Issue by snaildos** [is-a-dev/register#403]
### Expected outcome
I get my website

### Observed outcome
UNSUPPORTED PROTOCOL

**Comment by phenax** [comment]
You haven't configured cloudflare correctly (https://github.com/is-a-dev/register/pull/197#issuecomment-707873357). If you don't want to spend time configuring this, you can use a URL redirection instead of CNAME.

```
$ dig +noall +answer snaildos.is-a.dev
snaildos.is-a.dev.      10453   IN      CNAME   snaildos.tk.
snaildos.tk.            243     IN      A       104.28.12.23
snaildos.tk.            243     IN      A       172.67.129.106
snaildos.tk.            243     IN      A       104.28.13.23
```
As you can see the dns records are correct.
