### ISSUE TITLE
Feedback/suggestion

### ISSUE THREAD

**Issue by s3mant** [is-a-dev/register#4042]
What about adding custom emails
for example some domain websites support email forwarding from their own servers

suggesting this becouse improvmx has many errors now and is very slow

**Comment by WilliamDavidHarrison** [comment]
@SemantCodes What do you mean?

Like users getting an email like `example@is-a.dev` or like we host an email forwarding service?

**Comment by VaibhavSys** [comment]
> What about adding custom emails for example some domain websites support email forwarding from their own servers
> 
> suggesting this becouse improvmx has many errors now and is very slow

ImprovMX doesn't throw errors if setup properly, we can help you out with that. And regarding slow, I don't think its slow however you can get their premium plan or use another email forwarding service or a email hosting service. There are many good free ones too.

**Comment by SemantCodes** [comment]
> @SemantCodes What do you mean?
> 
> Like users getting an email like `example@is-a.dev` or like we host an email forwarding service?

like some websites host their own email forwarding server

**Comment by SemantCodes** [comment]
> > What about adding custom emails for example some domain websites support email forwarding from their own servers
> > suggesting this becouse improvmx has many errors now and is very slow
> 
> ImprovMX doesn't throw errors if setup properly, we can help you out with that. And regarding slow, I don't think its slow however you can get their premium plan or use another email forwarding service or a email hosting service. There are many good free ones too.

I can't seem to find any other email forwarding service for free tho,

**Comment by VaibhavSys** [comment]
> > > What about adding custom emails for example some domain websites support email forwarding from their own servers
> > > suggesting this becouse improvmx has many errors now and is very slow
> > 
> > 
> > ImprovMX doesn't throw errors if setup properly, we can help you out with that. And regarding slow, I don't think its slow however you can get their premium plan or use another email forwarding service or a email hosting service. There are many good free ones too.
> 
> I can't seem to find any other email forwarding service for free tho,

[This](https://free-for.dev/#/?id=email) should help.

**Comment by WilliamDavidHarrison** [comment]
I don't think a custom forwarding server should be introduced as this could get expensive and most people use ImprovMX anyway, so there would be no reason to have one.

**Comment by SemantCodes** [comment]
> I don't think a custom forwarding server should be introduced as this could get expensive and most people use ImprovMX anyway, so there would be no reason to have one.

oh i see.
