### ISSUE TITLE
Domain not loading website

### ISSUE THREAD

**Issue by JoshAtticus** [is-a-dev/register#4206]
Your domain name: joshatticus.is-a.dev

Explain any issues you are facing
Domain redirects instead of leading to website.

**Comment by WilliamDavidHarrison** [comment]
@JoshAtticus Please clear your cache. It works fine for me.
![image](https://user-images.githubusercontent.com/87287585/208232785-d267d86f-f099-4dbd-9df2-4ba53758c051.png)

**Comment by JoshAtticus** [comment]
> @JoshAtticus Please clear your cache. It works fine for me.
> 
> ![image](https://user-images.githubusercontent.com/87287585/208232785-d267d86f-f099-4dbd-9df2-4ba53758c051.png)
> 
> 

Oh it's working now, thanks
