### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by Dheirya** [is-a-dev/register#4317]
**Your domain name:** https://dheirya.is-a.dev

**Explain any issues you are facing**
The site https://dheirya.is-a.dev is not loading https://dheirya.pages.dev and I keep getting a "can't establish secure connection" error.

**Comment by WilliamDavidHarrison** [comment]
Have you setup your is-a.dev domain on your Cloudflare Pages project?

**Comment by Dheirya** [comment]
Oh my bad... forgot that step, thanks!
