### ISSUE TITLE
Support - site insecure

### ISSUE THREAD

**Issue by ChaoticChaosTheGreat** [is-a-dev/register#4384]
Your domain name: chaotic.is-a.dev

Explain any issues you are facing
Whenever I try to load a page it says 
<img width="717" alt="Screenshot 2023-01-03 at 7 46 45 AM" src="https://user-images.githubusercontent.com/62819056/210391685-6b0464f3-4218-4a5b-93a4-0efa87e20f57.png">
I'm not sure since I'm not using any kind of hosting service besides just pointing the domain to my github.io (chaoticchaosthegreat.github.io)

**Comment by TerraPlayz** [comment]
Hello there

**Comment by TerraPlayz** [comment]
was your domain accepted recently within 24 hours?

**Comment by TerraPlayz** [comment]
I clicked on the website and it redirects to is-a.dev

**Comment by TerraPlayz** [comment]
^^

**Comment by SX-9** [comment]
Did you configure your host to use the domain

**Comment by TerraPlayz** [comment]
I can confirm it works for me too.

**Comment by SX-9** [comment]
> > Did you configure your host to use the domain
> 
> It's using GitHub pages and when clicked on website it redirects to is-a.dev so yes he/she did.

Send me the screenshot of the github pages settings @ChaoticChaosTheGreat

**Comment by TerraPlayz** [comment]
> > > Did you configure your host to use the domain
> > 
> > 
> > It's using GitHub pages and when clicked on website it redirects to is-a.dev so yes he/she did.
> 
> Send me the screenshot of the github pages settings @ChaoticChaosTheGreat

The domain works bro no need.

**Comment by SX-9** [comment]
> > > > Did you configure your host to use the domain
> > > 
> > > 
> > > It's using GitHub pages and when clicked on website it redirects to is-a.dev so yes he/she did.
> > 
> > Send me the screenshot of the github pages settings @ChaoticChaosTheGreat
> 
> The domain works bro no need.

Just checking for error

**Comment by SX-9** [comment]
Nvm it works (im kinda stupid with networking stuff and dns things)
