### ISSUE TITLE
Error: Domain does not resolve with Github Pages

### ISSUE THREAD

**Issue by Elflanded** [is-a-dev/register#445]
After changes my records to a cname, github pages brought up this error.

![image](https://user-images.githubusercontent.com/49889930/101664373-c34b0880-3a19-11eb-87d4-91a1a57a771f.png)

**Comment by phenax** [comment]
Its probably due to cache. Remove the custom domain and hit save. Give it a few hours or so and then add it back.

**Comment by Elflanded** [comment]
Alright, thank you!

**Comment by Elflanded** [comment]
It works now.
