### ISSUE TITLE
Can I?

### ISSUE THREAD

**Issue by MaheshTheDeveloper** [is-a-dev/register#4642]
Can I get the role to contribute in this repo... I want to actively accept people registering the subdomain.

**Comment by WilliamDavidHarrison** [comment]
Hey @MaheshTheDeveloper,

You can help us by reviewing PRs and answering issues, but roles like Maintainer are hand selected.

**Comment by MaheshTheDeveloper** [comment]
I am ok with it as I am just starting in this repo.

**Comment by MaheshTheDeveloper** [comment]
Hey @WilliamDavidHarrison How can I accept pull requests...? & what your discord server

**Comment by WilliamDavidHarrison** [comment]
Ok, can I close this issue?

**Comment by WilliamDavidHarrison** [comment]
> Hey @WilliamDavidHarrison How can I accept pull requests...? & what your discord server

You can't merge but you can review.

**Comment by WilliamDavidHarrison** [comment]
https://discord.gg/DXdRgZAJHR

**Comment by MaheshTheDeveloper** [comment]
Ya Sure @WilliamDavidHarrison
