### ISSUE TITLE
Support: bbhc.is-a.dev 409 Conflict

### ISSUE THREAD

**Issue by thetayloredman** [is-a-dev/register#480]
Your domain name: bbhc.is-a.dev

Record: CNAME badboyhalocat.tk

What am I doing wrong?

```
$ curl -v bbhc.is-a.dev
*   Trying 2606:4700:3033::ac43:d0ad...
* TCP_NODELAY set
* Connected to bbhc.is-a.dev (2606:4700:3033::ac43:d0ad) port 80 (#0)
> GET / HTTP/1.1
> Host: bbhc.is-a.dev
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 409 Conflict
< Date: Mon, 04 Jan 2021 17:08:48 GMT
< Content-Type: text/plain; charset=UTF-8
< Content-Length: 16
< Connection: close
< X-Frame-Options: SAMEORIGIN
< Cache-Control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Expires: Thu, 01 Jan 1970 00:00:01 GMT
< Set-Cookie: __cfduid=db014d469628512cccad2e1d55681982e1609780128; expires=Wed, 03-Feb-21 17:08:48 GMT; path=/; domain=.bbhc.is-a.dev; HttpOnly; SameSite=Lax
< cf-request-id: 076ff882040001000079323000000001
< Server: cloudflare
< CF-RAY: 60c69049a8d30000-SJC
< 
* Closing connection 0
error code: 1001
```

**Comment by phenax** [comment]
I think you'll need to configure your cloudflare server to recognize the new subdomain.

**Comment by thetayloredman** [comment]
> I think you'll need to configure your cloudflare server to recognize the new subdomain.

Where do I do that?

**Comment by thetayloredman** [comment]
[Oh.](https://support.cloudflare.com/hc/en-us/articles/360029779472#error1001)

**Comment by phenax** [comment]
Let me know if you need any more help. You can close this issue if you've figured it out.

**Comment by thetayloredman** [comment]
Wait, so would I just do `CNAME` to `badboyhalocat.tk.cdn.cloudflare.net` or would this not be possible?

**Comment by phenax** [comment]
Yes. Create a PR with the changes and I'll merge it in

**Comment by thetayloredman** [comment]
#482

**Comment by phenax** [comment]
$ dig +noall +answer bbhc.is-a.dev
bbhc.is-a.dev.          1200    IN      CNAME   badboyhalocat.tk.cdn.cloudflare.net.
badboyhalocat.tk.cdn.cloudflare.net. 69 IN A    104.27.172.70
badboyhalocat.tk.cdn.cloudflare.net. 69 IN A    104.27.173.70
badboyhalocat.tk.cdn.cloudflare.net. 69 IN A    172.67.208.173

**Comment by thetayloredman** [comment]
Okay so I think it's because we're trying to CNAME to a cloudflare site from a non-cloudflare domain.

I'm going to add `bbhc.is-a.dev` as a supported Virtual Host to my web server, and then we can just do a normal A to my actual web server. #493
