### ISSUE TITLE
Recent GitHub Pages deploy caused is-a.dev to fail with 404

### ISSUE THREAD

**Issue by D-Pow** [is-a-dev/register#485]
### Expected outcome
Traversing to https://devon.is-a.dev/ results in a normal website and you can see the contents.

### Observed outcome
Traversing to https://devon.is-a.dev/ results in a 404 Not Found error.

FWIW I did not change any settings to the repository nor to core files of the webapp, I simply changed the service worker. Thus, any problems present are not likely to be caused by me.

**Comment by phenax** [comment]
The CNAME file seems to be incorrect. Changing this to `devon.is-a.dev` should fix the issue - https://github.com/D-Pow/d-pow.github.io/blob/master/CNAME

**Comment by D-Pow** [comment]
Huh, seems that the repo > `Settings` > `GitHub Pages` > `Custom domain` field was deleted after my last deploy, thank you for pointing that out.

As for the CNAME file, I have another domain name pointing to d-pow.github.io so I can't remove it, at least until it expires in the coming months. I may just have to change the GitHub Pages settings after every deploy until then.
