### ISSUE TITLE
[Support] Domain already owned by a vercel account

### ISSUE THREAD

**Issue by tejasag** [is-a-dev/register#489]
Your domain name: tejas.is-a.dev

Hi! So I just got my domain name approved and I was trying to configure Vercel to support it, but then I got this error
![image](https://user-images.githubusercontent.com/67542663/104118557-0e757580-5350-11eb-9569-bf36fca14128.png)
Any idea what I can do at this point?

Thanks in advance 
\- Tejas

**Comment by phenax** [comment]
You have a URL redirection record not a subdomain so the link `https://tejas.is-a.dev` will redirect to `https://tejasagarwal.vercel.app` (https://github.com/is-a-dev/register/pull/488/files).
Also, it seems like vercel doesn't support using `is-a.dev` subdomains so you cannot use CNAME record for vercel. https://github.com/is-a-dev/register/issues/249

If you wanted a subdomain (a CNAME record), you will have to use a different hosting service.

**Comment by tejasag** [comment]
Ok thanks! I'll keep the website on vercel for now, but if I find another host, then we can switch to a CNAME record i guess.
But for now, lets keep it as it is. thanks a lot!

**Comment by phenax** [comment]
Alrighty. Closing this issue

**Comment by anondev-sudo** [comment]
I have same problem and I can't understand why does vercel count when someone owns x.domain.com as owner of domain.com

Will someone suggest them to add support for subdomains on different accounts?

**Comment by TheBotlyNoob** [comment]
made (another) discussion about this in https://github.com/vercel/vercel/discussions/6378

**Comment by TheBotlyNoob** [comment]
Reopening because this is kind of annoying.

**Comment by anondev-sudo** [comment]
I tried to use netlify intead of vercel but they are same kind of annoying
![image](https://user-images.githubusercontent.com/85408287/122915582-2d931d00-d35c-11eb-93b3-4bb80000a778.png)

**Comment by TheBotlyNoob** [comment]
NO

**Comment by Bedrock16** [comment]
Hmmm

**Comment by leecheeyong** [comment]
@TheBotlyNoob yea i'm having a kinda same issue but on replit

**Comment by Bedrock16** [comment]
Really I too want it so that I can use it on repl.it

**Comment by leecheeyong** [comment]
I have a solution, which is to notify the user who wants to give up or change the domain to unlink their projects so other users could link their project

**Comment by IbrahimDevX** [comment]
The issue is another user has registered their .is-a.dev domain using vercel, and Vercel only counts the last .is-a.dev subdomain and they think it's a whole company for example; Google.com wouldn't need another Vercel account for accounts.google.com so Vercel would block it as Google.com is registered on a different account. The same situation applys with is-a.dev and you'll need to look for a different host. (Netlify gives the same error)

**Comment by anondev-sudo** [comment]
Or just ask netlify and vercel to whitelist this subdomain, or suggest them not to check if someone else owns another subdomain. Just display this error when someone would like to link test.is-a.dev and test.is-a.dev is owned by someone, but not when someone would like to add test2.is-a.dev

**Comment by mtgsquad** [comment]
> Ok thanks! I'll keep the website on vercel for now, but if I find another host, then we can switch to a CNAME record i guess.
> But for now, lets keep it as it is. thanks a lot!

Maybe you can switch to cloudflare, when i registered a .js.org subdoimain i did have issues with them, and ended up using Vercel. but try again, maybe vercel works now, as stated above by Bedrock16.

**Comment by anondev-sudo** [comment]
So what to do to fix the issue? is-a.dev needs to migrate to cloudflare?

**Comment by mtgsquad** [comment]
> I have a solution, which is to notify the user who wants to give up or change the domain to unlink their projects so other users could link their project

I don't think that is even possible for us. We want to keep is-a.dev, the same for everyone. We do not want to stop someone from using their website because others are having issues. Plus even getting them to remove it, only one of you guys will be able to use it.

**Comment by mtgsquad** [comment]
> So what to do to fix the issue? is-a.dev needs to migrate to cloudflare?

Look at #1091 . I have provided an answer to your question there.

**Comment by TheBotlyNoob** [comment]
you could use [Railway](https://railway.app/?referralCode=jj)

**Comment by anondev-sudo** [comment]
Is that free? Also there is not that problem?

**Comment by TheBotlyNoob** [comment]
> Is that free? Also there is not that problem?

It is, and it works for `is-a.dev`
