### ISSUE TITLE
Hi. Can I get a 3rd level domain?

### ISSUE THREAD

**Issue by magic4me** [is-a-dev/register#492]
Hi, I have a magic4me.is-a.dev domain. Can I register a search.magic4me.is-a.dev? Or something like this?

**Comment by magic4me** [comment]
**4th level

**Comment by phenax** [comment]
Currently sub-subdomains are not supported. You can use hyphens instead `search-magic4me.is-a.dev`.

**Comment by magic4me** [comment]
Thanks, can I get once more domain for my account?

**Comment by phenax** [comment]
Sure. Create a new pr with the sub-domains you want to register

**Comment by magic4me** [comment]
Thank you
