### ISSUE TITLE
Domain still redirecting to is-a.dev

### ISSUE THREAD

**Issue by ThinLiquid** [is-a-dev/register#4923]
Your domain name: liquid.is-a.dev

Explain any issues you are facing

I've waited for about 4 days, and it still redirects me to the home page.
I'm using Glitch for hosting.

**Comment by mtgsquad** [comment]
@ThinLiquid You should try clearing your DNS cache. If the issue persists, join our discord [here.](https://discord.gg/ZXB4zuRXkC)

(https://discord.gg/ZXB4zuRXkC)

**Comment by piotr25691** [comment]
> Your domain name: liquid.is-a.dev
> 
> Explain any issues you are facing
> 
> I've waited for about 4 days, and it still redirects me to the home page. I'm using Glitch for hosting.

That is not the only issue, your site throws a `PR_END_OF_FILE_ERROR` error on Firefox, and it doesn't load.

**Comment by ThinLiquid** [comment]
> > Your domain name: liquid.is-a.dev
> > Explain any issues you are facing
> > I've waited for about 4 days, and it still redirects me to the home page. I'm using Glitch for hosting.
> 
> That is not the only issue, your site throws a `PR_END_OF_FILE_ERROR` error on Firefox, and it doesn't load.

what does that mean?

**Comment by piotr25691** [comment]
> > > Your domain name: liquid.is-a.dev
> > > Explain any issues you are facing
> > > I've waited for about 4 days, and it still redirects me to the home page. I'm using Glitch for hosting.
> > 
> > 
> > That is not the only issue, your site throws a `PR_END_OF_FILE_ERROR` error on Firefox, and it doesn't load.
> 
> what does that mean?

From what I recall, this is a security/certificate error that appears on Firefox, I don't know if it works on Chrome yet. Your certificate might not have applied to the domain yet.

**Comment by ThinLiquid** [comment]
so what would be a fix?

**Comment by piotr25691** [comment]
> so what would be a fix?

i don't know, it might fix itself when all the records start working

**Comment by anshtyagi0** [comment]
Same issue with me.
Domain: https://anshtyagi0.is-a.dev

**Comment by WilliamDavidHarrison** [comment]
@andrewstech

**Comment by ThinLiquid** [comment]
Now my site is just blank and gives a Chrome error. :(

**Comment by andrewstech** [comment]
> Now my site is just blank and gives a Chrome error. :(

I'm not getting an error. I get Glitch is starting up then blank. On liquid.is-a.dev

**Comment by ThinLiquid** [comment]
The problem is fixed!
