### ISSUE TITLE
Is it possible to register mail?

### ISSUE THREAD

**Issue by kotru21** [is-a-dev/register#4939]
How can I register a mail/mail domain on is-a.dev?

**Comment by piotr25691** [comment]
> How can I register a mail/mail domain on is-a.dev?

You can use https://improvmx.com, you will just have to add the records to your domain

**Comment by WilliamDavidHarrison** [comment]
In addition to @piotr25691's answer, you can use any mail server as long it doesn't require verification (e.g: Microsoft 365 Mail won't work, but ImprovMX will).

**Comment by kotru21** [comment]
> > How can I register a mail/mail domain on is-a.dev?
> 
> You can use https://improvmx.com, you will just have to add the records to your domain in a pull request

Thanks, but what records I need to add in pull?

**Comment by WilliamDavidHarrison** [comment]
Whatever records the service asks you to. What service are you using?

**Comment by kotru21** [comment]
> Whatever records the service asks you to. What service are you using?

Improvmx.com

**Comment by kotru21** [comment]
Oh, see this
![Screenshot_2023-02-25-11-41-07-75_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/88907641/221347760-30754e7b-381e-471c-bcc4-0f07dc9b4bee.jpg)

**Comment by WilliamDavidHarrison** [comment]
Yes, you need to add those records to your domain.

**Comment by piotr25691** [comment]
> Oh, see this ![Screenshot_2023-02-25-11-41-07-75_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/88907641/221347760-30754e7b-381e-471c-bcc4-0f07dc9b4bee.jpg)

so create a PR for it, link it to #4939 just in case and add those records

**Comment by kotru21** [comment]
> > Oh, see this ![Screenshot_2023-02-25-11-41-07-75_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/88907641/221347760-30754e7b-381e-471c-bcc4-0f07dc9b4bee.jpg)
> 
> so create a PR for it, link it to #4939 just in case and add those records 

Already done it

**Comment by piotr25691** [comment]
> > > Oh, see this ![Screenshot_2023-02-25-11-41-07-75_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/88907641/221347760-30754e7b-381e-471c-bcc4-0f07dc9b4bee.jpg)
> > 
> > 
> > so create a PR for it, link it to #4939 just in case and add those records
> 
> Already done it

before ImprovMX can recognize your records, your PR must be merged and you'll have to wait up to 12 hours for the new records to propagate

**Comment by kotru21** [comment]
> > > > Oh, see this ![Screenshot_2023-02-25-11-41-07-75_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/88907641/221347760-30754e7b-381e-471c-bcc4-0f07dc9b4bee.jpg)
> > > 
> > > 
> > > so create a PR for it, link it to #4939 just in case and add those records
> > 
> > Already done it
> 
> before ImprovMX can recognize your records, your PR must be merged and you'll have to wait up to 12 hours for the new records to propagate

Okay, got it
