### ISSUE TITLE
Redirection not working

### ISSUE THREAD

**Issue by tejasag** [is-a-dev/register#494]
### Expected outcome
It should have redirected me to my website, i.e. https://tejasagarwal.vercel.app/

### Observed outcome
![](https://cyberknight.wheres-my-ta.co/nfintM.gif)
It shows the favicon of my website but does not redirect me *to* the website soo i am pretty sure this is some sort of bug..

Thanks
-Tejas

**Comment by phenax** [comment]
To me it is redirecting correctly. I think this is a result of caching. Try clearing your browser cache or maybe use a private window to check

**Comment by tejasag** [comment]
Yep clearing cache worked 😅😅 thanks
