### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by joeleeofficial** [is-a-dev/register#495]
Your domain name: joelee.is-a.dev

Explain any issues you are facing

so i was trying to visit my website after getting merged, but it comes out with an Error 
![image](https://user-images.githubusercontent.com/70639311/104263434-9086ab00-54c4-11eb-9b93-8b5e63605936.png)
![image](https://user-images.githubusercontent.com/70639311/104263460-9da39a00-54c4-11eb-9352-624cdd3f622e.png)

I've try it on my phone, tablet and laptop. but still not working. 
i just want to know is that my cert problem or the HSTS Cloudflare problem.

**Comment by phenax** [comment]
You need to click the Enforce HTTPS checkbox in the github pages settings of your repo. [It is referenced in the docs](https://github.com/is-a-dev/register/blob/main/docs/hosted-at/github-pages.md)

**Comment by joeleeofficial** [comment]
i can't 
![image](https://user-images.githubusercontent.com/70639311/104293169-ab731280-54f8-11eb-847b-8a2cf4fa2595.png)

**Comment by phenax** [comment]
This usually happens when the github page custom domain is set before the sub-domain was published. This will take some time. You could try clearing the "Custom Domain" field and saving it and then adding it back.

**Comment by joeleeofficial** [comment]
> 
> 
> This usually happens when the github page custom domain is set before the sub-domain was published. This will take some time. You could try clearing the "Custom Domain" field and saving it and then adding it back.


It works ! thanks for helping me !
