### ISSUE TITLE
can I use a cname with another records?

### ISSUE THREAD

**Issue by mdsmax** [is-a-dev/register#5158]
I'm asking this question, because I tryed to record a CNAME and a TXT + CX (to make an email) and William said that I cannot use more records, beucase there is a CNAME record already registered.

if you need, [call me on my discord](https://discord.com/users/895663660154892289) (ID: 895663660154892289)

**Comment by WilliamDavidHarrison** [comment]
Unfortunately, due to DNS restrictions CNAME records with other records do not work. *But*, you can reverse lookup the CNAME and use the A records it points to instead. So then you can use other records.

**Comment by mdsmax** [comment]
Hey William! How can I change my CNAME record to A record in Replit?

**Comment by WilliamDavidHarrison** [comment]
Use the website https://whatsmydns.net and put in your CNAME record and then use the A record that comes up.

**Comment by mdsmax** [comment]
Thanks! It worked.
