### ISSUE TITLE
Facing warnings while accessing my domain

### ISSUE THREAD

**Issue by realpxd** [is-a-dev/register#5163]
My domain is :- [pxd.is-a.dev](https://pxd.is-a.dev) 

And am facing such error - " Attackers might be trying to steal your information from pxd.is-a.dev "
Proof attached below.

How do i fix it and why am i facing this warning , meanwhile i just recently created this domain.
#5143 

![Screenshot_2023-03-29-10-09-29-366_com android chrome](https://user-images.githubusercontent.com/70265763/228429137-08dfd75a-3c38-4f37-bd41-325d67cd2102.jpg)

**Comment by VaibhavSys** [comment]
Your domain hasn't been issued a valid SSL Certificate, did you read the [docs](https://is-a.dev/docs)?

**Comment by realpxd** [comment]
Finally the issue is fixed , thanks for the help !
