### ISSUE TITLE
Support - CORS

### ISSUE THREAD

**Issue by realpxd** [is-a-dev/register#5178]
Your domain name: [pxd.is-a.dev](https://pxd.is-a.dev)  #5143 

Explain any issues you are facing

I have a website which uses git api for accessing another repo file , and after setting up my is-a.dev domain , am facing this error :- 
`[`
`Access to fetch at 'https://realpxd.github.io/lgc/db.json' from origin 'https://pxd.is-a.dev' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

`line:0 of : https://pxd.is-a.dev/Instagram-Clone-Beta/ Uncaught (in promise) TypeError:
]`

I tried setting up an cors.json in my root dir but it didn't worked.
`[
Cors.json file content :- 
[{"path":"*","origin":"https://pxd.is-a.dev","methods":["GET"]}]
]`

The same website is running fine in my local-machine , but am facing the cors error when trying to access the published website

**Comment by WilliamDavidHarrison** [comment]
> `'https://realpxd .github.io/lgc/db.json'`

In the error it shows a space between `https://realpxd` and `.github.io`, are you fetching the correct URL?

**Comment by realpxd** [comment]
Yes , the url in code is correct, it was an type error in this issues.

**Comment by WilliamDavidHarrison** [comment]
I think this may be an issue with GitHub Pages, I'm not sure. As we do not handle CORS, the end user does.
