### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by Firepup6500** [is-a-dev/register#5309]
Your domain name: firepup650.is-a.dev

Explain any issues you are facing
Domain is returning an SSL error, replit said that it was returning both an A and a CNAME record, and that I need to ask you to remove the A record.
```markdown
It looks like you had previously requested an A record for your is-a.dev domain, which is why it’s returning both an A and a CNAME record.
If you ask them to remove the A record for your subdomain, that should fix the issue!
```

**Comment by Firepup6500** [comment]
Posted this from my other account, if you'd like, I can confirm this from my main as well.

**Comment by WilliamDavidHarrison** [comment]
Please open a new PR removing the records you don't need.

**Comment by Firepup6500** [comment]
There is no A record in the records I originally provided, I'm not sure how to proceed here.
