### ISSUE TITLE
SSL error when trying to load domain

### ISSUE THREAD

**Issue by rtb523** [is-a-dev/register#5397]
Your domain name: ginut.is-a.dev

Explain any issues you are facing it gives me an ssl error as shown bellow
![Screenshot (16)](https://user-images.githubusercontent.com/59374749/233630707-bce1fb5c-a9da-4997-a680-d8b26705be8f.png)
i have the host(repl.it) configured for this domain but as far as i know repl.it does not let you edit ssl certificate

**Comment by WilliamDavidHarrison** [comment]
Has Replit verified the domain is linked?

**Comment by rtb523** [comment]
still verifying and not loading

**Comment by jdev082** [comment]
facing same issue

**Comment by WilliamDavidHarrison** [comment]
@andrewstech
