### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by F1repup650** [is-a-dev/register#5401]
Your domain name: firepup650.is-a.dev

Explain any issues you are facing
In reference to #5309:
The records I provided did not include an A record, how should I proceed?

**Comment by F1repup650** [comment]
Replit community says it's from cluodflare flattening the CNAME, and to ask you to turn off the proxy for my subdomain please.

**Comment by WilliamDavidHarrison** [comment]
We don't use Cloudflare DNS, so proxying is not the issue.

**Comment by F1repup650** [comment]
Any ideas as to where the A record is coming from then? I didn't provide one in my original records.

**Comment by WilliamDavidHarrison** [comment]
Not sure. Can you please confirm the records your domain needs?

**Comment by F1repup650** [comment]
A `CNAME` record, with address `5828eaa1-491a-4323-9d54-d5e80935eab3.id.repl.co`.

**Comment by WilliamDavidHarrison** [comment]
Your domain is setup with that record, so I believe this is an issue with Replit and not us.
