### ISSUE TITLE
website flagged as malicious

### ISSUE THREAD

**Issue by WilliamAfton-codes** [is-a-dev/register#5517]
### Expected outcome
Getting to my is-a.dev subdomain normally

### Observed outcome
Multiple browsers flagged it as malicious
```
Your connection is not private
Attackers might be trying to steal your information from afton.is-a.dev (for example, passwords, messages, or credit cards).

NET::ERR_CERT_COMMON_NAME_INVALID
```

Subdomain is https://afton.is-a.dev

**Comment by WilliamDavidHarrison** [comment]
It is an issue with your SSL certificate.

**Comment by WilliamAfton-codes** [comment]
right, i dont really have one

**Comment by WilliamAfton-codes** [comment]
@WilliamDavidHarrison i got it working, had to change a setting in the source repo

**Comment by Dumbo-programmer** [comment]
What did you change ?
