### ISSUE TITLE
Cannot register vis CLI

### ISSUE THREAD

**Issue by CasperOng** [is-a-dev/register#5596]
### Expected outcome
Err, make a repo, open a PR

### Observed outcome

 is-a.dev  v2.0.2 CLI
Register your own is-a.dev subdomain from your command line!

Username: CasperOng
Email: casper10528@gmail.com

✔ What subdomain would you like? … casperong
✔ What type of record do you want to use? › CNAME
✔ What should the value of the record be? … casperong.github.io

✖ UNHANDLED ERROR
✖ ERROR → Error
ℹ REASON → HttpError: Unable to read Git repository contents. We've notified our support staff. If this error persists, or if you have any questions, please contact us.
ℹ ERROR STACK ↓ 
 Error: HttpError: Unable to read Git repository contents. We've notified our support staff. If this error persists, or if you have any questions, please contact us.
    at /opt/homebrew/lib/node_modules/@is-a-dev/cli/src/functions/register.js:81:41
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by CasperOng** [comment]
> @andrewstech I demand an explanation 

What happen?

**Comment by WilliamDavidHarrison** [comment]
> @andrewstech I demand an explanation

I make the CLI now, not Andrew.

> What happen?

It seems the CLI cannot read your forked repository. Have you tried running the register command again?

**Comment by CasperOng** [comment]
> > @andrewstech I demand an explanation
> 
> I make the CLI now, not Andrew.
> 
> > What happen?
> 
> It seems the CLI cannot read your forked repository. Have you tried running the register command again?

Yes, I even reinstalled the whole package. Still the same..

**Comment by WilliamDavidHarrison** [comment]
Try deleting your fork of is-a-dev/register and try registering again.

**Comment by andrewstech** [comment]
> @andrewstech I demand an explanation

William remade the Cli. I know much as you.

**Comment by CasperOng** [comment]
Thanks @andrewstech @WilliamDavidHarrison, I don't know why, but it can register normally if I register it with another computer. Thanks for your help

<img width="777" alt="Screenshot 2023-05-14 at 12 13 39 AM" src="https://github.com/is-a-dev/register/assets/90828938/95041fe4-cdf1-4f28-878c-aceebfd342e5">

**Comment by WilliamDavidHarrison** [comment]
It might be an issue with your internet connection on the other computer, glad it worked!
