### ISSUE TITLE
domain is not loading my css

### ISSUE THREAD

**Issue by saifrahmn** [is-a-dev/register#5644]
### Expected outcome
When I go with the github pages domain, my website works properly showing all the css styles and working in a proper order. these is what a expected while using the domain as well.

### Observed outcome
When I used the is-a.dev domain, it doesn't  shows my css in any way.

![Screenshot from 2023-05-20 10-06-05](https://github.com/is-a-dev/register/assets/64410006/8da974f6-d25a-49d1-981c-83d54e9f3e5e)

**Comment by WilliamDavidHarrison** [comment]
It's a problem with your imports, not the domain.
