### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by NotArya100** [is-a-dev/register#5709]
Your domain name:
notarya.is-a.dev

Explain any issues you are facing:
SSL error and the website not working and redirecting to suspendedwebsite

**Comment by WilliamDavidHarrison** [comment]
What do you mean by suspended website?

**Comment by NotAryaaa** [comment]
suspendedwebsite.org

**Comment by NotAryaaa** [comment]
*suspendeddomain.org

**Comment by VaibhavSys** [comment]
> notarya.is-a.dev

It looks like you haven't issued a SSL certificate for nor `notarya.rf.gd.` neither `notarya.is-a.dev`.
We do not provide SSL certificates, you must issue them yourself. Ask your host to issue one for you, or use a tool like certbot to do it yourself if you are self-hosting.

**Comment by NotAryaaa** [comment]
im using infinityfree to host my website and for the domain, i have SSL certificate for that too

**Comment by NotAryaaa** [comment]
im going to change my website from .rf.gd to github.io to see if it works.

**Comment by WilliamDavidHarrison** [comment]
You need to open a new PR to make changes to your file.

**Comment by NotAryaaa** [comment]
done, but still nothing works 😔

**Comment by WilliamDavidHarrison** [comment]
You need to create a file called `CNAME` in your GitHub Pages repository with the content `notarya.is-a.dev`

**Comment by WilliamDavidHarrison** [comment]
It's your issue not ours, your subdomain has been registered, you just haven't set it up.
