### ISSUE TITLE
Visiting http://comicly.is-a.dev/

### ISSUE THREAD

**Issue by Comicly69** [is-a-dev/register#5736]
When i visit http://comicly.is-a.dev/ which i have registered using the cli, and have the CNAME  set to comicly69.github.io that works fine when visited by itself, but when i visit my is a dev website it gives a 404 saying that there isnt a github pages site here, when i copy paste the link github.io link from the CNAME in my json it works just fine. Could anyone advise me on why this is happening? or try visiting it themseves and see if its a issue for them too.

Thanks,
Max

**Comment by WilliamDavidHarrison** [comment]
You need to create a file called `CNAME` in your website repository with this content and then enable `Enforce HTTPS` in your GitHub Pages settings.
```
comicly.is-a.dev
```

**Comment by WilliamDavidHarrison** [comment]
It seems to work now, so I will close this issue.
