### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by frostzzone** [is-a-dev/register#5808]
Your domain name: frostzzone.is-a.dev

Hosted on a repl, when you visit the repl its fine, but uing the is-a.dev link returns a `This site can’t provide a secure connection` or `run repl to see output`

**Comment by WilliamDavidHarrison** [comment]
@andrewstech Can you help?

**Comment by andrewstech** [comment]
I'm not sure

**Comment by VaibhavSys** [comment]
> Your domain name: frostzzone.is-a.dev
> 
> Hosted on a repl, when you visit the repl its fine, but uing the is-a.dev link returns a `This site can’t provide a secure connection` or `run repl to see output`

Did you add your is-a.dev subdomain to the repl? And make sure it is verified if you did add it

**Comment by Rahuletto** [comment]
This happened to me too.

Replit says
> Currently, your domain is either not returning any records, or something is getting in the way of our verification process.

but you can see that it returns the correct CNAME record as seen here:
https://www.whatsmydns.net/#CNAME/1st.is-a.dev

**Comment by WilliamDavidHarrison** [comment]
You don't have a verification TXT if that's what you're talking about. I removed it since we don't support them.

**Comment by Rahuletto** [comment]
But it asked CNAME or TXT record

**Comment by WilliamDavidHarrison** [comment]
We don't support either.

**Comment by Rahuletto** [comment]
Ok then, thanks for the reply
