### ISSUE TITLE
Support Email forwarding with ZOHO

### ISSUE THREAD

**Issue by Techpro709** [is-a-dev/register#5815]
Your domain name:prozt

Explain any issues you are facing

Just want to know if I can add these records to the domain...

<img width="585" alt="image" src="https://github.com/is-a-dev/register/assets/61668117/fff6fc16-dc93-442f-a7b7-4cc41a01b369">
<img width="479" alt="image" src="https://github.com/is-a-dev/register/assets/61668117/daefcda7-20de-4395-91f9-92d584ba83e0">
<img width="536" alt="image" src="https://github.com/is-a-dev/register/assets/61668117/10d6ab7e-bb02-43c8-b688-717988e7b413">

That way I can send emails...

If yes, I can send them here or I can try to implement it into the json file.

**Comment by WilliamDavidHarrison** [comment]
We unfortunately don't support services like Zoho due to them requiring domain verification but you can use https://improvmx.com for email forwarding.

**Comment by Techpro709** [comment]
I already have to domain verified already. I was able to do this using a diffenent method involving uploading an html file to my website.

Because the verification is done is it now possible to do this?

I can show proof of the verification.

I know it works because I was able to send messages, but if I add these records I can also receve messages.

<img width="393" alt="image" src="https://github.com/is-a-dev/register/assets/61668117/034d5914-bb95-424e-86cb-e71176a84f56">


The second image I sent back wasn't able to be recieved, because of the MX records not being set.

I will also check out what you sent.

Thanks

**Comment by Techpro709** [comment]
Also this one also uses MX records,

<img width="594" alt="image" src="https://github.com/is-a-dev/register/assets/61668117/c9d13b77-d0df-436f-bb92-7829d7b390d5">

**Comment by Techpro709** [comment]
@WilliamDavidHarrison how do I add MX records?
is it in the same file with the CNAME or what?

**Comment by WilliamDavidHarrison** [comment]
You can't combine records with CNAME records.

**Comment by Techpro709** [comment]
Why not? can I use A Records? I am trying to send to my Github Pages.
