### ISSUE TITLE
con.json under the domains directory

### ISSUE THREAD

**Issue by Bibs24** [is-a-dev/register#5823]
### Expected outcome
While cloning the repo it should have cloned the files present inside

### Observed outcome
But it throws an exception stating that
```
--error: invalid path 'domains/con.json'
--fatal: unable to checkout working tree
--warning: Clone succeeded, but checkout failed.
```
I'm using a windows machine.

**Comment by WilliamDavidHarrison** [comment]
Is your clone up to date?

**Comment by Bibs24** [comment]
@WilliamDavidHarrison yes it is! when I googled about it , it said I need to remove the con.json to clone it. So I did it and added my json file and opened a PR. Can you check it out if that works? PR labeled as bibhu is-a.dev

**Comment by WilliamDavidHarrison** [comment]
Ohhh, I know why it won't clone. Files named `con` are not allowed on Windows systems. But you cannot remove the file as it is another user's domain. I will restore `con.json` and merge your PR.

**Comment by WilliamDavidHarrison** [comment]
I've merged your PR and I will discuss with the other maintainers about the `con.json` file causing issues with Windows computers.

**Comment by Bibs24** [comment]
Thanks @WilliamDavidHarrison , appreciate that!
