### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by CattopyTheWeb** [is-a-dev/register#5986]
Your domain name: cattopytheweb.is-a.dev

Explain any issues you are facing
When I try add my domain in github pages I get this error:

`cattopytheweb.is-a.dev is improperly configured
Domain does not resolve to the GitHub Pages server. For more information, see [documentation](https://docs.github.com/articles/setting-up-a-custom-domain-with-github-pages/) (NotServedByPagesError).`

**Comment by CattopyTheWeb** [comment]
Help!

**Comment by CattopyTheWeb** [comment]
@WilliamDavidHarrison

**Comment by WilliamDavidHarrison** [comment]
Your website seems to be working now.
