### ISSUE TITLE
hexaa.is-a.dev doesnt redirect into my website

### ISSUE THREAD

**Issue by hexaaagon** [is-a-dev/register#5997]
my last pull request #5991

### Expected outcome
it will automaticly redirect into https://www.hexagonn.my.id/

### Observed outcome
errors...
![image](https://github.com/is-a-dev/register/assets/128217934/7b571c0f-a3f6-4020-9b2d-cd0e4286cc55)

**Comment by WilliamDavidHarrison** [comment]
Your website works now, please clear your cache.
