### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by anshtyagi0** [is-a-dev/register#6114]
Your domain name: api.anshtyagi.is-a.dev

Explain any issues you are facing
I tried to link this domain to replit but its over 48hours and my domain is not yet linked.

**Comment by WilliamDavidHarrison** [comment]
We are having a lot of issues with Replit recently. I think the issue is with your SSL, can you provide a screenshot of the domain linking page on Replit?

**Comment by anshtyagi0** [comment]
> We are having a lot of issues with Replit recently. I think the issue is with your SSL, can you provide a screenshot of the domain linking page on Replit?
@WilliamDavidHarrison Here is the screenshot.
<img width="331" alt="Screenshot 2023-07-10 at 3 37 42 PM" src="https://github.com/is-a-dev/register/assets/73632579/2a1f7dec-f71c-42bd-9d9a-9d13384835fd">

**Comment by WilliamDavidHarrison** [comment]
We don't support TXT verification.

**Comment by anshtyagi0** [comment]
> We don't support TXT verification.

But you docs says that it supports.

**Comment by WilliamDavidHarrison** [comment]
We support the service just not TXT verification.
