### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by DoxrGitHub** [is-a-dev/register#6117]
Your domain name: https://shadow.is-a.dev/

Explain any issues you are facing

```
shadow.is-a.dev unexpectedly closed the connection.
```

I think it could be because of the records. CNAME fails on Replit and A... does this? I don't know. I got the A record by using a DNS checker (on the CNAME URL, but Replit does automatically give it). `34.149.204.188`. I only got one but the thing requires four, maybe it's that.

**Comment by WilliamDavidHarrison** [comment]
This is most likely a Replit issue, have you setup your domain on Replit?

**Comment by DoxrGitHub** [comment]
Yeah, it sucessfully verified shadow.is-a.dev and it even made it the normal link instead of the repl.co link/

yet is-a.dev fails

**Comment by DoxrGitHub** [comment]
Wait, what if I add the TXT and CNAME records along with the A records? Is that possible, @WilliamDavidHarrison ? How about adding just A and TXT? I tried just CNAME and it failed.

**Comment by WilliamDavidHarrison** [comment]
Unfortunately, it is not possible. CNAME records cannot be combined with other records.

**Comment by DoxrGitHub** [comment]
Oh, ok, then I'll make a pull request with both A and TXT.
