### ISSUE TITLE
Replit not linking

### ISSUE THREAD

**Issue by SoulUchiha** [is-a-dev/register#6146]
### Expected outcome
Domain should've been linked in replit

### Observed outcome
Still trying to link the domain

**Comment by LeGi0N09** [comment]
same problem here also

**Comment by WilliamDavidHarrison** [comment]
Not yet unfortunately.

**Comment by SoulUchiha** [comment]
How can i host a discord bot on these pages things idk

**Comment by LeGi0N09** [comment]
paste it on GitHub and deploy it

**Comment by anshtyagi0** [comment]
> You can try [GitHub Pages](https://pages.github.com) or [Cloudflare Pages](https://pages.cloudflare.com/).

I won't be able to deploy dynamic websites.

**Comment by WilliamDavidHarrison** [comment]
Unfortunately we cannot do anything about it as Vercel and Netlify both do not allow SSL certificates to be issued on the is-a.dev domain for some reason. You could try https://railway.app which can host dynamic websites.

I will close this issue as there is nothing we can do about it.
