### ISSUE TITLE
Add TXT verification

### ISSUE THREAD

**Issue by anshtyagi0** [is-a-dev/register#6166]
Please add TXT verification so we can link domain to replit.

**Comment by WilliamDavidHarrison** [comment]
I will have a chat with the other maintainers to see what they think of it.

**Comment by phenax** [comment]
https://ask.replit.com/t/replit-not-running-on-custom-domain/33552

Seems like replit verification only supports a few services like cloudflare that don't follow the DNS spec completely. Unfortunately, the DNS service we use and the spec for DNS itself doesn't support CNAME along with TXT.
