### ISSUE TITLE
Feedback/suggestion: Ability to add sub-sub-domains through sub-domain configuration

### ISSUE THREAD

**Issue by nottisa** [is-a-dev/register#6252]
In the originating JSON for example: isa.json, it would be really cool to be able to configure addition sub domains to the originating sub domain. For example, there would be an array in the JSON with the subdomain name and the record for that subdomain. Hopefully I make sense... :)

**Comment by WilliamDavidHarrison** [comment]
You can add nested subdomains like `blog.isa.is-a.dev` by just creating a file like `blog.isa.json`.
