### ISSUE TITLE
Can I use a subdomain for a website hosted on github pages?

### ISSUE THREAD

**Issue by TalinTheDev** [is-a-dev/register#6359]
So I have a domain for my user site (WIP): talinsharma.is-a.dev

And I have a project repo: TalinTheDev/Nonograms which has the gh-pages url of "https://talinthedev.github.io/Nonograms/"

So I made a pull request for "nonograms.talinsharma.is-a.dev" and I want to link it to my project.

I wasn't sure but for now I set the CNAME record for the pull request to "talinthedev.github.io" because I wasn't sure what else to do. Is this the correct record/steps?

Thanks!

**Comment by WilliamDavidHarrison** [comment]
Yes, just set your CNAME record to `talinthedev.github.io` (you will need to update it and send another PR), once merged, add a file called `CNAME` into your repository with the content `talinsharma.is-a.dev`.

**Comment by TalinTheDev** [comment]
@wdhdev Wouldn't I set my repository's CNAME to `nonograms.talinsharama.is-a.dev`?

**Comment by WilliamDavidHarrison** [comment]
No, unless that is the domain you want to use.
