### ISSUE TITLE
This site can't provide a secure connection

### ISSUE THREAD

**Issue by TheBotlyNoob** [is-a-dev/register#660]
### Expected outcome

able to access the site

### Observed outcome

![image](https://user-images.githubusercontent.com/72417807/113913769-50bd2000-97a2-11eb-813b-4a3c611d45af.png)

**Comment by TheBotlyNoob** [comment]
but im using https

**Comment by C1200** [comment]
If you use http, not https, it brings up a cloudflare 1001 error.

**Comment by mtgsquad** [comment]
I think that you do not have SSL on the server...

**Comment by phenax** [comment]
Since it is a CNAME record and [DNS lookup](https://www.whatsmydns.net/dns-lookup?query=raksix.is-a.dev&server=google) seems to check out, it must be an SSL misconfiguration

**Comment by phenax** [comment]
Closing this issue. Feel free to re-open this issue or create a new one if needed.
