### ISSUE TITLE
Support : The domain has been verified by another user/organization

### ISSUE THREAD

**Issue by fdciabdul** [is-a-dev/register#6627]
Your domain name: fdciabdul.is-a.dev

Explain any issues you are facing

github sent me like this 

![image](https://github.com/is-a-dev/register/assets/31664438/708d3864-a72c-4f5e-aba5-06cf9fca075d)

even my domain is still in there 

![image](https://github.com/is-a-dev/register/assets/31664438/e5b4121b-9460-4e94-bda9-1728d95ac674)

then when i trying to verify the CNAME ,this happen

![image](https://github.com/is-a-dev/register/assets/31664438/a8306537-1913-4e07-b7b2-d1fd3bdb8609)

i don't know

**Comment by vikramv20** [comment]
![Screenshot_20230805-030001](https://github.com/is-a-dev/register/assets/80647839/3383bf12-f717-4772-8625-9a5e2589014a)

I got this problem too.

**Comment by Jesgran** [comment]
got this problem too

**Comment by NatBLida68** [comment]
same issue got the mail just now

**Comment by ItachiSan** [comment]
Same here!

**Comment by Adolar0042** [comment]
just got the mail too

**Comment by techpixel** [comment]
Got the email as well

**Comment by seriaati** [comment]
same issue.

**Comment by antton-dev** [comment]
Same problem for me

**Comment by ejaz4** [comment]
+1 here, just got an email with the exact same thing.
![image](https://github.com/is-a-dev/register/assets/73548455/77dc3562-2cd6-495f-8918-d997a023b35d)

**Comment by loiSvelasco** [comment]
Got the same problem too :<

**Comment by vncsmnl** [comment]
Got the same problem too here !!!

**Comment by zyrouge** [comment]
Same issue here too.

**Comment by WilliamDavidHarrison** [comment]
Hi everyone, we are currently looking into this. We do not know why this has happened.

**Comment by boredcodebyk** [comment]
got the same mail

**Comment by 404Dev-404** [comment]
got this email too i had a mini heart attack when i saw it

**Comment by AldenizenMC** [comment]
same issue

**Comment by ShivangKakkar** [comment]
Same!

**Comment by Shinyzenith** [comment]
Recieved this mail too. Says I have 7 days to resolve the issue before someone else can claim it.

**Comment by WilliamDavidHarrison** [comment]
I have found the issue that caused it, PR #6624. I have reverted the pull request, but I believe everyone will need to re-verify their domains with GitHub Pages.

**Comment by seriaati** [comment]
how do you re-verify?

**Comment by WilliamDavidHarrison** [comment]
I think if you click on the 3 dots next to your domain and then click Verify.

**Comment by sekharmalla** [comment]
Yes, is there a guide or steps we can follow to re-verify because the re-verification process contains steps lile Txt records updation. Kindly please help us.

**Comment by WilliamDavidHarrison** [comment]
You just need to get the new TXT value then find your GitHub Pages verification domain file in the domains folder then edit the record value to the new one and open a PR.

**Comment by WilliamDavidHarrison** [comment]
**You need to update your file which starts with `_github-pages-challenge`, not your main file.**

**Comment by roktim32** [comment]
Can it be done using manage.is-a.dev website?

**Comment by WilliamDavidHarrison** [comment]
Most likely.

**Comment by ThisisThamizh** [comment]
BETA: Update thamizh.is-a.dev #6706

**Comment by ThisisThamizh** [comment]
#6726

**Comment by ThisisThamizh** [comment]
#6706

**Comment by ThisisThamizh** [comment]
#6706

**Comment by jcgaming-official** [comment]
I got this problem too. Help me. Is there a way to fix this on mobile device?

**Comment by KenWuqianghao** [comment]
any updates?

**Comment by caodoc** [comment]
how can i verify my domain like github said on the domain?

**Comment by amalpotra** [comment]
> how can i verify my domain like github said on the domain?

Just make a Pull request like https://github.com/is-a-dev/register/pull/6761 with your details as requested by GitHub.

**Comment by caodoc** [comment]
thanks man

**Comment by WilliamDavidHarrison** [comment]
I'm just going to comment again since my previous comment is buried above.

Please refer to https://github.com/is-a-dev/register/issues/6627#issuecomment-1666382002.

**Comment by WilliamDavidHarrison** [comment]
> @jcgaming-official I got this problem too. Help me. Is there a way to fix this on mobile device?

Please follow the steps in this comment: https://github.com/is-a-dev/register/issues/6794#issuecomment-1666690493

**Comment by thesanju** [comment]
> **You need to update your file which starts with `_github-pages-challenge`, not your main file.**
> 
> Please also note, your filename needs to be in **lowercase**.

So, I need to keep main file as it is and create a new file `_github-pages-challenge`, and TXT value there?

**Comment by caodoc** [comment]
> > **You need to update your file which starts with `_github-pages-challenge`, not your main file.**
> > Please also note, your filename needs to be in **lowercase**.
> 
> So, I need to keep main file as it is and create a new file `_github-pages-challenge`, and TXT value there?

yes

**Comment by sekharmalla** [comment]
Hi team, it's been more than 24 hours and yet I am still not seeing that verification had been completed. I have completed the following steps.


- [x] Create a TXT record in your DNS configuration for the following hostname: `_github-pages-challenge-sekharmalla.chandra`
- [x] Use this code for the value of the TXT record: Done too.   [_github-pages-challenge-sekharmalla.chandra.chandra.json](https://github.com/is-a-dev/register/blob/main/domains/_github-pages-challenge-sekharmalla.chandra.chandra.json) 
- [x] https://github.com/is-a-dev/register/pull/6669

still I am seeing the issue as `We were unable to verify ownership of chandra.is-a.dev. We couldn't find the TXT record. Note that DNS changes can take up to 24 hours.`

Please help me with a solution.

Thanks for all you do for the community.

**Comment by amalpotra** [comment]
> Hi team, it's been more than 24 hours and yet I am still not seeing that verification had been completed. I have completed the following steps.
> 
> * [x]  Create a TXT record in your DNS configuration for the following hostname: `_github-pages-challenge-sekharmalla.chandra`
> * [x]  Use this code for the value of the TXT record: Done too.   [_github-pages-challenge-sekharmalla.chandra.chandra.json](https://github.com/is-a-dev/register/blob/main/domains/_github-pages-challenge-sekharmalla.chandra.chandra.json)
> * [x]  [Update chandra.json #6669](https://github.com/is-a-dev/register/pull/6669)
> 
> still I am seeing the issue as `We were unable to verify ownership of chandra.is-a.dev. We couldn't find the TXT record. Note that DNS changes can take up to 24 hours.`
> 
> Please help me with a solution.
> 
> Thanks for all you do for the community.

Hey @sekharmalla, as I can see your file ends with the word `chandra` twice so, instead of `_github-pages-challenge-sekharmalla.chandra.chandra.json` you might need to rename your file to `_github-pages-challenge-sekharmalla.chandra.json`.

**Comment by andyfaizan** [comment]
What if I don't have a `_github-pages-challenge-` file? (I don't see mine atleast). Should I then create one?

**Comment by WilliamDavidHarrison** [comment]
Yes, you will need to create one.

**Comment by KenWuqianghao** [comment]
is it just me or I still can't verify the domain even after creating the needed files?

**Comment by WilliamDavidHarrison** [comment]
Did you open a PR and has the PR been merged?

**Comment by vikramv20** [comment]
what is the value we should put in the record txt.

**Comment by WilliamDavidHarrison** [comment]
The value GitHub Pages gives you.

**Comment by KenWuqianghao** [comment]
> Did you open a PR and has the PR been merged?

yeah, and i did insert the correct txt value given by github

**Comment by WilliamDavidHarrison** [comment]
Please verify the file name and TXT values are correct and if not, please change them and open another PR.

**Comment by WilliamDavidHarrison** [comment]
I'm going to close this issue as it seems to have been solved, for any future issues, please open a new issue.
