### ISSUE TITLE
Unable to access website

### ISSUE THREAD

**Issue by MysteriousK69** [is-a-dev/register#664]
So, I got approved for my is-a.dev domain and typed out "lawliet.host.is-a.dev". I expected to see my website, but instead it gave me an error.
The error I got was:
Did Not Connect: Potential Security Issue

Firefox detected a potential security threat and did not continue to lawliet.host.is-a.dev because this website requires a secure connection.

What can you do about it?

lawliet.host.is-a.dev has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.

The issue is most likely with the website, and there is nothing you can do to resolve it. You can notify the website’s administrator about the problem.

Please let me know if I am doing anything wrong or if it is an issue with the website.

**Comment by C1200** [comment]
Hi!
First of all the domain you wanted was "mysteriousk.is-a.dev" not "lawliet.host.is-a.dev".
Also, approval means nothing. It just means that your domain request is ready to merge to the main branch. Please wait for your PR to be merged.
Hope this helps!

**Comment by MysteriousK69** [comment]
oh alright, my bad :moyai:
