### ISSUE TITLE
Feedback/suggestion: Please add some more maintainers!

### ISSUE THREAD

**Issue by C1200** [is-a-dev/register#665]
Hi!
It would be great if this project would have more maintainers to merge the PRs so people can add, change or remove domains faster.

**Comment by TheBotlyNoob** [comment]
yes, @phenax, please add more maintainers!

**Comment by phenax** [comment]
You're right. Unfortunately, I'm unable to give as much time to this as I used to. I've created a post looking for new maintainers here -> https://github.com/is-a-dev/register/discussions/667

Closing this issue to resume the discussion over there.
