### ISSUE TITLE
can i get a txt record to verify my domain on github

### ISSUE THREAD

**Issue by boolean44-repos** [is-a-dev/register#6791]
You can elaborate here

**Comment by WilliamDavidHarrison** [comment]
Yes, you can. The GitHub Pages documentation can help you.

**Comment by boolean44-repos** [comment]
where?

**Comment by WilliamDavidHarrison** [comment]
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages

**Comment by boolean44-repos** [comment]
how should i put this in my file

**Comment by WilliamDavidHarrison** [comment]
You will need to create a new file with the name GitHub Pages provides you and the TXT set to the value it also provides you.
