### ISSUE TITLE
I got this problem too. Help me. Is there a way to fix this on mobile device?

### ISSUE THREAD

**Issue by ThisisThamizh** [is-a-dev/register#6794]
I got this problem too. Help me. Is there a way to fix this on mobile device?

_Originally posted by @jcgaming-official in https://github.com/is-a-dev/register/issues/6627#issuecomment-1666476385_

**Comment by WilliamDavidHarrison** [comment]
The only way to fix it on a mobile device is to do what is required, although it would be harder to do.

**Comment by ThisisThamizh** [comment]
yeah you can!

go to github web in your mobile > settings > "under `Code, planning, and automation`" pages > three dots in your is-a.dev domain tab > continue verifying,

now you can get the information to reverify your domain,

go to the `is-a.dev / resiger` that forked by you **In the browser**

in the browser url address bar, you could see the address of the repo you just forked,`https://github.com/is-a-dev/register/`

change the address 
from `https://github.com/is-a-dev/register/`
to `https://github.dev/is-a-dev/register/`

this will open the web editor for that particular repo

now you can follow the instructions given by `is-a.dev` dev 
https://github.com/is-a-dev/register/issues/6627#issuecomment-1666382002 ,

PR and wait for the PR to get merged

if the PR got merged, return to the domain verification tab and hit verify to successfully finish your work!
