### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by 7xh** [is-a-dev/register#682]
Your domain name:flexico.is-a.dev

Explain any issues you are facing
The CNAME `flexico.is-a.dev/` is not properly formatted. See https://docs.github.com/articles/troubleshooting-custom-domains/#github-repository-setup-errors for more information.

says that when i try to link domain and when i go to it i get a security error

**Comment by jasonappah** [comment]
I think it should work if you get rid of that trailing slash.

**Comment by mtgsquad** [comment]
Yes, please remove the slash

**Comment by Codeize** [comment]
Hi! Is this issue still active? @7xh

**Comment by phenax** [comment]
Closing this issue as it seems like the website seems to be working now.
