### ISSUE TITLE
AdGuard Family blocking `is-a.dev` and subdomains

### ISSUE THREAD

**Issue by thunder-coding** [is-a-dev/register#6838]
### Expected outcome

AdGuard Family should not block is-a.dev

### Observed outcome

Cloudflare DNS :+1:
```
$ dnslookup is-a.dev 1.1.1.1
dnslookup v1.9.1
dnslookup result (elapsed 237.200857ms):
;; opcode: QUERY, status: NOERROR, id: 53708
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;is-a.dev.      IN       A

;; ANSWER SECTION:
is-a.dev.       1200    IN      A       68.65.123.44
```

With Google DNS (8.8.8.8) :+1:

```
$ dnslookup is-a.dev 8.8.8.8
dnslookup v1.9.1
dnslookup result (elapsed 136.851108ms):
;; opcode: QUERY, status: NOERROR, id: 19213
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;is-a.dev.      IN       A                                                 
;; ANSWER SECTION:
is-a.dev.       1200    IN      A       68.65.123.44
```

With AdGuard Default (blocks ads + trackers) :+1:
```
$ dnslookup is-a.dev 94.140.14.14
dnslookup v1.9.1                                                           dnslookup result (elapsed 409.14004ms):
;; opcode: QUERY, status: NOERROR, id: 52383
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;is-a.dev.      IN       A

;; ANSWER SECTION:
is-a.dev.       1200    IN      A       68.65.123.44

$ dnslookup is-a.dev 94.140.15.15
dnslookup v1.9.1
dnslookup result (elapsed 156.634599ms):
;; opcode: QUERY, status: NOERROR, id: 26887
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;is-a.dev.      IN       A

;; ANSWER SECTION:
is-a.dev.       1183    IN      A       68.65.123.44
```

AdGuard non-filtering (same result as for above default filtering one) :+1:

AdGuard Family :-1:

```
$ dnslookup is-a.dev 94.140.14.15
dnslookup v1.9.1
dnslookup result (elapsed 167.088819ms):
;; opcode: QUERY, status: NOERROR, id: 22995
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;is-a.dev.      IN       A

;; ANSWER SECTION:
is-a.dev.       3600    IN      A       94.140.14.35

$ dnslookup is-a.dev 94.140.15.16
dnslookup v1.9.1
dnslookup result (elapsed 198.463718ms):
;; opcode: QUERY, status: NOERROR, id: 31559
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;is-a.dev.      IN       A

;; ANSWER SECTION:
is-a.dev.       3600    IN      A       94.140.14.35
```

Note that 68.65.123.44 is the good IP, 94.140.14.35 returns a site displaying that access to the site was denied (can't open in browser as Firefox refuses to open the page due to.SSL certificate errors). Raw HTML can be viewed with `curl -k`. **WARNING: `-k` WILL IGNORE ANY CERTIFICATE**

More information about AdGuard DNS
https://adguard-dns.io/en/public-dns.html

## Additional details

This issue was found as I was not able to connect to any of `*.is-a.dev` as well as `is-a.dev` on my phone. I use a VPN server running on localhost which disables ads by DNS injection (basically all ad sites are routed to 0.0.0.0, this disables ads on most sites improving my internet experience). This along with uBlock origin gives a really clean experience on my phone. A temporary workaround for me is to use CloudFlare ot Google's DNS servers. This doesn't make any difference to me as I have a separate blocklist as well which disables ad sites which are not included by AdGuard

**Comment by WilliamDavidHarrison** [comment]
I believe you can open a thread here: https://forum.adguard.com/index.php?forums/false-positives.68/

**Comment by thunder-coding** [comment]
> I believe you can open a thread here: https://forum.adguard.com/index.php?forums/false-positives.68/

Posting on forum requires an account to be created. I've reported this issue on GitHub though https://github.com/AdguardTeam/AdguardFilters/issues/158457

**Comment by thunder-coding** [comment]
I can confirm that AdGuard Family DNS is no longer blocking any of `is-a.dev` or subdomain. They have removed the site from parental control list
