### ISSUE TITLE
it's been more than 24 hours and yet I am still not seeing that verification had been completed. I have completed the following steps.

### ISSUE THREAD

**Issue by ThisisThamizh** [is-a-dev/register#6840]
Hi team, it's been more than 24 hours and yet I am still not seeing that verification had been completed. I have completed the following steps.

- [x] Create a TXT record in your DNS configuration for the following hostname: `_github-pages-challenge-sekharmalla.chandra`
- [x] Use this code for the value of the TXT record: Done too.   [_github-pages-challenge-sekharmalla.chandra.chandra.json](https://github.com/is-a-dev/register/blob/main/domains/_github-pages-challenge-sekharmalla.chandra.chandra.json) 
- [x] https://github.com/is-a-dev/register/pull/6669

still I am seeing the issue as `We were unable to verify ownership of chandra.is-a.dev. We couldn't find the TXT record. Note that DNS changes can take up to 24 hours.`

Please help me with a solution.

Thanks for all you do for the community.

_Originally posted by @sekharmalla in https://github.com/is-a-dev/register/issues/6627#issuecomment-1666921319_

**Comment by amalpotra** [comment]
This might help https://github.com/is-a-dev/register/issues/6627#issuecomment-1666931981

**Comment by ThisisThamizh** [comment]
i see you've changed your main file entirely different than it's need to be looks like while re-verification.

I think you could solve this problem by re-editing your main file to make it to be as it is before
the re-verification.

you many use my main domain file for reference - https://github.com/is-a-dev/register/blob/a88ca8e1886747fe85c94a11633b1403ecd49ca3/domains/thamizh.json

after finishing the work open another PR to fix this problem  _in my opinion_ 

@sekharmalla
