### ISSUE TITLE
Cannot link the domain with my Replit repl

### ISSUE THREAD

**Issue by Hyderite** [is-a-dev/register#6870]
As the title suggests, I cannot link the domain hyderite.is-a.dev with my [Replit repl](https://replit.com/@Hyderite/Hyderite) (it's been 48 hours). I have correctly added the CNAME record from Replit (as shown in the image below), but it still doesn't work. Thank you in advance.

![image](https://github.com/is-a-dev/register/assets/79314475/19392984-19b5-4bc3-872a-e01163953f6a)
![image](https://github.com/is-a-dev/register/assets/79314475/49b228d2-900c-4494-a2c8-8caa549266ca)

**Comment by WilliamDavidHarrison** [comment]
Replit is now requiring a TXT verification record, which we do not support. I would recommend using another service such as GitHub Pages.
