### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Avnoor-Gamerz** [is-a-dev/register#693]
My website is not working

**Comment by hackermondev** [comment]
@Avnoor-Gamerz please give me more data. can u send the link of the website and what error does it show?

**Comment by mtgsquad** [comment]
> @Avnoor-Gamerz please give me more data. can u send the link of the website and what error does it show?

Dude, leave it, i don't think this guy knows that we have to approve his PR. It hasn't been approved yet. @Avnoor-Gamerz Just wait a little while

**Comment by mtgsquad** [comment]
I meant it hasn't been merged yet, wait.

**Comment by phenax** [comment]
@Avnoor-Gamerz, I'm closing this issue for now as it seems your domain hasn't been merged yet. Feel free to create a new issue in case you have any other questions or if you run into some trouble setting things up after the domain has been published.
