### ISSUE TITLE
`is-a.dev` domain blocked by Bing

### ISSUE THREAD

**Issue by j-eo** [is-a-dev/register#6989]
It seems like `is-a.dev` and all of its subdomains are not showing up on Bing and DuckDuckGo results. [Try for yourselves](https://www.bing.com/search?q=site:is-a.dev).

Can you check this issue on [Bing Webmaster Tools](https://www.bing.com/webmasters/about)?

Thank you.

**Comment by WilliamDavidHarrison** [comment]
I don't think there is much we can do about this unfortunately due to how Bing works.
After searching for a solution, I cannot find one.

I would just recommend using Google instead.

**Comment by j-eo** [comment]
@WilliamDavidHarrison, can you clarify on what happened? Is the domain breaking the [Bing Webmaster Guidelines](https://www.bing.com/webmasters/help/webmaster-guidelines-30fba23a)?

**Comment by WilliamDavidHarrison** [comment]
I'm not sure why it happened, but we have verified the domain and Bing is now re-indexing the domain.

This issue should be solved.
