### ISSUE TITLE
Cannot change domain to custom domain

### ISSUE THREAD

**Issue by HmonsterG** [is-a-dev/register#6992]
Hi guys,
When i try to access the page I get this error `NET::ERR_CERT_COMMON_NAME_INVALID` due to it using HSTS. I figured this is as I have not changed by domain on my github pages settings to the new `is-a.dev` domain, however, when I try to do this I recieve the following error: `You must verify your domain soap.is-a.dev before being able to use it.`, in user settings I am required to add a domain (I did) and verify it, however I am unsure of how to verify it as Im required to create a text record for a hostname using a code for the value. 
Full steps as copied from that page:
```
1. Create a TXT record in your DNS configuration for the following hostname: _github-pages-challenge-HmonsterG.soap.is-a.dev
2. Use this code for the value of the TXT record: <key>
3. Wait until your DNS configuration changes. This could take up to 24 hours to propagate.
```
Therefore I don't really know how to advance from here to get the site working.

After reading some closed issues, I found this issue which I believe to be relevant #3385. Is there a solution to requiring TXT verification, or should I move to another hosting platform?

**Comment by j-eo** [comment]
Create a json file called `_github-pages-challenge-HmonsterG.soap.json` and add the TXT record like so:
``` json
{
  "record": {
    "TXT": "<key>"
  }
}
```
Alternatively, you can use Cloudflare Pages which doesn't require TXT record verification.

**Comment by HmonsterG** [comment]
Thanks :D I made the pull request and it was approved; now I just need to wait 24 hours to turn on HTTPs.
