### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by nikeedev** [is-a-dev/register#7229]
Your domain name: nikeedev.is-a.dev

Explain any issues you are facing

I removed by doamin in the issue #6600, but if you go to my normal https://nikeedev.github.io/ it redirects for some reason back to is-a.dev website. Github reports they sent github pages to https://nikeedev.github.io/, but it still does redirect. The issue is probably at yours side as all cname files and all settings deleted, your domain is still catching mine website.

Website repo https://github.com/nikeedev/nikeedev.github.io

**Comment by WilliamDavidHarrison** [comment]
You need to delete your CNAME file, it is not an issue on our end.

**Comment by nikeedev** [comment]
@WilliamDavidHarrison are you crazy? I told you that CNAME file is deleted. Have you ever visited the repo that I mentioned.

**Comment by WilliamDavidHarrison** [comment]
Sorry, I was very tired when I was looking over this issue and I must've misread it.

Please try clearing your browser's cache.

**Comment by nikeedev** [comment]
Nvm, the website is working now, although it didn’t for 2 weeks?! Did you do anything @WilliamDavidHarrison?

**Comment by WilliamDavidHarrison** [comment]
Your browser would've cached the redirect which is why it still redirected the github.io domain.
