### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PsxScriptsW** [is-a-dev/register#7400]
Unable to connect to FTP server hosts.is-a.dev21 on port 21.

Are you sure this is the address of the FTP server? This is often different from that of the HTTP (web) server. Please contact your ISP helpdesk or system administrator for help.

  what does this mean it wont let me upload files

**Comment by WilliamDavidHarrison** [comment]
You are trying to connect to `hosts.is-a.dev21`, not `hosts.is-a.dev`. I think you accidently put `21` in the FTP server field.

**Comment by PsxScriptsW** [comment]
What do I put in the ftp then or do put nothing

**Comment by PsxScriptsW** [comment]
Because it says this 

Host: hosts.is-a.dev
Port: 21
Username: notugotskillz
Password: Set by User

**Comment by WilliamDavidHarrison** [comment]
On the dashboard, click the link which says "Manage files" and enter your FTP password and manage them that way.
