### ISSUE TITLE
Report abuse

### ISSUE THREAD

**Issue by lyertia** [is-a-dev/register#751]
Domain you want to report: 

### Reason
My domain lyertia.is-a.dev is a not active

**Comment by lyertia** [comment]
lyertia.json file exists

**Comment by hackermondev** [comment]
This isn't abuse 😑

**Comment by hackermondev** [comment]
and your domains works perfectly for me. its just redirects to lyertia.me. try clearing your cache

**Comment by lyertia** [comment]
ah okay sorry
