### ISSUE TITLE
2 approvals?

### ISSUE THREAD

**Issue by TheBotlyNoob** [is-a-dev/register#752]
I think merging wold go much faster if we were able to merge with 2 approvals.

**Comment by mtgsquad** [comment]
Yes, i think this is a good idea @phenax since me and botly are pretty active, we could just quickly merge and review PRs

**Comment by hackermondev** [comment]
sure

**Comment by FatGrizzly** [comment]
Hmmm, seems good

**Comment by TheBotlyNoob** [comment]
@phenax any thoughts?

**Comment by phenax** [comment]
This isn't a topic for a github issue. We have a discord chat for this. I'll make it 2.
