### ISSUE TITLE
no verify email, cannot use domain.

### ISSUE THREAD

**Issue by thetoasta** [is-a-dev/register#7554]
domain: toasta.is-a.dev

never got a verify email

**Comment by thetoasta** [comment]
i'm using vercel also

**Comment by thetoasta** [comment]
so i'm not using vercel, but i need a verify email

**Comment by andrewstech** [comment]
> toasta.is-a.dev

I've manually activated it for you. :) 

Re open this issue if you have anymore problems

**Comment by thetoasta** [comment]
thanks!

**Comment by thetoasta** [comment]
yoo it works
