### ISSUE TITLE
Support AAAA records

### ISSUE THREAD

**Issue by notomne** [is-a-dev/register#7617]
I just enabled IPv6 on my AWS EC2 instance and opened a pull request (#7614) to add the IPv6, but noticed it failed a check - it appears AAAA records aren't supported.

We need more websites to support IPv6 if we want to move away from IPv4, and I believe the effects of IPv4 address exhaustion are already known. I won't explain the benefits of IPv6 again because there's entire articles, indeed, entire websites, dedicated to doing such.

Thanks~

**Comment by WilliamDavidHarrison** [comment]
For now you will need to use an IPv4 address as we don't support IPv6 addresses as of now, but I will ask @phenax to work on getting AAAA records added.

**Comment by phenax** [comment]
This is the most I've heard anyone go doomsday-mode for IPv6 in a while now XD. But yeah, I agree, we definitely should support `AAAA` records. I'll try to pick it up in the next couple of weeks.
