### ISSUE TITLE
Clarification on requirements for <domain>.json

### ISSUE THREAD

**Issue by EpicGamer007** [is-a-dev/register#762]
I would like to get a `.is-a.dev` domain with this service. According to [domains-json.md](https://github.com/is-a-dev/register/blob/main/docs/domains-json.md), we are supposed to add an email, and if not an email, a social media site. However, I am confused by what will count as a "social media" site for this service. I do not feel comfortable giving my email but I do not use any mainstream "social media" sites such as twitter, facebook, etc. The only "social media" like site I can think of which I use is [discord](https://discord.com) and [repl talk](https://replit.com/talk/all), however I am not entirely sure if these can count as "social media". Any clarification on this topic would be appreciated. And sorry if I am asking a dumb question..

**Comment by TheBotlyNoob** [comment]
You are able to use any social media site, as there is no check for this. As long as there is sufficient information, you should be ok 😃.

**Comment by EpicGamer007** [comment]
Ok thank you :)
