### ISSUE TITLE
Mail forwarded automatically for is-s.dev hosted pages?

### ISSUE THREAD

**Issue by lfom** [is-a-dev/register#7760]
Hello!

First of all, thank you a lot for providing a short URL to host personal projects/pages for free, with a simple sign up procedure. 

I have seen some entries that seem to have been configured to host the page with is-a.dev. Besides the A record pointing to its IPv4, they also have a MX record pointing to hosts.is-a.dev and also a TXT record with a spf config for the same IP.

Does it mean that when hosting the page using is-a.dev all mail (i.e. catchall address) will be forwarded to the registered user email?

I've looked around and didn't find any info about the MX record pointing to hosts.is-a.dev, so I decided to ask here before trying to register a new subdomain.

By the way, I've seen some people registering multiple addresses, is it OK?

Thanks again! Regards.

**Comment by WilliamDavidHarrison** [comment]
Hi there, I might be able to answer most of your questions.

You are currently able to send emails with your domain using SMTP. But the MX records are not used at the moment but will be in the future as we are working on an email server so you can send & receive emails using your is-a.dev subdomain.

You are allowed to register as many subdomains as you would like with us :)

**Comment by lfom** [comment]
Understood. I will keep this issue open until the e-mail service (that uses the is-a.dev MX record) is released, but feel free to close it if preferable.

Thank you again!

**Comment by lfom** [comment]
@WilliamDavidHarrison

Hello, there! I hope you are OK. Closing the issue means this was implemented or abandoned? 

Regards

**Comment by WilliamDavidHarrison** [comment]
In your comment above you sent this:
> but feel free to close it if preferable.
