### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by CycloneAddons** [is-a-dev/register#7872]
Your domain name: deepesh.is-a.dev

Explain any issues you are facing

Why domain not registering on Infinityfree 

![Screenshot_2023-09-16-15-16-14-120_com android chrome](https://github.com/is-a-dev/register/assets/90061864/bf7ae5ef-ddfd-4a48-a005-98f5beaf6da0)

**Comment by PhoenixOrigin** [comment]
That can't work; using infinity free would entail letting them manage the namservers. AFAIK, this means all the existing domains won't work; infinity free will modify the DNS to only work on their servers. Instead, you can use the free is-a.dev web hosting and upload your project files there
