### ISSUE TITLE
Feedback/suggestion: Dealing with Let’s Encrypt Rate Limits

### ISSUE THREAD

**Issue by fu-sen** [is-a-dev/register#793]
I look like `is-a.dev` is currently accepting several `subdomain.is-a.dev` registrations almost every day.
If the number of registrations increases in the future,
there is a concern that the Let's Encrypt Rate Limits will cause problems in issuing certificates.
Perhaps in the future of `is-a.dev` there is a possibility of registering 50 subdomains a week.
https://letsencrypt.org/docs/rate-limits/

It will take days to deal with it, so it is safe to do it now, Will be one of the following:
- Apply using the `rate limiting form` at the URL above (Have you done this already?)
- Register to [Public Suffix List ](https://publicsuffix.org/) ([JS.ORG](https://js.org/) registered)

For reference, the certificate issuance status of `it-s.dev`:
https://crt.sh/?q=is-a.dev

**Comment by phenax** [comment]
@fu-sen. The certificates for is-a.dev are registered as a wildcard instead of one per subdomain. So the rate limit will not be a problem. Currently, we register 2 certificates every 3 months, one for the host domain and another for the subdomains.

Closing this issue for now. Feel free to re-open it if I misunderstood your suggestion.

**Comment by fu-sen** [comment]
Yup? That's when you admins happen, but `SUBDOMAIN.Is-a.dev` prompts users to publish individually.
It will be issued by different email addresses, web services, hosting, etc., so it will count differently.

**Comment by fu-sen** [comment]
I'll put this link again for you to confirm:
https://crt.sh/?q=is-a.dev

There is no wildcard certificate `*.is-a.dev` here. 
Mostly personally issued `SUBDOMAIN.is-a.dev`. The dates are also completely individual.

**Comment by phenax** [comment]
@fu-sen, Thank you for the suggestion. I will be adding is-a.dev to the public suffix list.

**Comment by fu-sen** [comment]
If you leave it closed, you'll get confused issues in months or years. I am relieved that you understand.
If you forget this TODO, don't forget to re-open.

**Comment by phenax** [comment]
@fu-sen, I have acknowledge this issue and have already created a pull request for the public suffix listing of is-a.dev.

On a more personal note, enough with the condescending tone. I'm going to give you the benefit of the doubt if english isn't your first language but there is a better way to communicate with open source projects and for your sake, I hope you learn it.

**Comment by fu-sen** [comment]
I usually speak Japanese, so I take the time to translate this issue into English.
I thought it was an issue that needed to be done up to that point.
You closed it right away! It's an angry and natural act.
Please understand if I have commented so far.

**Comment by phenax** [comment]
I understand. The thing is even before, with your pr, I didn't agree with your tone towards the other maintainers here. I really appretiate you taking the time to open this issue and I'm sure your intentions are pure but the maintainers here are just people taking time off their day to help out. I apologize if I came off a bit harsh or rude, that was not my intention.
Anyways, thank you for informing us about this!
