### ISSUE TITLE
Support for `_discord` subdomains

### ISSUE THREAD

**Issue by WilliamDavidHarrison** [is-a-dev/register#7933]
Allow users to connect their domains to their Discord account by allowing DNS verification. Currently it is already possible with HTTPS verification, but DNS verification would also be good.

**Comment by 2618Zahid** [comment]
It's been 24 hours still why my domain not approved

**Comment by DEV-DIBSTER** [comment]
> It's been 24 hours still why my domain not approved

@2618Zahid Wrong issue bucko, this issue is related to a suggestion, not a place to ask about pull request status.
