### ISSUE TITLE
SSL error with GitHub Pages

### ISSUE THREAD

**Issue by sushi-ae** [is-a-dev/register#8102]
Your domain name: sushi.is-a.dev

My domain currently has a CNAME record that is set to "sushi-ae.neocities.org"
registered over the CLI tool. (already merged)

Today, I transferred the files from my neocities website to a github pages repo
[here](https://github.com/sushi-ae/sushi-ae.github.io), however, even when unpublished, sushi-ae.github.io still redirects to sushi.is-a.dev. (there is no CNAME in the repo yet)

![image](https://github.com/is-a-dev/register/assets/118438453/3f747226-9f41-4ede-98de-157b03966963)
![image](https://github.com/is-a-dev/register/assets/118438453/87a0c20b-a668-4a0d-a0c5-02667b5c1dd9)

it does this instantaneously, so i'm pretty lost right now. I cant find a solution to it

**Comment by WilliamDavidHarrison** [comment]
Have you tried clearing your browser cache?

**Comment by sushi-ae** [comment]
Enforce HTTPS is ticked yes, and no I haven't tried clearing the browser cache, i'll try that right now

**Comment by sushi-ae** [comment]
oh thanks so much, clearing the browser cache worked, can I submit a new PR now?

**Comment by WilliamDavidHarrison** [comment]
Yes
