### ISSUE TITLE
Missing www.json

### ISSUE THREAD

**Issue by phenax** [is-a-dev/register#8126]
@andrewstech can you please explain these prs that were merged into main?

- https://github.com/is-a-dev/register/pull/6622
- https://github.com/is-a-dev/register/pull/6625
- https://github.com/is-a-dev/register/pull/6637
- https://github.com/is-a-dev/register/pull/6640

**Comment by andrewstech** [comment]
I believe it was when we were trying to verify a wildcard SSL certificate for the webhosting. Before we managed to get in contact.

**Comment by phenax** [comment]
That's alright but that doesn't explain deleting the www record without communication
