### ISSUE TITLE
Broken URL Redirects

### ISSUE THREAD

**Issue by VaibhavSys** [is-a-dev/register#8171]
This issue is related to #1150, which addresses unused/broken domains.

We've noticed that some registered domains are broken or unused. If you've parked a domain for later use, consider giving someone else the chance to put it to good use. Feel free to comment here if you need assistance or want to share your domain.

| Name | Email | Domain | Broken URL | Path |
| ---- | ----- | ------ | ---------- | ---- |
| @s3mant | contact@semant.is-a.dev | [panda.is-a.dev](https://panda.is-a.dev) | [https://semant.panda.is-a.dev](https://semant.panda.is-a.dev) | https://github.com/is-a-dev/register/blob/main/domains/panda.json |
| @Kobe523 | kfni@madison.k12.wi.us | [kobeff.is-a.dev](https://kobeff.is-a.dev) | [https://its.kobeff.repl.co](https://its.kobeff.repl.co) | https://github.com/is-a-dev/register/blob/main/domains/kobeff.json |
| @Riotly | email@oharsh.vip | [harsh.is-a.dev](https://harsh.is-a.dev) | [https://oharsh.vip](https://oharsh.vip) | https://github.com/is-a-dev/register/blob/main/domains/harsh.json |
| @dropheart | ahmed@techfromtheheart.com | [ahmed.is-a.dev](https://ahmed.is-a.dev) | [https://techfromtheheart.com](https://techfromtheheart.com) | https://github.com/is-a-dev/register/blob/main/domains/ahmed.json |
| @iiMaxxi | iimaxxiguilham@gmail.com | [guilherme.is-a.dev](https://guilherme.is-a.dev) | [https://eu.dzxdev.repl.co](https://eu.dzxdev.repl.co) | https://github.com/is-a-dev/register/blob/main/domains/guilherme.json |
| @ba-e | bae.nyom@gmail.com | [bae.is-a.dev](https://bae.is-a.dev) | [https://bae.codes](https://bae.codes) | https://github.com/is-a-dev/register/blob/main/domains/bae.json |
| @Fauzannnnh | fauzan@eenthlh.xyz | [fauzannnnh.is-a.dev](https://fauzannnnh.is-a.dev) | [https://eenthlh.xyz](https://eenthlh.xyz) | https://github.com/is-a-dev/register/blob/main/domains/fauzannnnh.json |
| @baumistlustig | johannes.hoellwerth@protonmail.com | [baumistlustig.is-a.dev](https://baumistlustig.is-a.dev) | [https://baumistlustig.eu](https://baumistlustig.eu) | https://github.com/is-a-dev/register/blob/main/domains/baumistlustig.json |
| @adripo | adripo@hi2.in | [adri.is-a.dev](https://adri.is-a.dev) | [https://adri.ninja](https://adri.ninja) | https://github.com/is-a-dev/register/blob/main/domains/adri.json |
| @kaiodcosta | kaiod@riseup.net | [k4i0d.is-a.dev](https://k4i0d.is-a.dev) | [https://kaiod.icu](https://kaiod.icu) | https://github.com/is-a-dev/register/blob/main/domains/k4i0d.json |
| @n3rd3x3 | me@n3rd3x3.xyz | [nerd.is-a.dev](https://nerd.is-a.dev) | [https://n3rd3x3.xyz](https://n3rd3x3.xyz) | https://github.com/is-a-dev/register/blob/main/domains/nerd.json |
| @hodss | hod@hodss.xyz | [hod.is-a.dev](https://hod.is-a.dev) | [https://hodss.xyz/?refer=is-a-dev](https://hodss.xyz/?refer=is-a-dev) | https://github.com/is-a-dev/register/blob/main/domains/hod.json |
| @cooper25 | cooper@tsor.is | [cooper.is-a.dev](https://cooper.is-a.dev) | [https://cppr.dev](https://cppr.dev) | https://github.com/is-a-dev/register/blob/main/domains/cooper.json |
| @Krchip | elite7744@gmail.com | [chip.is-a.dev](https://chip.is-a.dev) | [https://krchip.github.io](https://krchip.github.io) | https://github.com/is-a-dev/register/blob/main/domains/chip.json |
| @imsudip | sudipghosh9333@gmail.com | [imsudip.is-a.dev](https://imsudip.is-a.dev) | [https://portfolio.imsudip.ml](https://portfolio.imsudip.ml) | https://github.com/is-a-dev/register/blob/main/domains/imsudip.json |
| @itsbravestone | imbravestone@zarena.ga | [bravestone.is-a.dev](https://bravestone.is-a.dev) | [https://imbravestone.ga](https://imbravestone.ga) | https://github.com/is-a-dev/register/blob/main/domains/bravestone.json |
| @iancheung0202 | support@ianbrawlstars.com | [iancheung.is-a.dev](https://iancheung.is-a.dev) | [https://ianbrawlstars.com](https://ianbrawlstars.com) | https://github.com/is-a-dev/register/blob/main/domains/iancheung.json |
| @KodingDev | kodingdev@pm.me | [koding.is-a.dev](https://koding.is-a.dev) | [https://koding.dev](https://koding.dev) | https://github.com/is-a-dev/register/blob/main/domains/koding.json |
| @onem0 | kremersneo0@gmail.com | [thiomains.is-a.dev](https://thiomains.is-a.dev) | [http://bindergamer.de](http://bindergamer.de) | https://github.com/is-a-dev/register/blob/main/domains/thiomains.json |
| @ajachintya | ajachintyajaiswal@gmail.com | [achintya.is-a.dev](https://achintya.is-a.dev) | [https://portfolio-app-production.up.railway.app](https://portfolio-app-production.up.railway.app) | https://github.com/is-a-dev/register/blob/main/domains/achintya.json |
| @Johna-123 | j-verstraaten@hotmail.com | [johna.is-a.dev](https://johna.is-a.dev) | [https://johna.is-a-fullstack.dev](https://johna.is-a-fullstack.dev) | https://github.com/is-a-dev/register/blob/main/domains/johna.json |
| @austindyoung | austin@doesweb.dev | [austin.is-a.dev](https://austin.is-a.dev) | [http://austindyoung.github.io](http://austindyoung.github.io) | https://github.com/is-a-dev/register/blob/main/domains/austin.json |
| @kr-tukimi |  | [tukimi.is-a.dev](https://tukimi.is-a.dev) | [https://tuki.dev](https://tuki.dev) | https://github.com/is-a-dev/register/blob/main/domains/tukimi.json |
| @InfiniteCode | infinitecode@infiniteco.de | [infinitecode.is-a.dev](https://infinitecode.is-a.dev) | [https://infiniteco.de](https://infiniteco.de) | https://github.com/is-a-dev/register/blob/main/domains/infinitecode.json |
| @didiermunezero | didiermunezer38@gmail.com | [didier.is-a.dev](https://didier.is-a.dev) | [https://munezero.me](https://munezero.me) | https://github.com/is-a-dev/register/blob/main/domains/didier.json |
| @ailakks | hola@cortmnzz.com | [ailakks.is-a.dev](https://ailakks.is-a.dev) | [https://cortmnzz.com](https://cortmnzz.com) | https://github.com/is-a-dev/register/blob/main/domains/ailakks.json |
| @jy1263 |  | [ayanamy.is-a.dev](https://ayanamy.is-a.dev) | [https://jy1263.github.io](https://jy1263.github.io) | https://github.com/is-a-dev/register/blob/main/domains/ayanamy.json |
| @Attachment-Studios | aditya.adigo@gmail.com | [attaditya.is-a.dev](https://attaditya.is-a.dev) | [https://attaditya.deta.dev](https://attaditya.deta.dev) | https://github.com/is-a-dev/register/blob/main/domains/attaditya.json |
| @hikaruisasleep | i@jxcb.xyz | [jxcb.is-a.dev](https://jxcb.is-a.dev) | [https://jxcb.xyz](https://jxcb.xyz) | https://github.com/is-a-dev/register/blob/main/domains/jxcb.json |
| @Atzu | atzu@nextgenteam.tech | [atzu.is-a.dev](https://atzu.is-a.dev) | [https://atzu.studio](https://atzu.studio) | https://github.com/is-a-dev/register/blob/main/domains/atzu.json |
| @CodeWhiteWeb | web.codewhite@gmail.com | [codewhiteweb.is-a.dev](https://codewhiteweb.is-a.dev) | [https://codewhiteweb.cf](https://codewhiteweb.cf) | https://github.com/is-a-dev/register/blob/main/domains/codewhiteweb.json |
| @mrshoeshoe66 | mrshoeshoe66@gmail.com | [mrshoe.is-a.dev](https://mrshoe.is-a.dev) | [https://mrshoe.dev](https://mrshoe.dev) | https://github.com/is-a-dev/register/blob/main/domains/mrshoe.json |
| @18o4 |  | [18o4.is-a.dev](https://18o4.is-a.dev) | [https://18o4.tk](https://18o4.tk) | https://github.com/is-a-dev/register/blob/main/domains/18o4.json |
| @michaelbelete | it.michael.belete@gmail.com | [michaelbelete.is-a.dev](https://michaelbelete.is-a.dev) | [https://michaelb.iceiy.com](https://michaelb.iceiy.com) | https://github.com/is-a-dev/register/blob/main/domains/michaelbelete.json |
| @fuccsoc | me@fuccsoc.com | [fuccsoc.is-a.dev](https://fuccsoc.is-a.dev) | [https://fuccsoc.com](https://fuccsoc.com) | https://github.com/is-a-dev/register/blob/main/domains/fuccsoc.json |
| @willothy | willothyh@gmail.com | [willothy.is-a.dev](https://willothy.is-a.dev) | [https://willothy.com](https://willothy.com) | https://github.com/is-a-dev/register/blob/main/domains/willothy.json |

**Comment by Rayrsn** [comment]
Hi my domain isn't broken and https://guess-who.is-a.dev/ gets successfully redirected to my homepage ([rayr.link](https://rayr.link/))

**Comment by WilliamDavidHarrison** [comment]
@Rayrsn It redirects to a 403 error page, hence why it was listed here.

**Comment by Rayrsn** [comment]
The root page is designed to always return a 403 response.
An example of a correct use case for my domain would be (https://guess-who.is-a.dev/LinkInBio) which would redirect the user to (https://rayr.link/LinkInBio)

**Comment by WilliamDavidHarrison** [comment]
@Rayrsn Can you make the main page redirect to something? Then I will remove it from this list.

**Comment by Rayrsn** [comment]
@WilliamDavidHarrison Alright

**Comment by Alex-idk** [comment]
Mine is redirecting fine (https://alexidk.is-a.dev), what's the issue?

**Comment by WilliamDavidHarrison** [comment]
@Alex-idk The script is not 100% perfect, either way I have removed your domain from the list 😄

**Comment by Rayrsn** [comment]
@WilliamDavidHarrison Can you check mine again?
also 
@Alex-idk I like the minimalistic design!

**Comment by WilliamDavidHarrison** [comment]
@Rayrsn Yep, it works. I am removing your domain from the list.

**Comment by NiHaiden** [comment]
Hi world, I forgot I had a name registered here and for that I am sorry. I updated all the relevant details and opened a PR #8177.

**Comment by WilliamDavidHarrison** [comment]
@NiHaiden All good, I have merged your PR!

**Comment by J0J0HA** [comment]
Hello, my domain (jojojux.is-a.dev) seems to be redirecting fine. Can I know why I am listed here?

**Comment by OnionDev1885** [comment]
Hello there,
My domain isn't broken.
https://onion.is-a.dev successfully redirects to https://trgop.gq

**Comment by WilliamDavidHarrison** [comment]
> Its a redirect, please dont ban me

You won't get banned, you just need to fix it and make it redirect to a valid website.

**Comment by WilliamDavidHarrison** [comment]
> Hello, my domain (jojojux.is-a.dev) seems to be redirecting fine. Can I know why I am listed here?

The script isn't perfect so it's probably just an error on the script, I will remove your domain from the list.

**Comment by Alex-idk** [comment]
> @Alex-idk The script is not 100% perfect, and your domain seems to be redirecting properly so I have removed your domain from the list 😄

All good!
Probably just cloudflare being cloudflare

**Comment by WilliamDavidHarrison** [comment]
> Hello there, My domain isn't broken. [onion.is-a.dev](https://onion.is-a.dev) successfully redirects to [trgop.gq](https://trgop.gq)

All good, it does seem to be redirecting properly. I have removed your domain from the list.

**Comment by fuccsoc** [comment]
Is redirect records still available for registration?

**Comment by dev0cloo** [comment]
Hello, I won't be putting the site back up for a while so you can go ahead and remove from the list. Thank you.

**Comment by lynix27** [comment]
My domain is a redirect. Why am I listed here?

**Comment by Johna-123** [comment]
Sorry about that, I'm just redoing my site, should be back up soon.

**Comment by WilliamDavidHarrison** [comment]
> My domain is a redirect. Why am I listed here?

You are listed here because your website is most likely unreachable, please double check it.

**Comment by bast0006** [comment]
Since I've already been removed from the remove list, I'll drop off the issue! Thanks for proactive cleanup, this was probably an SSL expiry problem on my end due to beta server software, [site's been up the whole time](https://stats.uptimerobot.com/ZyjozS7A1m). If that's not the case please do @ me.

**Comment by abhisekp** [comment]
Mine is redirecting appropriately as well [abhisekp.is-a.dev](https://abhisekp.is-a.dev/) to [https://abhisekp.com](https://https//abhisekp.com)

**Comment by sn3kdev** [comment]
> > Its a redirect, please dont ban me
> 
> You won't get banned, you just need to fix it and make it redirect to a valid website.

It already redirects to my TG. Or I should set a domain?

**Comment by WilliamDavidHarrison** [comment]
> Mine is redirecting appropriately as well [abhisekp.is-a.dev](https://abhisekp.is-a.dev/) to [https://abhisekp.com](https://https//abhisekp.com)

I've removed your domain from the list.

**Comment by WilliamDavidHarrison** [comment]
> It already redirects to my TG. Or I should set a domain?

All good, I have removed your domain from the list.

**Comment by lynix27** [comment]
> > My domain is a redirect. Why am I listed here?
> 
> You are listed here because your website is most likely unreachable, please double check it.

Its redirecting to my linktree, which is reachable

**Comment by WilliamDavidHarrison** [comment]
> Its redirecting to my linktree, which is reachable. I also cannot edit my domain.

@lynix27 Your domain does seem to be redirecting, I have removed it from the list 😄
