### ISSUE TITLE
is-a-dev Hosting Not Activated

### ISSUE THREAD

**Issue by CycloneAddons** [is-a-dev/register#8234]
![IMG_20230926_080801](https://github.com/is-a-dev/register/assets/90061864/e7d8a054-73c6-4e55-8570-0092977654e6)

I choose is-a.dev hosting but it not working and not got any mail why...

**Comment by WilliamDavidHarrison** [comment]
@andrewstech will need to look into this.

**Comment by andrewstech** [comment]
Site is now activated

**Comment by CycloneAddons** [comment]
> Site is now activated

Than how i can activate it
