### ISSUE TITLE
my website did not turn into `.is-a.dev` yet

### ISSUE THREAD

**Issue by iop3** [is-a-dev/register#826]
It's been a day (about) and my website is still `.github.io` not `.is-a.dev`. Do I have to wait longer for it to reflect or what?

**Comment by hackermondev** [comment]
Well, your website does work on iop3.is-a.dev for me. Do you mean the Github pages aren't redirecting to iop3.is-a.dev?

**Comment by iop3** [comment]
This is what I see:
![Uploading Screenshot 2021-06-04 093256.png…]()

**Comment by hackermondev** [comment]
Hmm weird, try [clearing your cache](https://support.google.com/googleplay/answer/32050) on chrome.

**Comment by iop3** [comment]
im on edge lol

**Comment by iop3** [comment]
oh now it works suddenly
