### ISSUE TITLE
How to register a subdomain

### ISSUE THREAD

**Issue by Riders004** [is-a-dev/register#8303]
How to get .dev domain in free or subdomain like is-a.dev or is-a.dev in free

**Comment by dushmanta05** [comment]
To secure a .dev domain, you will need to purchase it, but you can create a is-a.dev subdomain for free, you can do this by contributing to this repo.

Checkout the guidelines here: [Link](https://github.com/is-a-dev/register#register)

Let me know if you face any issues.

**Comment by WilliamDavidHarrison** [comment]
If you want to learn how to register an is-a.dev subdomain, please read the docs: https://www.is-a.dev/docs
