### ISSUE TITLE
Run failed: Pull Request Labeler - main

### ISSUE THREAD

**Issue by dushmanta05** [is-a-dev/register#8313]
I've received 5 notifications of run failures in my forked repo, and although I've not made any changes, I don't know why it happened. I've no knowledge of it, so can anyone help? Even if it's fixed, I would like to know why this happened. Here's a screenshot of the run-fail notification. Thanks.

![Error](https://github.com/is-a-dev/register/assets/73304098/8881273b-d2d3-4c35-ad1c-953dc7f290a5)

![Error 2](https://github.com/is-a-dev/register/assets/73304098/0b13f940-f391-4ec7-a464-23e2b5374f6c)

**Comment by VaibhavSys** [comment]
That is just github actions on your fork. Some actions will not succeed on the forks as they require some secrets which only the is-a-dev repository has access to. You can [turn off actions](https://github.com/orgs/community/discussions/25591#discussioncomment-3248406) on your fork.

Feel free to reopen the issue if you need further help with this!
