### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by tushar202108** [is-a-dev/register#8332]
domain name: devchaudhary.is-a.dev

I am unable to sign in  at FTP server for uploading my files 
First, I set my password and then go to manage files ,
 I tried with same password it occur an error than ,I filled a given password by manage files  this wasn't work
![image_2023-09-30_123449301](https://github.com/is-a-dev/register/assets/88264750/c87bd9e7-b455-4aff-806a-62a40466d0dd)

**Comment by WilliamDavidHarrison** [comment]
Are you still having this issue? is-a.dev hosting may have been down at that time.
