### ISSUE TITLE
I can't access my domain :(

### ISSUE THREAD

**Issue by SealedSaucer** [is-a-dev/register#835]
Your domain name: phantom.is-a.dev

Explain any issues you are facing

I can't access my "phantom.is-a.dev"... The sub-domain was supposed to be redirected to phantomcodes.ga...

**Comment by phenax** [comment]
It seems to be working fine on our end. Try clearing your browser cache and let us know if that doesn't fix it.

**Comment by SealedSaucer** [comment]
oh, ok... lemme try that...

**Comment by SealedSaucer** [comment]
it works for others, but everytime i enter the urlm it just redirects me to www.is-a.dev website...

**Comment by SealedSaucer** [comment]
anyway, thanks for help me out! :D

**Comment by SealedSaucer** [comment]
should i close this issue now?

**Comment by Afsan751** [comment]
> نام دامنه شما: phantom.is-a.dev
> 
> درمورد هر پزشکی ای که با آن روبرو توضیح می دهید
> 
> نمی توانم به "phantom.is-a.dev" خود را پیدا کنم ... قرار بود زیر دامنه به phantomcodes.ga هدایت شود ...
