### ISSUE TITLE
Report abuse

### ISSUE THREAD

**Issue by Spilleparadis** [is-a-dev/register#8425]
Domain you want to report: 
00.is-a.dev
### Reason
its redericting to a website ryar.link that dont even show up on google so it can be a phising, etc.

**Comment by iMatx** [comment]
This [link](https://guess-who.is-a.dev/LinkInBio/) and the link you mentioned are owned by @Rayrsn. @WilliamDavidHarrison whenever you can please review this report. I’m guessing the user i mentioned is hogging special named domains to promote the SEO on his [Unidentified link with no CSS](https://rayr.link) that so happens to not appear on google when searched.

**Comment by Rayrsn** [comment]
Hello,
I recently had an issue with my hosting provider and got it resolved this morning, and still haven't had the time to check if everything is working. Sorry if it looks like a mess.

**Comment by iMatx** [comment]
> Hello,
> I recently had an issue with my hosting provider and got it resolved this morning, and still haven't had the time to check if everything is working. Sorry if it looks like a mess.

Ah. Alright. I’ll make sure one of the maintainers close this report. Thank you for responding.

**Comment by Spilleparadis** [comment]
Oh! Thank You.
