### ISSUE TITLE
Feedback/suggestion: Get MX record support?

### ISSUE THREAD

**Issue by quackduck** [is-a-dev/register#844]
Is it possible to have MX records?

**Comment by TheBotlyNoob** [comment]
No, this is said [here](https://github.com/is-a-dev/register/blob/main/docs/domains-json.md#record-required) in the docs.

**Comment by quackduck** [comment]
Yes, but is it possible to add support for MX records?

**Comment by phenax** [comment]
@quackduck, sorry about the misunderstanding. MX records however are a little complicated because of its sensitive nature.

**Comment by quackduck** [comment]
Hi, I've seen that https://improvmx.com has the same MX record details for every user, implying that this information is not secret.

**Comment by phenax** [comment]
The concern isn't the MX records itself but the emails that will be sent through them. We'll need guarentees that being scoped doesn't have an impact on how the emails are transfered. Let me know if you have any information about this.

**Comment by quackduck** [comment]
See, since the information isn't secret, we know that there's no downsides to making it public!

**Comment by phenax** [comment]
Yes. As I said, I'm not worried about the record being public. The problem is I'm unsure how being an unregistered suffix affects the emails sent/recieved via the record and if there are any known or unknown security vulnerabilities associated with it. We will need to research this topic better to ship it safely.

**Comment by quackduck** [comment]
I'm not sure what you mean by:
> unregistered suffix

**Comment by mtgsquad** [comment]
> I'm not sure what you mean by:
> […](#)
> unregistered suffix

I believe he means, that he wants to make sure that there are no security vulnerabilities with it. Because our safety and the safety of users is our top-priority, so please give us some time, we'll be doing some research and will figure out how to implement this safely. Thanks for the suggestion.

**Comment by TheBotlyNoob** [comment]
by adding `MX` record support we should add `TXT` record support

**Comment by mtgsquad** [comment]
> by adding `MX` record support we should add `TXT` record support

	Yes, i believe that is something that is necessary. This would also allow users to verify themselves on google search with the TXT record.

**Comment by anondev-sudo** [comment]
This is good idea to support MX records

**Comment by quackduck** [comment]
This could be helpful: https://github.com/foxcpp/maddy

**Comment by TheBotlyNoob** [comment]
@phenax Anything new?
