### ISSUE TITLE
> نام دامنه شما: phantom.is-a.dev

### ISSUE THREAD

**Issue by Afsan751** [is-a-dev/register#849]
#835  نام دامنه شما: goo.gle
> 
>I can't access domain

_Originally posted by @Afsan751 in https://github.com/is-a-dev/register/issues/835#issuecomment-859187623_
Fixes #

**Comment by phenax** [comment]
`phantom.is-a.dev` is accessible at our end. I'd suggest clearing your cache or trying it on incognito/private.

**Comment by mtgsquad** [comment]
Its accessible by us. Clear your cache or use incognito. And please don't reference to comments on closed issues.

**Comment by mtgsquad** [comment]
Seems to be dead. Since it was replied to 3 days ago. Closed.
