### ISSUE TITLE
Support: Privacy error

### ISSUE THREAD

**Issue by Nirlep5252** [is-a-dev/register#851]
Domain name: https://nirlep.is-a.dev/

I am getting privacy error for the domain. I host the website on netlify -> https://nirlep.netlify.app/

Screenshot: https://nirlep.is-a.fail/8YWhHp.png

**Comment by hackermondev** [comment]
@Nirlep5252 Duplicate of https://github.com/is-a-dev/register/issues/741. I'm not sure but I think you need to like create a custom ssl.

**Comment by Nirlep5252** [comment]
When I try creating SSL, I need to add the custom domain first -> https://nirlep.is-a.fail/vj0c32.png

But I can't add the domain because it's owned by another account -> https://nirlep.is-a.fail/Cuw0pp.png

**Comment by phenax** [comment]
@Nirlep5252 could you also create an issue with netlify about this? This issue cannot be handled from our end as netlify has to issue a new certificate including this subdomain.

**Comment by anondev-sudo** [comment]
I have the same problem with Vercel and also Netlify

**Comment by TheBotlyNoob** [comment]
no

**Comment by TheBotlyNoob** [comment]
nope...

**Comment by mtgsquad** [comment]
Hello. Is this issue still persisting?

**Comment by Nirlep5252** [comment]
Yes, netlify is not letting me add this domain, saying that it is owned by another account

**Comment by TheBotlyNoob** [comment]
You could try [Railway](https://railway.app/?referralCode=jj), they have a very generous free plan, and are able to be used with `is-a.dev`.
