### ISSUE TITLE
Improperly configured PROBLEM

### ISSUE THREAD

**Issue by dizzy123323** [is-a-dev/register#8562]
when i try to do DNS check it says 
"is improperly configured"

**Comment by WilliamDavidHarrison** [comment]
Is this still an issue?

**Comment by dizzy123323** [comment]
wait lemme check

**Comment by dizzy123323** [comment]
still the same

**Comment by VaibhavSys** [comment]
Please give more details, such as your subdomain, DNS configuration, etc.

**Comment by dizzy123323** [comment]
yeaa here it's ain't working ;(
