### ISSUE TITLE
What bug did you encounter?

### ISSUE THREAD

**Issue by dizzy123323** [is-a-dev/register#8563]
### Expected outcome
webpage to be loaded from net2ftp properly

### Observed outcome
it says internal server error

![Screenshot (857)](https://github.com/is-a-dev/register/assets/80522749/ea429073-0414-4369-95a4-4fcf5a422be2)

**Comment by DEV-DIBSTER** [comment]
@andrewstech

**Comment by dizzy123323** [comment]
Hello thank you for replying
i put the zip folder but it is not getting processed, or do you have
another way?
thank you
regards.
