### ISSUE TITLE
Can i change my domain to other now than its published?

### ISSUE THREAD

**Issue by dherediat97** [is-a-dev/register#8572]
Greetings,

I want change my domain of

dherediat.is-a.dev

to

davidheredia.is-a.dev

Regards 👍🏻

**Comment by DEV-DIBSTER** [comment]
> Greetings,
> 
> I want change my domain of
> 
> dherediat.is-a.dev
> 
> to
> 
> davidheredia.is-a.dev
> 
> Regards 👍🏻

Hey, you can do this by making a change in your file name, by renaming it to davidheredia.json. When you do this on your fork, then you can make a pull request to get that approved and you should be good.

**Comment by dherediat97** [comment]
Done, Thanks You 👍🏻
