### ISSUE TITLE
"Site Not Activated"

### ISSUE THREAD

**Issue by Spilleparadis** [is-a-dev/register#8622]
When I Go To My is-a.dev Website It Shows This: Whoops, that site has not been activated check your emails for an activation link or visit manage.is-a.dev. Please Tell Me What To Do?

My is-a.dev Website Link: [https://thetechguy.is-a.dev/](https://thetechguy.is-a.dev/)

**Comment by predefine** [comment]
same here: https://predefine.is-a.dev/

**Comment by predefine** [comment]
@is-a-dev/maintainers

**Comment by Spilleparadis** [comment]
no ones replying
