### ISSUE TITLE
Site Not Activated Bug

### ISSUE THREAD

**Issue by Spilleparadis** [is-a-dev/register#8672]
When I Go To My is-a.dev Website It Shows This: Whoops, that site has not been activated check your emails for an activation link or visit manage.is-a.dev. Please Tell Me What To Do?

My is-a.dev Website Link: [https://thetechguy.is-a.dev/](https://thetechguy.is-a.dev/)

**Comment by predefine** [comment]
same here: https://predefine.is-a.dev

**Comment by adyoblu** [comment]
same here: [adioblu.is-a.dev](url)

**Comment by WilliamDavidHarrison** [comment]
@Spilleparadis @predefine @adyoblu I have sent a request to @andrewstech to activate all of your domains.
