### ISSUE TITLE
Support with username

### ISSUE THREAD

**Issue by Caiden-P** [is-a-dev/register#8704]
Your domain name: caiden.xyz

Explain any issues you are facing
says its taken but its not it let me do it then it said error while preregistering your domain and i went to pull requests and searched for it and no one had claimed it just kept trying it gave the error so i said ill try later as to not break smth but clearly i did

**Comment by VaibhavSys** [comment]
You have already [registered](https://github.com/is-a-dev/register/blob/main/domains/caiden.json) the domain.
