### ISSUE TITLE
How can I access email with hosting by is-a.dev

### ISSUE THREAD

**Issue by Ice-Head** [is-a-dev/register#8732]
Recently I have changed the type of domain https://icehead.is-a.dev to Hosting by is-a.dev. I have enabled SMTP in the dashboard. How can I access or use email in the service?

**Comment by Guru322** [comment]
you can use [Improvmax](https://app.improvmx.com)

**Comment by VaibhavSys** [comment]
**Username:** yourdomain without the is-a.dev part (example.is-a.dev -> example)
**Password:** Same as FTP
**Port:** 25

**Comment by Ice-Head** [comment]
What would be the server + Is IMAP/POP available?

**Comment by WilliamDavidHarrison** [comment]
I believe it is SMTP only at the moment.
