### ISSUE TITLE
DNS Records on a .is-a.dev domains to Github Pages

### ISSUE THREAD

**Issue by Lightshayan** [is-a-dev/register#8807]
Hello. I have recently created codershayan.is-a.dev domain. I would like to have the domain link to a portfolio page on Github. I am following the guide that tells me to go to settings and pages, but that is not working. The error message is that the DNS check is unsuccessful. I am not able to point the DNS records. Is this an issue that will be resolved, or is this a thing that the admins have to do? Please look at the screenshots attached.
![Screenshot 2023-10-18 at 6 41 24 PM](https://github.com/is-a-dev/register/assets/64018536/80b37c60-e6eb-426d-a5fd-27536a3f8c2c)
![Screenshot 2023-10-18 at 6 40 56 PM](https://github.com/is-a-dev/register/assets/64018536/ab7cb8f2-5e00-402b-9ac5-90e013342fc2)

**Comment by JesseHoekema** [comment]
same

**Comment by BBaoVanC** [comment]
you need a CNAME on `codershayan.is-a.dev` that points to `lightshayan.github.io`

**Comment by Lightshayan** [comment]
How do you do that?

**Comment by mtgsquad** [comment]
@Lightshayan Please refer to our Discord server for this issue, please open a help thread in the help forum channel, https://discord.com/invite/cKAhUCUQ5F
