### ISSUE TITLE
Setting up GH Pages

### ISSUE THREAD

**Issue by AeolusDev** [is-a-dev/register#8853]
Your domain name: aeolus.is-a.dev

Explain any issues you are facing

While setting up my domain on github pages this shows up
![image](https://github.com/is-a-dev/register/assets/79212359/a61989fc-c2d8-4e5c-8ac8-7f0c1371f9dc)

**Comment by DEV-DIBSTER** [comment]
Your records are being pointed towards the manage dashboard, not your GitHub repository.

CC: @AeolusDev 

> This issue will be closed within 24 hours if no response is heard back from.

**Comment by AeolusDev** [comment]
> Your records are being pointed towards the manage dashboard, not your GitHub repository.
> 
> CC: @AeolusDev
> 
> > This issue will be closed within 24 hours if no response is heard back from.

how do I point it toward the repository then?

**Comment by DEV-DIBSTER** [comment]
> > Your records are being pointed towards the manage dashboard, not your GitHub repository.
> > CC: @AeolusDev
> > > This issue will be closed within 24 hours if no response is heard back from.
> 
> how do I point it toward the repository then?

You would need to change your records.

**Comment by AeolusDev** [comment]
> > > Your records are being pointed towards the manage dashboard, not your GitHub repository.
> > > CC: @AeolusDev
> > > > This issue will be closed within 24 hours if no response is heard back from.
> > 
> > 
> > how do I point it toward the repository then?
> 
> You would need to change your records.

I'm not sure how to do that

**Comment by DEV-DIBSTER** [comment]
> > > > Your records are being pointed towards the manage dashboard, not your GitHub repository.
> > > > CC: @AeolusDev
> > > > > This issue will be closed within 24 hours if no response is heard back from.
> > > 
> > > 
> > > how do I point it toward the repository then?
> > 
> > 
> > You would need to change your records.
> 
> I'm not sure how to do that

Edit your domain file json.

**Comment by AeolusDev** [comment]
> > > > > Your records are being pointed towards the manage dashboard, not your GitHub repository.
> > > > > CC: @AeolusDev
> > > > > > This issue will be closed within 24 hours if no response is heard back from.
> > > > 
> > > > 
> > > > how do I point it toward the repository then?
> > > 
> > > 
> > > You would need to change your records.
> > 
> > 
> > I'm not sure how to do that
> 
> Edit your domain file json.

how do I do that?

**Comment by VaibhavSys** [comment]
> > > > > > Your records are being pointed towards the manage dashboard, not your GitHub repository.
> > > > > > CC: @AeolusDev
> > > > > > > This issue will be closed within 24 hours if no response is heard back from.
> > > > > 
> > > > > 
> > > > > how do I point it toward the repository then?
> > > > 
> > > > 
> > > > You would need to change your records.
> > > 
> > > 
> > > I'm not sure how to do that
> > 
> > 
> > Edit your domain file json.
> 
> how do I do that?

Refer to GitHub [Documentation](https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files)

**Comment by VaibhavSys** [comment]
If the issue is still relevant, please provide more details and reopen the issue.
