### ISSUE TITLE
What bug did you encounter?

### ISSUE THREAD

**Issue by adyoblu** [is-a-dev/register#8866]
### Expected outcome
I expected to see the redirect page to https://is-a.dev

### Observed outcome
Whoops, that site has not been activated check your emails for an activation link or visit https://manage.is-a.dev.
Also opened the issue here:
https://discord.com/channels/830872854677422150/1165538190434771034
and here is another user encountering the same error:
https://github.com/is-a-dev/register/issues/8672

**Comment by WilliamDavidHarrison** [comment]
This was resolved in the support server.
