### ISSUE TITLE
how i can add new dns records

### ISSUE THREAD

**Issue by JesseHoekema** [is-a-dev/register#8873]
how can i add new dns records for jessehoekema.is-a.dev?
can i also connect it with cloudflare?

**Comment by WilliamDavidHarrison** [comment]
1. https://docs.is-a.dev, Just edit your file and add/remove the records you need.
2. No.

**Comment by JesseHoekema** [comment]
but if i do it it says that i have no write acess

**Comment by WilliamDavidHarrison** [comment]
Fork the repository and open a new PR.

**Comment by JesseHoekema** [comment]
What is a PR

**Comment by WilliamDavidHarrison** [comment]
Pull request
