### ISSUE TITLE
FTP Password Mismatch

### ISSUE THREAD

**Issue by zh4ck** [is-a-dev/register#8890]
Your domain name: zhxck.is-a.dev

Explain any issues you are facing :
The FTP keeps telling me that my password is wrong, although I have set it up in the hosting settings
![image](https://github.com/is-a-dev/register/assets/66990141/84624187-714b-4f0e-bede-86487d45530b)

**Comment by andrewstech** [comment]
Hi sorry for the delay my GitHub notifications are broken. I've recently pushed a bug fix so hopefully this is fixed but let me know.

**Comment by zh4ck** [comment]
> Hi sorry for the delay my GitHub notifications are broken. I've recently pushed a bug fix so hopefully this is fixed but let me know.

Doesn't seems to work. The FTP password is still incorrect.

**Comment by zh4ck** [comment]
Wait nevermind, it is fixed now. Thank you!
