### ISSUE TITLE
Transfer ownership and removing old data

### ISSUE THREAD

**Issue by lfom** [is-a-dev/register#8965]
Hi, there!

Thanks again for providing subdomains for free!

Some questions, it may help other people looking for the same info:

1. It it possible to transfer the ownership of a domain? What is the correct procedure to do so: a) simply submit a PR deleting the JSON from /domains so the other person can register the same domain or b) transfer the ownership of the forked repo to the other person that then can submit a PR with the updated info?

2. Supposed I want to remove the email provided previously from the git history, is it possible? I know that there are tools like [BFG Repo-Cleaner](https://rtyley.github.io/bfg-repo-cleaner/) or `git filter-repo`, but I am not sure if they are used on a fork then the changes remain after the merge. 

Regards

**Comment by WilliamDavidHarrison** [comment]
1. You would delete the domain and the other user would register it.
2. It is not really possible AFAIK.
