### ISSUE TITLE
not able to access my domain.

### ISSUE THREAD

**Issue by sequel-tj** [is-a-dev/register#8981]
issue:
The webpage at https://tanmayjaiswal.is-a.dev/ might be temporarily down or it may have moved permanently to a new web address.

![image](https://github.com/is-a-dev/register/assets/74481733/c31ab3fc-b029-4f65-a013-3d0b788f3c94)

Domain : tanmayjaiswal.is-a.dev

**Comment by Stef-00012** [comment]
![image](https://github.com/is-a-dev/register/assets/81536172/b79ad400-b971-4b20-8b8b-1112f1c3b47a)

**Comment by VaibhavSys** [comment]
Resolved
