### ISSUE TITLE
SSL peer has no certificate for the requested DNS name.

### ISSUE THREAD

**Issue by budderlovr** [is-a-dev/register#8991]
Site does not load and gives this error, manage page gives options for "Create Web Server" and "analytics", neither of which do anything

![image](https://github.com/is-a-dev/register/assets/102700186/43eb44ac-7424-4424-94c1-2d32b7da76e4)

**Comment by WilliamDavidHarrison** [comment]
The SSL issue should be resolved now. However, is-a.dev hosting is currently down.
