### ISSUE TITLE
Suggestion: ReviewMate

### ISSUE THREAD

**Issue by VaibhavSys** [is-a-dev/register#9152]
### 🚀 ReviewMate

> Note: ReviewMate treats the main branch as the ultimate source of truth

ReviewMate is hosted on a server provided by @andrewstech! :tada: 

I plan to add more features down the road which will make the review process even more efficient and error-free, this is free and [opensource](https://github.com/VaibhavSys/ReviewMate) with a MIT licence.

This will immensely speed up the review process of domains. It has the following features:

📸 **Website Screenshot**: Get a visual snapshot of the website.

🔍 **Domain Status**: Quickly identify if the domain has been Deleted, Added, or Modified.

🔒 **Authorization**: Find out if the user is authorized to modify or delete the file.

👤 **File Ownership**: Track both the Old and New File Owners.

📣 **PR Author**: Know who authored the Pull Request.

📄 **Domain Details**: Meta details such as repository, description.

### Triggers

- Pull Request Opened
- Pull Request Updated

### Demo

> You can see a live demo of it here: [ReviewMate Demo](https://github.com/VaibhavSys/register/pull/22)

### Installation

Its install and forget! No configuration required. You can install it here: [Install ReviewMate](https://github.com/apps/reviewmate)

**Comment by WilliamDavidHarrison** [comment]
@phenax I sent you an email a few days ago about approving the app installation for ReviewMate

**Comment by phenax** [comment]
Installed ReviewMate for this repo

**Comment by mtgsquad** [comment]
Perfect. This will make a huge difference in PR approvals.
