### ISSUE TITLE
Report abuse

### ISSUE THREAD

**Issue by burger1001** [is-a-dev/register#9163]
Domain you want to report: 
https://fartplayer69.is-a.dev/skids.txt
### Reason
Explain why you think this domain is being abused

using it just to put peoples usernames up there and call them slurs and stuff
![image](https://github.com/is-a-dev/register/assets/137465815/925d6ad3-077d-4acb-8963-40fc0272a72c)

**Comment by diyar2137237243** [comment]
Lol 🤯
