### ISSUE TITLE
"Your connection is not private" Privacy error.

### ISSUE THREAD

**Issue by RichardKanshen** [is-a-dev/register#9197]
### Expected outcome
*redirect to dsc.gg, and discord.gg afterwards*

### Observed outcome
![image](https://github.com/is-a-dev/register/assets/73738591/a05eafa7-2465-4660-8b63-e7112063bcd4)

**Comment by VaibhavSys** [comment]
If the issue is still relevant, please open a new one with more detail like domain name.
