### ISSUE TITLE
rice.is-a.dev page not working with github pages

### ISSUE THREAD

**Issue by JoaquinDaBest** [is-a-dev/register#9246]
Your domain name:
rice.is-a.dev
Explain any issues you are facing
i have set this page up correctly with [register.is-a.dev](https://manage.is-a.dev/register) , but it will not work.
![Screenshot 2023-11-07 at 6 19 05 PM](https://github.com/is-a-dev/register/assets/126218083/435060d6-62d1-4169-9902-f2362cdb0a9b)

**Comment by TBNRDev** [comment]
Make sure that the Record type is CNAME .
Based on your image, your CNAME Record is your Github pages domain without https;//

**Comment by JoaquinDaBest** [comment]
hi, i am reopening this issue because when I add a CNAME record from rice.is-a.dev TO keenwa.x10.mx the domain does not work. 

P.S. for keenwa.x10.mx I am using x10 hosting
