### ISSUE TITLE
How to solve this problem? "whoops, that site has not been activated visit manage.is-a.dev to activate it."

### ISSUE THREAD

**Issue by Heindale** [is-a-dev/register#9425]
### Expected outcome

![image](https://github.com/is-a-dev/register/assets/65243945/f81cebf4-148b-4a98-9b70-46972fa2db7c)

**Comment by Heindale** [comment]
Also i have this error, that does not allow me to click "Enforce HTTPS"


![image](https://github.com/is-a-dev/register/assets/65243945/0c7b70a7-dd1c-4855-a2d6-12ee080140be)

**Comment by CuteDog5695** [comment]
Late response (yipee) but you have to ask a maintainer in the discord server to activate the website for you (they verify it with a discord bot), thats what i've seen people do when they came across this.
Also with the "Enforce HTTPS" issue, you didnt verify the domain resulting in Github not letting you enable that unless you remove the domain.

**Comment by andrewstech** [comment]
Hi I've activated your site.
