### ISSUE TITLE
What bug did you encounter?

### ISSUE THREAD

**Issue by YEETEDWIN** [is-a-dev/register#945]
### Expected outcome

It to fully function on all browsers - ✅
It to function on all devices - ½

### Observed outcome

I am really happy as it works, but if I do it on **my** google account on my **macbook** it doesn't appear and instead shows this:
<img width="1440" alt="Screenshot 2021-07-17 at 14 17 43" src="https://user-images.githubusercontent.com/76407715/126036624-343dc2dd-07d9-4f8f-a5cf-d02d2320e0ba.png">

While if I do it on my iPad with **my** same google account it works or if i do it on guest mode on my **macbook**, it appears:
<img width="1440" alt="Screenshot 2021-07-17 at 14 19 43" src="https://user-images.githubusercontent.com/76407715/126036664-4aea7ed0-e0c6-4b8c-8277-f48e9f96e325.png">

_If you know how to fix this please tell me!_

**Comment by YEETEDWIN** [comment]
I reloaded 10 times and it got fixed... Its fixed for all my github websites! By the way, I loved my link and thanks so much for this oppurtunity @hackermondev and @TheBotlyNoob ... Sorry I can't buy you a coffee though :|

**Comment by TheBotlyNoob** [comment]
:| We don't get the donations tho, @phenax gets them. We are just maintainers who take time out of our day to add domains. Thanks for the thought tho...

**Comment by YEETEDWIN** [comment]
oh I didn't know... Well thanks for working. so hard @TheBotlyNoob
