### ISSUE TITLE
Cannot verify GHPages domain name, tried a PR, didnt work

### ISSUE THREAD

**Issue by FoxsDenYT** [is-a-dev/register#9470]
Your domain name: foxsden.is-a.dev

Cant verify following the steps

can someone apply the following (without removing my forwardemail)

1. Create a TXT record in your DNS configuration for the following hostname: _github-pages-challenge-FoxsDenYT.foxsden.is-a.dev
2. Use this code for the value of the TXT record: 37455d1a9cf706acc4f0cd6ada2ce7
3. Wait until your DNS configuration changes. This could take up to 24 hours to propagate.

**Comment by CuteDog5695** [comment]
![hsdsHJADjshd](https://github.com/is-a-dev/register/assets/69630113/7de37c73-2b7d-498a-aea7-a7a85bd7097b)
From what i see from your code you added 2 records to TXT, if i remember correctly from the is-a.dev doc you cant add more than 1 record. So you need to remove the Github Page TXT record over there.
I think what you could do is add CNAME to the record and add your github website link there (i verified my github page to my is-a.dev domain using CNAME and it worked). Idk if it would work for you the CNAME thing but try it out and see, if it doesnt work ask in the discord server, you might get a response faster than here.

**Comment by FoxsDenYT** [comment]
hm. thats a bummer, do you know a way to make my repos also be directories
on a subdir, like with the regular domain name?

**Comment by CuteDog5695** [comment]
If you are referring to Github Pages having github.io, just leave the custom domain (found on the Pages section in your repo) blank and it should work (tried it out on a new repo). But make sure that you name the repo like this example (insertnamehere.github.io), if you name it with any other thing but that it would add a / after it. (i think, thats what i did with a WIP website before connecting is-a.dev domain)
Not sure if that was what you were referring or that what i said above was wrong but oh well.
Also as a side note, i dont think you can add CNAME record along with TXT and MX (since my pr got rejected), im not sure how to do it so its better if you ask the same question in the discord server where there are other people who will help you.

**Comment by CuteDog5695** [comment]
Ok I now know how to do it, you need to make  _github-pages-challenge-FoxsDenYT.foxsden seperately, make it in your fork like the domain one but just put the TXT record there, make a PR and when accepted it should work. (also while your at the PR stuff take away the github TXT from your domain one, it wont be needed)

**Comment by VaibhavSys** [comment]
Also GH Pages asks you to create a TXT record on the subdomain `_github-pages-*`, not add that TXT record to the root subdomain.
![image](https://github.com/is-a-dev/register/assets/76240678/c9016093-8fb0-4d5c-a6f5-1f71d296a572)

**Comment by CuteDog5695** [comment]
> > ![hsdsHJADjshd](https://private-user-images.githubusercontent.com/69630113/284268913-7de37c73-2b7d-498a-aea7-a7a85bd7097b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MzM1NTcsIm5iZiI6MTcwMTQzMzI1NywicGF0aCI6Ii82OTYzMDExMy8yODQyNjg5MTMtN2RlMzdjNzMtMmI3ZC00OThhLWFlYTctYTdhODViZDcwOTdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDEyMjA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwMTFkNzhhMzA3NzEwZjYzY2ZjN2ZhMmI1YWM0NzhjZGYwYTZiZWI4MmJiZWQ1MmVkNDM0M2IzZDc1YjE1YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._gt66s_uAP9C-nNDV8rMo3vqvWEvuLDrv1EHF6CwIxg) From what i see in your code you added 2 records to TXT, if i remember correctly from the is-a.dev doc you cant add more than 1 record. So you need to remove the Github Page TXT record over there. I think what you could do is add CNAME to the record and add your github website link there (i verified my github page to my is-a.dev domain using CNAME and it worked). Idk if it would work for you the CNAME thing but try it out and see, if it doesnt work ask in the discord server, you might get a response faster than here.
> 
> We do support multiple TXT records, and it was reflected in the docs some time ago too.

when i read the doc at the time it showed that you could only use one record for TXT, but i see now that it either has changed or i misread but oh well
