### ISSUE TITLE
Activating Domain

### ISSUE THREAD

**Issue by LoganPaxton** [is-a-dev/register#9595]
Domain Name: loganpaxton.is-a.dev

I go to my domain, but I keep getting "Whoops, that site has not been activated visit manage.is-a.dev to activate it."
So I go to manage.is-a.dev but there is no activation button, or panel on there. Pretty much, how do I activate my domain?

**Comment by VaibhavSys** [comment]
You should have got an email with an activation link, but I have activated it for you.
