### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by lordwolfyy** [is-a-dev/register#9620]
Your domain name: lordwolfy.is-a.dev

Explain any issues you are facing

I cannot find the password for the ftp.

**Comment by andrewstech** [comment]
Go to https://manage.is-a.dev/domains/lordwolfy it might redirect you to the login page if it does login then revisit the link. On the page click hosting settings then there is a option to set the password.

**Comment by VaibhavSys** [comment]
If the issue is still relevant, please provide more details and reopen the issue.
