### ISSUE TITLE
Support : Unable to switch to the passive mode on FTP server

### ISSUE THREAD

**Issue by zh4ck** [is-a-dev/register#9711]
Your domain name: zhxck.is-a.dev and zh4ck.is-a.dev

Explain any issues you are facing:
So I tried to log on to the FTP page using my credentials and then this happen
![image](https://github.com/is-a-dev/register/assets/66990141/790857fd-e058-4da9-b974-f6ede3489e63)

**Comment by andrewstech** [comment]
Fixed
