### ISSUE TITLE
Hole pointing the domain name to my server?

### ISSUE THREAD

**Issue by khagdev** [is-a-dev/register#9750]
When I registered my subdomain, I pointed to my server ip and now it automatically points to your server ip, please help me re-point it.
My server IP: 103.97.126.26
The domain name needs to point to this ip: khag.is-a.dev
Hope you point it to my server soon. Thanks a lot.
![image](https://github.com/is-a-dev/register/assets/115873550/f437d47b-2b88-4f4a-8ecb-f77c6a947247)

**Comment by VaibhavSys** [comment]
You made this change by a PR, as you can see here: https://github.com/is-a-dev/register/pull/9676/files
You probably clicked the "Create webserver" button on the domain dashboard by mistake.
