### ISSUE TITLE
Domain/Site Not Activated

### ISSUE THREAD

**Issue by prakhillohiya** [is-a-dev/register#9751]
Your domain name: **prakhillohiya.is-a.dev**

Explain any issues you are facing: Domain/Site Not Activated

![Screenshot 2023-12-01 104731](https://github.com/is-a-dev/register/assets/40757726/8dbbcc42-0db8-4a43-9439-4b03abab1663)

**Comment by VaibhavSys** [comment]
prakhillohiya.is-a.dev has been activated.
