### ISSUE TITLE
Site has not been activated

### ISSUE THREAD

**Issue by Maikeruwu** [is-a-dev/register#9769]
Your domain name: maikeru.is-a.dev

Explain any issues you are facing: Whoops, that site has not been activated visit manage.is-a.dev to activate it.

I've waited a few days, but I didn't get an email to activate my domain, what should I do now?

**Comment by VaibhavSys** [comment]
I have activated it for you.

**Comment by itsmenewbie03** [comment]
I am having the same issue my domain is `itsmenewbie03.is-a.dev`

**Comment by wdhdev** [comment]
@itsmenewbie03 I have activated your domain.

**Comment by itsmenewbie03** [comment]
> @itsmenewbie03 I have activated your domain.

Thank you 💜

**Comment by itsmenewbie03** [comment]
> @itsmenewbie03 I have activated your domain.

hello my domain disappeared may i know what happened?

**Comment by wdhdev** [comment]
#11098

**Comment by itsmenewbie03** [comment]
> #11098

Thanks.
