### ISSUE TITLE
Need help for configure custom domain in github-pages.

### ISSUE THREAD

**Issue by Sunny-unik** [is-a-dev/register#9844]
I'm just getting my sub-domain `sunny.is-a.dev`, now I want to configure it on github-pages by following steps mentioned in a message by `is-a-dev-bot` I received that message on my PR.
```
- Go to your GitHub repository that you use for your is-a.dev domain
- Click on the Settings tab
- Click on the Pages link in the sidebar
- In the custom domain option, enter the domain you registered.
- Check the Enforce HTTPS checkbox
- Give your domain some time (~24 hours) for the changes to propagate
- Enjoy your domain!
```

And I'm stuck after 4th step and getting error: DNS check unsuccessful

Screenshot:

![image](https://github.com/is-a-dev/register/assets/65410458/2e130a07-57a8-4db4-9fd4-ab8adb7b5b69)

And I'm also trying to check the `Enforce HTTPS` checkbox but It is also blocked
Should I need to wait for 24 hours or do something else I don't know 

Please help!

**Comment by Sunny-unik** [comment]
My JSON look like this:
```json
{
    "owner": {
        "username": "Sunny-unik",
        "email": "sunnygandhwani027@gmail.com"
    },
    "record": {
        "A": ["217.174.245.249"],
        "AAAA": ["2a00:da00:1800:83a4::1"],
        "MX": ["hosts.is-a.dev"],
        "TXT": "v=spf1 a mx ip4:217.174.245.249 ~all"
    }
}
```
should I need to change it to this:
```json
{
    "owner": {
        "username": "Sunny-unik",
        "email": "sunnygandhwani027@gmail.com"
    },
     "record": {
        "CNAME": "Sunny-unik.github.io"
    },
    "description": "Add sub-domain to my portfolio website",
    "repo": "https://github.com/Sunny-unik/Sunny-unik.github.io",
    "record": {
        "A": ["217.174.245.249"],
        "AAAA": ["2a00:da00:1800:83a4::1"],
        "MX": ["hosts.is-a.dev"],
        "TXT": "v=spf1 a mx ip4:217.174.245.249 ~all"
    }
}
```
Please help!

**Comment by YouFoundAlpha** [comment]
> > Hello, @Sunny-unik
> > 
> > You can change your [JSON](https://github.com/is-a-dev/register/blob/main/domains/sunny.json) this:
> > 
> > ```
> > {
> >     "description": "Add sub-domain to my portfolio website",
> >     "repo": "https://github.com/Sunny-unik/Sunny-unik.github.io"
> >     "owner": {
> >         "username": "Sunny-unik",
> >         "email": "sunnygandhwani027@gmail.com",
> >     },
> >      "record": {
> >         "CNAME": "sunny-unik.github.io"
> >     }
> > }
> > ```
> 
> Thanks, that solution works for me.

Good
