### ISSUE TITLE
Can't edit my record on the manage site

### ISSUE THREAD

**Issue by ayvacs** [is-a-dev/register#9922]
I don't really understand the new changes to registering a domain, but I needed to edit the record for my site (ave.is-a.dev) and I don't have the option to -- only manage files, hosting settings, export data, and analytics. None of those pages give me the option to edit my record. Any help would be appreciated, thanks.

**Comment by VaibhavSys** [comment]
It seems like your record was deleted via the [cleanup](https://github.com/is-a-dev/register/pull/9887) script. Try clearing cache and cookies for the manage site and refreshing

**Comment by YouFoundAlpha** [comment]
@ayvacs Is this still a problem for you?

**Comment by ayvacs** [comment]
@YouFoundAlpha @VaibhavSys "_github-pages-challenge-ayvacs.ave.is-a.dev" still shows up in my domain list, but trying to re-register "ave.is-a.dev" is now an option -- it gives me this error after inputting the TXT record value:

![image](https://github.com/is-a-dev/register/assets/74518502/87ec3574-779b-4f65-ab1c-5a0a8615ce50)

And it doesn't show up in my domains list. Tried clearing my cache again and using another device, but no luck

**Comment by ayvacs** [comment]
After I tried registering the domain again, "_github-pages-challenge-ayvacs.ave.is-a.dev" still shows up in my domain list with the wrong TXT record.

**Comment by YouFoundAlpha** [comment]
Try to manually edit the file

**Comment by WilliamDavidHarrison** [comment]
@ayvacs Try deleting your fork and trying again.

**Comment by YouFoundAlpha** [comment]
![image](https://github.com/is-a-dev/register/assets/86548581/6f071656-8bfa-4a2c-8883-62c9054588ab)
The fork haven't been synced in a while

**Comment by ayvacs** [comment]
Thanks for the help, deleted my fork and submitted a new PR

**Comment by ayvacs** [comment]
It worked and the site is now displaying properly but I'm still not given an option to remove the old `_github-pages-challenge-ayvacs.ave.is-a.dev` subdomain or change the incorrect TXT record in order to verify the domain in Pages settings. Is there a way to do that?
