### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by lucas-labs** [is-a-dev/register#9925]
Your domain name: `lucas.is-a.dev`

Explain any issues you are facing

![image](https://github.com/is-a-dev/register/assets/12949236/6d63cd0a-13a3-471a-8620-ef405f17541b)

I've waited for a few days but it still says the domain is not activated. I've visited manage.is-a.dev as the message says but I couldn't find any option to activate it there. All I get is this:

![image](https://github.com/is-a-dev/register/assets/12949236/3994980c-2f75-483c-b9d6-b9a67a42e693)

Also checked my emails, spam folder included, but I haven't received any (besides the mail from github when the PR was merged).

I can't find out how to activate the domain, any hint would be appreciated.

Cheers!

**Comment by VaibhavSys** [comment]
That happens sometimes, I have activated your site. Enjoy :tada:
