### ISSUE TITLE
Domain not activated

### ISSUE THREAD

**Issue by tharth0ur** [is-a-dev/register#9927]
### Expected outcome
After receiving the validation email, I logged in to manage.is-a.dev, used the FTP credentials to edit the "index.html" file but nothing seems to work.

### Observed outcome
I get a web page with this message instead "Whoops, that site has not been activated visit manage.is-a.dev to activate it."

Domain Name: athir.is-a.dev

**Comment by VaibhavSys** [comment]
I have activated it for you, enjoy :tada:

**Comment by tharth0ur** [comment]
now it's gone, when i type "athir.is-a.dev" it redirects me to "www.is-a.dev" and i can't register it again, can you help ?
