### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lthon09** [is-a-dev/register#994]
So I have created a PR within a file named **lthon09.json**, so it should be **https://lthon09.is-a.dev**, right? (It isn't reflecting my website)

I'm asking just in case I did something wrong and I'll take days or weeks to realize that

File: **https://github.com/is-a-dev/register/pull/980**

Thank you!

**Comment by TheBotlyNoob** [comment]
https://lthon09.is-a.dev works, try clearing your cache

**Comment by lthon09** [comment]
wtf i waited for so long and all i did was to clear my cache

**Comment by lthon09** [comment]
lmaoo
