### ISSUE TITLE
GitHub pages broken

### ISSUE THREAD

**Issue by FoxsDenYT** [is-a-dev/register#9958]
Your domain name: foxsden.is-a.dev

Explain any issues you are facing

Site just 404s. Tried everything. All files are there.

Repo with problems. https://github.com/FoxsDenYT/foxsden.is-a.dev
See screenshots 
![Screenshot_20231210-074433.png](https://github.com/is-a-dev/register/assets/47910472/bee4d78f-a30d-43a1-9329-bb7a4f71559d)

![Screenshot_20231210-074438.png](https://github.com/is-a-dev/register/assets/47910472/13d103db-241e-4367-9622-0c47208f3a3f)

![Screenshot_20231210-074457.png](https://github.com/is-a-dev/register/assets/47910472/a0329946-49aa-4abe-afde-74d77f431c4b)

**Comment by VaibhavSys** [comment]
Try changing your A records to these:
```
FoxsDenYT.github.io.	3600	IN	A	185.199.109.153
FoxsDenYT.github.io.	3600	IN	A	185.199.111.153
FoxsDenYT.github.io.	3600	IN	A	185.199.108.153
FoxsDenYT.github.io.	3600	IN	A	185.199.110.153
```
And changing your repository name to FoxsDenYT.github.io
